/* ============================================================================
   Widget 97 · Graphs: Scaffold Split (`scaffold-split`) — PHM5005 09-2
   cells 18 (the workflow's two splits and the scaffold figure), 23–26 (a
   Murcko scaffold per molecule, 1,114 of them), 27–28 (GroupShuffleSplit in
   two stages) and 30 (each part's label proportions).

   The misconception (catalogue § Slot 97): a test score from a split that
   puts molecules sharing a backbone on both sides measures new chemistry.
   Cell 18 says a label split "may overestimate performance if model
   recognizes compounds with similar backbones"; the lesson never trains on
   one, so the claim is asserted there and shown here.

   THREE PAGES under Step, every call his from `_lab/scaffold-split-mock.html`
   (2026-10-10, "all recommendations"):

     SCAFFOLD   cell 18's figure on molecules from the file: two related
                molecules, a bracket, their scaffold. Indoles: the figure's
                3-methylindole (row 682) and tryptamine standing in for its
                5-bromoindole, which the file lacks — one scaffold. Quinolones:
                ciprofloxacin and norfloxacin, one family and TWO scaffolds
                (a cyclopropyl ring at N1 is kept, an ethyl removed), the case
                the figure does not have. One press, Find scaffold: each
                scaffold's atoms move across as a copy, the side chains stay
                behind in --ink-3. Below, the whole file as blocks, one a
                scaffold (cells 24–26), the example's block ringed.
     SPLIT      the same blocks; Split Label · Scaffold, Seed 42–51 (42 the
                lesson's SEED, so the page opens on cell 28's own split:
                1960 / 202 / 173). Two presses, cell 27's two stages: Split
                80 / 20, then Split 50 / 50. Cell 30's figure under the blocks.
     EVALUATE   the finished split; Compare rings every block holding a test
                AND a training molecule, Score drops the lesson's GCN's test
                macro F1 for all ten seeds into the split's column.

   THE BLOCKS ARE THE LESSON'S df, ALL 2,335 ROWS: the one SMILES RDKit cannot
   parse has cell 24's scaffold "" and sits with the acyclic molecules, so the
   parts count exactly what cell 28 prints. Data is derived numbers only
   (data.js, generated by `_lab/scaffold-split-data.py`): a group size, a label
   and a part per row; no SMILES beyond the four drawn molecules (his call).

   THE SCORE IS NOISY AND THE PAGE SAYS SO BY DRAWING IT: on seeds 42–51 the
   GCN's macro F1 is higher under the label split on 7 of 10 seeds (means 0.68
   and 0.63), and the scaffold split's test set runs 166–409 molecules with
   4–19 actives, so its scores spread twice as wide. Every seed is a dot and
   no caption says "always". What does not vary is the count Compare makes:
   57–63% of the label split's test molecules share a scaffold with training,
   none of the scaffold split's.

   Nothing trains in the page. Each press reveals what data.js holds; each
   split and each example is its own stage with its own presses (94's
   stageOf), so a student builds each split before seeing it.
   ========================================================================= */

import { defineWidget } from "../core/index.js";
import { FILE, GROUPS, NAMED, LABELS, SPLITS, STATS, EXAMPLES } from "./data.js";

const PAGES = [
  { value: "scaffold", label: "Scaffold" },
  { value: "split", label: "Split" },
  { value: "evaluate", label: "Evaluate" },
];
const EXAMPLE_OPTS = [{ value: "indoles", label: "Indoles" }, { value: "quinolones", label: "Quinolones" }];
const SPLIT_OPTS = [{ value: "label", label: "Label" }, { value: "scaffold", label: "Scaffold" }];
const SEEDS = Object.keys(STATS.label).map(Number).sort((a, b) => a - b);
const ON = (page) => ({ param: "page", equals: page });
const STEPS = { scaffold: 1, split: 2, evaluate: 2 };
const N = LABELS.length;
const fmtN = (v) => v.toLocaleString("en");
const pct = (v, d = 1) => `${(100 * v).toFixed(d)}%`;

/* -------------------------------------------------------------- strings */

const S = {
  subtitle:
    "A molecule's Murcko scaffold is its ring systems and the linkers that join them. " +
    "A label split assigns molecules one at a time, so molecules sharing a scaffold appear in both training and test. " +
    "A scaffold split assigns whole scaffold groups, which tests whether a model generalizes to new chemical families; its test score is usually lower.",
  pageLabel: "Step",
  exampleLabel: "Example",
  exampleDetail: "two molecules from the dataset and their Murcko scaffolds: the ring systems and the linkers between them, without the side chains",
  splitLabel: "Split",
  splitDetail: "Label assigns molecules one at a time and keeps each part's share of actives; Scaffold assigns whole scaffold groups",
  seedLabel: "Seed",
  seedDetail: "the random_state of both stages of the split; each seed gives a different split",

  stepLabel: {
    param: "page",
    labels: {
      scaffold: "Find scaffold",
      split: { anim: "beat", labels: { 0: "Split 80 / 20", 1: "Split 50 / 50" }, default: "Split 50 / 50" },
      evaluate: { anim: "beat", labels: { 0: "Compare", 1: "Score" }, default: "Score" },
    },
    default: "Find scaffold",
  },
  stepTitle: {
    param: "page",
    labels: {
      scaffold: "Remove each molecule's side chains, keeping its ring systems and linkers",
      split: { anim: "beat", labels: { 0: "Hold out 20% of the molecules; the other 80% train the model", 1: "Halve the held-out 20% into validation and test" }, default: "Halve the held-out 20% into validation and test" },
      evaluate: { anim: "beat", labels: { 0: "Find the scaffolds shared by test and training molecules", 1: "Score the GCN on the test set, for every seed" }, default: "Score the GCN on the test set, for every seed" },
    },
    default: "Remove each molecule's side chains, keeping its ring systems and linkers",
  },

  /* Scaffold */
  related: "Related molecules",
  scaffoldHead: (n) => (n === 1 ? "Scaffold" : "Scaffolds"),
  molName: (m) => `${m.name} · ${m.y ? "active" : "inactive"}`,
  scafName: (fam, g) => `${fam === "indoles" ? "indole · " : ""}${GROUPS[g][0]} molecules · ${GROUPS[g][1]} active`,
  fileCap: `The dataset: ${fmtN(FILE.scaffolds)} scaffolds in ${fmtN(FILE.rows)} molecules · each block is one scaffold`,
  /* once the press lands the ring needs naming, and the count is on the tile */
  fileCapRing: "each block is one scaffold · ringed: the example's scaffold",
  benzene: (n) => `benzene · ${n}`,
  empty: (n) => `no ring · ${n}`,
  band: (b) => `${b.count} scaffold${b.count === 1 ? "" : "s"} with ${b.range} molecule${b.range === "1" ? "" : "s"} each`,
  active: "active",

  /* Split */
  keyNone: "not yet split",
  keyTrain: "train",
  keyHeld: "held out",
  keyVal: "validation",
  keyTest: "test",
  splitStatus: [
    "the dataset grouped by scaffold, before the split",
    (kind) => (kind === "label" ? "80% of the molecules to train, assigned one at a time; 20% held out, on the right" : "80% of the scaffold groups to train, each group whole; 20% held out, on the right"),
    (kind) => (kind === "label" ? "the held-out molecules halved into validation and test, one at a time" : "the held-out groups halved into validation and test, each group whole"),
  ],
  colBand: (range, narrow) => (narrow ? `${range} per scaffold` : `${range} molecule${range === "1" ? "" : "s"} per scaffold`),
  colHead: (side, n, share) => (side === 0 ? `Train · ${fmtN(n)} molecules (${Math.round(100 * share)}%)` : `Held out · ${fmtN(n)} (${Math.round(100 * share)}%)`),
  hoverPair: (n, a, inTrain, inHeld) => `${n} molecules · ${a} active · train ${inTrain} · held out ${inHeld}`,
  barTitle: ["Train", "Validation", "Test"],
  barY: "Proportion",
  barX: "Activity label",

  /* Evaluate */
  evStatus: [
    (kind) => `the ${kind === "label" ? "label" : "scaffold"} split's test set`,
    "ringed: a scaffold found in both test and training, in both columns",
  ],
  scoreHead: "Macro F1 of the GCN on the test set · one dot a seed",
  colName: { label: "Label split", scaffold: "Scaffold split" },
  meanTag: (v) => `mean ${v}`,

  /* hover */
  hoverGroup: (n, a) => `${n} molecule${n === 1 ? "" : "s"} · ${a} active`,
  hoverParts: (n, a, p) => `${n} molecule${n === 1 ? "" : "s"} · ${a} active · train ${p[0]} · validation ${p[1]} · test ${p[2]}`,

  /* tiles */
  tileMol: "Molecules",
  tileMolNote: `${FILE.actives} have Activity 1: they inhibit the growth of E. coli`,
  tileScaf: "Scaffolds",
  tileScafNote: (big) => `${FILE.singletons} occur in one molecule only; benzene, the most common, is the scaffold of ${big}`,
  tileEx: "The example's scaffolds",
  tileExNote: (fam) => (fam === "indoles"
    ? "both molecules have the scaffold indole"
    : "one family of antibiotics, two scaffolds: a cyclopropyl ring at N1 is kept, an ethyl is removed"),
  tilePart: ["Train", "Validation", "Test"],
  tilePartNote: (a, n) => `${a} active · ${pct(a / n)}`,
  tileShared: "Shared scaffolds",
  tileSharedNote: "test molecules whose scaffold also occurs in training",
  tileSharedAct: "Actives sharing",
  tileSharedActNote: "test actives whose scaffold also occurs in a training active",
  tileF1: "Macro F1",
  tileF1Note: (m) => `the GCN on this seed's test set; the mean over ${SEEDS.length} seeds is ${m}`,
  tileWait: "—",

  sumScaf: (fam, done) => `${fam === "indoles" ? "3-methylindole and tryptamine" : "ciprofloxacin and norfloxacin"}${done ? (fam === "indoles" ? ", reduced to one scaffold, indole" : ", reduced to two different scaffolds") : ""}; below, ${fmtN(FILE.rows)} molecules in ${fmtN(FILE.scaffolds)} scaffold groups`,
  sumSplit: (kind, seed, beat, st) => `the ${kind} split, seed ${seed}${beat >= 2 ? `: train ${st.n[0]}, validation ${st.n[1]}, test ${st.n[2]}` : beat === 1 ? ": 80% to train, 20% held out" : ", not yet split"}`,
  sumEval: (kind, seed, beat, st) => `the ${kind} split, seed ${seed}: ${beat >= 1 ? `${st.shared} of ${st.n[2]} test molecules share a scaffold with training` : `${st.n[2]} test molecules`}${beat >= 2 ? `; the GCN's macro F1 ${st.f1.toFixed(2)}` : ""}`,
};

/* ------------------------------------------------------ drawing helpers */

const rgb = (c) => { const m = String(c).match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : [128, 128, 128]; };
const wash = (color, a) => { const p = rgb(color); return `rgba(${p[0]},${p[1]},${p[2]},${a})`; };
function fitText(ctx, s, maxW) {
  let out = s;
  while (ctx.measureText(out).width > maxW) {
    const cut = Math.max(out.lastIndexOf(" · "), out.lastIndexOf("; "), out.lastIndexOf(", "));
    if (cut <= 0) { while (out.length > 1 && ctx.measureText(out + "…").width > maxW) out = out.slice(0, -1); return out + "…"; }
    out = out.slice(0, cut);
  }
  return out;
}
function txt(ctx, colors, s, x, y, { font = null, fill = null, align = "left", baseline = "alphabetic", halo = false, maxW = null } = {}) {
  ctx.save();
  ctx.font = font ?? `${colors.fsXs} ${colors.font}`;
  if (maxW != null) s = fitText(ctx, String(s), maxW);
  ctx.textAlign = align; ctx.textBaseline = baseline;
  if (halo) { ctx.strokeStyle = colors.surface; ctx.lineWidth = 3; ctx.strokeText(s, x, y); }
  ctx.fillStyle = fill ?? colors.ink2;
  ctx.fillText(s, x, y);
  ctx.restore();
}
const capFont = (colors) => `600 ${colors.fsSm} ${colors.font}`;
const nodeFont = (colors) => `600 ${colors.fsXs} ${colors.font}`;
function line(ctx, x1, y1, x2, y2, stroke, width = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = width; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.restore();
}
function rect(ctx, x, y, w, h, fill, stroke = null, lw = 1) {
  ctx.save();
  if (fill) { ctx.fillStyle = fill; ctx.fillRect(x, y, w, h); }
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.strokeRect(x + lw / 2, y + lw / 2, w - lw, h - lw); }
  ctx.restore();
}
function dot(ctx, x, y, r, fill, stroke = null, lw = 1) {
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2);
  if (fill) { ctx.fillStyle = fill; ctx.fill(); }
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.stroke(); }
  ctx.restore();
}
function arrow(ctx, x1, y1, x2, y2, colour, width = 1.5, head = 8) {
  const a = Math.atan2(y2 - y1, x2 - x1);
  line(ctx, x1, y1, x2 - (head - 2) * Math.cos(a), y2 - (head - 2) * Math.sin(a), colour, width);
  ctx.save(); ctx.fillStyle = colour; ctx.beginPath(); ctx.moveTo(x2, y2);
  ctx.lineTo(x2 - head * Math.cos(a - 0.4), y2 - head * Math.sin(a - 0.4));
  ctx.lineTo(x2 - head * Math.cos(a + 0.4), y2 - head * Math.sin(a + 0.4));
  ctx.closePath(); ctx.fill(); ctx.restore();
}
function hoverLabel(ctx, colors, str, x, y, w) {
  ctx.save(); ctx.font = `600 ${colors.fsXs} ${colors.font}`;
  const tw = ctx.measureText(str).width; ctx.restore();
  const bx = Math.max(4, Math.min(w - tw - 14, x + 10)), by = Math.max(4, y - 26);
  rect(ctx, bx, by, tw + 10, 18, colors.surface, colors.ink3);
  txt(ctx, colors, str, bx + 5, by + 9.5, { font: `600 ${colors.fsXs} ${colors.font}`, fill: colors.ink1, baseline: "middle" });
}
/** a key entry: a swatch and its word; returns the x after it */
function keyItem(ctx, colors, x, y, fill, word, { active = false } = {}) {
  rect(ctx, x, y - 8, 10, 10, fill);
  if (active) rect(ctx, x + 2, y - 6, 6, 6, colors.ink1);
  txt(ctx, colors, word, x + 14, y + 1, { fill: colors.ink1 });
  ctx.save(); ctx.font = `${colors.fsXs} ${colors.font}`; const tw = ctx.measureText(word).width; ctx.restore();
  return x + 14 + tw + 14;
}

/* ------------------------------------------------------------ the blocks */

/* ONE BLOCK A SCAFFOLD, laid out ONCE at a fixed width so every page's
   height is a constant: a height that reads the width never settles in the
   harness (widget 62). A canvas narrower than the grid draws it scaled. Each
   group of two or more is a square-ish block of 5px cells, outlined, largest
   first; the single-molecule scaffolds follow as loose cells. The grid's order
   is data.js's: group by group, actives first inside a group. */
const PITCH = 6, CELL = 5, GAP = 5, GRID_W = 520, NAME_H = 14, CAP_H = 16, BAND_GAP = 10;
/* BANDS BY GROUP SIZE, EACH LABELLED (his pick A, round 1): the draft wrapped
   one flow of blocks into rows whose edges fell wherever the box shape
   changed, so the rows read as categories they were not (one mixed groups of
   7, 6, 5 and 4). Now a band is a size class, captioned with how many
   scaffolds it holds, and the separation says how lopsided the screen is. */
const BANDS = [[13, Infinity, "13 or more"], [7, 12, "7–12"], [4, 6, "4–6"], [3, 3, "3"], [2, 2, "2"], [1, 1, "1"]];
const GRID = (() => {
  const blocks = [], bands = [], cellAt = new Array(N), groupOf = new Array(N);
  const scols = Math.floor((GRID_W + 1) / PITCH);
  let y = 0, k = 0, singleTop = 0, nSingles = 0;
  BANDS.forEach(([lo, hi, range], bi) => {
    const gs = GROUPS.map(([n], g) => [n, g]).filter(([n]) => n >= lo && n <= hi);
    if (!gs.length) return;
    bands.push({ y, range, count: gs.length, single: lo === 1 });
    y += CAP_H;
    if (lo === 1) {
      singleTop = y; nSingles = gs.length;
      gs.forEach(([, g], j) => { cellAt[k] = [(j % scols) * PITCH, y + Math.floor(j / scols) * PITCH]; groupOf[k] = g; k += 1; });
      y += Math.ceil(gs.length / scols) * PITCH;
      return;
    }
    let x = 0, rowH = 0, row = 0;
    gs.forEach(([n, g]) => {
      const cols = Math.ceil(Math.sqrt(n)), rows = Math.ceil(n / cols), bw = cols * PITCH - 1, bh = rows * PITCH - 1;
      /* the first band's first row carries the two block names under it */
      if (x + bw > GRID_W) { x = 0; y += rowH + GAP + (bi === 0 && row === 0 ? NAME_H : 0); rowH = 0; row += 1; }
      blocks.push({ g, x, y, w: bw, h: bh, start: k, n });
      for (let j = 0; j < n; j++) { cellAt[k] = [x + (j % cols) * PITCH, y + Math.floor(j / cols) * PITCH]; groupOf[k] = g; k += 1; }
      x += bw + GAP; rowH = Math.max(rowH, bh);
    });
    y += rowH + (bi === 0 && row === 0 ? NAME_H : 0) + BAND_GAP;
  });
  const blockOfGroup = new Map(blocks.map((b) => [b.g, b]));
  return { blocks, bands, blockOfGroup, cellAt, groupOf, singleTop, nSingles, h: y };
})();
/** where the grid sits, and how much it is scaled, at this canvas width */
const gridBox = (w, top) => { const sc = Math.min(1, (w - 16) / GRID_W); return { x0: (w - GRID_W * sc) / 2, y0: top, sc }; };

/* per split and seed, the parts each group holds; for Compare */
const PARTS = {};
const partsOf = (kind, seed) => {
  const key = `${kind}${seed}`;
  if (!PARTS[key]) {
    const s = SPLITS[kind][seed], per = GROUPS.map(() => [0, 0, 0]);
    for (let k = 0; k < N; k++) per[GRID.groupOf[k]][+s[k]] += 1;
    PARTS[key] = per;
  }
  return PARTS[key];
};

/* TRAIN AND HELD OUT AS TWO COLUMNS (round 3, his pick B from
   `_lab/scaffold-split-groups-mock.html`, with hover pairing). Split 80 / 20
   moves every molecule out of the one grid into two columns, Train left and
   Held out right, each in the same size bands, the bands level across the gap
   so a size class reads straight across. A scaffold cut by the split appears
   in both columns as two pieces, each as WIDE as the whole block, so a strip
   of benzene on the right reads as benzene. Inside a band each column flows
   its own pieces: putting a scaffold's two pieces on one row needs a held-out
   column as wide as Train (a row of five large blocks has held-out strips
   about 300px wide), so hovering a piece rings its other piece instead. Split
   50 / 50 colours the held-out column in place, validation and test. */
const COL_L = 362, COL_GAP = 18, COL_R = GRID_W - COL_L - COL_GAP, HEAD_H = 20;
/* the move's staging, as fractions of the press: held-out cells start over the
   first MOVE.held, Train's from MOVE.train on; each cell takes MOVE.each */
const MOVE = { held: 0.4, train: 0.5, each: 0.12 };
const PAIRS = {};
function pairOf(kind, seed) {
  const key = `${kind}${seed}`;
  if (PAIRS[key]) return PAIRS[key];
  const split = SPLITS[kind][seed];
  const pos = new Array(N), outlines = [], caps = [];
  const sides = [[0, COL_L], [COL_L + COL_GAP, COL_R]].map(([x0, width], side) => {
    const byGroup = new Map();
    for (let k = 0; k < N; k++) if ((split[k] === "0") === (side === 0)) {
      const g = GRID.groupOf[k];
      if (!byGroup.has(g)) byGroup.set(g, []);
      byGroup.get(g).push(k);
    }
    return { x0, width, byGroup, n: [...byGroup.values()].reduce((t, ks) => t + ks.length, 0) };
  });
  let y = HEAD_H;
  BANDS.forEach(([lo, hi, range]) => {
    const per = sides.map((sd) => [...sd.byGroup.keys()].filter((g) => GROUPS[g][0] >= lo && GROUPS[g][0] <= hi));
    if (!per[0].length && !per[1].length) return;
    caps.push({ rule: y });
    let bottom = y + CAP_H;
    sides.forEach((sd, side) => {
      caps.push({ text: S.colBand(range, side === 1), x: sd.x0, y: y + CAP_H - 6 });
      let yy = y + CAP_H;
      if (lo === 1) {
        const sc = Math.floor((sd.width + 1) / PITCH);
        per[side].forEach((g, j) => { pos[sd.byGroup.get(g)[0]] = [sd.x0 + (j % sc) * PITCH, yy + Math.floor(j / sc) * PITCH]; });
        bottom = Math.max(bottom, yy + Math.ceil(per[side].length / sc) * PITCH);
        return;
      }
      let x = 0, rowH = 0;
      per[side].forEach((g) => {
        const ks = sd.byGroup.get(g), cols = Math.min(Math.ceil(Math.sqrt(GROUPS[g][0])), Math.floor((sd.width + 1) / PITCH));
        const rows = Math.ceil(ks.length / cols), bw = cols * PITCH - 1, bh = rows * PITCH - 1;
        if (x + bw > sd.width) { x = 0; yy += rowH + GAP; rowH = 0; }
        ks.forEach((k, j) => { pos[k] = [sd.x0 + x + (j % cols) * PITCH, yy + Math.floor(j / cols) * PITCH]; });
        outlines.push({ x: sd.x0 + x, y: yy, w: bw, h: bh, g, side });
        x += bw + GAP; rowH = Math.max(rowH, bh);
      });
      bottom = Math.max(bottom, yy + rowH);
    });
    y = bottom + BAND_GAP;
  });
  const heads = sides.map((sd, side) => ({ text: S.colHead(side, sd.n, sd.n / N), x: sd.x0 }));
  /* the order the move takes: held-out cells leave first, then Train closes up */
  const held = [], train = [];
  for (let k = 0; k < N; k++) (split[k] === "0" ? train : held).push(k);
  const start = new Float32Array(N);
  held.forEach((k, i) => { start[k] = MOVE.held * (i / held.length); });
  train.forEach((k, i) => { start[k] = MOVE.train + (1 - MOVE.train - MOVE.each) * (i / train.length); });
  PAIRS[key] = { pos, outlines, caps, heads, h: y, start, n: sides.map((sd) => sd.n) };
  return PAIRS[key];
}

/** every cell at posOf(k), coloured fillOf(k), an active marked inside it */
function drawCells(ctx, colors, b, posOf, fillOf) {
  ctx.save(); ctx.translate(b.x0, b.y0); ctx.scale(b.sc, b.sc);
  for (let k = 0; k < N; k++) {
    const [x, y] = posOf(k);
    ctx.fillStyle = fillOf(k); ctx.fillRect(x, y, CELL, CELL);
    if (LABELS[k] === "1") { ctx.fillStyle = colors.ink1; ctx.fillRect(x + 1, y + 1, CELL - 2, CELL - 2); }
  }
  ctx.restore();
}
/** the two columns' rules, captions, headings and outlines; pairG frames both pieces of one scaffold */
function drawPairFrame(ctx, colors, b, P, { ring = null, pairG = null } = {}) {
  ctx.save(); ctx.translate(b.x0, b.y0); ctx.scale(b.sc, b.sc);
  for (const c of P.caps) {
    if (c.rule != null) line(ctx, 0, c.rule - 4, GRID_W, c.rule - 4, colors.grid);
    else txt(ctx, colors, c.text, c.x, c.y, { fill: colors.ink3 });
  }
  P.heads.forEach((hd) => txt(ctx, colors, hd.text, hd.x, 13, { font: `600 ${colors.fsXs} ${colors.font}`, fill: colors.ink1 }));
  P.outlines.forEach((o, i) => {
    const paired = pairG != null && o.g === pairG, on = ring && ring(o, i);
    rect(ctx, o.x - 2, o.y - 2, o.w + 4, o.h + 4, null, paired ? colors.ink1 : on ? colors.highlight : colors.ink3, paired ? 2.5 : on ? 2 : 1);
  });
  ctx.restore();
}
/** the piece under the pointer in the two columns: { g, side }, side null for a one-molecule scaffold */
function pieceAt(b, P, p) {
  if (!p) return null;
  const x = (p.x - b.x0) / b.sc, y = (p.y - b.y0) / b.sc;
  for (const o of P.outlines) if (x >= o.x - 2 && x <= o.x + o.w + 2 && y >= o.y - 2 && y <= o.y + o.h + 2) return { g: o.g, side: o.side };
  for (let k = N - GRID.nSingles; k < N; k++) { const [cx, cy] = P.pos[k]; if (x >= cx && x < cx + PITCH && y >= cy && y < cy + PITCH) return { g: GRID.groupOf[k], side: null }; }
  return null;
}

/** paint every cell; fillOf(k) gives its colour, ringed groups get a highlight frame */
function drawGrid(ctx, colors, b, fillOf, { ring = null, labels = true } = {}) {
  ctx.save(); ctx.translate(b.x0, b.y0); ctx.scale(b.sc, b.sc);
  for (let k = 0; k < N; k++) {
    const [x, y] = GRID.cellAt[k];
    ctx.fillStyle = fillOf(k); ctx.fillRect(x, y, CELL, CELL);
    if (LABELS[k] === "1") { ctx.fillStyle = colors.ink1; ctx.fillRect(x + 1, y + 1, CELL - 2, CELL - 2); }
  }
  for (const bl of GRID.blocks) {
    const on = ring && ring(bl.g);
    rect(ctx, bl.x - 2, bl.y - 2, bl.w + 4, bl.h + 4, null, on ? colors.highlight : colors.ink3, on ? 2 : 1);
  }
  if (labels) {
    const bz = GRID.blockOfGroup.get(NAMED.benzene), em = GRID.blockOfGroup.get(NAMED.empty);
    txt(ctx, colors, S.benzene(GROUPS[NAMED.benzene][0]), bz.x, bz.y + bz.h + 13, { fill: colors.ink2 });
    txt(ctx, colors, S.empty(GROUPS[NAMED.empty][0]), em.x, em.y + em.h + 13, { fill: colors.ink2 });
    for (const band of GRID.bands) txt(ctx, colors, S.band(band), 0, band.y + CAP_H - 6, { fill: colors.ink3 });
  }
  ctx.restore();
}
/** the group under the pointer, or null */
function groupAt(b, p) {
  if (!p) return null;
  const x = (p.x - b.x0) / b.sc, y = (p.y - b.y0) / b.sc;
  for (const bl of GRID.blocks) if (x >= bl.x - 2 && x <= bl.x + bl.w + 2 && y >= bl.y - 2 && y <= bl.y + bl.h + 2) return { g: bl.g, k: null };
  if (y >= GRID.singleTop) {
    for (let k = N - GRID.nSingles; k < N; k++) { const [cx, cy] = GRID.cellAt[k]; if (x >= cx && x < cx + PITCH && y >= cy && y < cy + PITCH) return { g: GRID.groupOf[k], k }; }
  }
  return null;
}

/* ------------------------------------------------------------ molecules */

const BOND = { S: "SINGLE", D: "DOUBLE", T: "TRIPLE", A: "AROMATIC" };
const NODE_R = 8;
function node(ctx, colors, x, y, name, { stroke = null, ink = null } = {}) {
  dot(ctx, x, y, NODE_R, colors.surface);
  dot(ctx, x, y, NODE_R, colors.surface2, stroke ?? colors.ink1, 1.2);
  txt(ctx, colors, name, x, y + 0.5, { font: nodeFont(colors), fill: ink ?? colors.ink1, align: "center", baseline: "middle" });
}
function bond(ctx, p, q, type, colour) {
  const dx = q[0] - p[0], dy = q[1] - p[1], L = Math.hypot(dx, dy) || 1, nx = (-dy / L) * 2.2, ny = (dx / L) * 2.2;
  if (type === "D") { line(ctx, p[0] + nx, p[1] + ny, q[0] + nx, q[1] + ny, colour, 1.3); line(ctx, p[0] - nx, p[1] - ny, q[0] - nx, q[1] - ny, colour, 1.3); }
  else if (type === "T") { line(ctx, p[0], p[1], q[0], q[1], colour, 1.3); line(ctx, p[0] + 1.6 * nx, p[1] + 1.6 * ny, q[0] + 1.6 * nx, q[1] + 1.6 * ny, colour, 1.3); line(ctx, p[0] - 1.6 * nx, p[1] - 1.6 * ny, q[0] - 1.6 * nx, q[1] - 1.6 * ny, colour, 1.3); }
  else if (type === "A") { line(ctx, p[0] + nx, p[1] + ny, q[0] + nx, q[1] + ny, colour, 1.3); line(ctx, p[0] - nx, p[1] - ny, q[0] - nx, q[1] - ny, colour, 1.3, [3, 2.5]); }
  else line(ctx, p[0], p[1], q[0], q[1], colour, 1.3);
}
/** one scale for a pair, so a shared scaffold is drawn the same size in both */
function pairScale(mols, bw, bh) {
  let s = 24;
  for (const m of mols) {
    const xs = m.atoms.map((a) => a[1]), ys = m.atoms.map((a) => a[2]);
    s = Math.min(s, bw / Math.max(Math.max(...xs) - Math.min(...xs), 1e-6), bh / Math.max(Math.max(...ys) - Math.min(...ys), 1e-6));
  }
  return s;
}
/** the whole molecule centred in a box */
function placeBox(m, s, x0, y0, bw, bh) {
  const xs = m.atoms.map((a) => a[1]), ys = m.atoms.map((a) => a[2]);
  const cx = (Math.min(...xs) + Math.max(...xs)) / 2, cy = (Math.min(...ys) + Math.max(...ys)) / 2;
  return m.atoms.map((a) => [x0 + bw / 2 + (a[1] - cx) * s, y0 + bh / 2 + (a[2] - cy) * s]);
}
/** the molecule placed so its SCAFFOLD's centre is at (cx, cy): where the copy lands */
function placeScaffold(m, s, cx, cy) {
  const sc = m.atoms.filter((a) => a[3]);
  const mx = sc.reduce((t, a) => t + a[1], 0) / sc.length, my = sc.reduce((t, a) => t + a[2], 0) / sc.length;
  return m.atoms.map((a) => [cx + (a[1] - mx) * s, cy + (a[2] - my) * s]);
}
const scaffoldHalfW = (m, s) => {
  const sc = m.atoms.filter((a) => a[3]), mx = sc.reduce((t, a) => t + a[1], 0) / sc.length;
  return Math.max(...sc.map((a) => Math.abs(a[1] - mx))) * s + NODE_R;
};
function drawMol(ctx, colors, m, P, { only = false, dimSide = false } = {}) {
  const keep = (i) => !only || m.atoms[i][3];
  const side = (i) => dimSide && !m.atoms[i][3];
  m.bonds.forEach(([i, j, t]) => { if (keep(i) && keep(j)) bond(ctx, P[i], P[j], t, side(i) || side(j) ? colors.ink3 : colors.ink2); });
  m.atoms.forEach((a, i) => { if (keep(i)) node(ctx, colors, P[i][0], P[i][1], a[0], side(i) ? { stroke: colors.ink3, ink: colors.ink3 } : {}); });
}

/* ------------------------------------------------------------- timing */

const DUR = { scaffold: 2400, split: 3400, evaluate: 2000 };
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - (-2 * t + 2) ** 3 / 2);
const lerp = (a, b, t) => a + (b - a) * t;
/** each example and each split is its own stage, with its own presses (94's stageOf) */
const stageOf = (params) => (params.page === "scaffold" ? `scaffold-${params.example}` : `${params.page}-${params.split}`);
const stepsOf = (stage) => STEPS[stage.split("-")[0]];
/** the settled count: while a press is in flight, the count before it */
const shownStep = (anim, stage) => (anim.n[stage] ?? 0) - (anim.stage === stage && anim.t < 1 ? 1 : 0);
/** the progress of the press in flight on this stage, raw; null when settled */
const inFlight = (anim, stage) => (anim.stage === stage && anim.t < 1 ? anim.t : null);
/* A SWEEP, NOT A FADE: a press colours the cells in the grid's order, each
   switching at once when the sweep reaches it (tween-only-movement). */
const SWEEP_END = 0.85;
const swept = (k, t) => t >= (k / N) * SWEEP_END;

/* ---------------------------------------------------------- geometry */

const MOL_H = 356;
const H_SCAF = MOL_H + 30 + GRID.h + 14;
/* the key on one line, the status on its own line under it: beside the key it was cut off at the harness's 534px */
const GRID_TOP = 48;
const BARS_H = 138, SCORE_H = 170;
/* the two columns' height depends on the split and the seed, so these read the parameters */
const H_SPLIT = (params) => GRID_TOP + Math.max(GRID.h, pairOf(params.split, Number(params.seed)).h) + 26 + BARS_H;
const H_EVAL = (params) => GRID_TOP + pairOf(params.split, Number(params.seed)).h + 26 + SCORE_H;
const leftW = (w) => Math.min(270, w * 0.48);

/* ------------------------------------------------------------ Scaffold */

function drawScaffold(ctx, colors, w, params, anim, pointer) {
  const fam = params.example, ex = EXAMPLES[fam], stage = stageOf(params);
  const done = shownStep(anim, stage) >= 1, t = inFlight(anim, stage);
  const pressed = done || t != null;
  const lw = leftW(w), BW = lw - 20, BH = 124, tops = [40, 200];
  const s = pairScale(ex, BW - 24, BH - 20);
  const rx = lw + (w - lw) / 2 + 12;
  const mids = tops.map((y) => y + BH / 2), meet = (mids[0] + mids[1]) / 2;
  const ends = fam === "indoles" ? [meet, meet] : mids;
  const nScaf = new Set(ex.map((m) => m.group)).size;
  txt(ctx, colors, S.related, 12, 20, { font: capFont(colors), fill: colors.ink1 });
  txt(ctx, colors, S.scaffoldHead(nScaf), rx, 20, { font: capFont(colors), fill: colors.ink1, align: "center" });

  const left = ex.map((m, k) => placeBox(m, s, 10, tops[k], BW, BH));
  ex.forEach((m, k) => {
    drawMol(ctx, colors, m, left[k], { dimSide: pressed });
    txt(ctx, colors, S.molName(m), 10 + BW / 2, tops[k] + BH + 16, { fill: colors.ink1, align: "center", maxW: BW });
  });

  /* the bracket and arrows land with the copies (nothing moves over a mark in place) */
  if (done) {
    if (fam === "indoles") {
      const xb = lw + 4, half = scaffoldHalfW(ex[0], s);
      line(ctx, xb - 8, mids[0], xb, mids[0], colors.ink1, 1.5); line(ctx, xb, mids[0], xb, mids[1], colors.ink1, 1.5); line(ctx, xb - 8, mids[1], xb, mids[1], colors.ink1, 1.5);
      arrow(ctx, xb, meet, rx - half - 10, meet, colors.ink1);
    } else {
      ex.forEach((m, k) => arrow(ctx, lw - 2, mids[k], rx - scaffoldHalfW(m, s) - 10, mids[k], colors.ink1));
    }
  }
  /* each scaffold's copy moves from its molecule to the right, in its own lane */
  if (pressed) {
    const u = t == null ? 1 : ease(Math.min(1, t / 0.9));
    ex.forEach((m, k) => {
      const from = left[k], to = placeScaffold(m, s, rx, ends[k]);
      drawMol(ctx, colors, m, from.map((p, i) => [lerp(p[0], to[i][0], u), lerp(p[1], to[i][1], u)]), { only: true });
    });
  }
  if (done) {
    const named = fam === "indoles" ? [[ex[0], meet]] : ex.map((m, k) => [m, mids[k]]);
    named.forEach(([m, y]) => {
      const sc = m.atoms.filter((a) => a[3]), my = sc.reduce((q, a) => q + a[2], 0) / sc.length;
      const below = Math.max(...sc.map((a) => (a[2] - my) * s)) + NODE_R + 16;
      txt(ctx, colors, S.scafName(fam, m.group), rx, y + below, { fill: colors.ink1, align: "center", maxW: w - lw - 8 });
    });
  }

  /* the screen as blocks */
  line(ctx, 12, MOL_H, w - 12, MOL_H, colors.grid);
  const b = gridBox(w, MOL_H + 30);
  let kx = keyItem(ctx, colors, 12, MOL_H + 18, colors.surface3, S.active, { active: true });
  txt(ctx, colors, done ? S.fileCapRing : S.fileCap, kx, MOL_H + 19, { fill: done ? colors.ink1 : colors.ink2, maxW: w - kx - 8 });
  const rings = done ? new Set(ex.map((m) => m.group)) : null;
  drawGrid(ctx, colors, b, () => colors.surface3, { ring: rings ? (g) => rings.has(g) : null });
  const hov = groupAt(b, pointer);
  if (hov) hoverLabel(ctx, colors, S.hoverGroup(...GROUPS[hov.g]), pointer.x, pointer.y, w);
}

/* --------------------------------------------------------------- Split */

const partColor = (colors) => [colors.groupA, colors.groupB, colors.holdout];

function drawSplit(ctx, colors, w, params, anim, pointer) {
  const kind = params.split, seed = Number(params.seed), stage = stageOf(params);
  const split = SPLITS[kind][seed], st = STATS[kind][seed];
  const beat = shownStep(anim, stage), t = inFlight(anim, stage);
  const pc = partColor(colors);
  /* the state of cell k: -1 not yet split, 3 held out, else its part */
  /* before Split 80 / 20, the one grid, every cell not yet split */
  const fillOf = () => colors.surface3;

  /* the key names only what is drawn */
  const reached = beat + (t != null ? 1 : 0);
  let x = 12;
  if (reached === 0) x = keyItem(ctx, colors, x, 16, colors.surface3, S.keyNone);
  if (reached >= 1) x = keyItem(ctx, colors, x, 16, pc[0], S.keyTrain);
  if (reached === 1) x = keyItem(ctx, colors, x, 16, colors.ink3, S.keyHeld);
  if (reached >= 2) { x = keyItem(ctx, colors, x, 16, pc[1], S.keyVal); x = keyItem(ctx, colors, x, 16, pc[2], S.keyTest); }
  x = keyItem(ctx, colors, x, 16, colors.surface3, S.active, { active: true });
  const status = reached === 0 ? S.splitStatus[0] : S.splitStatus[Math.min(2, reached)](kind);
  txt(ctx, colors, status, 12, 36, { fill: colors.ink3, maxW: w - 24 });

  const b = gridBox(w, GRID_TOP), P = pairOf(kind, seed);
  if (beat === 0 && t == null) {
    drawGrid(ctx, colors, b, fillOf);
    const hov = groupAt(b, pointer);
    if (hov) hoverLabel(ctx, colors, S.hoverGroup(...GROUPS[hov.g]), pointer.x, pointer.y, w);
  } else if (beat === 0) {
    /* the move: each cell eases from the one grid to its column, held-out cells first */
    const at = (k) => {
      const u = ease(Math.max(0, Math.min(1, (t - P.start[k]) / MOVE.each)));
      const p0 = GRID.cellAt[k], p1 = P.pos[k];
      return [lerp(p0[0], p1[0], u), lerp(p0[1], p1[1], u)];
    };
    drawCells(ctx, colors, b, at, (k) => (t >= P.start[k] ? (split[k] === "0" ? pc[0] : colors.ink3) : colors.surface3));
  } else {
    /* settled in the two columns; Split 50 / 50 colours the held-out column in place */
    const fillCol = (k) => {
      const part = +split[k];
      if (part === 0) return pc[0];
      return beat >= 2 || (t != null && swept(k, t)) ? pc[part] : colors.ink3;
    };
    drawCells(ctx, colors, b, (k) => P.pos[k], fillCol);
    const hov = t == null ? pieceAt(b, P, pointer) : null;
    drawPairFrame(ctx, colors, b, P, { pairG: hov && hov.side != null ? hov.g : null });
    /* cell 30's figure, once all three parts exist */
    if (beat >= 2) drawBars(ctx, colors, w, GRID_TOP + P.h * b.sc + 22, st, pc);
    if (hov) {
      const [n, a] = GROUPS[hov.g], pr = partsOf(kind, seed)[hov.g];
      hoverLabel(ctx, colors, beat >= 2 ? S.hoverParts(n, a, pr) : S.hoverPair(n, a, pr[0], pr[1] + pr[2]), pointer.x, pointer.y, w);
    }
  }
}

function drawBars(ctx, colors, w, top, st, pc) {
  const pw = Math.min(150, (w - 70) / 3 - 18), ph = 72, gap = (w - 52 - 3 * pw) / 2;
  for (let p = 0; p < 3; p++) {
    /* the title clear of a tall bar's share above it (the overlap sweep: "Validation" × "95.6%") */
    const x0 = 46 + p * (pw + gap), y0 = top + 28, share = st.act[p] / st.n[p];
    txt(ctx, colors, S.barTitle[p], x0 + pw / 2, top + 8, { font: capFont(colors), fill: colors.ink1, align: "center" });
    line(ctx, x0, y0, x0, y0 + ph, colors.axis); line(ctx, x0, y0 + ph, x0 + pw, y0 + ph, colors.axis);
    if (p === 0) {
      txt(ctx, colors, "1", x0 - 5, y0 + 4, { fill: colors.ink3, align: "right" });
      txt(ctx, colors, "0", x0 - 5, y0 + ph + 3, { fill: colors.ink3, align: "right" });
      ctx.save(); ctx.translate(x0 - 22, y0 + ph / 2); ctx.rotate(-Math.PI / 2);
      txt(ctx, colors, S.barY, 0, 0, { fill: colors.ink3, align: "center" }); ctx.restore();
    }
    [1 - share, share].forEach((v, lab) => {
      const bw = Math.min(40, pw * 0.3), bx = x0 + pw * (lab === 0 ? 0.28 : 0.72) - bw / 2, bh = v * ph;
      rect(ctx, bx, y0 + ph - bh, bw, bh, pc[p]);
      txt(ctx, colors, pct(v), bx + bw / 2, y0 + ph - bh - 4, { fill: colors.ink1, align: "center" });
      txt(ctx, colors, String(lab), bx + bw / 2, y0 + ph + 13, { fill: colors.ink3, align: "center" });
    });
  }
  txt(ctx, colors, S.barX, w / 2, top + 28 + ph + 28, { fill: colors.ink3, align: "center" });
}

/* ------------------------------------------------------------ Evaluate */

const F1 = SEEDS.flatMap((s) => [STATS.label[s].f1, STATS.scaffold[s].f1]);
const F1_LO = Math.floor(Math.min(...F1) * 10) / 10, F1_HI = Math.ceil(Math.max(...F1) * 10) / 10;
const meanF1 = (kind) => SEEDS.reduce((t, s) => t + STATS[kind][s].f1, 0) / SEEDS.length;

function drawEvaluate(ctx, colors, w, params, anim, pointer) {
  const kind = params.split, seed = Number(params.seed), stage = stageOf(params);
  const split = SPLITS[kind][seed], parts = partsOf(kind, seed);
  const beat = shownStep(anim, stage), t = inFlight(anim, stage), pc = partColor(colors);
  const P = pairOf(kind, seed);
  /* the test set is the subject: validation washed back; Train keeps its colour, it is what test is compared with */
  const fillOf = (k) => { const p = +split[k]; return p === 1 ? wash(pc[1], 0.35) : pc[p]; };
  const sharedGroup = (g) => parts[g][2] > 0 && parts[g][0] > 0;
  /* Compare rings both pieces of every shared scaffold, in the columns' order, as a sweep */
  const ringOn = beat >= 1 ? (o) => sharedGroup(o.g) : t != null ? (o, i) => sharedGroup(o.g) && t >= (i / P.outlines.length) * SWEEP_END : null;

  let x = 12;
  x = keyItem(ctx, colors, x, 16, pc[0], S.keyTrain);
  x = keyItem(ctx, colors, x, 16, wash(pc[1], 0.35), S.keyVal);
  x = keyItem(ctx, colors, x, 16, pc[2], S.keyTest);
  x = keyItem(ctx, colors, x, 16, colors.surface3, S.active, { active: true });
  txt(ctx, colors, beat >= 1 || t != null ? S.evStatus[1] : S.evStatus[0](kind), 12, 36, { fill: beat >= 1 || t != null ? colors.ink1 : colors.ink3, maxW: w - 24 });

  const b = gridBox(w, GRID_TOP);
  drawCells(ctx, colors, b, (k) => P.pos[k], fillOf);
  const hov = pieceAt(b, P, pointer);
  drawPairFrame(ctx, colors, b, P, { ring: ringOn, pairG: hov && hov.side != null ? hov.g : null });

  /* under the columns as drawn: a grid scaled to a narrow canvas left a gap above the chart */
  drawScores(ctx, colors, w, GRID_TOP + P.h * b.sc + 22, params, anim);

  if (hov) { const [n, a] = GROUPS[hov.g]; hoverLabel(ctx, colors, S.hoverParts(n, a, parts[hov.g]), pointer.x, pointer.y, w); }
}

/* each split's column fills when ITS Score lands, and stays: the comparison
   is between the two columns, so a column scored earlier is kept */
function drawScores(ctx, colors, w, top, params, anim) {
  const x0 = 52, pw = w - x0 - 20, y0 = top + 26, ph = SCORE_H - 62;
  const sy = (v) => y0 + ph - ((v - F1_LO) / (F1_HI - F1_LO)) * ph;
  txt(ctx, colors, S.scoreHead, 12, top + 10, { font: capFont(colors), fill: colors.ink1, maxW: w - 24 });
  line(ctx, x0, y0, x0, y0 + ph, colors.axis);
  for (let v = F1_LO; v <= F1_HI + 1e-9; v += 0.1) {
    line(ctx, x0 - 4, sy(v), x0, sy(v), colors.axis);
    txt(ctx, colors, v.toFixed(1), x0 - 6, sy(v) + 3, { fill: colors.ink3, align: "right" });
  }
  ["label", "scaffold"].forEach((k, c) => {
    const cx = x0 + pw * (c === 0 ? 0.27 : 0.68), cur = k === params.split, st = `evaluate-${k}`;
    const n = shownStep(anim, st), tf = inFlight(anim, st);
    const ink = cur ? colors.ink1 : colors.ink3;
    txt(ctx, colors, S.colName[k], cx, y0 + ph + 18, { fill: ink, align: "center", font: cur ? `600 ${colors.fsXs} ${colors.font}` : null });
    /* dots appear one a seed while Score is in flight */
    const shown = n >= 2 ? SEEDS.length : n === 1 && tf != null ? Math.floor(SEEDS.length * Math.min(1, tf / SWEEP_END)) : 0;
    const dx = 9, xL = cx - ((SEEDS.length - 1) * dx) / 2;
    SEEDS.slice(0, shown).forEach((s, i) => {
      const v = STATS[k][s].f1;
      dot(ctx, xL + i * dx, sy(v), 3.2, ink);
      if (s === Number(params.seed) && cur) dot(ctx, xL + i * dx, sy(v), 6.5, null, colors.highlight, 2);
    });
    if (n >= 2) {
      const m = meanF1(k), half = ((SEEDS.length - 1) * dx) / 2 + 8;
      line(ctx, cx - half, sy(m), cx + half, sy(m), ink, 1.5);
      txt(ctx, colors, S.meanTag(m.toFixed(2)), cx + half + 6, sy(m) + 3, { fill: ink });
    }
  });
}

/* ------------------------------------------------------------- widget */

defineWidget({
  slug: "scaffold-split",
  status: "draft",
  title: "Deep Learning - Graphs: Scaffold Split",
  subtitle: S.subtitle,
  credit: "Molecule data: Stokes et al., Cell 2020, via FinGAT",
  layout: "side",
  height: (params) => (params.page === "scaffold" ? H_SCAF : params.page === "split" ? H_SPLIT(params) : H_EVAL(params)),
  pointer: true,

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "scaffold", display: true },
    example: { type: "segmented", label: S.exampleLabel, detail: S.exampleDetail, options: EXAMPLE_OPTS, default: "indoles", display: true, when: ON("scaffold") },
    split: { type: "segmented", label: S.splitLabel, detail: S.splitDetail, options: SPLIT_OPTS, default: "label", display: true, when: { param: "page", oneOf: ["split", "evaluate"] } },
    seed: { type: "int", label: S.seedLabel, detail: S.seedDetail, min: SEEDS[0], max: SEEDS[SEEDS.length - 1], default: 42, display: true, when: { param: "page", oneOf: ["split", "evaluate"] } },
    /* authoring escape hatch, first render only: presses already made on the stage the link opens */
    shown: { type: "int", min: 0, max: 2, default: 0, hidden: true },
  },

  /* none: every mark that needs naming appears with a press, and a legend reads
     params alone (95's walk-through) — each page keys its marks on the canvas */
  legend: [],

  compute: () => ({}),

  animation: {
    stepLabel: S.stepLabel,
    stepTitle: S.stepTitle,
    /* each press is read, once: Step alone (play-only-for-motion-or-repetition) */
    runLabel: null,

    init: ({ params, fromScratch }) => {
      const stage = stageOf(params);
      const anim = { stage, n: {}, t: 1, dur: DUR.scaffold, halt: false };
      anim.n[stage] = fromScratch ? 0 : Math.max(0, Math.min(stepsOf(stage), Number(params.shown) || 0));
      anim.beat = anim.n[stage];
      anim.done = anim.n[stage] >= stepsOf(stage);
      return anim;
    },

    advance: (anim, { dt }) => {
      /* a press a stage switch interrupted ends here, before the new stage's (mid-press-page-switch) */
      if (anim.halt) { anim.halt = false; return false; }
      const stage = anim.stage;
      if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
      else if ((anim.n[stage] ?? 0) < stepsOf(stage)) {
        anim.n[stage] = (anim.n[stage] ?? 0) + 1;
        anim.dur = DUR[stage.split("-")[0]];
        anim.t = 0;
      }
      anim.beat = anim.n[stage] ?? 0;
      anim.done = anim.beat >= stepsOf(stage) && anim.t >= 1;
      return anim.t < 1;
    },

    rebuild: (anim, { params }) => {
      const stage = stageOf(params);
      /* only a change of stage ends a press in flight; a new seed keeps it */
      if (stage !== anim.stage && anim.t < 1) { anim.t = 1; anim.halt = true; }
      anim.stage = stage;
      anim.beat = anim.n[stage] ?? 0;
      anim.done = anim.beat >= stepsOf(stage) && anim.t >= 1;
    },
  },

  draw({ ctx, colors, w, params, anim, pointer }) {
    if (params.page === "scaffold") drawScaffold(ctx, colors, w, params, anim, pointer);
    else if (params.page === "split") drawSplit(ctx, colors, w, params, anim, pointer);
    else drawEvaluate(ctx, colors, w, params, anim, pointer);
  },

  readout({ params, anim }) {
    const stage = stageOf(params), beat = shownStep(anim, stage);
    if (params.page === "scaffold") {
      const ex = EXAMPLES[params.example], nScaf = new Set(ex.map((m) => m.group)).size;
      return [
        { label: S.tileMol, value: fmtN(FILE.rows), note: S.tileMolNote },
        { label: S.tileScaf, value: fmtN(FILE.scaffolds), note: S.tileScafNote(GROUPS[NAMED.benzene][0]) },
        { label: S.tileEx, value: beat >= 1 ? String(nScaf) : S.tileWait, note: S.tileExNote(params.example) },
      ];
    }
    const st = STATS[params.split][Number(params.seed)];
    if (params.page === "split") {
      return [0, 1, 2].map((p) => {
        const ready = p === 0 ? beat >= 1 : beat >= 2;
        return { label: S.tilePart[p], value: ready ? fmtN(st.n[p]) : S.tileWait, note: ready ? S.tilePartNote(st.act[p], st.n[p]) : "" };
      });
    }
    return [
      { label: S.tileShared, value: beat >= 1 ? `${st.shared} of ${st.n[2]}` : S.tileWait, note: S.tileSharedNote },
      { label: S.tileSharedAct, value: beat >= 1 ? `${st.sharedAct} of ${st.act[2]}` : S.tileWait, note: S.tileSharedActNote },
      { label: S.tileF1, value: beat >= 2 ? st.f1.toFixed(2) : S.tileWait, note: S.tileF1Note(meanF1(params.split).toFixed(2)) },
    ];
  },

  summary({ params, anim }) {
    const stage = stageOf(params), beat = shownStep(anim, stage);
    if (params.page === "scaffold") return S.sumScaf(params.example, beat >= 1);
    const st = STATS[params.split][Number(params.seed)];
    if (params.page === "split") return S.sumSplit(params.split, params.seed, beat, st);
    return S.sumEval(params.split, params.seed, beat, st);
  },
});
