/* ============================================================================
   Widget 87 · Language: Explainability (`explainability`) — PHM5005
   08-1 cell 20, 08-2 cells 66–76, 08-3 cells 79–89. DRAFT 2026-10-04, built to his
   eight picks (catalogue § Slot 87; mock `_lab/explainability-mock.html`).

   ONE ANSWER, THREE WAYS OF GETTING IT. Every page draws the same STRIP in the same
   place — the tokens with the heat behind them (the lessons' overlay) over a bar a
   token (the lessons' bar chart) — and the page's MECHANISM under it:

     ATTENTION              the [CLS] row of one block's attention matrix, a head or
                            the mean of the four; the matrix under the strip, its
                            columns under the strip's tokens, so the strip IS its
                            first row. A press carries the next key's weight up.
     INTEGRATED GRADIENTS   the predicted class's logit along the straight path from
                            the baseline (α 0) to the input (α 1); a press is the
                            next step along it, the bars the running sum. The
                            completeness line says how far the sum is from
                            f(input) − f(baseline) (measured: 0.67 · 0.15 · 0.055 ·
                            0.010 at 5 · 20 · 50 · 300 steps). Show Signed ·
                            Positive only (the lesson's clip, scaled 0–1).
     OCCLUSION              a window replaced by [PAD] at a time, the logit with each
                            window charted under the strip; a position's bar is the
                            mean drop over the windows covering it (captum's rule).

   WHAT IS EXPLAINED is 85's own models (his pick): its Training control (default
   Transfer, the lesson's model) and its Task control, on its four held-out rows a
   task (Example 1–4, or a click on a row). Measured first: the attribution follows
   the MODEL (Drug error, Full: the drug or the symptom is the largest word in 152 of
   200 notes; Transfer at chance: "for" in 115), so the copy says what was measured
   and never says what a model "uses" ([[label-rule-not-model-reason]]).

   [CLS] (measured, his picks): the lesson's IG baseline sets EVERY id to [PAD],
   [CLS] included, and the head reads [CLS]'s row, so [CLS] can take the largest
   attribution (in up to 162 of 200 notes) — kept as the lesson's, with a caption.
   captum's occlusion slides over [CLS] too, and that window then dominates (1.4–3×
   any residue window on proteins), so the windows here cover words or residues
   ONLY, captioned. The strip's scale is the largest word or residue; a special
   token past it is clipped with a mark and its value printed.

   NOTHING RUNS IN THE BROWSER: every number is read from `table.js`, GENERATED by
   `_lab/explainability-table.py` (torch, on 85's models rebuilt and checked against
   85's table) and checked by `_lab/explainability-verify.mjs`.

   Colours: the signed values on --c-value-high (raises the predicted class's logit)
   and --c-value-low (lowers it), as 75's occlusion and 64's gradients; attention
   weights on --c-magnitude with a √ ramp, as 83 draws them. So --c-highlight is
   never used here (it shares --c-magnitude's slot): the moving window and the
   current step are marked in ink. EACH PAGE KEEPS ITS OWN PLACE (`anim.p[page]`); a
   page switch mid-press finishes the press (widget 70's rule). Tweens only move (his
   rule, 2026-09-26): a key's weight rides up to the strip, the α marker and the
   window slide; appearances switch at once.
   ========================================================================= */

import { defineWidget } from "../core/index.js";
import { TABLE } from "./table.js";

/* ================================================================== copy */

const PAGES = [
  { value: "attention", label: "Attention", detail: "The weights in one row of an attention matrix: how much the [CLS] token's query matches each token's key; the prediction is computed from [CLS]'s final vector." },
  /* two lines: "Integrated gradients" is wider than a third of the rail */
  { value: "integrated-gradients", label: "Integrated", qual: "gradients", detail: "The change from a baseline input to the input, times the gradient of the predicted class's logit averaged along the straight path between them." },
  { value: "occlusion", label: "Occlusion", detail: "A window of tokens replaced by [PAD], then the next window along, and the change in the predicted class's logit each time." },
];
const WAYS = {
  scratch: { label: "From scratch", group: "Random weights", name: "From scratch", detail: "Trained from random weights on 1,024 labelled examples." },
  transfer: { label: "Transfer", group: "Pretrained weights", name: "Transfer", detail: "The pretrained backbone frozen; only a new head trained on 1,024 labelled examples." },
  full: { label: "Full", group: "Pretrained weights", name: "Full fine-tuning", detail: "Every weight trained on 1,024 labelled examples, starting from the pretrained ones." },
  lora: { label: "LoRA", group: "Pretrained weights", name: "LoRA", detail: "The backbone frozen; a low-rank update to the Q and V weights, and the head, trained on 1,024 labelled examples." },
};
const TRAINING = Object.entries(WAYS).map(([value, w]) => ({ value, label: w.label, group: w.group, detail: w.detail }));
const DATA_NAME = { notes: "Clinical notes", proteins: "HA proteins" };
const TASKS = [
  { value: "outcome", label: "Outcome", group: DATA_NAME.notes, detail: "1 abnormal when the note asserts an abnormal finding, 0 normal otherwise. Synthetic notes." },
  { value: "drug-error", label: "Drug error", group: DATA_NAME.notes, detail: "1 error when the drug does not treat the symptom, 0 no error when it does. Synthetic notes." },
  { value: "influenza-host", label: "Influenza host", group: DATA_NAME.proteins, detail: "1 human when the virus was isolated from a person, 0 animal. HA sequences from BV-BRC." },
];
/* OUTCOME'S WORDS (2026-10-05, his pick after "positive = positive outcome or yes for illness?"): the lesson's
   clinical_outcome.csv has 1 = deteriorating, 0 = stable, so "positive" read as a good outcome; normal / abnormal says it */
const LABELS = { outcome: ["normal", "abnormal"], "drug-error": ["no error", "error"], "influenza-host": ["animal", "human"] };
const PROTEIN = (task) => TABLE.model[task] === "proteins";
const NOUN = (task) => (PROTEIN(task) ? "proteins" : "notes");
const UNIT = (task, n) => (PROTEIN(task) ? (n === 1 ? "residue" : "residues") : n === 1 ? "word" : "words");

const S = {
  title: "Deep Learning - Language: Explainability",
  /* his T1 (2026-10-05, after S2): attention first, the natural reading, then why it can mislead (measured: attention
     against |IG| 0.15–0.52), then the attribution scores; no line on models scoring differently */
  subtitle: "Attention weights show how much one token's query matches each key, but a large weight need not mean that token changed "
    + "the prediction. Attribution scores measure that change directly: integrated gradients adds up gradients along a path from a "
    + "baseline to the input, and occlusion replaces a window of the input and measures the change.",
  pageLabel: "Method", trainingLabel: "Training", taskLabel: "Task", exampleLabel: "Example",
  blockLabel: "Block", blockDetail: "Block 1's input is the token and position vectors; block 2's is block 1's output.",
  headLabel: "Head", headDetail: "One head's weights, or the mean of the four heads'.",
  stepsLabel: "Steps", stepsDetail: "How many points along the path the gradient is taken at.",
  showLabel: "Show", showDetail: "Positive only keeps the attributions above zero and divides them by the largest.",
  wordsLabel: "Window", wordsDetail: "How many words each window replaces; it moves by half a window, at least one word.",
  residuesLabel: "Window", residuesDetail: "How many residues each window replaces; it moves by half a window.",
  rowsHead: (n) => `Four of the 1,000 held-out ${n}`,
  predHead: (way) => `prediction · ${WAYS[way].name}`,
  stripHead: {
    attention: (b, h) => `Attention from [CLS], block ${b}, ${h === "mean" ? "mean of the four heads" : `head ${h}`}`,
    "integrated-gradients": (s, pos) => `Integrated gradients, ${s} steps${pos ? ", positive only, scaled 0–1" : ""}`,
    occlusion: (k, task) => `Occlusion, a window of ${k} ${UNIT(task, k)}`,
  },
  predicted: (task, e) => `prediction ${LABELS[task][e.pred]} ${prob(e).toFixed(2)}`,
  attHead: (b, h) => `Block ${b}, ${h === "mean" ? "the mean of the heads" : `head ${h}`}: a row a query, a column a key`,
  attHeadProt: (b, h) => `Block ${b}, ${h === "mean" ? "the mean of the heads" : `head ${h}`}, in bins of ${TABLE.bin} positions: a row a query, a column a key`,
  queryAxis: "query position", keyAxis: "key position",
  igHead: "The predicted class's logit, f, along the path",
  alpha0: "α = 0: every token [PAD]", alpha1: (task) => `α = 1: the ${PROTEIN(task) ? "protein" : "note"}`,
  igSum: (k, s, sum) => `after ${k} of ${s} steps the bars sum to ${f2(sum)}`,
  igDone: (sum, d, gap) => `the bars sum to ${f2(sum)} · f(input) − f(baseline) = ${f2(d)} · gap ${gap.toFixed(3)}`,
  occHead: "The predicted class's logit with each window replaced by [PAD]",
  occNone: "no window",
  occCount: (i, n, k, st, task) => `${i} of ${n} windows · ${k} ${UNIT(task, k)} each, every ${st}`,
  caption: {
    attention: "The bars above are the matrix's [CLS] row: the weight on each key when [CLS] is the query.",
    "integrated-gradients": "The baseline sets every token to [PAD], [CLS] and [SEP] included; the prediction is computed from [CLS]'s final vector.",
    occlusion: (task) => `Windows cover ${UNIT(task, 2)} only, not [CLS] or [SEP]: the prediction is computed from [CLS]'s final vector.`,
  },
  step: { attention: "Next key", "integrated-gradients": "Next step", occlusion: "Next window" },
  stepProt: { attention: "Next 50 keys" },
  stepTitle: {
    attention: "Show the next key's weight from the [CLS] row above its token",
    "integrated-gradients": "Take the gradient at the next point along the path and add it to the bars",
    occlusion: "Replace the next window by [PAD] and chart the logit",
  },
  tilePred: "Prediction", tilePredNote: (n) => `this model, this ${n === "notes" ? "note" : "protein"}`,
  tileAcc: "Held out", tileAccNote: (n) => `accuracy on 1,000 ${n}`,
  tileTop: "Largest weight", tileTopNote: (w, aa) => `${aa ? `${aa}, ` : ""}from [CLS], ${w.toFixed(2)}`,
  tileGap: "Gap", tileGapNote: "sum of the bars against f(input) − f(baseline)",
  tileWin: "Windows", tileWinNote: (k, st, task) => `${k} ${UNIT(task, k)} each, every ${st}`,
  wait: "—",
  legend: {
    up: "Raises the predicted class's logit", down: "Lowers the predicted class's logit", att: "Attention weight", pos: "Positive attribution, scaled to the largest",
  },
  sum: (page, task, i) => `${{ attention: "Attention", "integrated-gradients": "Integrated gradients", occlusion: "Occlusion" }[page]} on held-out ${NOUN(task).slice(0, -1)} ${i}.`,
};

/* ============================================================ the data */

const bytes = (b64) => Uint8Array.from(atob(b64), (c) => c.charCodeAt(0));
const unsigned = (b64, scale) => Float32Array.from(bytes(b64), (b) => (b / 255) * scale);
const signedOf = (b64, scale) => Float32Array.from(bytes(b64), (b) => ((b > 127 ? b - 256 : b) / 127) * scale);
const prob = (e) => { const m = Math.max(...e.logits), z = e.logits.map((v) => Math.exp(v - m)); return z[e.pred] / (z[0] + z[1]); };
const rowOf = (p) => TABLE.rows[p.task][p.training][Number(p.example) - 1];
const exampleOf = (p) => TABLE.examples[p.task][Number(p.example) - 1];
/** the tokens of a row: a note's words, or a protein's residues, between [CLS] and [SEP] */
const tokensOf = (p) => { const [s] = exampleOf(p); return ["[CLS]", ...(PROTEIN(p.task) ? [...s.slice(0, rowOf(p).ig["5"].attr.length - 2)] : s.split(" ")), "[SEP]"]; };
const f2 = (v) => { const r = Math.abs(v) < 0.005 ? 0 : v; return (r < 0 ? "−" : "") + Math.abs(r).toFixed(2); };
const windowOf = (p) => Number(PROTEIN(p.task) ? p.window : p.words);
const strideOf = (k) => Math.max(1, Math.floor(k / 2));

/** the [CLS] row of the chosen block and head (or the mean of the heads), every key */
const CACHE = {};
function clsRow(p) {
  const e = rowOf(p), b = Number(p.block) - 1, heads = p.head === "mean" ? [0, 1, 2, 3] : [Number(p.head) - 1];
  const key = `cls/${p.task}/${p.training}/${p.example}/${p.block}/${p.head}`;
  if (CACHE[key]) return CACHE[key];
  let out;
  if (PROTEIN(p.task)) {
    const rows = heads.map((h) => unsigned(e.att.cls[b * 4 + h], e.att.clsScale[b * 4 + h]));
    out = Float32Array.from(rows[0], (_, j) => rows.reduce((a, r) => a + r[j], 0) / rows.length);
  } else {
    const L = Math.round(Math.sqrt(e.att[b][0].length));
    out = Float32Array.from({ length: L }, (_, j) => heads.reduce((a, h) => a + e.att[b][h][j], 0) / heads.length);
  }
  return (CACHE[key] = out);
}
/** the attention matrix shown under the strip: notes L x L, proteins pooled into bins */
function attMatrix(p) {
  const e = rowOf(p), b = Number(p.block) - 1, heads = p.head === "mean" ? [0, 1, 2, 3] : [Number(p.head) - 1];
  const key = `mat/${p.task}/${p.training}/${p.example}/${p.block}/${p.head}`;
  if (CACHE[key]) return CACHE[key];
  let n, m;
  if (PROTEIN(p.task)) {
    n = e.att.bins; const mats = heads.map((h) => unsigned(e.att.pooled[b * 4 + h], e.att.pooledScale[b * 4 + h]));
    m = Float32Array.from(mats[0], (_, j) => mats.reduce((a, x) => a + x[j], 0) / mats.length);
  } else {
    n = Math.round(Math.sqrt(e.att[b][0].length));
    m = Float32Array.from(e.att[b][0], (_, j) => heads.reduce((a, h) => a + e.att[b][h][j], 0) / heads.length);
  }
  return (CACHE[key] = { n, m });
}
/** IG's running sum after checkpoint c (1-based; 0 is all zeros) */
function igPart(p, c) {
  const g = rowOf(p).ig[p.steps], L = g.attr.length;
  if (c <= 0) return new Float32Array(L);
  if (!PROTEIN(p.task)) return Float32Array.from(g.part[c - 1]);
  const key = `ig/${p.task}/${p.training}/${p.example}/${p.steps}`;
  const all = CACHE[key] ?? (CACHE[key] = signedOf(g.part, g.pscale));
  return all.subarray((c - 1) * L, c * L);
}
/** occlusion's windows: their first position (1-based over the tokens, [CLS] is 0) and the logit's drop */
function windows(p) {
  const e = rowOf(p), k = windowOf(p), st = strideOf(k), d = e.occ[String(k)];
  return d.map((v, i) => ({ s: 1 + i * st, k, d: v }));
}
/** each position's attribution from the first n windows: the mean drop over the windows covering it */
function occValues(p, n) {
  const L = rowOf(p).ig["5"].attr.length, tot = new Float32Array(L), cnt = new Float32Array(L);
  windows(p).slice(0, n).forEach(({ s, k, d }) => { for (let i = s; i < s + k; i++) { tot[i] += d; cnt[i] += 1; } });
  return Float32Array.from(tot, (v, i) => (cnt[i] ? v / cnt[i] : 0));
}

/* ============================================================ drawing kit */

const PAD = 12;
const cap = (c) => `600 ${c.fsSm} ${c.font}`;
const small = (c) => `${c.fsXs} ${c.font}`;
const smallBold = (c) => `600 ${c.fsXs} ${c.font}`;
const body = (c) => `${c.fsSm} ${c.font}`;
const monoS = (c) => `${c.fsSm} ${c.mono}`;
const monoX = (c) => `${c.fsXs} ${c.mono}`;
function txt(ctx, s, x, y, { font, fill, align = "left", baseline = "middle" }) {
  ctx.save(); ctx.font = font; ctx.fillStyle = fill; ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
function line(ctx, pts, stroke, lw = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); pts.forEach(([x, y], i) => (i ? ctx.lineTo(x, y) : ctx.moveTo(x, y))); ctx.stroke(); ctx.restore();
}
/** a caption over as many lines as it needs, a word at a time */
function wrap(ctx, s, x, y, room, lh, style) {
  let lineText = "", yy = y;
  for (const word of s.split(" ")) {
    const next = lineText ? `${lineText} ${word}` : word;
    if (lineText && width(ctx, next, style.font) > room) { txt(ctx, lineText, x, yy, style); lineText = word; yy += lh; } else lineText = next;
  }
  if (lineText) txt(ctx, lineText, x, yy, style);
}
const width = (ctx, s, font) => { ctx.save(); ctx.font = font; const v = ctx.measureText(s).width; ctx.restore(); return v; };
const rgb = (c) => { const m = String(c).match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : [128, 128, 128]; };
const mix = (a, b, u) => `rgb(${a.map((x, i) => Math.round(x + (b[i] - x) * Math.max(0, Math.min(1, u)))).join(",")})`;
/** the signed ramp: --surface-3 at zero, --c-value-high above, --c-value-low below */
const heat = (c, v, sc) => mix(rgb(c.surface3), rgb(v >= 0 ? c.valueHigh : c.valueLow), Math.abs(v) / (sc || 1));
/** an attention weight on 83's ramp, from --surface-3 to --c-magnitude, √ so small weights still show */
const weightFill = (c, v, sc) => mix(rgb(c.surface3), rgb(c.magnitude), Math.sqrt(Math.max(0, v) / (sc || 1)));

/* ============================================================ geometry */

/* every vertical position in one place, so the drawing and the height cannot disagree */
const ROWS_HEAD = 14, ROW0 = 36, ROW_PITCH = 20, ROW_LAB = 96;
const STRIP_HEAD = 132, TOK_Y = 160, BAR = 32, ZERO = TOK_Y + 14 + BAR, STRIP_END = ZERO + BAR + 22;
const MECH = STRIP_END + 22;
const CELL_H = 16, MAT_S = 288, CHART_H = 130;
/** the strip's left edge: room for the matrix's row labels under it */
const X0 = PAD + 104;
const maxTokens = (task) => Math.max(...TABLE.examples[task].map(([s]) => s.split(" ").length + 2));
function mechHeight(page, task) {
  if (page === "attention") return PROTEIN(task) ? 22 + MAT_S + 30 : 22 + maxTokens(task) * CELL_H + 12;
  return 22 + CHART_H + 50;
}
/* the caption at the foot takes two lines: at a 534 px canvas the IG caption is 24 px too long for one */
const CAP_H = 44;
const heightOf = (page, task) => MECH + mechHeight(page, task) + CAP_H;

/** where each token sits in the strip. Notes: a box a word, laid from X0. Proteins: [CLS] and [SEP] as labelled
    boxes at the ends, the residues as columns between them. */
function stripGeo(ctx, c, w, p) {
  const toks = tokensOf(p), L = toks.length;
  if (PROTEIN(p.task)) {
    const sw = 40, a = X0 + sw + 4, b = w - PAD - sw - 4, pitch = (b - a) / (L - 2);
    const cells = toks.map((_, i) => (i === 0 ? { x: X0, w: sw } : i === L - 1 ? { x: w - PAD - sw, w: sw } : { x: a + (i - 1) * pitch, w: pitch }));
    return { toks, L, cells, font: monoX(c), prot: true, a, b, pitch };
  }
  let font = body(c), gap = 6, ws = toks.map((s) => width(ctx, s, font) + 10);
  const room = w - PAD - X0;
  /* equal columns when every word fits one, up to 96 px: the matrix under the strip reads as a grid */
  const col = Math.min(96, (room - gap * (L - 1)) / L);
  if (ws.every((x) => x <= col)) ws = ws.map(() => col);
  if (ws.reduce((x, y) => x + y, 0) + gap * (L - 1) > room) { font = small(c); gap = 4; ws = toks.map((s) => width(ctx, s, font) + 8); }
  const tot = ws.reduce((x, y) => x + y, 0) + gap * (L - 1), squeeze = Math.min(1, (room - gap * (L - 1)) / (tot - gap * (L - 1)));
  let x = X0; const cells = ws.map((cw) => { const cell = { x, w: cw * squeeze }; x += cw * squeeze + gap; return cell; });
  return { toks, L, cells, font, prot: false };
}

/* ============================================================ the strip */

/** values per token (null = not yet revealed); `signed` for attributions, false for attention weights */
function drawStrip(ctx, c, w, p, G, vals, { signed, scale, title, e }) {
  txt(ctx, title, PAD, STRIP_HEAD, { font: cap(c), fill: c.ink1 });
  txt(ctx, S.predicted(p.task, e), w - PAD, STRIP_HEAD, { font: small(c), fill: c.ink2, align: "right" });
  line(ctx, [[X0, ZERO + 0.5], [w - PAD, ZERO + 0.5]], c.grid);
  txt(ctx, "0", X0 - 6, ZERO, { font: small(c), fill: c.ink3, align: "right" });
  const fill = (v) => (signed ? heat(c, v, scale) : weightFill(c, v, scale));
  G.cells.forEach((cell, i) => {
    const v = vals ? vals[i] : null, special = i === 0 || i === G.L - 1, boxed = !G.prot || special;
    const cx = cell.x + cell.w / 2;
    if (boxed) {
      ctx.save(); ctx.fillStyle = v == null ? c.surface2 : fill(v); ctx.fillRect(cell.x, TOK_Y - 10, cell.w, 20); ctx.restore();
      txt(ctx, G.toks[i], cx, TOK_Y, { font: G.prot ? small(c) : G.font, fill: c.ink1, align: "center" });
    } else {
      ctx.save(); ctx.fillStyle = v == null ? c.surface2 : fill(v); ctx.fillRect(cell.x, TOK_Y - 10, Math.max(1, cell.w + 0.3), 20); ctx.restore();
    }
    if (v == null) return;
    const over = Math.abs(v) > scale * 1.0001, hgt = (Math.min(Math.abs(v), scale) / (scale || 1)) * BAR;
    const bw = G.prot && !special ? Math.max(1, cell.w + 0.3) : Math.min(10, cell.w - 2);
    ctx.save(); ctx.fillStyle = signed ? (v >= 0 ? c.valueHigh : c.valueLow) : c.magnitude;
    if (v < 0) ctx.fillRect(cx - bw / 2, ZERO, bw, hgt); else ctx.fillRect(cx - bw / 2, ZERO - hgt, bw, hgt);
    ctx.restore();
    /* past the scale (a special token): the bar is clipped and broken by two strokes near its end, the value printed */
    if (over) for (const dy of [7, 11]) { const y = v >= 0 ? ZERO - BAR + dy : ZERO + BAR - dy; line(ctx, [[cx - bw / 2 - 1, y + 1.5], [cx + bw / 2 + 1, y - 1.5]], c.surface, 1.5); }
    if (boxed) txt(ctx, signed ? f2(v) : v.toFixed(2), cx, v < 0 ? ZERO + hgt + 9 : ZERO + 9, { font: monoX(c), fill: c.ink3, align: "center" });
  });
  if (G.prot) {
    const L = G.L;
    for (let r = 100; r < L - 1; r += 100) { const x = G.a + (r - 0.5) * G.pitch; line(ctx, [[x, TOK_Y + 11], [x, TOK_Y + 14]], c.ink3); txt(ctx, String(r), x, STRIP_END - 6, { font: small(c), fill: c.ink3, align: "center" }); }
    txt(ctx, "1", G.a, STRIP_END - 6, { font: small(c), fill: c.ink3, align: "left" });
  }
}

/* ============================================================ the rows */

function drawRows(ctx, c, w, p) {
  txt(ctx, S.rowsHead(NOUN(p.task)), PAD, ROWS_HEAD, { font: cap(c), fill: c.ink1 });
  txt(ctx, S.predHead(p.training), w - PAD, ROWS_HEAD, { font: small(c), fill: c.ink3, align: "right" });
  TABLE.examples[p.task].forEach(([t, y], i) => {
    const yy = ROW0 + i * ROW_PITCH, on = Number(p.example) === i + 1, e = TABLE.rows[p.task][p.training][i];
    if (on) { ctx.save(); ctx.fillStyle = c.surface2; ctx.fillRect(PAD - 4, yy - 10, w - 2 * PAD + 8, 20); ctx.restore(); }
    ctx.save(); ctx.strokeStyle = c.ink3; ctx.strokeRect(PAD + 0.5, yy - 9.5, ROW_LAB - 6, 19); ctx.restore();
    txt(ctx, `${y} ${LABELS[p.task][y]}`, PAD + (ROW_LAB - 6) / 2, yy, { font: small(c), fill: c.ink1, align: "center" });
    const pr = `${LABELS[p.task][e.pred]} ${prob(e).toFixed(2)}`, right = e.pred === y;
    const predW = width(ctx, pr, small(c)) + 22;
    if (PROTEIN(p.task)) {
      const cw = width(ctx, "M", monoS(c)), room = w - PAD - predW - (PAD + ROW_LAB) - 40;
      const shown = `${t.slice(0, Math.max(4, Math.floor(room / cw) - 1))}…`;
      txt(ctx, shown, PAD + ROW_LAB, yy, { font: monoS(c), fill: c.ink1 });
      txt(ctx, String(t.length), PAD + ROW_LAB + width(ctx, shown, monoS(c)) + 8, yy, { font: small(c), fill: c.ink3 });
    } else txt(ctx, t, PAD + ROW_LAB, yy, { font: on ? `600 ${c.fsSm} ${c.font}` : body(c), fill: c.ink1 });
    txt(ctx, right ? "✓" : "✗", w - PAD, yy, { font: cap(c), fill: c.ink1, align: "right" });
    txt(ctx, pr, w - PAD - 16, yy, { font: small(c), fill: right ? c.ink1 : c.ink2, align: "right" });
  });
}

/* ============================================================ the mechanisms */

/** ATTENTION. Notes: the whole matrix, its columns under the strip's tokens, a row label a query; the [CLS] row
    outlined, since the strip is that row. Proteins: the matrix in bins of 8 positions, square. */
function drawAttention(ctx, c, w, p, G, prog) {
  const { n, m } = attMatrix(p), b = p.block, h = p.head;
  if (G.prot) {
    txt(ctx, S.attHeadProt(b, h), PAD, MECH, { font: cap(c), fill: c.ink1 });
    const x0 = X0, y0 = MECH + 22, cs = MAT_S / n, mx = Math.max(...m);
    for (let i = 0; i < n; i++) for (let j = 0; j < n; j++) { ctx.fillStyle = weightFill(c, m[i * n + j], mx); ctx.fillRect(x0 + j * cs, y0 + i * cs, cs + 0.3, cs + 0.3); }
    ctx.save(); ctx.strokeStyle = c.ink1; ctx.lineWidth = 1.5; ctx.strokeRect(x0, y0, MAT_S, cs); ctx.restore();
    txt(ctx, "[CLS] …", x0 - 6, y0 + cs / 2, { font: small(c), fill: c.ink1, align: "right" });
    txt(ctx, S.queryAxis, x0 - 6, y0 + MAT_S / 2, { font: small(c), fill: c.ink3, align: "right" });
    txt(ctx, S.keyAxis, x0 + MAT_S / 2, y0 + MAT_S + 12, { font: small(c), fill: c.ink3, align: "center" });
    return;
  }
  txt(ctx, S.attHead(b, h), PAD, MECH, { font: cap(c), fill: c.ink1 });
  const y0 = MECH + 18, mx = Math.max(...m);
  for (let i = 0; i < n; i++) {
    const yy = y0 + i * CELL_H;
    txt(ctx, G.toks[i], X0 - 6, yy + CELL_H / 2, { font: i === 0 ? smallBold(c) : small(c), fill: i === 0 ? c.ink1 : c.ink2, align: "right" });
    for (let j = 0; j < n; j++) { const cell = G.cells[j]; ctx.fillStyle = weightFill(c, m[i * n + j], mx); ctx.fillRect(cell.x, yy + 1, cell.w, CELL_H - 2); }
  }
  const last = G.cells[n - 1];
  ctx.save(); ctx.strokeStyle = c.ink1; ctx.lineWidth = 1.5; ctx.strokeRect(X0 - 1, y0, last.x + last.w - X0 + 2, CELL_H); ctx.restore();
  /* the key in flight: its weight rides from the [CLS] row up to its token (his rule: only movement is eased) */
  if (prog.moving != null) {
    const j = prog.moving, cell = G.cells[j], u = prog.t, yA = y0 + 1, yB = TOK_Y - 10, yy = yA + (yB - yA) * ease(u);
    ctx.save(); ctx.fillStyle = weightFill(c, clsRow(p)[j], Math.max(...clsRow(p))); ctx.strokeStyle = c.ink1; ctx.lineWidth = 1.5;
    ctx.fillRect(cell.x, yy, cell.w, CELL_H - 2); ctx.strokeRect(cell.x, yy, cell.w, CELL_H - 2); ctx.restore();
  }
}

/** INTEGRATED GRADIENTS: the logit along the path, drawn up to the current α, a tick a step, the marker in ink */
function drawIG(ctx, c, w, p, alpha, k) {
  const e = rowOf(p), g = e.ig[p.steps], path = e.path, s = Number(p.steps), C = Math.min(s, TABLE.checks);
  txt(ctx, S.igHead, PAD, MECH, { font: cap(c), fill: c.ink1 });
  const ch = { x: X0, y: MECH + 22, w: w - PAD - X0 - 70, h: CHART_H };
  const lo = Math.min(...path), hi = Math.max(...path), pad = (hi - lo) * 0.1 || 1;
  const X = (a) => ch.x + a * ch.w, Y = (v) => ch.y + ch.h - ((v - lo + pad) / (hi - lo + 2 * pad)) * ch.h;
  line(ctx, [[ch.x, ch.y + ch.h + 0.5], [ch.x + ch.w, ch.y + ch.h + 0.5]], c.grid);
  line(ctx, [[ch.x - 0.5, ch.y], [ch.x - 0.5, ch.y + ch.h]], c.grid);
  txt(ctx, S.alpha0, ch.x, ch.y + ch.h + 12, { font: small(c), fill: c.ink3 });
  txt(ctx, S.alpha1(p.task), ch.x + ch.w, ch.y + ch.h + 12, { font: small(c), fill: c.ink3, align: "right" });
  for (let i = 1; i <= s; i++) { const x = X(i / s); line(ctx, [[x, ch.y + ch.h], [x, ch.y + ch.h - 4]], i / s <= alpha + 1e-9 ? c.ink2 : c.grid); }
  /* the curve, revealed up to α: between the table's 51 points, linear */
  const pts = [], N = path.length - 1;
  for (let i = 0; i <= N && i / N <= alpha + 1e-9; i++) pts.push([X(i / N), Y(path[i])]);
  if (alpha > 0 && alpha < 1) { const f = alpha * N, i = Math.floor(f), u = f - i; pts.push([X(alpha), Y(path[i] + (path[Math.min(N, i + 1)] - path[i]) * u)]); }
  if (pts.length > 1) line(ctx, pts, c.ink1, 2);
  txt(ctx, f2(path[0]), ch.x - 6, Y(path[0]), { font: monoX(c), fill: c.ink2, align: "right" });
  if (alpha > 0) {
    const [ex, ey] = pts[pts.length - 1];
    line(ctx, [[ex, ch.y], [ex, ch.y + ch.h]], c.ink2, 1, [3, 3]);
    ctx.save(); ctx.fillStyle = c.ink1; ctx.beginPath(); ctx.arc(ex, ey, 3.5, 0, 2 * Math.PI); ctx.fill(); ctx.restore();
    if (alpha >= 1) txt(ctx, f2(path[N]), ex + 8, ey, { font: monoX(c), fill: c.ink2 });
  }
  const part = igPart(p, k), sum = part.reduce((a, v) => a + v, 0), stepsDone = Math.round((k * s) / C);
  const msg = k >= C ? S.igDone(g.attr.reduce((a, v) => a + v, 0), g.fx - g.fb, Math.abs(g.delta)) : S.igSum(stepsDone, s, sum);
  txt(ctx, msg, X0, ch.y + ch.h + 32, { font: small(c), fill: c.ink1 });
}

/** OCCLUSION: the window on the strip, and the logit with each window occluded, charted under the strip's tokens */
function drawOcclusion(ctx, c, w, p, G, pos) {
  const e = rowOf(p), W = windows(p), f0 = e.occ.f0, n = Math.floor(pos);
  txt(ctx, S.occHead, PAD, MECH, { font: cap(c), fill: c.ink1 });
  const ch = { y: MECH + 22, h: CHART_H }, ys = W.map((x) => f0 - x.d);
  const lo = Math.min(f0, ...ys), hi = Math.max(f0, ...ys), pad = (hi - lo) * 0.1 || 1;
  const Y = (v) => ch.y + ch.h - ((v - lo + pad) / (hi - lo + 2 * pad)) * ch.h;
  const centre = (win) => { const a = G.cells[win.s], b = G.cells[win.s + win.k - 1]; return (a.x + b.x + b.w) / 2; };
  line(ctx, [[X0, Y(f0)], [w - PAD, Y(f0)]], c.ink3, 1, [4, 3]);
  txt(ctx, `${S.occNone} ${f2(f0)}`, X0 - 6, Y(f0), { font: small(c), fill: c.ink3, align: "right" });
  line(ctx, [[X0, ch.y + ch.h + 0.5], [w - PAD, ch.y + ch.h + 0.5]], c.grid);
  const shown = W.slice(0, n);
  if (G.prot) { if (shown.length > 1) line(ctx, shown.map((x, i) => [centre(x), Y(ys[i])]), c.ink1, 1.5); }
  else shown.forEach((x, i) => { ctx.save(); ctx.fillStyle = c.ink1; ctx.beginPath(); ctx.arc(centre(x), Y(ys[i]), 3.5, 0, 2 * Math.PI); ctx.fill(); ctx.restore(); });
  /* the window: on the strip's tokens, moving from one place to the next */
  if (pos > 0 && n < W.length + 1) {
    const i = Math.min(W.length - 1, Math.max(0, Math.ceil(pos) - 1)), u = pos - Math.floor(pos);
    const at = (win) => { const a = G.cells[win.s], b = G.cells[win.s + win.k - 1]; return [a.x - 2, b.x + b.w + 2]; };
    let [xa, xb] = at(W[i]);
    if (u > 0 && i > 0) { const [pa, pb] = at(W[i - 1]); const t = ease(u); xa = pa + (xa - pa) * t; xb = pb + (xb - pb) * t; }
    if (pos < W.length || u > 0) { ctx.save(); ctx.strokeStyle = c.ink1; ctx.lineWidth = 2; ctx.strokeRect(xa, TOK_Y - 13, xb - xa, 26); ctx.restore(); }
  }
  txt(ctx, S.occCount(Math.min(n, W.length), W.length, windowOf(p), strideOf(windowOf(p)), p.task), X0, ch.y + ch.h + 14, { font: small(c), fill: c.ink2 });
}

const ease = (u) => (u < 0.5 ? 2 * u * u : 1 - 2 * (1 - u) * (1 - u));

/* ============================================================ animation */

/** how many presses a page holds: a key (notes) or 50 keys (proteins); a checkpoint along the path; a window */
function unitsOf(page, p) {
  if (page === "attention") return PROTEIN(p.task) ? Math.ceil(tokensOf(p).length / 50) : tokensOf(p).length;
  if (page === "integrated-gradients") return Math.min(Number(p.steps), TABLE.checks);
  return windows(p).length;
}
/** a unit's duration: a press is slow enough to follow; Play takes about 4 s whatever the count */
const unitMs = (page, p, mode) => (mode === "step" ? (page === "occlusion" && PROTEIN(p.task) ? 120 : 450) : Math.max(15, Math.min(450, 4000 / unitsOf(page, p))));
const pageOf = (anim, params) => anim.p[params.page];
function settle(anim, params) {
  const pg = pageOf(anim, params);
  anim.key = params.page;
  anim.done = pg.n >= unitsOf(params.page, params) && pg.t >= 1;
}
/** the page's progress as a number of units, fractional while one is in flight */
const progress = (pg) => (pg.t < 1 ? pg.n - 1 + pg.t : pg.n);

defineWidget({
  slug: "explainability",
  status: "shipped",
  title: S.title,
  subtitle: S.subtitle,
  layout: "side",
  height: ({ page, task }) => heightOf(page, task),

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "attention", display: true },
    training: { type: "segmented", label: S.trainingLabel, options: TRAINING, groupHeads: true, default: "transfer" },
    task: { type: "segmented", label: S.taskLabel, options: TASKS, groupHeads: true, default: "drug-error" },
    example: { type: "segmented", label: S.exampleLabel, options: ["1", "2", "3", "4"].map((v) => ({ value: v, label: v })), default: "1",
      detail: "One of the four held-out examples drawn at the top; a click on a row chooses it too." },
    block: { type: "segmented", label: S.blockLabel, detail: S.blockDetail, options: [{ value: "1", label: "1" }, { value: "2", label: "2" }], default: "2", display: true,
      when: { param: "page", equals: "attention" } },
    head: { type: "segmented", label: S.headLabel, detail: S.headDetail, options: ["mean", "1", "2", "3", "4"].map((v) => ({ value: v, label: v === "mean" ? "Mean" : v })), default: "mean", display: true,
      when: { param: "page", equals: "attention" } },
    steps: { type: "segmented", label: S.stepsLabel, detail: S.stepsDetail, options: TABLE.steps.map((v) => ({ value: String(v), label: String(v) })), default: "50",
      when: { param: "page", equals: "integrated-gradients" } },
    show: { type: "segmented", label: S.showLabel, detail: S.showDetail, options: [{ value: "signed", label: "Signed" }, { value: "positive", label: "Positive only" }], default: "signed", display: true,
      when: { param: "page", equals: "integrated-gradients" } },
    words: { type: "segmented", label: S.wordsLabel, detail: S.wordsDetail, options: TABLE.windows.notes.map((v) => ({ value: String(v), label: String(v) })), default: "1",
      when: { all: [{ param: "page", equals: "occlusion" }, { param: "task", oneOf: ["outcome", "drug-error"] }] } },
    window: { type: "segmented", label: S.residuesLabel, detail: S.residuesDetail, options: TABLE.windows.proteins.map((v) => ({ value: String(v), label: String(v) })), default: "4",
      when: { all: [{ param: "page", equals: "occlusion" }, { param: "task", equals: "influenza-host" }] } },
    /* authoring escape hatch, first render only: 1 opens every page finished */
    shown: { type: "int", min: 0, max: 1, default: 0, hidden: true },
  },

  legend: ({ params: { page, show } }) => (page === "attention"
    ? [{ token: "magnitude", label: S.legend.att, mark: "bar" }]
    : page === "integrated-gradients" && show === "positive"
      ? [{ token: "value-high", label: S.legend.pos, mark: "bar" }]
      : [{ token: "value-high", label: S.legend.up, mark: "bar" }, { token: "value-low", label: S.legend.down, mark: "bar" }]),

  compute: ({ params }) => ({ task: params.task }),

  regions: ({ w, params }) => TABLE.examples[params.task].map((_, i) => ({
    x: PAD - 4, y: ROW0 + i * ROW_PITCH - 10, w: w - 2 * PAD + 8, h: 20, set: { example: String(i + 1) }, label: `example ${i + 1}`,
  })),

  animation: {
    stepLabel: { param: "page", labels: { ...S.step, attention: { param: "task", labels: { "influenza-host": S.stepProt.attention }, default: S.step.attention } }, default: S.step.attention },
    stepTitle: { param: "page", labels: S.stepTitle, default: S.stepTitle.attention },
    init: ({ params, fromScratch }) => {
      const anim = { p: Object.fromEntries(PAGES.map((pg) => [pg.value, { n: 0, t: 1 }])), moving: false, halt: false };
      if (!fromScratch && Number(params.shown) >= 1) for (const pg of PAGES) anim.p[pg.value].n = unitsOf(pg.value, params);
      settle(anim, params);
      return anim;
    },
    advance: (anim, { dt, params }) => {
      if (anim.halt) { anim.halt = false; anim.moving = false; settle(anim, params); return false; }
      const page = params.page, pg = pageOf(anim, params), N = unitsOf(page, params);
      let more;
      if (pg.t < 1) {
        pg.t = Math.min(1, pg.t + dt / unitMs(page, params, anim.mode));
        more = pg.t < 1 || (anim.mode === "run" && pg.n < N);
      } else if (pg.n < N) { pg.n += 1; pg.t = 0; more = true; }
      else more = false;
      anim.moving = more;
      settle(anim, params);
      return more;
    },
    rebuild: (anim, { params }) => {
      /* a press belongs to the page it started on: a switch mid-press finishes it (widget 70's rule) */
      if (anim.moving && params.page !== anim.key) {
        for (const [page, pg] of Object.entries(anim.p)) if (pg.t < 1) pg.t = 1;
        anim.halt = true;
      }
      settle(anim, params);
    },
  },

  draw({ ctx, colors: c, w, h, params: p, anim }) {
    const page = p.page, pg = pageOf(anim, p), pos = progress(pg), e = rowOf(p), G = stripGeo(ctx, c, w, p);
    drawRows(ctx, c, w, p);
    const inner = (v) => v.slice(1, -1);
    if (page === "attention") {
      const row = clsRow(p), per = G.prot ? 50 : 1, shown = Math.floor(pos) * per;
      const vals = Array.from(row, (v, i) => (i < shown ? v : null));
      drawStrip(ctx, c, w, p, G, vals, { signed: false, scale: Math.max(...row), title: S.stripHead.attention(p.block, p.head), e });
      drawAttention(ctx, c, w, p, G, { moving: !G.prot && pg.t < 1 ? pg.n - 1 : null, t: pg.t });
    } else if (page === "integrated-gradients") {
      const C = Math.min(Number(p.steps), TABLE.checks), k0 = Math.floor(pos), u = pos - k0;
      const a = igPart(p, k0), b = u > 0 ? igPart(p, k0 + 1) : a;
      let vals = Array.from(a, (v, i) => v + (b[i] - v) * u);
      const fin = e.ig[p.steps].attr;
      let scale = Math.max(...inner(fin).map(Math.abs)), signed = true;
      if (p.show === "positive") {
        const mx = Math.max(1e-12, ...fin.map((v) => Math.max(0, v)));
        vals = vals.map((v) => Math.max(0, v) / mx); scale = Math.max(...inner(fin).map((v) => Math.max(0, v) / mx)) || 1;
      }
      drawStrip(ctx, c, w, p, G, pos > 0 ? vals : null, { signed, scale, title: S.stripHead["integrated-gradients"](p.steps, p.show === "positive"), e });
      drawIG(ctx, c, w, p, pos / C, k0 + (u >= 1 ? 1 : 0));
    } else {
      const fin = occValues(p, windows(p).length), vals = occValues(p, Math.floor(pos));
      const scale = Math.max(1e-9, ...inner(fin).map(Math.abs));
      drawStrip(ctx, c, w, p, G, pos >= 1 ? Array.from(vals, (v, i) => (i === 0 || i === G.L - 1 ? 0 : v)) : null, { signed: true, scale, title: S.stripHead.occlusion(windowOf(p), p.task), e });
      drawOcclusion(ctx, c, w, p, G, pos);
    }
    const capText = page === "occlusion" ? S.caption.occlusion(p.task) : S.caption[page];
    wrap(ctx, capText, PAD, h - CAP_H + 14, w - 2 * PAD, 17, { font: body(c), fill: c.ink2 });
  },

  readout({ params: p, anim }) {
    const e = rowOf(p), pg = pageOf(anim, p), done = anim.done, n = NOUN(p.task);
    const tiles = [
      { label: S.tilePred, value: `${LABELS[p.task][e.pred]} ${prob(e).toFixed(2)}`, note: S.tilePredNote(n) },
      { label: S.tileAcc, value: `${Math.round(100 * TABLE.acc[p.task][p.training])}%`, note: S.tileAccNote(n) },
    ];
    if (p.page === "attention") {
      const row = clsRow(p), toks = tokensOf(p); let j = 0; row.forEach((v, i) => { if (v > row[j]) j = i; });
      const res = PROTEIN(p.task) && j > 0 && j < toks.length - 1;
      tiles.push({ label: S.tileTop, value: done ? (res ? `residue ${j}` : toks[j]) : S.wait, note: done ? S.tileTopNote(row[j], res ? toks[j] : null) : "" });
    } else if (p.page === "integrated-gradients") {
      tiles.push({ label: S.tileGap, value: done ? Math.abs(e.ig[p.steps].delta).toFixed(3) : S.wait, note: S.tileGapNote });
    } else {
      const N = windows(p).length;
      tiles.push({ label: S.tileWin, value: `${Math.min(pg.n, N)} of ${N}`, note: S.tileWinNote(windowOf(p), strideOf(windowOf(p)), p.task) });
    }
    return tiles;
  },

  summary({ params }) {
    return S.sum(params.page, params.task, params.example);
  },
});
