/* GENERATED by _lab/ms-features-extract.mjs from MTBLS6038 (the 02-2 download): regenerate, do not edit. */
export default {
 "source": "MTBLS6038 MAF (negative mode), the 02-2 download; exact [M-H]- from the formula",
 "samples": [
  {
   "id": "P210302925",
   "cohort": "Prostate cancer"
  },
  {
   "id": "P210302932",
   "cohort": "Prostate cancer"
  },
  {
   "id": "P210302935",
   "cohort": "Prostate cancer"
  },
  {
   "id": "P210302965",
   "cohort": "Prostatic hyperplasia"
  },
  {
   "id": "P210302966",
   "cohort": "Prostatic hyperplasia"
  },
  {
   "id": "P210302969",
   "cohort": "Prostatic hyperplasia"
  }
 ],
 "metabolites": [
  {
   "name": "Lactic acid",
   "formula": "C3H6O3",
   "mz": 88.989,
   "rt": 1.33,
   "exact": 89.0244,
   "zeros": 0,
   "minNz": 1350000,
   "medNz": 5590000,
   "at": [
    2090000,
    5550000,
    5830000,
    7340000,
    5910000,
    4900000
   ]
  },
  {
   "name": "Succinic acid",
   "formula": "C4H6O4",
   "mz": 116.937,
   "rt": 1.54,
   "exact": 117.0193,
   "zeros": 0,
   "minNz": 25510,
   "medNz": 120360,
   "at": [
    66440,
    47930,
    59420,
    110990,
    88370,
    64990
   ]
  },
  {
   "name": "Fumaric acid",
   "formula": "C4H4O4",
   "mz": 114.984,
   "rt": 2.2,
   "exact": 115.0037,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "Malic acid",
   "formula": "C4H6O5",
   "mz": 132.982,
   "rt": 1.25,
   "exact": 133.0142,
   "zeros": 0,
   "minNz": 8590,
   "medNz": 50120,
   "at": [
    44430,
    102120,
    147760,
    114630,
    84610,
    56310
   ]
  },
  {
   "name": "Maleic acid",
   "formula": "C4H4O4",
   "mz": 114.965,
   "rt": 1.78,
   "exact": 115.0037,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "Citric acid",
   "formula": "C6H8O7",
   "mz": 190.907,
   "rt": 1.66,
   "exact": 191.0197,
   "zeros": 1,
   "minNz": 559,
   "medNz": 900000,
   "at": [
    2220000,
    1710000,
    3000000,
    1690000,
    2110000,
    2610000
   ]
  },
  {
   "name": "Malonic acid",
   "formula": "C3H4O4",
   "mz": 102.969,
   "rt": 1.42,
   "exact": 103.0037,
   "zeros": 14,
   "minNz": 26100,
   "medNz": 157260,
   "at": [
    0,
    0,
    0,
    313280,
    831370,
    145650
   ]
  },
  {
   "name": "Glutaric acid",
   "formula": "C5H8O4",
   "mz": 130.967,
   "rt": 2.11,
   "exact": 131.035,
   "zeros": 149,
   "minNz": 10670,
   "medNz": 16300,
   "at": [
    0,
    16300,
    22420,
    0,
    0,
    10870
   ]
  },
  {
   "name": "Vanillic acid",
   "formula": "C8H8O4",
   "mz": 167.212,
   "rt": 5.26,
   "exact": 167.035,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "D-Glucuronic acid",
   "formula": "C6H10O7",
   "mz": 193.122,
   "rt": 1.04,
   "exact": 193.0354,
   "zeros": 0,
   "minNz": 1590,
   "medNz": 14450,
   "at": [
    5460,
    6800,
    52570,
    31600,
    11070,
    42270
   ]
  },
  {
   "name": "Pantothenic acid",
   "formula": "C9H17NO5",
   "mz": 218.033,
   "rt": 2.8,
   "exact": 218.1034,
   "zeros": 0,
   "minNz": 1620,
   "medNz": 9270,
   "at": [
    10130,
    8850,
    10490,
    8510,
    7910,
    8910
   ]
  },
  {
   "name": "Nicotinic acid",
   "formula": "C6H5NO2",
   "mz": 122.015,
   "rt": 1.26,
   "exact": 122.0248,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "Adipic acid",
   "formula": "C6H10O4",
   "mz": 144.932,
   "rt": 3.48,
   "exact": 145.0506,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "Tartaric acid",
   "formula": "C4H6O6",
   "mz": 149.113,
   "rt": 1.39,
   "exact": 149.0092,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "Hippuric acid",
   "formula": "C9H9NO3",
   "mz": 177.979,
   "rt": 4.87,
   "exact": 178.051,
   "zeros": 0,
   "minNz": 2380,
   "medNz": 114000,
   "at": [
    155000,
    32400,
    148000,
    40700,
    20700,
    1250000
   ]
  },
  {
   "name": "Pyroglutamic acid",
   "formula": "C5H7NO3",
   "mz": 127.955,
   "rt": 1.39,
   "exact": 128.0353,
   "zeros": 0,
   "minNz": 8000,
   "medNz": 42210,
   "at": [
    20400,
    30270,
    35020,
    43650,
    34020,
    42410
   ]
  },
  {
   "name": "5-Hydroxymethyl-2-furoic acid",
   "formula": "C6H6O4",
   "mz": 140.817,
   "rt": 2.52,
   "exact": 141.0193,
   "zeros": 1,
   "minNz": 1030,
   "medNz": 42200,
   "at": [
    1120,
    18100,
    5970,
    12700,
    11200,
    12200
   ]
  },
  {
   "name": "3-Methylglutaric acid",
   "formula": "C6H10O4",
   "mz": 145.038,
   "rt": 3.68,
   "exact": 145.0506,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "Ethylmalonic acid",
   "formula": "C5H8O4",
   "mz": 130.85,
   "rt": 3.39,
   "exact": 131.035,
   "zeros": 0,
   "minNz": 1310,
   "medNz": 84300,
   "at": [
    85800,
    78700,
    119000,
    191000,
    53100,
    261000
   ]
  },
  {
   "name": "Suberic acid",
   "formula": "C8H14O4",
   "mz": 173.065,
   "rt": 8.92,
   "exact": 173.0819,
   "zeros": 110,
   "minNz": 2290,
   "medNz": 6440,
   "at": [
    6150,
    0,
    7410,
    12300,
    0,
    13260
   ]
  },
  {
   "name": "Phenyllactic acid",
   "formula": "C9H10O3",
   "mz": 164.915,
   "rt": 7.9,
   "exact": 165.0557,
   "zeros": 23,
   "minNz": 6130,
   "medNz": 21840,
   "at": [
    0,
    0,
    0,
    17110,
    17990,
    57430
   ]
  },
  {
   "name": "Pyridoxine",
   "formula": "C8H11NO3",
   "mz": 168.027,
   "rt": 1.08,
   "exact": 168.0666,
   "zeros": 171,
   "minNz": 650,
   "medNz": 720,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "3-Indoleacetic acid",
   "formula": "C10H9NO2",
   "mz": 173.95,
   "rt": 9.37,
   "exact": 174.0561,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "Homovanillic acid",
   "formula": "C9H10O4",
   "mz": 180.785,
   "rt": 5.78,
   "exact": 181.0506,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  },
  {
   "name": "3-Hydroxy-3-methylglutaric acid",
   "formula": "C6H10O5",
   "mz": 160.929,
   "rt": 1.69,
   "exact": 161.0455,
   "zeros": 108,
   "minNz": 1280,
   "medNz": 2850,
   "at": [
    2850,
    3540,
    4400,
    2290,
    3900,
    4020
   ]
  },
  {
   "name": "Phenylpyruvic acid",
   "formula": "C9H8O3",
   "mz": 162.924,
   "rt": 8.88,
   "exact": 163.0401,
   "zeros": 179,
   "minNz": 0,
   "medNz": 0,
   "at": [
    0,
    0,
    0,
    0,
    0,
    0
   ]
  }
 ],
 "n": 179
};
