/* ============================================================================
   Widget 100 · Multi-omics: DIABLO (`diablo`) — PHM5003 10, 03 cells 6–28
   (the blocks and Y, the design matrix, keepX, block.splsda), 04 cells 6–13
   (plotDiablo, plotIndiv) and 05 cells 17–24 (predict with RPPA missing,
   the weighted vote, BER).

   The misconception (catalogue § The multi-omics arc, slot 100): the design
   matrix records how correlated the omics blocks are (03 cell 10 says so;
   cells 12–14 measure 0.78–0.89 and suggest weights of 0.7–0.9). It is a
   choice of objective. DIABLO's loop is 99's PLS loop with the subtype, Y,
   added as one more block linked to every omics block at 1: each block's
   loading vector follows z = c · (the other blocks' scores) + 1 · (Y's
   score), so the weight c sets how much a block follows the others against
   the subtype. Measured (`_lab/diablo-measure.R`, `_lab/diablo-toy.mjs`):
   on the lesson's blocks weight 0 → 1 moves the mRNA–methylation agreement
   only 0.849 → 0.868 and the CV error 0.195 → 0.256; the blocks already
   agree through the subtype they are all fitted to.

   PLANNED 2026-10-10 from `_lab/diablo-mock.html`, all eight calls the
   recommendation:
     METHOD
       Design      two simulated blocks of two features sharing a large axis
                   with no subtype in it, each holding the subtype on an axis
                   of its own (the lesson's latent variable 3: r 0.85,
                   subtype share 0.02). Weight 0 · 0.1 · 0.5 · 1. Presses:
                   Start (each block on its direction of most variance,
                   mixOmics' init = "svd.single") · Update mRNA · Update
                   methylation … until the arrows stop. The loop is
                   sparse.mint.block_iteration written out (horst scheme,
                   features scaled, Y its indicator matrix scaled) and
                   matches block.plsda to 5e-7 in every loading.
     TCGA UCEC
       Weight      the lesson's model refitted at the four weights,
                   mRNA's component 1 against methylation's (plotDiablo).
       Select      keepX on mRNA's component 1: the last update X'z over
                   8,383 genes, cut to 25 (soft_thresholding_L1), scored.
       Predict     a test sample with no RPPA: each block's nearest subtype
                   centre, then the weighted vote. With two blocks the vote
                   is the heavier block's call: mRNA's on 102 of 102.

   Nothing is fitted on the TCGA pages: data.js (generated by
   `_lab/diablo-measure.R widget100`) holds the scores, the loading vector
   and the calls. The Design blocks are simulated here.
   ========================================================================= */

import { defineWidget, mathmlRenders } from "../core/index.js";
import { SUBTYPES, Y, FEATURES, KEEPX, SWEEP, SELECT, PREDICT } from "./data.js";

const PAGES = [
  { value: "design", label: "Design", group: "Method" },
  { value: "weight", label: "Weight", group: "TCGA UCEC" },
  { value: "select", label: "Select", group: "TCGA UCEC" },
  { value: "predict", label: "Predict", group: "TCGA UCEC" },
];
const WEIGHTS = [0, 0.1, 0.5, 1];
const WEIGHT_OPTS = WEIGHTS.map((v) => ({ value: String(v), label: String(v) }));
const COMP_OPTS = [1, 2, 3, 4].map((v) => ({ value: String(v), label: String(v) }));
const ON = (page) => ({ param: "page", equals: page });
const N_TOY = 80;
const N_DATA = Y.length;
const N_TEST = PREDICT.truth.length;
/* the test sample a link opens on: mRNA and methylation disagree on it at 2
   components, methylation is right and the vote follows mRNA (the mock's pick) */
const TRACED_TEST = 12;
const BLOCK_NAME = { mRNA: "mRNA", meth: "Methylation", rppa: "RPPA" };

/** how far apart the last kept and the first dropped update values are, as a share of the kept one */
const pctOf = (raw) => `${(100 * (Math.abs(raw[KEEPX.mRNA - 1]) - Math.abs(raw[KEEPX.mRNA])) / Math.abs(raw[KEEPX.mRNA - 1])).toFixed(1)}%`;

/* ------------------------------------------------------------- strings */

const S = {
  subtitle:
    "DIABLO extends partial least squares to several omics blocks and a categorical outcome Y, here the cancer subtype. " +
    "Each block's loading vector follows a weighted sum of the other blocks' scores and Y's, with the weights set by the design matrix; keepX keeps a few features per block, and a new sample is classified by a weighted vote of the blocks it was measured on.",
  pageLabel: "Step",
  weightLabel: "Design weight",
  weightDetail: "the design matrix's entry between two omics blocks; every block is linked to Y at 1",
  compLabel: "Components",
  compDetail: "a block's call uses its components 1 to this number",
  sampleLabel: "Test tumour",
  sampleDetail: "the test tumour whose calls are worked through; a click on a square picks one",

  blockA: "mRNA",
  blockB: "Methylation",
  featA: ["gene 1", "gene 2"],
  featB: ["CpG 1", "CpG 2"],
  scores: "Scores t and u",
  scoreX: "mRNA score t",
  scoreY: "methylation score u",
  sub: ["Subtype 1", "Subtype 2"],
  arrow: "loading vector w",
  start: "where the loop started",

  /* Design */
  dCap: {
    before: "Two omics blocks on the same 80 samples, and Y, the subtype. DIABLO links each block to the others and to Y through the design matrix: the weight c between the omics blocks, and 1 between each block and Y.",
    start: "Start: each block's loading vector (arrow) is its direction of most variance, mixOmics' starting point. Here it is the axis the two blocks share, along which the subtypes do not differ.",
    updA: "Update mRNA: each gene's loading becomes its covariance with z = c·u + y, the methylation scores times the weight c plus Y's scores. The two parts pull the arrow in different directions.",
    updB: "Update methylation: each CpG site's loading becomes its covariance with z = c·t + y, the mRNA scores times the weight c plus Y's scores.",
    done: (c, r, e, r0, e0) => `Another round changes neither loading vector. At Start the scores already agreed (r ${r0}) with the subtypes mixed (${e0} of the mRNA score's variance between them); at weight ${c} they end at r ${r}, with ${e} between the subtypes. A larger weight keeps more agreement and separates the subtypes less.`,
  },
  dmHead: "Design matrix",
  dmY: "Y: the subtype",
  dmExplain: "The weight control sets c, the two violet entries; each block's entry with Y is 1. An update reads its block's row: how much each other block counts.",
  yLine: (a, b) => `Y is the subtype written as a table of 0s and 1s, scaled like the other blocks; its score y is ${a} for subtype 1 and ${b} for subtype 2.`,
  startLine: (b, w) => `${b}: w = (${w}), the direction of most variance`,
  updHead: (b) => `this press: ${b}'s loading vector`,
  zLine: (c, o) => `z = ${c} · ${o} + 1 · y`,
  pullHead: (c, o) => [`${c} · cov(·, ${o})`, "cov(·, y)", "sum"],
  scaleLine: (n, w) => `÷ ${n} (length 1) → w = (${w})`,
  pullKey: (c, o, b) => [`solid: ${c} · cov(·, ${o}), ${b}'s pull`, "dashed: cov(·, y), Y's pull", "violet: their sum, the direction of the new w"],
  tableHead: ["weight", "r(t, u)", "share t", "share u"],
  tableNote: "share: the score's variance between the subtypes",

  /* Weight */
  wCap: {
    before: "The same loop on three omics blocks measured on 405 endometrial tumours, thousands of features each, and four subtypes; the weight c now sits between every pair of omics blocks. Fit runs DIABLO at the chosen weight and draws each tumour's mRNA component 1 against its methylation component 1.",
    after: (c, r) => `At weight ${c} the two blocks' component 1 correlate ${r}. Component 1 separates CN_HIGH from the other three subtypes; later components separate those (Predict uses up to 4). Every block is also linked to Y at 1, so the blocks agree through the subtype at any weight; the weight changes how far the subtypes separate.`,
  },
  wDims: `${N_DATA} tumours: mRNA ${FEATURES.mRNA.toLocaleString("en-US")} genes · methylation ${FEATURES.meth.toLocaleString("en-US")} CpG sites · RPPA ${FEATURES.rppa} proteins`,
  wAxes: ["mRNA component 1", "methylation component 1"],
  wTable: ["weight", "r", "share", "CV error"],
  wNotes: [
    "r: the correlation of mRNA and methylation component 1",
    "share: the share of mRNA component 1's variance that lies between the four subtypes",
    "CV error: how often the full model (4 components) calls held-out tumours wrongly, averaged over the four subtypes (10-fold cross-validation); lower is better",
  ],
  wRppa: (a, b) => `RPPA component 1: r ${a} with mRNA, ${b} with methylation`,
  wBefore: "Component 1: one score per tumour in each block.",

  /* Select */
  sCap: [
    `On the real blocks a loading vector has one entry per feature: ${FEATURES.mRNA.toLocaleString("en-US")} for mRNA. DIABLO's sparse version keeps a fixed number per block, keepX, and sets the rest to 0. Update computes mRNA's loading vector at weight 0.1 with every gene; Keep ${KEEPX.mRNA} makes the cut.`,
    `Update: each of the ${FEATURES.mRNA.toLocaleString("en-US")} genes' loading is its covariance with z, the methylation and RPPA scores times 0.1 plus Y's scores. Every gene gets a loading; the bars are the largest 60.`,
    `Keep ${KEEPX.mRNA}: each of the ${KEEPX.mRNA} largest keeps only its part above the largest one dropped (violet), and every other gene's loading is set to 0. Scaled to length 1, this is the loading vector mixOmics reports. The ${KEEPX.mRNA}th and ${KEEPX.mRNA + 1}th largest differ by ${pctOf(SELECT.raw)}: keepX sets the number, not a gap in the loadings. The genes just above the cut keep almost nothing.`,
    `Score: each tumour's score from the ${KEEPX.mRNA} kept genes against its score from all ${FEATURES.mRNA.toLocaleString("en-US")}. The two nearly agree, and the ${KEEPX.mRNA}-gene score separates the subtypes slightly better.`,
  ],
  sBars: (n) => `size of each gene's loading, sign dropped: the largest 60 of ${n}`,
  sAll: (n) => `all ${n} sizes, largest first; the bars are its left end`,
  sTop: (names) => `largest kept: ${names.join(", ")}`,
  sSame: "This share is Weight's at weight 0.1.",
  sCut: "the largest one dropped",
  sWeight1: (k, n) => `At weight 1, ${k} of these ${n} genes are different ones.`,
  sZ: "z = 0.1 · methylation scores + 0.1 · RPPA scores + 1 · Y's scores",
  sScat: ["score from all genes (no cut)", (k) => `score from ${k} genes`],
  sHov: (nm, v) => `${nm} · loading ${v}`,

  /* Predict */
  pCap: [
    "A test tumour has mRNA and methylation measured but no RPPA. Each panel is one block's training tumours on components 1 and 2, with each subtype's centre (×). Component 2 separates MSI from CN_LOW; POLE sits between them.",
    "Place: the test tumours (squares) are projected onto each block's components, using that block's loading vectors.",
    "Call: each block calls the subtype whose centre is nearest, over components 1 to the chosen number; the panels draw components 1 and 2.",
    "Vote: each block's call counts with its weight, the correlation of its scores with Y's on the training tumours. RPPA has no data and no vote.",
  ],
  pAxes: ["component 1", "component 2"],
  rppa: "RPPA",
  notMeasured: "not measured",
  noVote: "no vote",
  pCalls: (b, c) => `${b} calls ${c}`,
  pWeight: (w) => `weight ${w}`,
  pVote: (c) => `vote: ${c}`,
  pTruth: (c) => `true subtype: ${c}`,
  pSum: (c, s) => `${c} ${s}`,
  pSums: (parts) => `summed weights: ${parts}`,
  pTwo: (n) => `With two blocks every disagreement goes to the block with the larger weight: the vote is mRNA's call on ${n} of ${N_TEST} test tumours.`,
  pThree: (n, v, m) => `With all three blocks (10-fold cross-validation on the ${N_DATA} training tumours) the vote overrules mRNA on ${n}, and its error is ${v} against mRNA's ${m}.`,
  pHov: (n, c) => `test tumour ${n} · ${c}`,

  /* tiles */
  tileR: "Correlation of the scores",
  tileRNote: "t and u, each block's component 1",
  tileEtaA: "Subtype share, mRNA score",
  tileEtaB: "Subtype share, methylation score",
  tileEtaNote: "share of the score's variance between the subtypes",
  tileRw: "Correlation, mRNA–methylation",
  tileRwNote: "component 1 of each block",
  tileCv: "CV error",
  tileCvNote: "held-out tumours called wrongly, averaged over the subtypes",
  tileKept: "Genes with a loading",
  tileKeptNote: "mRNA component 1",
  tileRs: "Kept-gene score vs all-gene score",
  tileRsNote: "correlation over 405 tumours",
  tileEtaS: "Subtype share of the score",
  tileEtaSNote: "all genes → kept genes",
  tileBer: "Test error, vote",
  tileBerNote: (k) => `share called wrongly, averaged over the four subtypes; ${N_TEST} test tumours, ${k} component${k > 1 ? "s" : ""}`,
  tileBlock: "mRNA alone · methylation alone",
  tileSame: "Vote = mRNA's call",
  tileSameNote: "test tumours",
  tileWait: "—",
};

const LOOP_LABEL = (n) => (n === 0 ? "Start" : n % 2 === 1 ? "Update mRNA" : "Update methylation");
const LOOP_TITLE = (n) => (n === 0
  ? "Set each block's loading vector to its direction of most variance and score every sample"
  : n % 2 === 1
    ? "Set each gene's loading to its covariance with z = c·u + y"
    : "Set each CpG site's loading to its covariance with z = c·t + y");
const MAX_PRESSES = 1 + 2 * 12;
const D_LABELS = Object.fromEntries(Array.from({ length: MAX_PRESSES }, (_, n) => [n, LOOP_LABEL(n)]));
const D_TITLES = Object.fromEntries(Array.from({ length: MAX_PRESSES }, (_, n) => [n, LOOP_TITLE(n)]));
const SEL_LABELS = { 0: "Update", 1: `Keep ${KEEPX.mRNA}`, 2: "Score" };
const SEL_TITLES = {
  0: "Set each gene's loading to its covariance with z",
  1: `Keep the ${KEEPX.mRNA} largest loadings and set the rest to 0`,
  2: `Score every tumour from the ${KEEPX.mRNA} kept genes`,
};
const PRE_LABELS = { 0: "Place", 1: "Call", 2: "Vote" };
const PRE_TITLES = {
  0: "Project the test tumours onto each block's components",
  1: "Let each block call the subtype with the nearest centre",
  2: "Combine the blocks' calls, each weighted by its correlation with Y",
};
const FIT_TITLE = "Fit DIABLO at this design weight and draw each block's component 1";

S.stepLabel = {
  param: "page",
  labels: {
    design: { anim: "beat", labels: D_LABELS, default: "Update methylation" },
    weight: "Fit",
    select: { anim: "beat", labels: SEL_LABELS, default: SEL_LABELS[2] },
    predict: { anim: "beat", labels: PRE_LABELS, default: PRE_LABELS[2] },
  },
  default: "Fit",
};
S.stepTitle = {
  param: "page",
  labels: {
    design: { anim: "beat", labels: D_TITLES, default: D_TITLES[2] },
    weight: FIT_TITLE,
    select: { anim: "beat", labels: SEL_TITLES, default: SEL_TITLES[2] },
    predict: { anim: "beat", labels: PRE_TITLES, default: PRE_TITLES[2] },
  },
  default: FIT_TITLE,
};

/* --------------------------------------------------------- formula card */

const MATHML = mathmlRenders();
const mi = (s) => `<mi>${s}</mi>`, mo = (s) => `<mo>${s}</mo>`, mn = (s) => `<mn>${s}</mn>`, sub = (a, b) => `<msub><mi>${a}</mi><mn>${b}</mn></msub>`;
const subI = (a, b) => `<msub><mi>${a}</mi><mi>${b}</mi></msub>`;
const supT = (s) => `<msup>${s}<mi>T</mi></msup>`, gap = (em) => `<mspace width="${em}em"/>`;
const MATH = {
  objective: {
    math: `<math display="block"><mrow><munder><mo>max</mo><mrow>${sub("w", 1)}${mo(",")}${mo("…")}</mrow></munder>${gap(0.3)}<munder><mo>∑</mo><mrow>${mi("k")}${mo("&lt;")}${mi("l")}</mrow></munder>${subI("c", "kl")}${gap(0.2)}<mtext>cov</mtext>${mo("(")}${subI("X", "k")}${subI("w", "k")}${mo(",")}${subI("X", "l")}${subI("w", "l")}${mo(")")}</mrow></math>`,
    plain: "max over w₁, … of Σₖ₍ₗ cₖₗ cov(Xₖwₖ, Xₗwₗ)",
    note: "The sum runs over every pair of blocks, Y among them. cₖₗ is the design matrix's entry: c between two omics blocks, 1 between each block and Y. With Y left out, this is the PLS objective.",
  },
  update: {
    math: `<math display="block"><mrow>${sub("z", 1)}${mo("=")}${mi("c")}${mi("u")}${mo("+")}${mi("y")}${mo(",")}${gap(0.5)}${sub("w", 1)}${mo("∝")}${supT(sub("X", 1))}${sub("z", 1)}${mo(";")}${gap(1.2)}${sub("z", 2)}${mo("=")}${mi("c")}${mi("t")}${mo("+")}${mi("y")}${mo(",")}${gap(0.5)}${sub("w", 2)}${mo("∝")}${supT(sub("X", 2))}${sub("z", 2)}</mrow></math>`,
    plain: "z₁ = c u + y,  w₁ ∝ X₁ᵀz₁;   z₂ = c t + y,  w₂ ∝ X₂ᵀz₂",
    note: "Each block's loading vector is its features' covariances with z, the other block's scores times c plus Y's scores y, scaled to length 1. At c = 0 a block follows Y alone; at c = 1 the other block pulls as hard as Y.",
  },
  sparse: {
    math: `<math display="block"><mrow>${mi("w")}${mo("∝")}<msub><mtext>keep</mtext>${mn(KEEPX.mRNA)}</msub>${mo("(")}${supT(mi("X"))}${mi("z")}${mo(")")}${mo(",")}${gap(1)}${mi("z")}${mo("=")}${mn("0.1")}${gap(0.1)}${sub("t", "meth")}${mo("+")}${mn("0.1")}${gap(0.1)}${sub("t", "RPPA")}${mo("+")}${mi("y")}</mrow></math>`,
    plain: `w ∝ keep${KEEPX.mRNA}(Xᵀz),   z = 0.1 t_meth + 0.1 t_RPPA + y`,
    note: `keepX = ${KEEPX.mRNA}: the ${KEEPX.mRNA} largest loadings are kept, each reduced by the largest one dropped, and the rest are set to 0. The cut is made at every update, so the kept genes are the largest of the last update.`,
  },
  vote: {
    math: `<math display="block"><mrow><mover><mi>k</mi><mo>^</mo></mover>${mo("=")}<munder><mtext>arg max</mtext>${mi("k")}</munder>${gap(0.2)}<munder><mo>∑</mo>${mi("b")}</munder>${subI("a", "b")}${gap(0.1)}${mo("[")}${subI("call", "b")}${mo("=")}${mi("k")}${mo("]")}${mo(",")}${gap(1)}${subI("a", "b")}${mo("=")}<mtext>cor</mtext>${mo("(")}${subI("t", "b")}${mo(",")}${mi("y")}${mo(")")}</mrow></math>`,
    plain: "k̂ = arg maxₖ Σ_b a_b [call_b = k],   a_b = cor(t_b, y)",
    note: "Each measured block b calls the subtype whose centre is nearest; the calls are summed with weights a_b, each block's correlation with Y's scores y on the training tumours, averaged over components.",
  },
};
let mathHost = null, mathKey = null;
function renderFormula(key) {
  if (!mathHost) {
    const figure = document.querySelector("#widget .w-figure");
    if (!figure || !figure.parentNode) return;
    mathHost = document.createElement("div");
    mathHost.className = "w-math";
    figure.parentNode.insertBefore(mathHost, figure);
  }
  if (mathKey === key) return;
  mathKey = key;
  const F = MATH[key];
  mathHost.innerHTML = `<div class="w-math-eq"><span style="color:var(--ink-2)">${MATHML ? F.math : F.plain}</span></div><div class="w-math-note">${F.note}</div>`;
}

/* ------------------------------------------------------------- helpers */

const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
const seg = (t, a, b) => clamp((t - a) / (b - a), 0, 1);
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - ((-2 * t + 2) ** 3) / 2);
const lerp = (a, b, t) => a + (b - a) * t;
const lerpPt = (a, b, t) => [lerp(a[0], b[0], t), lerp(a[1], b[1], t)];
const mean = (v) => v.reduce((s, x) => s + x, 0) / v.length;
function corr(a, b) {
  const ma = mean(a), mb = mean(b);
  let sab = 0, saa = 0, sbb = 0;
  for (let i = 0; i < a.length; i++) { sab += (a[i] - ma) * (b[i] - mb); saa += (a[i] - ma) ** 2; sbb += (b[i] - mb) ** 2; }
  return sab / Math.sqrt(saa * sbb);
}
/** the share of a score's variance between the groups (η²) */
function etaOf(t, g, K) {
  const mt = mean(t);
  let b = 0;
  for (let k = 0; k < K; k++) { const v = t.filter((_, i) => g[i] === k); if (v.length) b += v.length * (mean(v) - mt) ** 2; }
  return b / t.reduce((a, x) => a + (x - mt) ** 2, 0);
}
/* a true minus sign, and no −0.00 */
const f2 = (v) => (Math.abs(v) < 0.005 ? 0 : v).toFixed(2).replace("-", "−");
const f3 = (v) => (Math.abs(v) < 0.0005 ? 0 : v).toFixed(3).replace("-", "−");
const sgn2 = (v) => (v >= 0 ? `+${f2(v)}` : f2(v));
const pair2 = (v) => `${f2(v[0])}, ${f2(v[1])}`;
const pct = (v) => `${Math.round(100 * v)}%`;

function txt(ctx, colors, s, x, y, { size = colors.fsSm, fill = colors.ink2, align = "left", baseline = "alphabetic", weight = "" } = {}) {
  ctx.save(); ctx.font = `${weight ? weight + " " : ""}${size} ${colors.font}`; ctx.fillStyle = fill;
  ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
function line(ctx, x1, y1, x2, y2, col, w = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = w; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.restore();
}
function dot(ctx, colors, x, y, r, fill, edge = true) {
  ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.fillStyle = fill; ctx.fill();
  if (edge) { ctx.lineWidth = 1; ctx.strokeStyle = colors.surface; ctx.stroke(); }
}
function square(ctx, colors, x, y, r, fill) {
  ctx.fillStyle = fill; ctx.fillRect(x - r, y - r, 2 * r, 2 * r);
  ctx.lineWidth = 1; ctx.strokeStyle = colors.ink1; ctx.strokeRect(x - r, y - r, 2 * r, 2 * r);
}
function ring(ctx, x, y, r, col) {
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.lineWidth = 2; ctx.strokeStyle = col; ctx.stroke(); ctx.restore();
}
function cross(ctx, x, y, r, col) { line(ctx, x - r, y - r, x + r, y + r, col, 2.6); line(ctx, x - r, y + r, x + r, y - r, col, 2.6); }
function frame(ctx, colors, x, y, w, h, col = colors.axis, lw = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash); ctx.strokeRect(x + 0.5, y + 0.5, w - 1, h - 1); ctx.restore();
}
function arrowHead(ctx, x0, y0, x1, y1, col, head) {
  const a = Math.atan2(y1 - y0, x1 - x0);
  ctx.save(); ctx.fillStyle = col; ctx.beginPath(); ctx.moveTo(x1, y1);
  ctx.lineTo(x1 - head * Math.cos(a - 0.42), y1 - head * Math.sin(a - 0.42));
  ctx.lineTo(x1 - head * Math.cos(a + 0.42), y1 - head * Math.sin(a + 0.42));
  ctx.closePath(); ctx.fill(); ctx.restore();
}
/** a component's direction has no sign: drawn double-headed, as 99's are */
function axisArrow(ctx, p0, p1, col, lw = 2.2) {
  line(ctx, p0[0], p0[1], p1[0], p1[1], col, lw);
  arrowHead(ctx, p0[0], p0[1], p1[0], p1[1], col, 7); arrowHead(ctx, p1[0], p1[1], p0[0], p0[1], col, 7);
}
/** a vector from the origin: one head */
function vecArrow(ctx, p0, p1, col, lw = 1.6, dash = null) {
  line(ctx, p0[0], p0[1], p1[0], p1[1], col, lw, dash);
  if (Math.hypot(p1[0] - p0[0], p1[1] - p0[1]) > 6) arrowHead(ctx, p0[0], p0[1], p1[0], p1[1], col, 6);
}
const REF_DASH = [6, 5];
function vText(ctx, colors, s, x, y, opts) {
  ctx.save(); ctx.translate(x, y); ctx.rotate(-Math.PI / 2); txt(ctx, colors, s, 0, 0, { align: "center", ...opts }); ctx.restore();
}
function hoverLabel(ctx, colors, str, x, y, w) {
  ctx.save(); ctx.font = `600 ${colors.fsXs} ${colors.font}`;
  const tw = ctx.measureText(str).width; ctx.restore();
  const bx = Math.max(4, Math.min(w - tw - 14, x + 10)), by = Math.max(4, y - 26);
  ctx.save(); ctx.fillStyle = colors.surface; ctx.fillRect(bx, by, tw + 10, 18);
  ctx.strokeStyle = colors.ink3; ctx.strokeRect(bx + 0.5, by + 0.5, tw + 9, 17); ctx.restore();
  txt(ctx, colors, str, bx + 5, by + 9.5, { size: colors.fsXs, fill: colors.ink1, baseline: "middle", weight: "600" });
}
const subColour = (colors, g) => colors.clusters[g];
/** words laid into lines no wider than `maxW`, `lh` apart; returns the line count */
function wrapText(ctx, colors, str, x, y, maxW, lh, opts = {}) {
  ctx.save(); ctx.font = `${opts.weight ? opts.weight + " " : ""}${opts.size ?? colors.fsSm} ${colors.font}`;
  const lines = []; let cur = "";
  for (const word of str.split(" ")) {
    const tryLine = cur ? `${cur} ${word}` : word;
    if (ctx.measureText(tryLine).width > maxW && cur) { lines.push(cur); cur = word; } else cur = tryLine;
  }
  if (cur) lines.push(cur);
  ctx.restore();
  lines.forEach((l, i) => txt(ctx, colors, l, x, y + i * lh, { fill: colors.ink2, ...opts }));
  return lines.length;
}
function panelFrame(ctx, colors, P, name, ax) {
  txt(ctx, colors, name, P.x, P.y - 6, { fill: colors.ink1, weight: "600", size: colors.fsXs });
  frame(ctx, colors, P.x, P.y, P.s, P.s);
  txt(ctx, colors, ax[0], P.x + P.s / 2, P.y + P.s + 12, { size: colors.fsXs, fill: colors.ink3, align: "center" });
  vText(ctx, colors, ax[1], P.x - 7, P.y + P.s / 2, { size: colors.fsXs, fill: colors.ink3 });
}
const toPxOf = (P, span) => (x, y) => [P.x + P.s / 2 + (x / span) * (P.s / 2), P.y + P.s / 2 - (y / span) * (P.s / 2)];
/** an axis turns the short way: it has no sign, so a half-turn is no turn */
function blendAxis(a, b, t) {
  const c = lerpPt(a[0], a[1], 0.5), L = Math.hypot(b[1][0] - b[0][0], b[1][1] - b[0][1]) / 2;
  const a0 = Math.atan2(a[1][1] - a[0][1], a[1][0] - a[0][0]), a1 = Math.atan2(b[1][1] - b[0][1], b[1][0] - b[0][0]);
  let d = a1 - a0;
  while (d > Math.PI / 2) d -= Math.PI;
  while (d < -Math.PI / 2) d += Math.PI;
  const ang = a0 + d * t;
  return [[c[0] - L * Math.cos(ang), c[1] - L * Math.sin(ang)], [c[0] + L * Math.cos(ang), c[1] + L * Math.sin(ang)]];
}

/* ===================================================== the Design blocks */

/* Two blocks on the same 80 samples (`_lab/diablo-toy.mjs`, measured before
   the mock). In each, a shared factor h (sd 1.8) with no subtype in it, and
   the subtype z (±0.8 + noise) on an axis of the block's own. Every feature
   is scaled, as mixOmics scales it, so each block's direction of most
   variance is the shared axis at 45° or 135°. */
const ANG = { ha: 35, za: 115, hb: 145, zb: 60 };
const unitAt = (deg) => [Math.cos((deg * Math.PI) / 180), Math.sin((deg * Math.PI) / 180)];
const norm = (v) => { const n = Math.hypot(...v); return v.map((x) => x / n); };
const proj = (X, w) => X.map((r) => r.reduce((a, x, j) => a + x * w[j], 0));
const xtz = (X, z) => X[0].map((_, j) => X.reduce((a, r, i) => a + r[j] * z[i], 0));
/** each feature's covariance with a score vector: Xᵀs / n */
const covWith = (X, s) => xtz(X, s).map((v) => v / X.length);
const angleBetween = (a, b) => Math.acos(clamp(Math.abs(a[0] * b[0] + a[1] * b[1]), 0, 1)) * 180 / Math.PI;
function scaleCols(X) {
  const p = X[0].length, m = [], s = [];
  for (let j = 0; j < p; j++) {
    const c = X.map((r) => r[j]); m[j] = mean(c);
    s[j] = Math.sqrt(c.reduce((a, x) => a + (x - m[j]) ** 2, 0) / (c.length - 1));
  }
  return X.map((r) => r.map((x, j) => (x - m[j]) / s[j]));
}
/** the first right singular vector (mixOmics' svd.single start), by power iteration */
function pc1(X) {
  let v = norm(X[0].map((_, j) => 1 + 0.1 * j));
  for (let k = 0; k < 500; k++) v = norm(xtz(X, proj(X, v)));
  return v;
}

function makeToy(rng) {
  const ha = unitAt(ANG.ha), za = unitAt(ANG.za), hb = unitAt(ANG.hb), zb = unitAt(ANG.zb);
  const g = [], A0 = [], B0 = [];
  for (let i = 0; i < N_TOY; i++) {
    const grp = i % 2, h = 1.8 * rng.normal(), z = (grp ? 0.8 : -0.8) + 0.4 * rng.normal();
    g.push(grp);
    A0.push([0, 1].map((j) => h * ha[j] + z * za[j] + 0.25 * rng.normal()));
    B0.push([0, 1].map((j) => h * hb[j] + z * zb[j] + 0.25 * rng.normal()));
  }
  const A = scaleCols(A0), B = scaleCols(B0), Yd = scaleCols(g.map((k) => (k ? [0, 1] : [1, 0])));
  const blocks = [A, B, Yd];
  const pos2 = (t) => mean(t.filter((_, i) => g[i] === 1)) >= 0;

  /* sparse.mint.block_iteration, horst scheme, blocks updated in turn
     (mRNA, methylation, Y). One frame per omics update; Y's own update is
     run but not pressed: with two subtypes its score is the subtype however
     the weight is set. Signs: subtype 2 scores positive on mRNA and on Y,
     methylation's start agrees with mRNA's, so every pull points one way. */
  const loopAt = (c) => {
    const C = [[0, c, 1], [c, 0, 1], [1, 1, 0]];
    const W = blocks.map(pc1);
    if (!pos2(proj(A, W[0]))) W[0] = W[0].map((x) => -x);
    if (corr(proj(A, W[0]), proj(B, W[1])) < 0) W[1] = W[1].map((x) => -x);
    if (!pos2(proj(Yd, W[2]))) W[2] = W[2].map((x) => -x);
    const T = blocks.map((X, q) => proj(X, W[q]));
    const snap = (upd) => ({ wA: [...W[0]], wB: [...W[1]], t: [...T[0]], u: [...T[1]], y: [...T[2]], upd });
    const frames = [{}, snap(null)];
    for (let it = 0; it < 100; it++) {
      const old = W.map((w) => [...w]);
      for (let q = 0; q < 3; q++) {
        let upd = null;
        if (q < 2) upd = { block: q, other: covWith(blocks[q], T[1 - q]).map((v) => c * v), y: covWith(blocks[q], T[2]) };
        const z = T[0].map((_, i) => C[q].reduce((a, cc, l) => a + cc * T[l][i], 0));
        W[q] = norm(xtz(blocks[q], z));
        T[q] = proj(blocks[q], W[q]);
        if (q < 2) frames.push(snap(upd));
      }
      if (Math.max(...W.map((w, q) => w.reduce((a, x, j) => a + (x - old[q][j]) ** 2, 0))) < 1e-6) break;
    }
    /* the rounds after the arrows stopped moving are not pressed */
    let end = frames.length - 1;
    while (end > 3 && angleBetween(frames[end].wA, frames[end - 2].wA) < 0.5 && angleBetween(frames[end].wB, frames[end - 2].wB) < 0.5) end -= 2;
    const out = frames.slice(0, end + 1);
    out.forEach((f) => {
      if (!f.t) return;
      f.r = corr(f.t, f.u); f.cv = f.t.reduce((a, v, i) => a + v * f.u[i], 0) / N_TOY;
      f.etaA = etaOf(f.t, g, 2); f.etaB = etaOf(f.u, g, 2);
    });
    return out;
  };
  const loops = Object.fromEntries(WEIGHTS.map((c) => [String(c), loopAt(c)]));
  const all = Object.values(loops).flat().filter((f) => f.t);
  const span = 1.1 * Math.max(...A.flat().map(Math.abs), ...B.flat().map(Math.abs));
  const sspan = 1.08 * Math.max(...all.flatMap((f) => [...f.t, ...f.u]).map(Math.abs));
  return { g, A, B, loops, span, sspan, yVals: [Math.min(...all[0].y), Math.max(...all[0].y)] };
}

/* ========================================================= DESIGN page */

/* A caption across the top; three squares (mRNA · Scores · methylation), as
   99's N-integration page; under them the design matrix, this press's
   arithmetic, and the two pulls added head to tail. */
const DL = { cap: 72, padL: 30, padR: 12, gap: 24, sMax: 150, below: 46, low: 172 };
const H_DESIGN = DL.cap + 18 + DL.sMax + DL.below + DL.low;
function dLayout(w) {
  const s = Math.floor(Math.min(DL.sMax, (w - DL.padL - DL.padR - 2 * DL.gap) / 3));
  const y = DL.cap + 18, xA = DL.padL, xB = w - DL.padR - s, xS = (xA + s + xB) / 2 - s / 2;
  const ly = y + s + DL.below;
  const vs = 118, cell = 34;
  return {
    s, A: { x: xA, y, s }, S: { x: xS, y, s }, B: { x: xB, y, s },
    dm: { x: xA + 40, y: ly + 30, cell },
    mid: { x: xA + 40 + 3 * cell + 20, y: ly, w: w - DL.padR - vs - 16 - (xA + 40 + 3 * cell + 20) },
    vec: { x: w - DL.padR - vs, y: ly + 4, s: vs },
  };
}
const loopOf = (st, params) => st.loops[params.weight] ?? st.loops["0.1"];
const loopEnd = (st, params) => loopOf(st, params).length - 1;
/** one scale for a weight's whole loop, so a pull's length can be compared press to press */
const pullMaxOf = (frames) => Math.max(...frames.filter((f) => f.upd).map((f) => Math.max(Math.hypot(...f.upd.other), Math.hypot(...f.upd.y), Math.hypot(f.upd.other[0] + f.upd.y[0], f.upd.other[1] + f.upd.y[1]))));

function drawDesign(ctx, colors, w, params, st, anim, pointer) {
  const Lm = dLayout(w), frames = loopOf(st, params), end = frames.length - 1;
  const k = Math.min(anim.n.design ?? 0, end), p = inFlight(anim, "design");
  const F = frames[k], prev = p != null && k >= 2 ? frames[k - 1] : null;
  const turn = prev ? ease(seg(p, 0, 0.5)) : 1, slide = prev ? ease(seg(p, 0.5, 1)) : 1;
  const c = Number(params.weight);

  const cap = k === 0 ? S.dCap.before : k === 1 ? S.dCap.start : k === end ? S.dCap.done(params.weight, f2(F.r), pct(F.etaA), f2(frames[1].r), pct(frames[1].etaA)) : k % 2 === 0 ? S.dCap.updA : S.dCap.updB;
  wrapText(ctx, colors, cap, 10, 14, w - 20, 16, { fill: colors.ink1 });

  [[Lm.A, S.blockA, S.featA], [Lm.S, S.scores, [S.scoreX, S.scoreY]], [Lm.B, S.blockB, S.featB]].forEach(([P, name, ax]) => panelFrame(ctx, colors, P, name, ax));
  const pa = toPxOf(Lm.A, st.span), pb = toPxOf(Lm.B, st.span), ps = toPxOf(Lm.S, st.sspan), R = 0.95 * st.span;
  st.A.forEach((q, i) => { const [x, y] = pa(q[0], q[1]); dot(ctx, colors, x, y, 3.2, subColour(colors, st.g[i])); });
  st.B.forEach((q, i) => { const [x, y] = pb(q[0], q[1]); dot(ctx, colors, x, y, 3.2, subColour(colors, st.g[i])); });
  if (k >= 1) {
    /* from the first update on, the start stays as a dashed line */
    const s0 = frames[1];
    if (k >= 2) {
      line(ctx, ...pa(-R * s0.wA[0], -R * s0.wA[1]), ...pa(R * s0.wA[0], R * s0.wA[1]), colors.reference, 2, REF_DASH);
      line(ctx, ...pb(-R * s0.wB[0], -R * s0.wB[1]), ...pb(R * s0.wB[0], R * s0.wB[1]), colors.reference, 2, REF_DASH);
    }
    const axisOf = (px, d) => [px(-R * d[0], -R * d[1]), px(R * d[0], R * d[1])];
    const now = (px, key) => (prev ? blendAxis(axisOf(px, prev[key]), axisOf(px, F[key]), turn) : axisOf(px, F[key]));
    const a = now(pa, "wA"), b = now(pb, "wB");
    axisArrow(ctx, a[0], a[1], colors.highlight); axisArrow(ctx, b[0], b[1], colors.highlight);
    /* the scores: they slide once the arrow has turned */
    F.t.forEach((t, i) => {
      const q = prev ? lerpPt(ps(prev.t[i], prev.u[i]), ps(t, F.u[i]), slide) : ps(t, F.u[i]);
      dot(ctx, colors, q[0], q[1], 3.2, subColour(colors, st.g[i]));
    });
    const r = prev ? lerp(prev.r, F.r, slide) : F.r;
    txt(ctx, colors, `r = ${f2(r)}`, Lm.S.x + Lm.S.s - 5, Lm.S.y + 14, { fill: colors.ink1, align: "right", weight: "600", size: colors.fsXs });
    txt(ctx, colors, `w = (${pair2(F.wA)})`, Lm.A.x, Lm.A.y + Lm.s + 26, { size: colors.fsXs, fill: colors.highlight, weight: "600" });
    txt(ctx, colors, `w = (${pair2(F.wB)})`, Lm.B.x, Lm.B.y + Lm.s + 26, { size: colors.fsXs, fill: colors.highlight, weight: "600" });
  }

  drawDesignMatrix(ctx, colors, Lm, c, F.upd);
  drawDesignMiddle(ctx, colors, Lm, st, params, frames, k, F);
  if (F.upd) drawPulls(ctx, colors, Lm, pullMaxOf(frames), F.upd, F.upd.block === 0 ? S.featA : S.featB, params.weight);

  if (pointer) {
    let best = -1, bd = 64, where = null;
    const tryAt = (q, i, wh) => { const d = (q[0] - pointer.x) ** 2 + (q[1] - pointer.y) ** 2; if (d < bd) { bd = d; best = i; where = wh; } };
    st.A.forEach((q, i) => tryAt(pa(q[0], q[1]), i, "a"));
    st.B.forEach((q, i) => tryAt(pb(q[0], q[1]), i, "b"));
    if (k >= 1) F.t.forEach((t, i) => tryAt(ps(t, F.u[i]), i, "s"));
    if (best >= 0) hoverLabel(ctx, colors, `sample ${best + 1} · ${S.sub[st.g[best]]}`, pointer.x, pointer.y, w);
    void where;
  }
}

/** 03 cell 11's matrix with the Y row and column 03 cell 16 adds; the
   entries the weight control sets are framed, and so is the row this press uses */
function drawDesignMatrix(ctx, colors, Lm, c, upd) {
  const { x, y, cell } = Lm.dm, names = ["mRNA", "meth", "Y"];
  txt(ctx, colors, S.dmHead, x - 40, y - 22, { size: colors.fsXs, fill: colors.ink1, weight: "600" });
  names.forEach((nm, j) => txt(ctx, colors, nm, x + j * cell + cell / 2, y - 6, { size: colors.fsXs, fill: colors.ink3, align: "center" }));
  names.forEach((nm, i) => txt(ctx, colors, nm, x - 6, y + i * cell + cell / 2 + 4, { size: colors.fsXs, fill: colors.ink3, align: "right" }));
  const D = [[0, c, 1], [c, 0, 1], [1, 1, 0]];
  for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) {
    frame(ctx, colors, x + j * cell, y + i * cell, cell, cell, colors.grid);
    const set = i < 2 && j < 2 && i !== j;
    txt(ctx, colors, String(D[i][j]), x + j * cell + cell / 2, y + i * cell + cell / 2 + 4, { size: colors.fsXs, align: "center", fill: set ? colors.highlight : colors.ink1, weight: set ? "600" : "" });
  }
  if (upd) frame(ctx, colors, x - 2, y + upd.block * cell - 2, 3 * cell + 4, cell + 4, colors.ink1, 1.5);
  txt(ctx, colors, S.dmY, x - 40, y + 3 * cell + 16, { size: colors.fsXs, fill: colors.ink3 });
}

function drawDesignMiddle(ctx, colors, Lm, st, params, frames, k, F) {
  const { x, y, w: mw } = Lm.mid, lh = 15, xs = colors.fsXs;
  let yy = y + 8;
  const put = (s, opts = {}) => { txt(ctx, colors, s, x, yy, { size: xs, fill: colors.ink2, ...opts }); yy += lh; };
  const end = frames.length - 1;
  if (k === 0) {
    wrapText(ctx, colors, S.dmExplain, x, yy, mw, lh, { size: xs, fill: colors.ink2 });
    return;
  }
  if (k === end) {
    /* the four weights side by side: the page's last readout */
    const cols = [0, 48, 100, 152];
    S.tableHead.forEach((h, j) => txt(ctx, colors, h, x + cols[j], yy, { size: xs, fill: colors.ink1, weight: "600" }));
    yy += 6;
    WEIGHTS.forEach((wv) => {
      yy += lh;
      const L = st.loops[String(wv)], f = L[L.length - 1], cur = String(wv) === params.weight;
      [String(wv), f2(f.r), pct(f.etaA), pct(f.etaB)].forEach((v, j) => txt(ctx, colors, v, x + cols[j], yy, { size: xs, fill: cur ? colors.ink1 : colors.ink2, weight: cur ? "600" : "" }));
      if (cur) frame(ctx, colors, x - 4, yy - 11, Math.min(mw, cols[3] + 48) + 4, 15, colors.highlight, 1.5);
    });
    txt(ctx, colors, S.tableNote, x, yy + 18, { size: xs, fill: colors.ink3 });
    return;
  }
  if (k === 1) {
    put(S.startLine("mRNA", pair2(F.wA)));
    put(S.startLine("methylation", pair2(F.wB)));
    yy += 6;
    wrapText(ctx, colors, S.yLine(f2(st.yVals[0]), sgn2(st.yVals[1])), x, yy, mw, lh, { size: xs, fill: colors.ink1 });
    return;
  }
  const u = F.upd, mine = u.block === 0, feats = mine ? S.featA : S.featB, o = mine ? "u" : "t";
  const sum = [u.other[0] + u.y[0], u.other[1] + u.y[1]], n = Math.hypot(...sum);
  put(S.updHead(mine ? "mRNA" : "methylation"), { fill: colors.ink1, weight: "600" });
  put(S.zLine(params.weight, o));
  /* each feature's covariance with z, in its two parts: a column per part */
  const cx = [0, 46, 126, 190];
  yy += 2;
  S.pullHead(params.weight, o).forEach((h, j) => txt(ctx, colors, h, x + cx[j + 1], yy, { size: xs, fill: colors.ink3 }));
  feats.forEach((f, j) => {
    yy += lh;
    [f, f2(u.other[j]), f2(u.y[j]), f2(sum[j])].forEach((v, c) => txt(ctx, colors, v, x + cx[c], yy, { size: xs, fill: c === 3 ? colors.ink1 : colors.ink2 }));
  });
  yy += lh + 2;
  put(S.scaleLine(f2(n), pair2([sum[0] / n, sum[1] / n])), { fill: colors.highlight, weight: "600" });
}

/** this press's two pulls, head to tail, and their sum: the new loading vector's direction */
function drawPulls(ctx, colors, Lm, pullMax, u, feats, c) {
  /* the origin low in the box: with the signs held one way, every pull points upward */
  const { x, y, s } = Lm.vec, o = [x + s / 2, y + 0.8 * s], k = (0.7 * s) / pullMax;
  frame(ctx, colors, x, y, s, s, colors.grid);
  line(ctx, x, o[1], x + s, o[1], colors.grid); line(ctx, o[0], y, o[0], y + s, colors.grid);
  txt(ctx, colors, feats[0], x + s - 3, o[1] + 12, { size: colors.fsXs, fill: colors.ink3, align: "right" });
  txt(ctx, colors, feats[1], o[0] - 4, y + 12, { size: colors.fsXs, fill: colors.ink3, align: "right" });
  const P = (v) => [o[0] + v[0] * k, o[1] - v[1] * k];
  const a = P(u.other), sum = [u.other[0] + u.y[0], u.other[1] + u.y[1]], b = P(sum);
  vecArrow(ctx, o, a, colors.ink2, 1.6);
  vecArrow(ctx, a, b, colors.ink2, 1.6, [4, 3]);
  vecArrow(ctx, o, b, colors.highlight, 2.2);
  /* the key names each arrow by the table column it draws, right-aligned under the box */
  const mine = u.block === 0;
  S.pullKey(c, mine ? "u" : "t", mine ? "methylation" : "mRNA").forEach((kl, i) =>
    txt(ctx, colors, kl, x + s, y + s + 14 + 13 * i, { size: colors.fsXs, fill: i === 2 ? colors.highlight : colors.ink2, align: "right" }));
}

/* ========================================================= WEIGHT page */

const WL = { cap: 72, top: 112, x0: 40, sMax: 270 };
const H_WEIGHT = WL.top + WL.sMax + 44;
function wLayout(w) {
  const s = Math.min(WL.sMax, Math.floor(w - WL.x0 - 272));
  return { s, x: WL.x0, y: WL.top, side: WL.x0 + s + 26 };
}
const sweepOf = (c) => SWEEP.find((f) => String(f.w) === String(c)) ?? SWEEP[1];
/* each axis fitted to the data across all four weights, so a change of
   weight moves the tumours within one frame */
const W_RANGE = (() => {
  const ext = (key) => { const v = SWEEP.flatMap((f) => f.t[key]); const lo = Math.min(...v), hi = Math.max(...v), pad = 0.04 * (hi - lo); return [lo - pad, hi + pad]; };
  return { x: ext("mRNA"), y: ext("meth") };
})();
const W_ETA = Object.fromEntries(SWEEP.map((f) => [String(f.w), { mRNA: etaOf(f.t.mRNA, Y, 4), meth: etaOf(f.t.meth, Y, 4) }]));
function wMarks(L, c) {
  const f = sweepOf(c), [x0, x1] = W_RANGE.x, [y0, y1] = W_RANGE.y;
  return f.t.mRNA.map((t, i) => [L.x + ((t - x0) / (x1 - x0)) * L.s, L.y + L.s - ((f.t.meth[i] - y0) / (y1 - y0)) * L.s]);
}

function drawWeight(ctx, colors, w, params, anim, pointer) {
  const L = wLayout(w), found = shownStep(anim, "weight") >= 1 || inFlight(anim, "weight") != null;
  const t = inFlight(anim, "weight"), ez = ezOf(anim, "weight");
  const f = sweepOf(params.weight);
  wrapText(ctx, colors, found && t == null ? S.wCap.after(params.weight, f3(f.r[0])) : S.wCap.before, 10, 14, w - 20, 16, { fill: colors.ink1 });
  txt(ctx, colors, S.wDims, 10, WL.cap + 18, { size: colors.fsXs, fill: colors.ink2 });
  panelFrame(ctx, colors, { x: L.x, y: L.y, s: L.s }, "", S.wAxes);
  if (!found) {
    wrapText(ctx, colors, S.wBefore, L.x + 14, L.y + L.s / 2 - 8, L.s - 28, 16, { fill: colors.ink3 });
    return;
  }
  /* Fit: the tumours drop from the centre to their places; a change of
     weight after it moves each tumour from where the last weight put it */
  const to = wMarks(L, params.weight), from = ez ? wMarks(L, ez.params.weight) : null;
  const e = ez ? ease(ez.t) : 1, grow = t != null ? ease(seg(t, 0, 1)) : 1, c0 = [L.x + L.s / 2, L.y + L.s / 2];
  const pts = to.map((q, i) => (from ? lerpPt(from[i], q, e) : lerpPt(c0, q, grow)));
  pts.forEach((q, i) => dot(ctx, colors, q[0], q[1], 2.6, subColour(colors, Y[i])));
  const rNow = from ? lerp(sweepOf(ez.params.weight).r[0], f.r[0], e) : f.r[0];
  if (t == null) txt(ctx, colors, `r = ${f3(rNow)}`, L.x + 8, L.y + 18, { fill: colors.ink1, weight: "600" });

  /* beside it: the four weights, the current one framed */
  if (t == null) {
    const x = L.side, cols = [0, 46, 112, 170];
    let y = L.y + 10;
    S.wTable.forEach((h, j) => txt(ctx, colors, h, x + cols[j], y, { size: colors.fsXs, fill: colors.ink1, weight: "600" }));
    /* a row for each weight fitted so far (anim.visited, never the URL), in the control's order */
    const seen = WEIGHTS.filter((wv) => (anim.visited ?? []).includes(String(wv)) || String(wv) === params.weight);
    seen.forEach((wv, i) => {
      const ff = sweepOf(wv), cur = String(wv) === params.weight, yy = y + 22 + i * 19;
      [String(wv), f3(ff.r[0]), pct(W_ETA[String(wv)].mRNA), f3(ff.cvBER)].forEach((v, j) => txt(ctx, colors, v, x + cols[j], yy, { size: colors.fsSm, fill: cur ? colors.ink1 : colors.ink2, weight: cur ? "600" : "" }));
      if (cur) frame(ctx, colors, x - 5, yy - 14, Math.min(w - x - 4, cols[3] + 50), 19, colors.highlight, 1.5);
    });
    /* the table keeps the room of four rows, so the notes under it stay put as rows arrive */
    y += 22 + 4 * 19 + 2;
    const width = w - x - 8;
    y += 13 * wrapText(ctx, colors, S.wRppa(f3(f.r[1]), f3(f.r[2])), x, y, width, 13, { size: colors.fsXs, fill: colors.ink2 }) + 8;
    for (const n of S.wNotes) y += 13 * wrapText(ctx, colors, n, x, y, width, 13, { size: colors.fsXs, fill: colors.ink3 }) + 4;
  }
  if (pointer && t == null && !(ez && ez.t < 1)) {
    let hov = -1, best = 49;
    pts.forEach((q, i) => { const d = (q[0] - pointer.x) ** 2 + (q[1] - pointer.y) ** 2; if (d < best) { best = d; hov = i; } });
    if (hov >= 0) {
      ring(ctx, pts[hov][0], pts[hov][1], 6, colors.ink1);
      hoverLabel(ctx, colors, `${SUBTYPES[Y[hov]]} · mRNA ${f2(f.t.mRNA[hov])} · methylation ${f2(f.t.meth[hov])}`, pointer.x, pointer.y, w);
    }
  }
}

/* ========================================================= SELECT page */

const SL = { cap: 88, barsH: 150, stripH: 26, sMax: 200 };
const N_BARS = 60;
const H_SELECT = SL.cap + 30 + SL.barsH + 40 + SL.stripH + 64 + SL.sMax + 30;
function sLayout(w) {
  const x0 = 34, bw = Math.floor((w - x0 - 16) / N_BARS);
  const by = SL.cap + 30, sy = by + SL.barsH + 40;
  const s = Math.min(SL.sMax, Math.floor((w - x0) * 0.42));
  return { x0, bw, by, sy, scat: { x: x0, y: sy + SL.stripH + 64, s }, side: x0 + s + 30 };
}
const SEL_ETA = { all: etaOf(SELECT.tAll, Y, 4), cut: etaOf(SELECT.tCut, Y, 4) };
const SEL_MAX = Math.abs(SELECT.raw[0]);
const SEL_W1_DIFF = sweepOf(1).genes.filter((g) => !sweepOf(0.1).genes.includes(g)).length;
const SEL_NORM = {
  all: Math.hypot(...SELECT.raw),
  kept: Math.hypot(...SELECT.raw.slice(0, KEEPX.mRNA).map((v) => Math.abs(v) - SELECT.cut)),
};

function drawSelect(ctx, colors, w, params, anim, pointer) {
  const L = sLayout(w), n = Math.min(anim.n.select ?? 0, 3), p = inFlight(anim, "select");
  wrapText(ctx, colors, S.sCap[n], 10, 14, w - 20, 16, { fill: colors.ink1 });
  txt(ctx, colors, S.sZ, L.x0, L.by - 8, { size: colors.fsXs, fill: colors.ink2 });
  const base = L.by + SL.barsH, K = KEEPX.mRNA, cut = SELECT.cut;
  line(ctx, L.x0, base, L.x0 + N_BARS * L.bw, base, colors.axis);
  txt(ctx, colors, S.sBars(FEATURES.mRNA.toLocaleString("en-US")), L.x0, base + 30, { size: colors.fsXs, fill: colors.ink3 });
  if (n >= 1) {
    /* Keep (2026-10-10, measured): the 25th and 26th largest are 371.9 and
       371.1, so the soft threshold leaves the kept loadings 50.7 down to 0.8
       of a bar 422 tall. Shrinking the bars to that would flatten them, so
       the bars stay at the update's values, outlined once cut, and what is
       kept is the violet part above the largest dropped one. Switches at the
       press: nothing moves (tween-only-movement-no-fades). */
    for (let j = 0; j < N_BARS; j++) {
      const v = Math.abs(SELECT.raw[j]), h = (v / SEL_MAX) * SL.barsH, x = L.x0 + j * L.bw;
      if (n < 2) { ctx.fillStyle = colors.ink3; ctx.fillRect(x, base - h, L.bw - 1, h); continue; }
      frame(ctx, colors, x, base - h, L.bw - 1, h, colors.ink3);
      if (j < K) { const hc = ((v - cut) / SEL_MAX) * SL.barsH; ctx.fillStyle = colors.highlight; ctx.fillRect(x, base - h, L.bw - 1, hc); }
    }
    [1, K, N_BARS].forEach((r) => txt(ctx, colors, String(r), L.x0 + (r - 0.5) * L.bw, base + 13, { size: colors.fsXs, fill: colors.ink3, align: "center" }));
    if (n >= 2) {
      const yc = base - (cut / SEL_MAX) * SL.barsH;
      line(ctx, L.x0, yc, L.x0 + N_BARS * L.bw, yc, colors.ink1, 1, [3, 3]);
      txt(ctx, colors, S.sCut, L.x0 + N_BARS * L.bw, yc - 4, { size: colors.fsXs, fill: colors.ink1, align: "right" });
    }
    /* all 8,383, sorted: the 25 kept are a sliver at the left */
    const sy = L.sy, sw = N_BARS * L.bw, P = SELECT.raw.length;
    ctx.save(); ctx.strokeStyle = colors.ink3; ctx.lineWidth = 1; ctx.beginPath();
    for (let j = 0; j < P; j += 4) { const x = L.x0 + (j / P) * sw, hh = (Math.abs(SELECT.raw[j]) / SEL_MAX) * SL.stripH; j ? ctx.lineTo(x, sy + SL.stripH - hh) : ctx.moveTo(x, sy + SL.stripH - hh); }
    ctx.stroke(); ctx.restore();
    frame(ctx, colors, L.x0, sy, sw, SL.stripH, colors.grid);
    if (n >= 2) { ctx.fillStyle = colors.highlight; ctx.fillRect(L.x0, sy, Math.max(2, (K / P) * sw), SL.stripH); }
    txt(ctx, colors, S.sAll(FEATURES.mRNA.toLocaleString("en-US")), L.x0, sy + SL.stripH + 13, { size: colors.fsXs, fill: colors.ink3 });
    /* moved here from Weight (walk-through 2026-10-10): the kept genes are the design weight's too */
    if (n >= 2) {
      txt(ctx, colors, S.sWeight1(SEL_W1_DIFF, K), L.x0, sy + SL.stripH + 43, { size: colors.fsXs, fill: colors.ink2 });
      /* as selectVar lists them (the next step after the fit) */
      txt(ctx, colors, S.sTop(SELECT.names.slice(0, 5)), L.x0, sy + SL.stripH + 28, { size: colors.fsXs, fill: colors.ink1 });
    }
  }
  if (n >= 3 && p == null) drawSelectScores(ctx, colors, L, w);
  else if (n >= 3) drawSelectScores(ctx, colors, L, w, ease(seg(p, 0, 1)));
  if (pointer && n >= 1 && pointer.y > L.by && pointer.y < base) {
    const j = Math.floor((pointer.x - L.x0) / L.bw);
    if (j >= 0 && j < N_BARS && j < SELECT.names.length) {
      /* the loading as mixOmics reports it: scaled to length 1, before the cut over all genes, after it over the kept */
      const v = SELECT.mixSign * SELECT.raw[j], cutV = n >= 2 ? (j < K ? Math.sign(v) * (Math.abs(v) - cut) / SEL_NORM.kept : 0) : v / SEL_NORM.all;
      hoverLabel(ctx, colors, S.sHov(SELECT.names[j], f3(cutV)), pointer.x, pointer.y, w);
    }
  }
}

function drawSelectScores(ctx, colors, L, w, grow = 1) {
  const P = L.scat, xs = 1.08 * Math.max(...SELECT.tAll.map(Math.abs)), ys = 1.08 * Math.max(...SELECT.tCut.map(Math.abs));
  panelFrame(ctx, colors, P, "", [S.sScat[0], S.sScat[1](KEEPX.mRNA)]);
  const c0 = [P.x + P.s / 2, P.y + P.s / 2];
  SELECT.tAll.forEach((t, i) => {
    const q = [P.x + P.s / 2 + (t / xs) * (P.s / 2), P.y + P.s / 2 - (SELECT.tCut[i] / ys) * (P.s / 2)];
    const at = lerpPt(c0, q, grow);
    dot(ctx, colors, at[0], at[1], 2.2, subColour(colors, Y[i]), false);
  });
  if (grow < 1) return;
  txt(ctx, colors, `r = ${f2(SELECT.r)}`, P.x + 8, P.y + 16, { fill: colors.ink1, weight: "600" });
  const x = L.side;
  txt(ctx, colors, S.tileEtaS, x, P.y + 14, { size: colors.fsXs, fill: colors.ink1, weight: "600" });
  txt(ctx, colors, `all ${FEATURES.mRNA.toLocaleString("en-US")} genes  ${pct(SEL_ETA.all)}`, x, P.y + 32, { size: colors.fsXs });
  txt(ctx, colors, `${KEEPX.mRNA} kept genes  ${pct(SEL_ETA.cut)}`, x, P.y + 47, { size: colors.fsXs, fill: colors.ink1 });
  const n2 = wrapText(ctx, colors, S.tileEtaNote, x, P.y + 68, w - x - 8, 13, { size: colors.fsXs, fill: colors.ink3 });
  wrapText(ctx, colors, S.sSame, x, P.y + 74 + 13 * n2, w - x - 8, 13, { size: colors.fsXs, fill: colors.ink2 });
}

/* ========================================================= PREDICT page */

const PL = { cap: 72, sMax: 220, rppaW: 92, low: 150 };
const H_PREDICT = PL.cap + 18 + PL.sMax + 30 + PL.low;
function pLayout(w) {
  const x0 = 30, gap = 26;
  const s = Math.min(PL.sMax, Math.floor((w - x0 - 12 - PL.rppaW - 2 * gap) / 2));
  const y = PL.cap + 18;
  return { s, A: { x: x0, y, s }, B: { x: x0 + s + gap, y, s }, R: { x: x0 + 2 * s + 2 * gap, y, w: Math.min(PL.rppaW, w - 12 - (x0 + 2 * s + 2 * gap)), h: s }, low: { x: x0, y: y + s + 34 } };
}
const P_SPAN = Object.fromEntries(["mRNA", "meth"].map((b) => [b, 1.06 * Math.max(...PREDICT.train[b][0].map(Math.abs), ...PREDICT.train[b][1].map(Math.abs), ...PREDICT.test[b][0].map(Math.abs), ...PREDICT.test[b][1].map(Math.abs))]));
/** the balanced error rate: the mean over subtypes of the share called wrongly */
function berOf(calls) {
  const rates = SUBTYPES.map((_, l) => {
    const idx = PREDICT.truth.map((t, i) => (t === l ? i : -1)).filter((i) => i >= 0);
    return idx.filter((i) => calls[i] !== l).length / idx.length;
  });
  return mean(rates);
}
const P_STATS = [1, 2, 3, 4].map((k) => {
  const v = PREDICT.vote[k - 1], a = PREDICT.calls.mRNA[k - 1], b = PREDICT.calls.meth[k - 1];
  return {
    ber: berOf(v), berA: berOf(a), berB: berOf(b),
    same: v.filter((c, i) => c === a[i]).length,
    pole: v.filter((c, i) => c === 3 && PREDICT.truth[i] !== 3).length,
  };
});
const testOf = (params) => clamp((Number(params.sample) || TRACED_TEST) - 1, 0, N_TEST - 1);

function drawPredict(ctx, colors, w, params, anim, pointer) {
  const L = pLayout(w), n = Math.min(anim.n.predict ?? 0, 3), p = inFlight(anim, "predict");
  const k = Number(params.components) || 2, i0 = testOf(params);
  wrapText(ctx, colors, S.pCap[n], 10, 14, w - 20, 16, { fill: colors.ink1 });
  const calls = { mRNA: PREDICT.calls.mRNA[k - 1][i0], meth: PREDICT.calls.meth[k - 1][i0] };
  [["mRNA", L.A, S.blockA], ["meth", L.B, S.blockB]].forEach(([b, P, name]) => {
    panelFrame(ctx, colors, P, name, S.pAxes);
    const px = toPxOf(P, P_SPAN[b]);
    PREDICT.train[b][0].forEach((x, i) => { const q = px(x, PREDICT.train[b][1][i]); dot(ctx, colors, q[0], q[1], 1.7, subColour(colors, Y[i]), false); });
    /* the centres go on top of the test tumours, so the call's line can be followed to one */
    const centres = () => PREDICT.centres[b].forEach((c, l) => { const q = px(c[0], c[1]); cross(ctx, q[0], q[1], 7, colors.ink1); cross(ctx, q[0], q[1], 5.4, subColour(colors, l)); });
    if (n < 1) centres();
    if (n >= 1) {
      PREDICT.test[b][0].forEach((x, i) => { const q = px(x, PREDICT.test[b][1][i]); square(ctx, colors, q[0], q[1], 2.6, subColour(colors, PREDICT.truth[i])); });
      centres();
      const q = px(PREDICT.test[b][0][i0], PREDICT.test[b][1][i0]);
      if (n >= 2 && !(p != null && n === 2)) {
        const c = PREDICT.centres[b][calls[b]], cq = px(c[0], c[1]);
        line(ctx, q[0], q[1], cq[0], cq[1], colors.ink1, 1.4, [3, 3]);
        ring(ctx, cq[0], cq[1], 10, colors.ink1);
        txt(ctx, colors, S.pCalls(b === "mRNA" ? "mRNA" : "methylation", SUBTYPES[calls[b]]), P.x, P.y + P.s + 28, { size: colors.fsSm, fill: colors.ink1, weight: "600" });
      }
      ring(ctx, q[0], q[1], 7, colors.ink1);
    }
  });
  /* RPPA: not measured on any test tumour */
  frame(ctx, colors, L.R.x, L.R.y, L.R.w, L.R.h, colors.unknown, 1, [4, 3]);
  txt(ctx, colors, S.rppa, L.R.x, L.R.y - 6, { fill: colors.ink1, weight: "600", size: colors.fsXs });
  txt(ctx, colors, S.notMeasured, L.R.x + L.R.w / 2, L.R.y + L.R.h / 2, { size: colors.fsXs, fill: colors.unknown, align: "center" });
  if (n >= 2) txt(ctx, colors, S.noVote, L.R.x, L.R.y + L.R.h + 28, { size: colors.fsSm, fill: colors.unknown, weight: "600" });

  /* the vote and what it does on all 102 */
  const wts = PREDICT.weights;
  if (n >= 3) {
    [[L.A, wts[0]], [L.B, wts[1]], [{ x: L.R.x }, wts[2]]].forEach(([P, wv], j) => txt(ctx, colors, S.pWeight(f2(wv)), P.x, L.A.y + L.s + 44, { size: colors.fsXs, fill: j === 2 ? colors.unknown : colors.ink2 }));
  }
  if (n >= 3 && !(p != null && n === 3)) {
    const x = L.low.x, width = w - x - 12;
    let y = L.low.y + 34;
    const sums = {};
    sums[calls.mRNA] = (sums[calls.mRNA] ?? 0) + wts[0];
    sums[calls.meth] = (sums[calls.meth] ?? 0) + wts[1];
    const vote = PREDICT.vote[k - 1][i0];
    const parts = S.pSums(Object.entries(sums).map(([c, s]) => S.pSum(SUBTYPES[c], f2(s))).join(" · "));
    txt(ctx, colors, parts, x, y, { size: colors.fsSm, fill: colors.ink2 });
    txt(ctx, colors, S.pVote(SUBTYPES[vote]), x + Math.min(width - 150, 300), y, { size: colors.fsMd, fill: colors.ink1, weight: "600" });
    txt(ctx, colors, S.pTruth(SUBTYPES[PREDICT.truth[i0]]), x + Math.min(width - 150, 300), y + 16, { size: colors.fsXs, fill: colors.ink2 });
    y += 30;
    y += 14 * wrapText(ctx, colors, S.pTwo(P_STATS[k - 1].same), x, y, width, 14, { size: colors.fsXs, fill: colors.ink1 });
    const cv = PREDICT.cv;
    wrapText(ctx, colors, S.pThree(cv.overrule[k - 1], f3(cv.vote[k - 1]), f3(cv.mRNA[k - 1])), x, y + 2, width, 14, { size: colors.fsXs, fill: colors.ink3 });
  }
  const hit = n >= 1 ? pickTest(L, pointer) : null;
  if (hit != null) hoverLabel(ctx, colors, S.pHov(hit + 1, SUBTYPES[PREDICT.truth[hit]]), pointer.x, pointer.y, w);
}

function pickTest(L, pointer) {
  if (!pointer) return null;
  let best = -1, bd = 49;
  [["mRNA", L.A], ["meth", L.B]].forEach(([b, P]) => {
    const px = toPxOf(P, P_SPAN[b]);
    PREDICT.test[b][0].forEach((x, i) => { const q = px(x, PREDICT.test[b][1][i]), d = (q[0] - pointer.x) ** 2 + (q[1] - pointer.y) ** 2; if (d < bd) { bd = d; best = i; } });
  });
  return best >= 0 ? best : null;
}

/* ==================================================== stages and easing */

const stepsOf = (stage, st, params) => (stage === "design" ? loopEnd(st, params) : stage === "weight" ? 1 : 3);
const durOf = (stage, n) => {
  if (stage === "design") return n === 1 ? 450 : 1400;
  if (stage === "weight") return 1200;
  if (stage === "select") return n === 3 ? 900 : 450;
  return 450;
};
const EASE_MS = 900;
const shownStep = (anim, stage) => (anim.n[stage] ?? 0) - (anim.stage === stage && anim.t < 1 ? 1 : 0);
const inFlight = (anim, stage) => (anim.stage === stage && anim.t < 1 ? anim.t : null);
const ezOf = (anim, page) => (anim.ez && anim.ez.page === page && anim.ez.t < 1 ? anim.ez : null);
const complete = (anim, stage, st, params) => (anim.n[stage] ?? 0) >= stepsOf(stage, st, params);
const formulaKey = (params, anim) => {
  if (params.page === "design") return shownStep(anim, "design") >= 1 ? "update" : "objective";
  if (params.page === "weight") return "objective";
  if (params.page === "select") return "sparse";
  return "vote";
};

/* ------------------------------------------------------------- widget */

defineWidget({
  slug: "diablo",
  status: "draft",
  title: "Multi-omics: DIABLO",
  subtitle: S.subtitle,
  credit: "Data: TCGA Research Network (PanCanAtlas UCEC), via cBioPortal",
  layout: "side",
  height: (params) => ({ design: H_DESIGN, weight: H_WEIGHT, select: H_SELECT }[params.page] ?? H_PREDICT),
  pointer: true,

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, groupHeads: true, default: "design", display: true },
    weight: { type: "segmented", label: S.weightLabel, detail: S.weightDetail, options: WEIGHT_OPTS, default: "0.1", display: true, when: { param: "page", oneOf: ["design", "weight"] } },
    components: { type: "segmented", label: S.compLabel, detail: S.compDetail, options: COMP_OPTS, default: "2", display: true, when: ON("predict") },
    sample: { type: "int", label: S.sampleLabel, detail: S.sampleDetail, min: 1, max: N_TEST, default: TRACED_TEST, display: true, when: ON("predict") },
    /* the Design blocks' seed: 100 is the example measured and mocked (`_lab/diablo-toy.mjs`) */
    seed: { type: "int", min: 1, max: 999, default: 100, hidden: true },
    /* authoring escape hatch, first render only: presses already made on the page the link opens */
    shown: { type: "int", min: 0, max: MAX_PRESSES, default: 0, hidden: true },
  },

  legend: ({ params }) => {
    if (params.page === "design") return [
      { token: "cluster-a", label: S.sub[0], mark: "dot" }, { token: "cluster-b", label: S.sub[1], mark: "dot" },
      { token: "highlight", label: S.arrow, mark: "line" }, { token: "reference", label: S.start, mark: "line" },
    ];
    const subs = SUBTYPES.map((s, i) => ({ token: `cluster-${"abcd"[i]}`, label: s, mark: "dot" }));
    if (params.page === "select") return [...subs, { token: "highlight", label: "kept gene", mark: "bar" }];
    if (params.page === "predict") return [...subs, { token: "unknown", label: "not measured", mark: "line" }];
    return subs;
  },

  compute: ({ rng }) => makeToy(rng),

  /* Predict: a click on a test tumour's square, in either block, traces it */
  regions: ({ w, params, anim }) => {
    if (params.page !== "predict" || (anim?.n?.predict ?? 0) < 1) return [];
    const L = pLayout(w), out = [];
    [["mRNA", L.A], ["meth", L.B]].forEach(([b, P]) => {
      const px = toPxOf(P, P_SPAN[b]);
      PREDICT.test[b][0].forEach((x, i) => { const q = px(x, PREDICT.test[b][1][i]); out.push({ x: q[0] - 4, y: q[1] - 4, w: 8, h: 8, set: { sample: i + 1 }, label: `test tumour ${i + 1} in ${BLOCK_NAME[b]}` }); });
    });
    return out;
  },

  animation: {
    stepLabel: S.stepLabel,
    stepTitle: S.stepTitle,
    /* each press is read once: Step alone (play-only-for-motion-or-repetition) */
    runLabel: null,

    init: ({ params, state, fromScratch }) => {
      const stage = params.page;
      const anim = { stage, n: {}, t: 1, dur: 1400, halt: false, ez: null, last: { ...params } };
      anim.n[stage] = fromScratch ? 0 : clamp(Number(params.shown) || 0, 0, stepsOf(stage, state, params));
      /* the weights fitted on the Weight page, for its table's rows */
      anim.visited = stage === "weight" && anim.n.weight >= 1 ? [params.weight] : [];
      anim.beat = anim.n[stage];
      anim.done = complete(anim, stage, state, params);
      return anim;
    },

    advance: (anim, { dt, state, params }) => {
      /* a press a page switch interrupted ends here, before the new page's (mid-press-page-switch) */
      if (anim.halt) { anim.halt = false; return false; }
      const stage = anim.stage;
      if (anim.ez && anim.ez.t < 1) anim.ez.t = Math.min(1, anim.ez.t + dt / EASE_MS);
      if (anim.mode === "ease") {
        if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
        anim.done = complete(anim, stage, state, params) && anim.t >= 1;
        return anim.t < 1 || (anim.ez != null && anim.ez.t < 1);
      }
      if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
      else if ((anim.n[stage] ?? 0) < stepsOf(stage, state, params)) {
        anim.n[stage] = (anim.n[stage] ?? 0) + 1;
        if (stage === "weight" && !anim.visited.includes(params.weight)) anim.visited.push(params.weight);
        anim.dur = durOf(stage, anim.n[stage]);
        anim.t = 0;
      }
      anim.beat = anim.n[stage] ?? 0;
      anim.done = complete(anim, stage, state, params) && anim.t >= 1;
      if (anim.t >= 1 && anim.ez) anim.ez.t = 1;
      return anim.t < 1;
    },

    rebuild: (anim, { params, state }) => {
      const stage = params.page, was = anim.stage;
      /* only a page change, or a new weight on Design, ends a press in flight (mid-press-page-switch) */
      if (stage !== was && anim.t < 1) { anim.t = 1; anim.halt = true; }
      /* a new weight is a new loop: Design starts over (a data change for that page; the other pages keep their presses) */
      if (params.weight !== anim.last.weight) {
        if (stage === "design" && anim.t < 1) { anim.t = 1; anim.halt = true; }
        anim.n.design = 0;
      }
      /* on Weight, once fitted, a new weight moves each tumour from where the last one put it */
      if (stage === was && stage === "weight" && complete(anim, "weight", state, params) && params.weight !== anim.last.weight) {
        anim.ez = { page: "weight", params: { ...anim.last }, t: 0 };
        anim.easing = true;
        if (!anim.visited.includes(params.weight)) anim.visited.push(params.weight);
      } else if (stage !== was) anim.ez = null;
      anim.last = { ...params };
      anim.stage = stage;
      anim.beat = anim.n[stage] ?? 0;
      anim.done = complete(anim, stage, state, params) && anim.t >= 1;
    },
  },

  draw({ ctx, colors, w, params, state, anim, pointer }) {
    renderFormula(formulaKey(params, anim));
    if (params.page === "design") drawDesign(ctx, colors, w, params, state, anim, pointer);
    else if (params.page === "weight") drawWeight(ctx, colors, w, params, anim, pointer);
    else if (params.page === "select") drawSelect(ctx, colors, w, params, anim, pointer);
    else drawPredict(ctx, colors, w, params, anim, pointer);
  },

  readout({ params, state, anim }) {
    const page = params.page, n = shownStep(anim, page);
    if (page === "design") {
      const frames = loopOf(state, params), F = frames[clamp(n, 0, frames.length - 1)];
      return [
        { label: S.tileR, value: F.r != null ? f2(F.r) : S.tileWait, note: S.tileRNote },
        { label: S.tileEtaA, value: F.etaA != null ? pct(F.etaA) : S.tileWait, note: S.tileEtaNote },
        { label: S.tileEtaB, value: F.etaB != null ? pct(F.etaB) : S.tileWait, note: S.tileEtaNote },
      ];
    }
    if (page === "weight") {
      const f = sweepOf(params.weight);
      return [
        { label: S.tileRw, value: n >= 1 ? f3(f.r[0]) : S.tileWait, note: S.tileRwNote },
        { label: S.tileEtaA, value: n >= 1 ? pct(W_ETA[params.weight].mRNA) : S.tileWait, note: S.tileEtaNote },
        { label: S.tileCv, value: n >= 1 ? f3(f.cvBER) : S.tileWait, note: S.tileCvNote },
      ];
    }
    if (page === "select") {
      return [
        { label: S.tileKept, value: n >= 2 ? `${KEEPX.mRNA} of ${FEATURES.mRNA.toLocaleString("en-US")}` : n >= 1 ? `${FEATURES.mRNA.toLocaleString("en-US")}` : S.tileWait, note: S.tileKeptNote },
        { label: S.tileRs, value: n >= 3 ? f2(SELECT.r) : S.tileWait, note: S.tileRsNote },
        { label: S.tileEtaS, value: n >= 3 ? `${pct(SEL_ETA.all)} → ${pct(SEL_ETA.cut)}` : S.tileWait, note: S.tileEtaSNote },
      ];
    }
    const k = Number(params.components) || 2, P = P_STATS[k - 1];
    return [
      { label: S.tileBer, value: n >= 3 ? f3(P.ber) : S.tileWait, note: S.tileBerNote(k) },
      { label: S.tileBlock, value: n >= 2 ? `${f3(P.berA)} · ${f3(P.berB)}` : S.tileWait, note: S.tileBerNote(k) },
      { label: S.tileSame, value: n >= 3 ? `${P.same} of ${N_TEST}` : S.tileWait, note: S.tileSameNote },
    ];
  },

  summary({ params, state, anim }) {
    const page = params.page, n = shownStep(anim, page);
    if (page === "design") {
      const frames = loopOf(state, params), F = frames[clamp(n, 0, frames.length - 1)];
      return `Two simulated blocks and the subtype at design weight ${params.weight}; ${n} of ${frames.length - 1} presses${F.r != null ? `; the scores correlate ${f2(F.r)}` : ""}.`;
    }
    if (page === "weight") return `The TCGA UCEC blocks at design weight ${params.weight}: ${n >= 1 ? `mRNA and methylation component 1 correlate ${f3(sweepOf(params.weight).r[0])}` : "not fitted yet"}.`;
    if (page === "select") return `mRNA's component 1 loading vector over ${FEATURES.mRNA} genes; ${n >= 2 ? `cut to ${KEEPX.mRNA}` : "every gene"}.`;
    return `Test tumour ${params.sample}, mRNA and methylation measured, RPPA missing; ${params.components} components; ${n} of 3 presses.`;
  },
});

/* The page draws mixOmics' own calls (PREDICT.calls). Recomputed from the
   stored scores as the nearest centre over components 1..k (mixOmics'
   centroids.dist), 815 of 816 agree; the one is a tie lost to
   rounding the scores to 3 decimals (test tumour 31, 3 components:
   8.650 against 8.648). */
