/* ============================================================================
   Widget 99 · Multi-omics: Shared Components (`shared-components`) — PHM5003
   10, 01 cell 2 (matrix factorization X ≈ T·Wᵀ; N-integration and its
   max Σ cov(T₁ⱼ, T₂ⱼ); P-integration, X = [X₁; X₂]), 02 cell 0 (DIABLO's
   latent variables) and 03 cells 12–13 (pls(X$mRNA, X$meth, ncomp = 1) and
   the correlation of its two scores).

   The misconception (catalogue § The multi-omics arc, slot 99): a block's
   component is its largest variation. PLS takes, in each block, the
   direction whose scores covary most with the other block's, which is not
   the direction of largest variance. Measured on the lesson's own blocks
   (`_lab/multiomics-measure.R shared`): each block's largest-variance
   direction (PC1) correlates 0.37 · 0.51 · 0.47 with the other's; PLS
   component 1 0.89 · 0.89 · 0.78, keeping 1–2 points less of each block.

   HOW IT GOT HERE, five rounds in a day, every call his from a `_lab` mock
   ("all recommendations" each time): the draft set PCA against PLS; round 1
   added mixOmics' loop and a Factorize page; round 2 dropped PCA as a method
   and kept it as the dashed BENCHMARK; round 3 put the picture and the
   matrix on one page with a traced sample; round 4 (his "review it from a
   student's viewpoint ... this widget should explain the concepts the
   notebook introduces", `_lab/shared-components-notebook-mock.html`) laid the
   pages out in 01 cell 2's order and took the notebook's single letter W for
   the loadings:

     METHOD
       Factorization   one block (mRNA): Score (w₁, the direction that
                       rebuilds the most of X; t₁ = Xw₁) · Rebuild (t₁w₁ᵀ,
                       each sample at its foot on the arrow) · Subtract (E) ·
                       Component 2 (from E; T and W gain their second
                       columns, and with L = P the rebuild is exact). The
                       matrices in the notebook's shapes: X (N × P) ≈ T
                       (N × L) · Wᵀ (L × P).
       N-integration   the two blocks on the same samples, matrices' rows
                       aligned across the page; mixOmics' loop as presses
                       (Start · Update mRNA · Update methylation …, from a
                       start 80° off so the rule can be seen), then Rebuild ·
                       Subtract · Shortcut (X₁ᵀX₂ and its first singular pair,
                       which is the loop's end, and exists only because the
                       rows are the same samples).
       P-integration   two studies with the same two genes: Stack (X₂ moves
                       under X₁) · Find w (one w for both, each gene's
                       covariance with the subtype, the notebook's "PLS
                       against a response") · Score (each study's samples
                       their own scores). Per-study centring (MINT) was
                       measured and left out: it gave no clean lesson
                       without a held-out study.
     DATA
       TCGA UCEC       the lesson's 405 training samples, Pair over the three
                       pairs 03 cell 13 correlates.

   A traced sample (rail control, or a click on a dot or a matrix row) runs
   through Factorization and N-integration with its arithmetic beside it.
   "Kept" means one thing on every page: the share of a block's variance
   along w, ‖t‖² / ‖X‖², what t wᵀ rebuilds.

   Nothing is fitted on the page for TCGA UCEC: data.js (generated by
   `_lab/multiomics-measure.R widget99`) holds the scores, weights and kept
   shares. The Method blocks are simulated here; the largest-variance
   directions are exact 2 × 2 eigenvectors and PLS's the loop's end.
   ========================================================================= */

import { defineWidget, mathmlRenders } from "../core/index.js";
import { SUBTYPES, Y, BLOCKS, PAIRS } from "./data.js";

const PAGES = [
  { value: "factorization", label: "Factorization", group: "Method" },
  { value: "n-integration", label: "N-integration", group: "Method" },
  { value: "p-integration", label: "P-integration", group: "Method" },
  { value: "data", label: "TCGA UCEC", group: "Data" },
];
const SHORT = { mRNA: "mRNA", meth: "meth", rppa: "RPPA" };
const PAIR_OPTS = PAIRS.map((p) => ({ value: `${p.a}-${p.b}`.toLowerCase(), label: `${SHORT[p.a]}–${SHORT[p.b]}` }));
const ON = (page) => ({ param: "page", equals: page });
const BLOCK_NAME = { mRNA: "mRNA", meth: "Methylation", rppa: "RPPA" };
const BLOCK_UNIT = { mRNA: "genes", meth: "CpG sites", rppa: "proteins" };
const N_DATA = Y.length;
const MAX_ROUNDS = 5;
const N_CONCEPT = 80;
const N_STUDY = 40;
/* the traced sample a link opens on: subtype 2, with values well away from
   0 in both blocks, so its arithmetic is not all near-zero terms (picked on
   seed 1's blocks, round 3's mock) */
const TRACED = 62;

/* ------------------------------------------------------------- strings */

const S = {
  subtitle:
    "Partial least squares finds, in each of two omics blocks measured on the same samples, the direction whose scores covary most with the other block's. " +
    "Each block's weights are its features' covariances with the other block's scores, found by alternating between the blocks. " +
    "Like other matrix factorizations it writes each block as scores times loadings, but the components are chosen to agree across blocks rather than to keep the most variance within one.",
  pageLabel: "Step",
  pairLabel: "Pair",
  pairDetail: "two of the three blocks, measured on the same 405 samples",
  sampleLabel: "Traced sample",
  sampleDetail: "the sample whose numbers are worked through; a click on a dot or a matrix row picks one",

  blockA: "mRNA",
  blockE: "mRNA: E, after component 1",
  blockB: "Methylation",
  featA: ["gene 1", "gene 2"],
  featB: ["CpG 1", "CpG 2"],
  scores: "Scores",
  scoreX: "mRNA score t",
  scoreY: "methylation score u",
  sub: ["Subtype 1", "Subtype 2"],
  arrow: "component 1",

  /* Factorization */
  fCap: [
    "One block: mRNA, 2 genes measured on 80 samples. Each dot is one row of X.",
    "Score: w₁ is the direction that rebuilds the most of X. Each sample's score is its row times w₁, its position along the arrow.",
    "Rebuild: t₁w₁ᵀ puts every sample at its foot on the arrow (hollow). This is the part of X that component 1 keeps.",
    "Subtract: E = X − t₁w₁ᵀ is what is left, the gap from each foot to its dot.",
    "Component 2: each sample moves to its row of E, its gap from arrow 1. With 2 features E lies on one line, so w₂ has no choice: the one direction left. With thousands of features, component 2 is E's direction of largest variance. T and W now have two columns, and X = T·Wᵀ exactly.",
  ],
  fRow: (n, a, b) => `sample ${n}: gene 1 = ${a}, gene 2 = ${b}`,
  fScore: (k, x, w, t) => `t${k} = ${x[0]} × ${w[0]} + ${x[1]} × ${w[1]} = ${t}`,
  fRebuilt: (t, w, r) => `rebuilt row = t₁ × w₁ = ${t} × (${w}) = (${r})`,
  fE: (e) => `E row = row − rebuilt = (${e})`,
  fBoth: (r) => `t₁w₁ + t₂w₂ = (${r}), the row of X exactly`,
  shapes: ["N × P", "N × L", "L × P"],

  /* N-integration */
  caption: {
    before: "Two blocks measured on the same 80 samples: each dot above is one row of the matrix below it.",
    start: "Start: methylation's arrow points in an arbitrary direction. Each sample's methylation score u is its position along it.",
    updA: "Update mRNA: each gene's weight becomes its covariance with the methylation scores u. The arrow, w and the t column change together.",
    updB: "Update methylation: each CpG site's weight becomes its covariance with the mRNA scores t. The arrow, w and the u column change together.",
    done: "Another round changes neither arrow: PLS's component 1. Dashed: each block's direction of largest variance.",
    rebuild: "Rebuild: t wᵀ puts every sample at its foot on its block's arrow (hollow).",
    subtract: "Subtract: E = X − t wᵀ is what component 1 leaves. Component 2 is found in E the same way.",
    shortcut: "Shortcut: the loop computed the first singular pair of X₁ᵀX₂. It multiplies the two tables row by row, so it exists only because the rows are the same samples.",
  },
  sameRows: "N-integration: the rows are the same 80 samples in both tables.",
  sampleHead: (n, g) => `sample ${n} · ${g}`,
  noArrow: "no arrow yet",
  covHead: (b) => (b === "a" ? "this press: w from u" : "this press: w from t"),
  covLine: (f, o, v) => `cov(${f}, ${o}) = ${v}`,
  scaleLine: (n, w) => `÷ ${n} (length 1) → w = (${w})`,
  rebuiltLine: (s, t, v) => `${s} rebuilt = ${t} × w = (${v})`,
  eLine: (s, v) => `${s} E row = (${v})`,
  crossHead: "X₁ᵀX₂ / n",
  pairHead: "first singular pair",
  sameAs: "the loop's w₁ and w₂",
  mX: ["X₁", "X₂"], mT: ["t", "u"], mE: "E",
  colPls: "PLS",
  colRef: ["largest", "variance"],
  rowR: "correlation r",
  rowKept: (name) => `${name} kept`,

  /* P-integration */
  pCap: [
    "Two studies measured the same 2 genes on different samples, 40 each. Study 2 reads higher on both genes.",
    "Stack: the studies share their columns, so their tables stack into one, X = [X₁; X₂].",
    "Find w: one w for both studies, each gene's covariance with the subtype, scaled to length 1.",
    "Score: every sample, from either study, gets its score t = row × w along the same arrow.",
  ],
  study: ["study 1", "study 2"],
  studyKey: "● study 1   ■ study 2",
  pCov: (g, v) => `cov(${g}, subtype) = ${v}`,
  pW: (n, w) => `÷ ${n} (length 1) → w = (${w}), one w for both studies`,
  pScore: (s, t) => `${s}: scores from ${t}`,

  /* TCGA UCEC */
  dims: (b) => `${BLOCK_NAME[b]}: ${N_DATA} samples × ${BLOCKS[b].features.toLocaleString("en-US")} ${BLOCK_UNIT[b]}`,
  strip: (b) => `${BLOCK_NAME[b]} component 1`,
  dataBefore: "Component 1 gives each sample one score per block.",
  weights: (b) => `${BLOCK_NAME[b]} w: ${BLOCKS[b].features.toLocaleString("en-US")} weights`,

  /* tiles */
  tileR: "Correlation of the scores",
  tileRNote: "t and u, the two blocks' component 1",
  tileCov: "Covariance of the scores",
  tileCovNote: "what PLS makes as large as it can",
  tileKept: (b) => `${b} kept`,
  tileKeptNote: "share of the block's variance along w",
  tileK1: "Component 1 keeps",
  tileK2: "Components 1 and 2 keep",
  tileKNote: "share of X's variance",
  tileShape: "T and W",
  tileShapeNote: "N × L and P × L",
  tileW: "Shared w",
  tileWNote: "the same weights for both studies",
  tileSub: "Scores and subtype",
  tileSubNote: "correlation of t with the subtype, all 80",
  tileN: "Samples",
  tileWait: "—",

  hovSample: (n, g) => `sample ${n} · ${g}`,
  hovStudy: (s, g) => `${s} · ${g}`,
  hovData: (st, a, ta, b, tb) => `${st} · ${a} ${ta} · ${b} ${tb}`,
};

/* the N-integration presses: the loop (its length is the blocks', set in makeBlocks), then the factorization */
const AFTER = ["Rebuild", "Subtract", "Shortcut"];
const AFTER_TITLE = [
  "Rebuild each block from its score column: t wᵀ",
  "Subtract the rebuilt part: E = X − t wᵀ",
  "Find both weight vectors in one step, as the first singular pair of X₁ᵀX₂",
];
const loopLabel = (n) => (n === 0 ? "Start" : n % 2 === 1 ? "Update mRNA" : "Update methylation");
const loopTitle = (n) => (n === 0
  ? "Point methylation's arrow in an arbitrary direction and score the samples along it"
  : n % 2 === 1
    ? "Set each gene's weight to its covariance with the methylation scores u"
    : "Set each CpG site's weight to its covariance with the mRNA scores t");
const SLOTS = 2 + 2 * MAX_ROUNDS + AFTER.length;
const N_LABELS = Object.fromEntries(Array.from({ length: SLOTS }, (_, n) => [n, loopLabel(n)]));
const N_TITLES = Object.fromEntries(Array.from({ length: SLOTS }, (_, n) => [n, loopTitle(n)]));
const FIND_TITLE = "In each block, find the direction whose scores covary most with the other block's, and give every sample its score along it";
const F_LABELS = { 0: "Score", 1: "Rebuild", 2: "Subtract", 3: "Component 2" };
const F_TITLES = {
  0: "Find the direction that rebuilds the most of X, and score every sample along it: t₁ = Xw₁",
  1: "Rebuild X from the scores: t₁w₁ᵀ",
  2: "Subtract the rebuilt part: E = X − t₁w₁ᵀ",
  3: "Find component 2 in E the same way",
};
const P_LABELS = { 0: "Stack", 1: "Find w", 2: "Score" };
const P_TITLES = {
  0: "Stack the two studies' tables into one: X = [X₁; X₂]",
  1: "Set each gene's weight to its covariance with the subtype: one w for both studies",
  2: "Score every sample along the shared w",
};

S.stepLabel = {
  param: "page",
  labels: {
    factorization: { anim: "beat", labels: F_LABELS, default: F_LABELS[3] },
    "n-integration": { anim: "beat", labels: N_LABELS, default: AFTER[2] },
    "p-integration": { anim: "beat", labels: P_LABELS, default: P_LABELS[2] },
    data: "Find component 1",
  },
  default: "Find component 1",
};
S.stepTitle = {
  param: "page",
  labels: {
    factorization: { anim: "beat", labels: F_TITLES, default: F_TITLES[3] },
    "n-integration": { anim: "beat", labels: N_TITLES, default: AFTER_TITLE[2] },
    "p-integration": { anim: "beat", labels: P_TITLES, default: P_TITLES[2] },
    data: FIND_TITLE,
  },
  default: FIND_TITLE,
};

/* --------------------------------------------------------- formula card */

const MATHML = mathmlRenders();
const mi = (s) => `<mi>${s}</mi>`, mo = (s) => `<mo>${s}</mo>`, sub = (a, b) => `<msub><mi>${a}</mi><mn>${b}</mn></msub>`;
const supT = (s) => `<msup>${s}<mi>T</mi></msup>`, gap = (em) => `<mspace width="${em}em"/>`;
const under = (s, u) => `<munder>${s}<mtext mathsize="70%">${u}</mtext></munder>`;
const MATH = {
  factor1: {
    math: `<math display="block"><mrow>${under(mi("X"), "N × P")}${mo("≈")}${under(mi("T"), "N × L")}${mo("·")}${under(supT(mi("W")), "L × P")}${mo(",")}${gap(1)}${mi("t")}${mo("=")}${mi("X")}${mi("w")}</mrow></math>`,
    plain: "X (N × P) ≈ T (N × L) · Wᵀ (L × P),   t = X w",
    note: "A row of T is one sample's scores; a column of W is one component's loadings, how much each feature contributes. On one block, component 1's w is the direction that rebuilds the most of X.",
  },
  pls: {
    math: `<math display="block"><mrow>${mi("t")}${mo("=")}${sub("X", 1)}${sub("w", 1)}${mo(",")}${gap(0.6)}${mi("u")}${mo("=")}${sub("X", 2)}${sub("w", 2)}${mo(",")}${gap(1)}<munder><mo>max</mo><mrow>${mo("‖")}${sub("w", 1)}${mo("‖")}${mo("=")}${mo("‖")}${sub("w", 2)}${mo("‖")}${mo("=")}<mn>1</mn></mrow></munder>${gap(0.3)}<mtext>cov</mtext>${mo("(")}${mi("t")}${mo(",")}${mi("u")}${mo(")")}</mrow></math>`,
    plain: "t = X₁w₁,  u = X₂w₂,   max over ‖w₁‖ = ‖w₂‖ = 1 of cov(t, u)",
    note: "One pair (w₁, w₂) for the two blocks together: the first of the components that maximise Σ cov(T₁ⱼ, T₂ⱼ). The benchmark is each block's direction of largest variance.",
  },
  loop: {
    math: `<math display="block"><mrow>${mi("t")}${mo("=")}${sub("X", 1)}${sub("w", 1)}${mo(",")}${gap(0.5)}${sub("w", 1)}${mo("∝")}${supT(sub("X", 1))}${mi("u")}${mo(";")}${gap(1.2)}${mi("u")}${mo("=")}${sub("X", 2)}${sub("w", 2)}${mo(",")}${gap(0.5)}${sub("w", 2)}${mo("∝")}${supT(sub("X", 2))}${mi("t")}</mrow></math>`,
    plain: "t = X₁w₁,  w₁ ∝ X₁ᵀu;    u = X₂w₂,  w₂ ∝ X₂ᵀt",
    note: "Each block's weights are its features' covariances with the other block's scores, scaled to length 1; repeated until neither changes, they maximise cov(t, u). The dashed benchmark is each block's direction of largest variance.",
  },
  factorN: {
    math: `<math display="block"><mrow>${sub("X", 1)}${mo("≈")}${mi("t")}${supT(sub("w", 1))}${mo("+")}${sub("E", 1)}${mo(",")}${gap(1)}${sub("X", 2)}${mo("≈")}${mi("u")}${supT(sub("w", 2))}${mo("+")}${sub("E", 2)}</mrow></math>`,
    plain: "X₁ ≈ t w₁ᵀ + E₁,   X₂ ≈ u w₂ᵀ + E₂",
    note: "Each block keeps its own factorization, X ≈ T·Wᵀ; what the two share is that their score columns are chosen to agree.",
  },
  shortcut: {
    math: `<math display="block"><mrow>${mo("(")}${sub("w", 1)}${mo(",")}${sub("w", 2)}${mo(")")}${mo("=")}<mtext>first singular pair of</mtext>${gap(0.3)}${supT(sub("X", 1))}${sub("X", 2)}</mrow></math>`,
    plain: "(w₁, w₂) = first singular pair of X₁ᵀX₂",
    note: "One block's largest-variance direction is the first singular vector of that block alone; PLS's pair is that of X₁ᵀX₂, the covariances between the blocks' features, summed over the samples they share.",
  },
  stack: {
    math: `<math display="block"><mrow>${mi("X")}${mo("=")}<mrow>${mo("[")}<mtable><mtr><mtd>${sub("X", 1)}</mtd></mtr><mtr><mtd>${sub("X", 2)}</mtd></mtr></mtable>${mo("]")}</mrow>${mo(",")}${gap(1)}${mi("w")}${mo("∝")}${supT(mi("X"))}${mi("y")}${mo(",")}${gap(0.6)}${mi("t")}${mo("=")}${mi("X")}${mi("w")}</mrow></math>`,
    plain: "X = [X₁; X₂],   w ∝ Xᵀy,   t = X w",
    note: "The studies share their features (P), so the tables stack and one w serves both; y is the response, here the subtype.",
  },
};
let mathHost = null, mathKey = null;
function renderFormula(key) {
  if (!mathHost) {
    const figure = document.querySelector("#widget .w-figure");
    if (!figure || !figure.parentNode) return;
    mathHost = document.createElement("div");
    mathHost.className = "w-math";
    figure.parentNode.insertBefore(mathHost, figure);
  }
  if (mathKey === key) return;
  mathKey = key;
  const F = MATH[key];
  mathHost.innerHTML = `<div class="w-math-eq"><span style="color:var(--ink-2)">${MATHML ? F.math : F.plain}</span></div><div class="w-math-note">${F.note}</div>`;
}

/* ------------------------------------------------------------- helpers */

const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
const seg = (t, a, b) => clamp((t - a) / (b - a), 0, 1);
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - ((-2 * t + 2) ** 3) / 2);
const lerp = (a, b, t) => a + (b - a) * t;
const lerpPt = (a, b, t) => [lerp(a[0], b[0], t), lerp(a[1], b[1], t)];
const mean = (v) => v.reduce((s, x) => s + x, 0) / v.length;
function corr(a, b) {
  const ma = mean(a), mb = mean(b);
  let sab = 0, saa = 0, sbb = 0;
  for (let i = 0; i < a.length; i++) { sab += (a[i] - ma) * (b[i] - mb); saa += (a[i] - ma) ** 2; sbb += (b[i] - mb) ** 2; }
  return sab / Math.sqrt(saa * sbb);
}
const f2 = (v) => v.toFixed(2);
/** a factor in a product: negatives in brackets, so "× (−0.39)" reads as one term */
const fx = (v) => (v < 0 ? `(${f2(v)})` : f2(v));
const pair2 = (v) => `${f2(v[0])}, ${f2(v[1])}`;
const pct = (v) => `${(100 * v).toFixed(1)}%`;

function txt(ctx, colors, s, x, y, { size = colors.fsSm, fill = colors.ink2, align = "left", baseline = "alphabetic", weight = "" } = {}) {
  ctx.save(); ctx.font = `${weight ? weight + " " : ""}${size} ${colors.font}`; ctx.fillStyle = fill;
  ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
function line(ctx, x1, y1, x2, y2, col, w = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = w; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.restore();
}
function dot(ctx, colors, x, y, r, fill, edge = true) {
  ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.fillStyle = fill; ctx.fill();
  if (edge) { ctx.lineWidth = 1; ctx.strokeStyle = colors.surface; ctx.stroke(); }
}
function square(ctx, colors, x, y, r, fill) {
  ctx.fillStyle = fill; ctx.fillRect(x - r, y - r, 2 * r, 2 * r);
  ctx.lineWidth = 1; ctx.strokeStyle = colors.surface; ctx.strokeRect(x - r, y - r, 2 * r, 2 * r);
}
function hollow(ctx, x, y, r, col) {
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.lineWidth = 1.2; ctx.strokeStyle = col; ctx.stroke(); ctx.restore();
}
function ring(ctx, x, y, r, col) {
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.lineWidth = 2; ctx.strokeStyle = col; ctx.stroke(); ctx.restore();
}
function frame(ctx, colors, x, y, w, h, col = colors.axis, lw = 1) {
  ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = lw; ctx.strokeRect(x + 0.5, y + 0.5, w - 1, h - 1); ctx.restore();
}
function arrowHead(ctx, x0, y0, x1, y1, col, head) {
  const a = Math.atan2(y1 - y0, x1 - x0);
  ctx.save(); ctx.fillStyle = col; ctx.beginPath(); ctx.moveTo(x1, y1);
  ctx.lineTo(x1 - head * Math.cos(a - 0.42), y1 - head * Math.sin(a - 0.42));
  ctx.lineTo(x1 - head * Math.cos(a + 0.42), y1 - head * Math.sin(a + 0.42));
  ctx.closePath(); ctx.fill(); ctx.restore();
}
/** a component's direction has no sign: drawn double-headed, as pca's are */
function axisArrow(ctx, p0, p1, col, lw = 2.2) {
  line(ctx, p0[0], p0[1], p1[0], p1[1], col, lw);
  arrowHead(ctx, p0[0], p0[1], p1[0], p1[1], col, 7); arrowHead(ctx, p1[0], p1[1], p0[0], p0[1], col, 7);
}
/** the benchmark: a direction drawn dashed in --c-reference, no heads */
const REF_DASH = [6, 5];
function refLine(ctx, colors, p0, p1) { line(ctx, p0[0], p0[1], p1[0], p1[1], colors.reference, 2, REF_DASH); }
function vText(ctx, colors, s, x, y, opts) {
  ctx.save(); ctx.translate(x, y); ctx.rotate(-Math.PI / 2); txt(ctx, colors, s, 0, 0, { align: "center", ...opts }); ctx.restore();
}
function hoverLabel(ctx, colors, str, x, y, w) {
  ctx.save(); ctx.font = `600 ${colors.fsXs} ${colors.font}`;
  const tw = ctx.measureText(str).width; ctx.restore();
  const bx = Math.max(4, Math.min(w - tw - 14, x + 10)), by = Math.max(4, y - 26);
  ctx.save(); ctx.fillStyle = colors.surface; ctx.fillRect(bx, by, tw + 10, 18);
  ctx.strokeStyle = colors.ink3; ctx.strokeRect(bx + 0.5, by + 0.5, tw + 9, 17); ctx.restore();
  txt(ctx, colors, str, bx + 5, by + 9.5, { size: colors.fsXs, fill: colors.ink1, baseline: "middle", weight: "600" });
}
const subColour = (colors, g) => colors.clusters[g];
/** words laid into lines no wider than `maxW`, `lh` apart; returns the line count */
function wrapText(ctx, colors, str, x, y, maxW, lh, opts = {}) {
  ctx.save(); ctx.font = `${opts.weight ? opts.weight + " " : ""}${opts.size ?? colors.fsSm} ${colors.font}`;
  const lines = []; let cur = "";
  for (const word of str.split(" ")) {
    const tryLine = cur ? `${cur} ${word}` : word;
    if (ctx.measureText(tryLine).width > maxW && cur) { lines.push(cur); cur = word; } else cur = tryLine;
  }
  if (cur) lines.push(cur);
  ctx.restore();
  lines.forEach((l, i) => txt(ctx, colors, l, x, y + i * lh, { fill: colors.ink2, ...opts }));
  return lines.length;
}
/* the value ramp, --c-value-low through --surface-3 to --c-value-high. A
   panel drawn in it colours nothing by identity: subtypes are ink brackets */
const hex = (c) => { const m = String(c).trim().match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : null; };
function valueColour(colors, v) {
  const t = clamp(v, -1, 1), a = hex(colors.surface3), b = hex(t < 0 ? colors.valueLow : colors.valueHigh);
  if (!a || !b) return t < 0 ? colors.valueLow : colors.valueHigh;
  return `rgb(${a.map((x, i) => Math.round(x + (b[i] - x) * Math.abs(t))).join(",")})`;
}
/** ink brackets naming row groups beside a matrix (a value-coloured panel colours nothing by identity) */
function bracket(ctx, colors, x, y0, y1, label) {
  line(ctx, x, y0 + 2, x, y1 - 2, colors.ink2, 1.5);
  vText(ctx, colors, label, x - 6, (y0 + y1) / 2, { size: colors.fsXs, fill: colors.ink2 });
}

/** PLS beside the benchmark: PLS framed in --c-highlight, the benchmark in
   ink-3 under a dashed key. rows: [label, PLS, benchmark] */
function drawTrade(ctx, colors, x, y, width, rows) {
  const cw = 56, rh = 19, lw = Math.max(0, width - 2 * cw);
  const cP = x + lw + cw / 2, cR = x + lw + cw * 1.5;
  txt(ctx, colors, S.colPls, cP, y, { align: "center", fill: colors.ink1, weight: "600" });
  txt(ctx, colors, S.colRef[0], cR, y - 12, { align: "center", size: colors.fsXs, fill: colors.ink3 });
  txt(ctx, colors, S.colRef[1], cR, y, { align: "center", size: colors.fsXs, fill: colors.ink3 });
  line(ctx, cR - 16, y + 6, cR + 16, y + 6, colors.reference, 2, REF_DASH);
  rows.forEach((r, i) => {
    const yy = y + (i + 1) * rh + 4;
    txt(ctx, colors, r[0], x, yy, { size: colors.fsXs, fill: colors.ink2 });
    txt(ctx, colors, r[1], cP, yy, { align: "center", fill: colors.ink1 });
    txt(ctx, colors, r[2], cR, yy, { align: "center", fill: colors.ink3 });
  });
  ctx.save(); ctx.strokeStyle = colors.highlight; ctx.lineWidth = 2;
  ctx.strokeRect(cP - cw / 2 + 3.5, y - 16, cw - 6, rows.length * rh + 26); ctx.restore();
}

/* ========================================================= the simulations */

/* Two blocks on the same samples. In each, the shared axis carries the
   subtype difference (±0.85 plus noise) and is the SMALLER spread; a private
   axis, unrelated to the other block, is the larger (sd 1.6). The
   largest-variance directions keep ~75% of each block and their scores
   correlate ~0.1; PLS's ~30% and ~0.9. The angles keep the four axes apart. */
const ANG = { a: [62, -28], b: [18, 108] };
const unitAt = (deg) => [Math.cos((deg * Math.PI) / 180), Math.sin((deg * Math.PI) / 180)];
const unit2 = (v) => { const n = Math.hypot(v[0], v[1]); return [v[0] / n, v[1] / n]; };
const rot = (v, deg) => { const c = Math.cos((deg * Math.PI) / 180), s = Math.sin((deg * Math.PI) / 180); return [c * v[0] - s * v[1], s * v[0] + c * v[1]]; };
const angleBetween = (a, b) => Math.acos(clamp(Math.abs(a[0] * b[0] + a[1] * b[1]), 0, 1)) * 180 / Math.PI;
function topEig2(a, b, d) {
  const tr = a + d, det = a * d - b * b, l = tr / 2 + Math.sqrt(Math.max(0, (tr * tr) / 4 - det));
  const v = Math.abs(b) > 1e-12 ? [l - d, b] : a >= d ? [1, 0] : [0, 1];
  return unit2(v);
}
const project = (X, d) => X.map((p) => p[0] * d[0] + p[1] * d[1]);
const flip = (d) => [-d[0], -d[1]];
const centre = (X) => { const m = [0, 1].map((j) => mean(X.map((p) => p[j]))); return X.map((p) => [p[0] - m[0], p[1] - m[1]]); };
const crossOf = (X, Z) => { const M = [[0, 0], [0, 0]]; X.forEach((x, i) => { for (let r = 0; r < 2; r++) for (let c = 0; c < 2; c++) M[r][c] += x[r] * Z[i][c]; }); return M; };
const largestVar = (X) => { const C = crossOf(X, X); return topEig2(C[0][0], C[0][1], C[1][1]); };
/** each feature's covariance with a score vector: Xᵀs / n */
const covWith = (X, s) => [0, 1].map((j) => X.reduce((acc, p, i) => acc + p[j] * s[i], 0) / X.length);
/** the share of X's variance along w: what t wᵀ rebuilds, ‖t‖² / ‖X‖² (round 4, the notebook's single W) */
const keptBy = (X, t) => t.reduce((s, v) => s + v * v, 0) / X.reduce((s, p) => s + p[0] ** 2 + p[1] ** 2, 0);

function makeBlocks(rng) {
  const ua = unitAt(ANG.a[0]), va = unitAt(ANG.a[1]), ub = unitAt(ANG.b[0]), vb = unitAt(ANG.b[1]);
  const g = [], A0 = [], B0 = [];
  for (let i = 0; i < N_CONCEPT; i++) {
    const grp = i % 2;
    const s = (grp ? 0.85 : -0.85) + 0.35 * rng.normal();
    const a = 1.6 * rng.normal(), b = 1.6 * rng.normal();
    g.push(grp);
    A0.push([0, 1].map((j) => s * ua[j] + a * va[j] + 0.2 * rng.normal()));
    B0.push([0, 1].map((j) => s * ub[j] + b * vb[j] + 0.2 * rng.normal()));
  }
  const A = centre(A0), B = centre(B0);

  /* PLS: mixOmics' loop, run to its end from a start 80° off the answer.
     Signs: subtype 2 scores positive on mRNA, and the loop's start chosen so
     its end agrees, so every frame keeps one orientation. */
  const loop = (start) => {
    let w2 = start, u = project(B, w2);
    const frames = [{}, { w2, u }];
    for (let r = 0; r < 40; r++) {
      const c1 = covWith(A, u), w1 = unit2(c1), t = project(A, w1);
      const prev2 = w2;
      const c2 = covWith(B, t); w2 = unit2(c2); u = project(B, w2);
      const prev1 = frames.at(-1).w1;
      if (r < MAX_ROUNDS) {
        frames.push({ w1, t, w2: prev2, u: project(B, prev2), cov: { block: "a", v: c1 } });
        frames.push({ w1, t, w2, u, cov: { block: "b", v: c2 } });
      }
      if (prev1 && angleBetween(prev1, w1) < 0.5 && angleBetween(prev2, w2) < 0.5) break;
    }
    /* trim rounds after the arrows stopped: the press that changes nothing is the reader's to see once */
    let end = frames.length - 1;
    while (end > 4 && angleBetween(frames[end].w1, frames[end - 2].w1) < 0.5 && angleBetween(frames[end].w2, frames[end - 2].w2) < 0.5) end -= 2;
    return frames.slice(0, end + 1);
  };
  let frames = loop([0, 1]);
  let start = unit2(rot(frames.at(-1).w2, 80));
  frames = loop(start);
  if (mean(frames.at(-1).t.filter((_, i) => g[i])) < 0) { start = flip(start); frames = loop(start); }
  const loopEnd = frames.length - 1;
  /* the button names the presses this loop has, then the factorization's */
  for (let n = loopEnd; n < SLOTS; n++) {
    N_LABELS[n] = AFTER[Math.min(n - loopEnd, 2)];
    N_TITLES[n] = AFTER_TITLE[Math.min(n - loopEnd, 2)];
  }
  const fin = frames.at(-1);
  const finish = (f) => {
    if (f.w1) f.keptA = keptBy(A, f.t);
    if (f.w2) f.keptB = keptBy(B, f.u);
    if (f.t && f.u) { f.r = corr(f.t, f.u); f.cv = f.t.reduce((acc, v, i) => acc + v * f.u[i], 0) / f.t.length; }
    return f;
  };
  frames = frames.map(finish);

  /* the benchmark, and Factorization's component 1: each block's direction
     of largest variance, turned to agree with PLS's so the dashed and solid
     lines are read side by side */
  let ra = largestVar(A), rb = largestVar(B);
  if (ra[0] * fin.w1[0] + ra[1] * fin.w1[1] < 0) ra = flip(ra);
  if (corr(project(A, ra), project(B, rb)) < 0) rb = flip(rb);
  const ref = finish({ w1: ra, t: project(A, ra), w2: rb, u: project(B, rb) });

  /* Factorization: mRNA alone, components 1 and 2 (w₂ at right angles, found in E) */
  const fw2 = [-ra[1], ra[0]];
  const fac = { w: [ra, fw2], t: [project(A, ra), project(A, fw2)] };
  fac.kept1 = keptBy(A, fac.t[0]);

  /* the Shortcut: X₁ᵀX₂ / n and its first singular pair, by the same
     alternation on the 2 × 2 table itself; it lands on the loop's end */
  const M = crossOf(A, B).map((r) => r.map((v) => v / N_CONCEPT));
  let s1 = [1, 0], s2 = [0, 1];
  for (let k = 0; k < 200; k++) {
    s1 = unit2([M[0][0] * s2[0] + M[0][1] * s2[1], M[1][0] * s2[0] + M[1][1] * s2[1]]);
    s2 = unit2([M[0][0] * s1[0] + M[1][0] * s1[1], M[0][1] * s1[0] + M[1][1] * s1[1]]);
  }
  if (s1[0] * fin.w1[0] + s1[1] * fin.w1[1] < 0) { s1 = flip(s1); s2 = flip(s2); }

  const span = 1.08 * Math.max(...A.flat().map(Math.abs), ...B.flat().map(Math.abs));
  const sspan = 1.08 * Math.max(...frames.filter((f) => f.t || f.u).flatMap((f) => [...(f.t ?? []), ...(f.u ?? [])]).map(Math.abs));
  const order = [...A.keys()].sort((i, j) => g[i] - g[j] || i - j);
  return { g, A, B, loop: frames, loopEnd, ref, fac, cross: { M, w1: s1, w2: s2 }, span, sspan, order };
}

/* P-integration: two studies, 40 samples each, the same two genes, an even
   subtype mix in each (an uneven one confounds study with subtype, measured
   in round 4's mock, and is not this page's subject). Study 2 reads higher
   on both genes. The stacked table is centred as one, as 01 cell 2 stacks
   it; w ∝ Xᵀy with y the subtype, centred. */
function makeStudies(rng) {
  const d = unitAt(-35), sh = unitAt(60), X0 = [], study = [], g = [];
  for (let st = 0; st < 2; st++) for (let i = 0; i < N_STUDY; i++) {
    const grp = i % 2, s = grp ? 0.8 : -0.8;
    X0.push([0, 1].map((j) => s * d[j] + 0.55 * rng.normal() + (st ? 0.9 * sh[j] : 0)));
    study.push(st); g.push(grp);
  }
  const X = centre(X0), y = g.map((v) => v - 0.5);
  const c = covWith(X, y), w = unit2(c), t = project(X, w);
  /* rows: each study's in subtype order, study 1's first */
  const order = [...X.keys()].sort((i, j) => study[i] - study[j] || g[i] - g[j] || i - j);
  const span = 1.1 * Math.max(...X.flat().map(Math.abs));
  return { X, study, g, c, w, t, order, span, rSub: corr(t, g) };
}

/* ======================================================= shared drawing */

const toPxOf = (P, span) => (x, y) => [P.x + P.s / 2 + (x / span) * (P.s / 2), P.y + P.s / 2 - (y / span) * (P.s / 2)];
/** a matrix column (or columns) of values, rows in `order`, coloured by value */
function cols(ctx, colors, x, y, rh, cw, order, valueOf, ncol, scale) {
  order.forEach((i, r) => { for (let j = 0; j < ncol; j++) { ctx.fillStyle = valueColour(colors, valueOf(i, j) / scale); ctx.fillRect(x + j * cw, y + r * rh, cw, rh + 0.2); } });
  frame(ctx, colors, x, y, ncol * cw, order.length * rh);
}
function panelFrame(ctx, colors, P, name, ax) {
  txt(ctx, colors, name, P.x, P.y - 6, { fill: colors.ink1, weight: "600", size: colors.fsXs });
  frame(ctx, colors, P.x, P.y, P.s, P.s);
  txt(ctx, colors, ax[0], P.x + P.s / 2, P.y + P.s + 12, { size: colors.fsXs, fill: colors.ink3, align: "center" });
  vText(ctx, colors, ax[1], P.x - 7, P.y + P.s / 2, { size: colors.fsXs, fill: colors.ink3 });
}

/* ==================================================== FACTORIZATION page */

/* One block, its scatter on the left and its matrices to the right in the
   notebook's shapes, the traced sample's arithmetic underneath. */
const FL = { cap: 64, s: 200, rh: 2.5, cw: 15 };
const H_FACTOR = FL.cap + 14 + FL.s + 128;
function factorLayout(w) {
  const s = Math.min(FL.s, Math.floor(w * 0.38));
  const P = { x: 30, y: FL.cap + 14, s };
  const mx = P.x + s + 34, my = P.y + 20, cw = FL.cw;
  const m = { X: mx, T: mx + 2 * cw + 22, W: mx + 4 * cw + 34, E: mx + 6 * cw + 56 };
  return { P, my, m, cw, rh: FL.rh, text: { x: 30, y: P.y + s + 34 } };
}

function drawFactorization(ctx, colors, w, params, st, anim, pointer) {
  const L = factorLayout(w), n = Math.min(anim.n.factorization ?? 0, 4), p = inFlight(anim, "factorization");
  const F = st.fac, X = st.A, pick = tracedOf(params), px = toPxOf(L.P, st.span), R = 0.92 * st.span;
  wrapText(ctx, colors, S.fCap[n], 10, 14, w - 20, 16, { fill: colors.ink1 });
  /* Component 2 (round 5, his "it just draws the orthogonal arrow?"): the
     samples first move to their rows of E, their gaps from arrow 1, drawn
     from the centre (0–0.55); with 2 features E lies on one line, so w₂ is
     drawn along it once they land. With P features it would be E's
     direction of largest variance among P − 1; here it has no choice. */
  const comp2 = n >= 4, mv = comp2 ? (p != null && n === 4 ? ease(seg(p, 0, 0.55)) : 1) : 0;
  const w2On = comp2 && (p == null || n !== 4 || p >= 0.55);
  panelFrame(ctx, colors, L.P, comp2 && mv >= 1 ? S.blockE : S.blockA, S.featA);
  const scored = n >= 1, drop = p != null && n === 1 ? ease(seg(p, 0.1, 0.8)) : 1;
  if (scored) axisArrow(ctx, px(-R * F.w[0][0], -R * F.w[0][1]), px(R * F.w[0][0], R * F.w[0][1]), colors.highlight);
  if (w2On) axisArrow(ctx, px(-R * F.w[1][0], -R * F.w[1][1]), px(R * F.w[1][0], R * F.w[1][1]), colors.ink2, 1.6);
  const posOf = (i) => {
    const q = X[i];
    if (!comp2) return q;
    const t = F.t[0][i], e = [q[0] - t * F.w[0][0], q[1] - t * F.w[0][1]];
    return [lerp(q[0], e[0], mv), lerp(q[1], e[1], mv)];
  };
  X.forEach((q, i) => {
    const [x, y] = px(...posOf(i));
    if (scored && !comp2) {
      const t = F.t[0][i], ft = px(t * F.w[0][0], t * F.w[0][1]), fp = [lerp(x, ft[0], drop), lerp(y, ft[1], drop)];
      if (drop < 1) line(ctx, x, y, fp[0], fp[1], colors.ink3, 1);
      /* Subtract: E as the gap from each foot to its dot */
      if (n >= 3) line(ctx, ft[0], ft[1], x, y, colors.ink3, 1);
      if (n >= 2) hollow(ctx, fp[0], fp[1], 2.4, colors.ink2); else dot(ctx, colors, fp[0], fp[1], 2.2, subColour(colors, st.g[i]), false);
    }
    dot(ctx, colors, x, y, 3.6, subColour(colors, st.g[i]));
  });
  const pq = px(...posOf(pick)); ring(ctx, pq[0], pq[1], 6.5, colors.ink1);
  if (scored && !comp2 && p == null) { const t = F.t[0][pick], ft = px(t * F.w[0][0], t * F.w[0][1]); line(ctx, pq[0], pq[1], ft[0], ft[1], colors.ink1, 1, [2, 2]); ring(ctx, ft[0], ft[1], 4.5, colors.ink1); }

  /* the matrices, in the notebook's shapes */
  const { my, m, cw, rh } = L, H = N_CONCEPT * rh, xm = Math.max(...X.flat().map(Math.abs)), tm = Math.max(...F.t[0].map(Math.abs));
  const head = (x, wdt, name, shape) => { txt(ctx, colors, name, x + wdt / 2, my - 18, { align: "center", fill: colors.ink1, weight: "600", size: colors.fsXs }); txt(ctx, colors, shape, x + wdt / 2, my - 6, { align: "center", fill: colors.ink3, size: colors.fsXs }); };
  cols(ctx, colors, m.X, my, rh, cw, st.order, (i, j) => X[i][j], 2, xm); head(m.X, 2 * cw, "X", S.shapes[0]);
  const Lc = n >= 4 ? 2 : 1;
  if (scored) {
    cols(ctx, colors, m.T, my, rh, cw, st.order, (i, j) => F.t[j][i], Lc, tm); head(m.T, Lc * cw, "T", S.shapes[1]);
    for (let l = 0; l < Lc; l++) for (let j = 0; j < 2; j++) { ctx.fillStyle = valueColour(colors, F.w[l][j]); ctx.fillRect(m.W + j * cw, my + l * cw, cw - 1, cw - 1); }
    frame(ctx, colors, m.W, my, 2 * cw, Lc * cw); head(m.W, 2 * cw, "Wᵀ", S.shapes[2]);
  }
  if (n >= 2) txt(ctx, colors, "≈", m.X + 2 * cw + 11, my + H / 2 + 5, { align: "center", fill: colors.ink1, size: colors.fsMd });
  if (n >= 3) {
    txt(ctx, colors, "+", m.E - 11, my + H / 2 + 5, { align: "center", fill: colors.ink1, size: colors.fsMd });
    const rest = (i, j) => X[i][j] - F.t[0][i] * F.w[0][j] - (n >= 4 ? F.t[1][i] * F.w[1][j] : 0);
    cols(ctx, colors, m.E, my, rh, cw, st.order, rest, 2, xm); head(m.E, 2 * cw, "E", n >= 4 ? "= 0" : S.shapes[0]);
  }
  [0, 1].forEach((g) => { const ra = st.order.findIndex((i) => st.g[i] === g); bracket(ctx, colors, m.X - 5, my + ra * rh, my + (ra + N_CONCEPT / 2) * rh, S.sub[g]); });
  const r = st.order.indexOf(pick), right = n >= 3 ? m.E + 2 * cw : scored ? m.T + Lc * cw : m.X + 2 * cw;
  frame(ctx, colors, m.X - 2, my + r * rh - 2, right - m.X + 4, rh + 4, colors.ink1, 1.5);

  /* the traced sample's arithmetic */
  const x = X[pick], tx = L.text.x;
  let yy = L.text.y;
  const put = (s, fill = colors.ink2) => { txt(ctx, colors, s, tx, yy, { size: colors.fsXs, fill }); yy += 15; };
  put(S.fRow(pick + 1, f2(x[0]), f2(x[1])), colors.ink1);
  if (scored) put(S.fScore("₁", [fx(x[0]), fx(x[1])], [fx(F.w[0][0]), fx(F.w[0][1])], f2(F.t[0][pick])));
  if (n >= 2) { const t = F.t[0][pick]; put(S.fRebuilt(f2(t), pair2(F.w[0]), pair2([t * F.w[0][0], t * F.w[0][1]]))); }
  if (n === 3) { const t = F.t[0][pick]; put(S.fE(pair2([x[0] - t * F.w[0][0], x[1] - t * F.w[0][1]])), colors.ink1); }
  if (n >= 4) {
    const t1 = F.t[0][pick], e = [x[0] - t1 * F.w[0][0], x[1] - t1 * F.w[0][1]];
    put(S.fE(pair2(e)));
    put(S.fScore("₂", [fx(e[0]), fx(e[1])], [fx(F.w[1][0]), fx(F.w[1][1])], f2(F.t[1][pick])));
    put(S.fBoth(pair2([F.t[0][pick] * F.w[0][0] + F.t[1][pick] * F.w[1][0], F.t[0][pick] * F.w[0][1] + F.t[1][pick] * F.w[1][1]])), colors.ink1);
  }
  hoverSample(ctx, colors, w, pointer, pickAtFactor(L, st, pointer));
}

function pickAtFactor(L, st, pointer) {
  if (!pointer) return null;
  const px = toPxOf(L.P, st.span);
  let best = -1, bd = 64;
  st.A.forEach((q, i) => { const p = px(q[0], q[1]), d = (p[0] - pointer.x) ** 2 + (p[1] - pointer.y) ** 2; if (d < bd) { bd = d; best = i; } });
  if (best >= 0) return best;
  const { my, rh, m, cw } = L;
  if (pointer.x >= m.X && pointer.x <= m.E + 2 * cw && pointer.y >= my && pointer.y < my + N_CONCEPT * rh) return st.order[Math.floor((pointer.y - my) / rh)];
  return null;
}
function hoverSample(ctx, colors, w, pointer, hit, st) {
  if (hit == null || !pointer) return;
  hoverLabel(ctx, colors, S.hovSample(hit + 1, S.sub[hit % 2]), pointer.x, pointer.y, w);
}
const tracedOf = (params) => clamp((Number(params.sample) || TRACED) - 1, 0, N_CONCEPT - 1);

/* ==================================================== N-INTEGRATION page */

/* Layout, one function read by `draw`, `regions` and the height constant:
   a caption across the top; three squares — mRNA's scatter, the Scores
   panel, methylation's scatter; under each scatter its matrix, mRNA's
   reading left to right (X₁, t, then E) and methylation's mirrored (E, u,
   X₂), so the two score columns face each other across the middle panel
   and a row is one sample all the way across. */
const L0 = { cap: 34, padL: 30, padR: 12, gap: 24, sMax: 150, mGap: 52, rh: 2, cw: 14 };
const H_N = L0.cap + 18 + L0.sMax + L0.mGap + N_CONCEPT * L0.rh + 18;
function nLayout(w) {
  const s = Math.floor(Math.min(L0.sMax, (w - L0.padL - L0.padR - 2 * L0.gap) / 3));
  const y = L0.cap + 18, xA = L0.padL, xB = w - L0.padR - s, xS = (xA + s + xB) / 2 - s / 2;
  const my = y + s + L0.mGap, cw = L0.cw;
  const mA = { X: xA, t: xA + 2 * cw + 6, E: xA + 3 * cw + 14 };
  const mB = { X: w - L0.padR - 2 * cw, t: w - L0.padR - 3 * cw - 6, E: w - L0.padR - 5 * cw - 14 };
  const mid = { x: mA.E + 2 * cw + 14, y: my, w: mB.E - 14 - (mA.E + 2 * cw + 14) };
  return { s, y, A: { x: xA, y, s }, S: { x: xS, y, s }, B: { x: xB, y, s }, my, mA, mB, mid, rh: L0.rh, cw };
}

/** what the page shows after `k` presses: the loop's frame, and how far the factorization has gone */
const nView = (st, k) => ({ frame: st.loop[Math.min(k, st.loopEnd)], loopDone: k >= st.loopEnd, after: Math.max(0, k - st.loopEnd) });

/** pixel positions of every mark one loop frame draws */
function nMarks(Lm, st, F) {
  const pa = toPxOf(Lm.A, st.span), pb = toPxOf(Lm.B, st.span), ps = toPxOf(Lm.S, st.sspan), R = 0.92 * st.span;
  const arrowOf = (p, d) => (d ? [p(-R * d[0], -R * d[1]), p(R * d[0], R * d[1])] : null);
  const feetOf = (p, X, d) => (d ? X.map((q) => { const t = q[0] * d[0] + q[1] * d[1]; return p(t * d[0], t * d[1]); }) : null);
  return {
    arrowA: arrowOf(pa, F.w1), arrowB: arrowOf(pb, F.w2),
    feetA: feetOf(pa, st.A, F.w1), feetB: feetOf(pb, st.B, F.w2),
    scores: F.t && F.u ? F.t.map((t, k) => ps(t, F.u[k])) : null,
  };
}
/** an axis turns the short way: it has no sign, so a half-turn is no turn */
function blendAxis(a, b, t) {
  const c = lerpPt(a[0], a[1], 0.5), L = Math.hypot(b[1][0] - b[0][0], b[1][1] - b[0][1]) / 2;
  const a0 = Math.atan2(a[1][1] - a[0][1], a[1][0] - a[0][0]), a1 = Math.atan2(b[1][1] - b[0][1], b[1][0] - b[0][0]);
  let d = a1 - a0;
  while (d > Math.PI / 2) d -= Math.PI;
  while (d < -Math.PI / 2) d += Math.PI;
  const ang = a0 + d * t;
  return [[c[0] - L * Math.cos(ang), c[1] - L * Math.sin(ang)], [c[0] + L * Math.cos(ang), c[1] + L * Math.sin(ang)]];
}

/* One loop press moves the page from frame k−1 to frame k, in two moves
   that never overlap (tweens-move-in-lanes): an arrow that exists turns
   (0–0.45), then the feet slide and the scores move (0.45–1). An arrow that
   did not exist appears at once and its samples drop onto it; scores that
   did not exist appear at 0.8. The matrices, w and the middle panel switch
   at the press (tween-only-movement-no-fades). The factorization's presses
   switch at once too. */
function drawN(ctx, colors, w, params, st, anim, pointer) {
  const Lm = nLayout(w), k = Math.min(anim.n["n-integration"] ?? 0, st.loopEnd + 3), p = inFlight(anim, "n-integration");
  const V = nView(st, k), F = V.frame;
  const inLoop = p != null && k >= 1 && k <= st.loopEnd;
  const prev = inLoop ? st.loop[k - 1] : null;
  const M = nMarks(Lm, st, F), P0 = prev ? nMarks(Lm, st, prev) : null;
  const turn = inLoop ? ease(seg(p, 0, 0.45)) : 1, slide = inLoop ? ease(seg(p, 0.45, 1)) : 1;
  const pick = tracedOf(params);
  const pa = toPxOf(Lm.A, st.span), pb = toPxOf(Lm.B, st.span);

  const cap = k === 0 ? S.caption.before
    : V.after === 3 ? S.caption.shortcut : V.after === 2 ? S.caption.subtract : V.after === 1 ? S.caption.rebuild
      : V.loopDone ? S.caption.done : k === 1 ? S.caption.start : k % 2 === 0 ? S.caption.updA : S.caption.updB;
  wrapText(ctx, colors, cap, 10, 14, w - 20, 16, { fill: colors.ink1 });

  [[Lm.A, S.blockA, S.featA], [Lm.S, S.scores, [S.scoreX, S.scoreY]], [Lm.B, S.blockB, S.featB]].forEach(([P, name, ax]) => panelFrame(ctx, colors, P, name, ax));
  if (V.loopDone) {
    const R = nMarks(Lm, st, st.ref);
    refLine(ctx, colors, ...R.arrowA); refLine(ctx, colors, ...R.arrowB);
  }
  const arrowNow = (key) => (M[key] && P0 && P0[key] ? blendAxis(P0[key], M[key], turn) : M[key]);
  ["arrowA", "arrowB"].forEach((key) => { const a = arrowNow(key); if (a) axisArrow(ctx, a[0], a[1], colors.highlight); });

  const scoresNow = M.scores && P0?.scores ? M.scores.map((q, i) => lerpPt(P0.scores[i], q, slide)) : M.scores;
  const scoresOn = !!M.scores && (P0?.scores || !inLoop || p >= 0.8);
  const footAt = (key, i, x, y) => {
    let foot = M[key][i];
    if (P0 && P0[key]) return lerpPt(P0[key][i], foot, slide);
    if (inLoop) { const drop = ease(seg(p, 0.1, 0.8)); foot = [lerp(x, foot[0], drop), lerp(y, foot[1], drop)]; if (drop < 1) line(ctx, x, y, foot[0], foot[1], colors.ink3, 1); }
    return foot;
  };
  const feetDrawn = { feetA: [], feetB: [] };
  [[pa, st.A, "feetA"], [pb, st.B, "feetB"]].forEach(([px, X, key]) => {
    X.forEach((pt, i) => {
      const [x, y] = px(pt[0], pt[1]);
      if (M[key]) {
        const foot = footAt(key, i, x, y); feetDrawn[key][i] = foot;
        /* Subtract: E as the gap from each foot to its dot; Rebuild: the feet are the rebuilt points (hollow) */
        if (V.after >= 2) line(ctx, foot[0], foot[1], x, y, colors.ink3, 1);
        if (V.after >= 1) hollow(ctx, foot[0], foot[1], 2.2, colors.ink2); else dot(ctx, colors, foot[0], foot[1], 2.2, subColour(colors, st.g[i]), false);
      }
      dot(ctx, colors, x, y, 3.4, subColour(colors, st.g[i]));
    });
  });
  if (scoresOn) {
    scoresNow.forEach((q, i) => dot(ctx, colors, q[0], q[1], 3.4, subColour(colors, st.g[i])));
    const r = P0?.scores && inLoop ? lerp(prev.r, F.r, slide) : F.r, cv = P0?.scores && inLoop ? lerp(prev.cv, F.cv, slide) : F.cv;
    txt(ctx, colors, `r = ${f2(r)}`, Lm.S.x + Lm.S.s - 5, Lm.S.y + 14, { fill: colors.ink1, align: "right", weight: "600", size: colors.fsXs });
    txt(ctx, colors, `cov = ${f2(cv)}`, Lm.S.x + Lm.S.s - 5, Lm.S.y + 27, { fill: colors.ink2, align: "right", size: colors.fsXs });
  }

  /* the traced sample, ringed in every panel */
  [[pa(...st.A[pick]), "feetA"], [pb(...st.B[pick]), "feetB"]].forEach(([q, key]) => {
    ring(ctx, q[0], q[1], 6, colors.ink1);
    const ft = feetDrawn[key][pick];
    if (ft && !inLoop) { line(ctx, q[0], q[1], ft[0], ft[1], colors.ink1, 1, [2, 2]); ring(ctx, ft[0], ft[1], 4.5, colors.ink1); }
  });
  if (scoresOn && !inLoop) ring(ctx, scoresNow[pick][0], scoresNow[pick][1], 6, colors.ink1);

  drawNMatrices(ctx, colors, Lm, st, F, V, pick);
  drawNMiddle(ctx, colors, Lm, st, F, V, k, pick);
  hoverSample(ctx, colors, w, pointer, pickAtN(Lm, st, F, pointer));
}

function drawNMatrices(ctx, colors, Lm, st, F, V, pick) {
  const { my, rh, cw, mA, mB } = Lm, H = N_CONCEPT * rh;
  [{ X: st.A, m: mA, wv: F.w1, sc: F.t, sideL: true, i: 0 }, { X: st.B, m: mB, wv: F.w2, sc: F.u, sideL: false, i: 1 }].forEach((B) => {
    const xm = Math.max(...B.X.flat().map(Math.abs));
    cols(ctx, colors, B.m.X, my, rh, cw, st.order, (i, j) => B.X[i][j], 2, xm);
    txt(ctx, colors, S.mX[B.i], B.m.X + cw, my - 5, { align: "center", fill: colors.ink1, weight: "600", size: colors.fsXs });
    /* w over X: the arrow as two numbers */
    if (B.wv) txt(ctx, colors, `w = (${pair2(B.wv)})`, B.sideL ? B.m.X : B.m.X + 2 * cw, my - 20, { size: colors.fsXs, fill: colors.highlight, weight: "600", align: B.sideL ? "left" : "right" });
    if (B.sc) {
      cols(ctx, colors, B.m.t, my, rh, cw, st.order, (i) => B.sc[i], 1, Math.max(...B.sc.map(Math.abs)));
      txt(ctx, colors, S.mT[B.i], B.m.t + cw / 2, my - 5, { align: "center", fill: colors.ink1, weight: "600", size: colors.fsXs });
    }
    if (V.after >= 2) {
      cols(ctx, colors, B.m.E, my, rh, cw, st.order, (i, j) => B.X[i][j] - B.sc[i] * B.wv[j], 2, xm);
      txt(ctx, colors, S.mE, B.m.E + cw, my - 5, { align: "center", fill: colors.ink1, weight: "600", size: colors.fsXs });
    }
  });
  [0, 1].forEach((g) => { const ra = st.order.findIndex((i) => st.g[i] === g); bracket(ctx, colors, mA.X - 5, my + ra * rh, my + (ra + N_CONCEPT / 2) * rh, S.sub[g]); });
  /* the traced row, outlined in both tables: one sample all the way across */
  const r = st.order.indexOf(pick), yr = my + r * rh;
  const xa1 = V.after >= 2 ? mA.E + 2 * cw : F.t ? mA.t + cw : mA.X + 2 * cw;
  const xb0 = V.after >= 2 ? mB.E : F.u ? mB.t : mB.X;
  frame(ctx, colors, mA.X - 2, yr - 2, xa1 - mA.X + 4, rh + 4, colors.ink1, 1.5);
  frame(ctx, colors, xb0 - 2, yr - 2, mB.X + 2 * cw - xb0 + 4, rh + 4, colors.ink1, 1.5);
  /* stubs toward each other in the gaps beside the middle panel, which holds text on that line */
  line(ctx, xa1 + 3, yr + rh / 2, Lm.mid.x - 4, yr + rh / 2, colors.ink3, 1, [2, 3]);
  line(ctx, Lm.mid.x + Lm.mid.w + 4, yr + rh / 2, xb0 - 3, yr + rh / 2, colors.ink3, 1, [2, 3]);
  void H;
}

function drawNMiddle(ctx, colors, Lm, st, F, V, k, pick) {
  const { x, y, w: mw } = Lm.mid, lh = 14, xs = colors.fsXs;
  let yy = y + 8;
  const put = (s, opts = {}) => { txt(ctx, colors, s, x, yy, { size: xs, fill: colors.ink2, ...opts }); yy += lh; };
  const a = st.A[pick], b = st.B[pick];
  put(S.sampleHead(pick + 1, S.sub[st.g[pick]]), { fill: colors.ink1, weight: "600" });
  if (k === 0) { yy += 4; wrapText(ctx, colors, S.sameRows, x, yy, mw, lh, { size: xs, fill: colors.ink1 }); return; }
  if (V.after === 3) {
    /* Shortcut: the 2 × 2 table and its first singular pair */
    const { M, w1, w2 } = st.cross, m = Math.max(...M.flat().map(Math.abs)), cs = 38, x0 = x + 38;
    put(S.crossHead, { fill: colors.ink1, weight: "600" });
    ["CpG 1", "CpG 2"].forEach((nm, j) => txt(ctx, colors, nm, x0 + j * cs + cs / 2, yy, { align: "center", size: xs, fill: colors.ink3 }));
    yy += 4;
    ["gene 1", "gene 2"].forEach((nm, i) => txt(ctx, colors, nm, x0 - 4, yy + i * cs + cs / 2 + 3, { align: "right", size: xs, fill: colors.ink3 }));
    for (let i = 0; i < 2; i++) for (let j = 0; j < 2; j++) {
      ctx.fillStyle = valueColour(colors, M[i][j] / m); ctx.fillRect(x0 + j * cs, yy + i * cs, cs - 2, cs - 2);
      txt(ctx, colors, f2(M[i][j]), x0 + j * cs + cs / 2 - 1, yy + i * cs + cs / 2 + 3, { align: "center", size: xs, fill: colors.ink1 });
    }
    yy += 2 * cs + 12;
    put(`${S.pairHead}: w₁ = (${pair2(w1)})`, { fill: colors.ink1 });
    put(`w₂ = (${pair2(w2)}), ${S.sameAs}`, { fill: colors.ink1 });
    return;
  }
  /* the traced sample's scores: a row of X times w */
  if (F.w1) { put(`t = ${fx(a[0])} × ${fx(F.w1[0])} + ${fx(a[1])} × ${fx(F.w1[1])}`); put(`  = ${f2(F.t[pick])}`, { fill: colors.ink1 }); }
  else put(`mRNA: ${S.noArrow}`, { fill: colors.ink3 });
  if (F.w2) { put(`u = ${fx(b[0])} × ${fx(F.w2[0])} + ${fx(b[1])} × ${fx(F.w2[1])}`); put(`  = ${f2(F.u[pick])}`, { fill: colors.ink1 }); }
  yy += 6;
  if (V.after >= 1) {
    const ra = [F.t[pick] * F.w1[0], F.t[pick] * F.w1[1]], rb = [F.u[pick] * F.w2[0], F.u[pick] * F.w2[1]];
    put(S.rebuiltLine("mRNA", f2(F.t[pick]), pair2(ra)));
    put(S.rebuiltLine("methylation", f2(F.u[pick]), pair2(rb)));
    if (V.after >= 2) {
      put(S.eLine("mRNA", pair2([a[0] - ra[0], a[1] - ra[1]])), { fill: colors.ink1 });
      put(S.eLine("methylation", pair2([b[0] - rb[0], b[1] - rb[1]])), { fill: colors.ink1 });
    }
    return;
  }
  if (V.loopDone) {
    const R = st.ref;
    drawTrade(ctx, colors, x, yy + 12, mw, [[S.rowR, f2(F.r), f2(R.r)], [S.rowKept(S.blockA), pct(F.keptA), pct(R.keptA)], [S.rowKept(S.blockB), pct(F.keptB), pct(R.keptB)]]);
    return;
  }
  if (F.cov) {
    /* the update this press made: the weights are covariances, then scaled to length 1 */
    const v = F.cov.v, feats = F.cov.block === "a" ? S.featA : S.featB, other = F.cov.block === "a" ? "u" : "t", n = Math.hypot(v[0], v[1]);
    put(S.covHead(F.cov.block), { fill: colors.ink1, weight: "600" });
    put(S.covLine(feats[0], other, f2(v[0])));
    put(S.covLine(feats[1], other, f2(v[1])));
    put(S.scaleLine(f2(n), pair2([v[0] / n, v[1] / n])), { fill: colors.highlight });
  }
}

/** the sample under a point: a dot in either scatter or the Scores panel, or a row of either matrix */
function pickAtN(Lm, st, F, pointer) {
  if (!pointer) return null;
  const { x, y } = pointer;
  const pa = toPxOf(Lm.A, st.span), pb = toPxOf(Lm.B, st.span), ps = toPxOf(Lm.S, st.sspan);
  let best = -1, bd = 64;
  const tryPt = (q, i) => { const d = (q[0] - x) ** 2 + (q[1] - y) ** 2; if (d < bd) { bd = d; best = i; } };
  st.A.forEach((q, i) => tryPt(pa(q[0], q[1]), i));
  st.B.forEach((q, i) => tryPt(pb(q[0], q[1]), i));
  if (F.t && F.u) F.t.forEach((t, i) => tryPt(ps(t, F.u[i]), i));
  if (best >= 0) return best;
  const { my, rh, mA, mB, cw } = Lm;
  const inA = x >= mA.X && x <= mA.X + 5 * cw + 14, inB = x >= mB.E && x <= mB.X + 2 * cw;
  if ((inA || inB) && y >= my && y < my + N_CONCEPT * rh) return st.order[Math.floor((y - my) / rh)];
  return null;
}

/* ==================================================== P-INTEGRATION page */

/* The stacked scatter on the left (subtype by colour, study by the marker's
   shape: a circle or a square, so colour carries one grouping); on the
   right the two studies' tables, side by side until Stack moves study 2's
   under study 1's, then the shared w and the score column. */
const PL = { cap: 50, s: 200, rh: 2.5, cw: 15 };
const H_P = PL.cap + 14 + PL.s + 104;
function pLayout(w) {
  const s = Math.min(PL.s, Math.floor(w * 0.38));
  const P = { x: 30, y: PL.cap + 14, s };
  const mx = P.x + s + 54, my = P.y + 20, cw = PL.cw, rh = PL.rh;
  return { P, mx, my, cw, rh, tCol: mx + 2 * cw + 52, text: { x: 30, y: P.y + s + 48 } };
}

function drawP(ctx, colors, w, params, pt, anim, pointer) {
  const L = pLayout(w), n = Math.min(anim.n["p-integration"] ?? 0, 3), p = inFlight(anim, "p-integration");
  const px = toPxOf(L.P, pt.span), R = 0.92 * pt.span;
  wrapText(ctx, colors, S.pCap[n], 10, 14, w - 20, 16, { fill: colors.ink1 });
  panelFrame(ctx, colors, L.P, `${S.study[0]} and ${S.study[1]}`, S.featA);
  if (n >= 2) axisArrow(ctx, px(-R * pt.w[0], -R * pt.w[1]), px(R * pt.w[0], R * pt.w[1]), colors.highlight);
  pt.X.forEach((q, i) => {
    const [x, y] = px(q[0], q[1]);
    if (n >= 3) { const t = pt.t[i], ft = px(t * pt.w[0], t * pt.w[1]); dot(ctx, colors, ft[0], ft[1], 2, subColour(colors, pt.g[i]), false); }
    (pt.study[i] ? (cx, cy, r, f) => square(ctx, colors, cx, cy, r * 0.85, f) : (cx, cy, r, f) => dot(ctx, colors, cx, cy, r, f))(x, y, 3.6, subColour(colors, pt.g[i]));
  });
  txt(ctx, colors, S.studyKey, L.P.x, L.P.y + L.P.s + 28, { size: colors.fsXs, fill: colors.ink2 });

  /* the two tables: study 2's beside study 1's, then moved under it by Stack */
  const { mx, my, cw, rh } = L, hS = N_STUDY * rh, xm = Math.max(...pt.X.flat().map(Math.abs));
  const stack = n >= 1 ? (p != null && n === 1 ? ease(p) : 1) : 0;
  const o1 = pt.order.slice(0, N_STUDY), o2 = pt.order.slice(N_STUDY);
  const x2 = lerp(mx + 2 * cw + 30, mx, stack), y2 = lerp(my, my + hS, stack);
  cols(ctx, colors, mx, my, rh, cw, o1, (i, j) => pt.X[i][j], 2, xm);
  cols(ctx, colors, x2, y2, rh, cw, o2, (i, j) => pt.X[i][j], 2, xm);
  txt(ctx, colors, n >= 1 ? "X = [X₁; X₂]" : "X₁", mx, my - 8, { size: colors.fsXs, fill: colors.ink1, weight: "600" });
  if (n < 1) txt(ctx, colors, "X₂", x2, y2 - 8, { size: colors.fsXs, fill: colors.ink1, weight: "600" });
  bracket(ctx, colors, mx - 5, my, my + hS, S.study[0]);
  bracket(ctx, colors, x2 - 5, y2, y2 + hS, S.study[1]);
  if (n >= 2) txt(ctx, colors, `w = (${pair2(pt.w)})`, mx, my - 22, { size: colors.fsXs, fill: colors.highlight, weight: "600" });
  if (n >= 3) {
    cols(ctx, colors, L.tCol, my, rh, cw, pt.order, (i) => pt.t[i], 1, Math.max(...pt.t.map(Math.abs)));
    txt(ctx, colors, "t", L.tCol + cw / 2, my - 8, { align: "center", size: colors.fsXs, fill: colors.ink1, weight: "600" });
  }

  /* the arithmetic: the shared w, from each gene's covariance with the subtype */
  let yy = L.text.y;
  const put = (s, fill = colors.ink2) => { txt(ctx, colors, s, L.text.x, yy, { size: colors.fsXs, fill }); yy += 15; };
  if (n >= 2) {
    const nn = Math.hypot(pt.c[0], pt.c[1]);
    put(S.pCov("gene 1", f2(pt.c[0]))); put(S.pCov("gene 2", f2(pt.c[1])));
    put(S.pW(f2(nn), pair2(pt.w)), colors.highlight);
  }
  if (pointer) {
    let best = -1, bd = 64;
    pt.X.forEach((q, i) => { const [x, y] = px(q[0], q[1]), d = (x - pointer.x) ** 2 + (y - pointer.y) ** 2; if (d < bd) { bd = d; best = i; } });
    if (best >= 0) hoverLabel(ctx, colors, S.hovStudy(S.study[pt.study[best]], S.sub[pt.g[best]]), pointer.x, pointer.y, w);
  }
}

/* =========================================================== TCGA UCEC page */

const pairOf = (key) => PAIRS.find((p) => `${p.a}-${p.b}`.toLowerCase() === key);
/** one pair's PLS reading, and its benchmark: each block's PC1, the largest-variance direction */
const DATA_VIEW = {};
function dataView(pairKey) {
  if (DATA_VIEW[pairKey]) return DATA_VIEW[pairKey];
  const P = pairOf(pairKey);
  const xs = 1.08 * Math.max(...P.t.map(Math.abs)), ys = 1.08 * Math.max(...P.u.map(Math.abs));
  DATA_VIEW[pairKey] = {
    P, t: P.t, u: P.u, keptA: P.keptA, keptB: P.keptB, wA: P.wA, wB: P.wB, topA: P.topA, topB: P.topB, r: corr(P.t, P.u), xs, ys,
    ref: { r: Math.abs(corr(BLOCKS[P.a].pc1, BLOCKS[P.b].pc1)), keptA: BLOCKS[P.a].kept, keptB: BLOCKS[P.b].kept },
  };
  return DATA_VIEW[pairKey];
}

const D = { top: 34, x0: 66, sMax: 260, strip: 22, gapStrip: 8 };
function dataLayout(w) {
  const s = Math.min(D.sMax, Math.floor(w - D.x0 - 240));
  return { s, x: D.x0, y: D.top, side: D.x0 + s + 34 };
}
const H_DATA = D.top + D.sMax + D.gapStrip + D.strip + 40;

function dataMarks(L, V) {
  const sx = (v) => L.x + L.s / 2 + (v / V.xs) * (L.s / 2), sy = (v) => L.y + L.s / 2 - (v / V.ys) * (L.s / 2);
  const stripY = L.y + L.s + D.gapStrip + D.strip / 2, stripX = L.x - D.gapStrip - D.strip / 2;
  return {
    pts: V.t.map((t, k) => [sx(t), sy(V.u[k])]),
    bottom: V.t.map((t) => [sx(t), stripY]),
    left: V.u.map((u) => [stripX, sy(u)]),
  };
}

/** a block's weights as one row of cells, thousands wide, and its largest named */
function drawWeights(ctx, colors, x, y, width, b, wv, top) {
  txt(ctx, colors, S.weights(b), x, y, { size: colors.fsXs, fill: colors.ink1, weight: "600" });
  /* scaled by three standard deviations, not the largest: a few large weights would leave the row grey */
  const m = 3 * Math.sqrt(wv.reduce((s, v) => s + v * v, 0) / wv.length) || 1, cw = width / wv.length;
  for (let j = 0; j < wv.length; j++) { ctx.fillStyle = valueColour(colors, wv[j] / m); ctx.fillRect(x + j * cw, y + 6, Math.max(cw, 0.6), 10); }
  frame(ctx, colors, x, y + 6, width, 10);
  top.name.slice(0, 3).forEach((nm, i) => txt(ctx, colors, `${nm}  ${top.value[i] > 0 ? "+" : ""}${top.value[i].toFixed(3)}`, x, y + 30 + i * 13, { size: colors.fsXs, fill: colors.ink2 }));
}

function drawData(ctx, colors, w, params, anim, pointer) {
  const L = dataLayout(w), V = dataView(params.pair), P = V.P;
  const beat = shownStep(anim, "data"), t = inFlight(anim, "data");
  const found = beat >= 1 || t != null;
  const rise = t != null ? ease(seg(t, 0.15, 1)) : 1;
  const ez = ezOf(anim, "data");
  const to = dataMarks(L, V);
  const from = ez ? dataMarks(L, dataView(ez.params.pair)) : null;
  const e = ez ? ease(ez.t) : 1;
  const at = (key, i) => (from ? lerpPt(from[key][i], to[key][i], e) : to[key][i]);

  txt(ctx, colors, S.dims(P.a), L.x - D.gapStrip - D.strip, 14, { fill: colors.ink2 });
  txt(ctx, colors, S.dims(P.b), L.x - D.gapStrip - D.strip, 28, { fill: colors.ink2 });

  frame(ctx, colors, L.x, L.y + 4, L.s, L.s - 4);
  frame(ctx, colors, L.x, L.y + L.s + D.gapStrip, L.s, D.strip);
  frame(ctx, colors, L.x - D.gapStrip - D.strip, L.y + 4, D.strip, L.s - 4);
  txt(ctx, colors, S.strip(P.a), L.x + L.s / 2, L.y + L.s + D.gapStrip + D.strip + 15, { size: colors.fsXs, fill: colors.ink3, align: "center" });
  vText(ctx, colors, S.strip(P.b), L.x - D.gapStrip - D.strip - 8, L.y + L.s / 2, { size: colors.fsXs, fill: colors.ink3 });

  if (!found) {
    txt(ctx, colors, S.dataBefore, L.x + L.s / 2, L.y + L.s / 2, { fill: colors.ink3, align: "center", baseline: "middle" });
  } else {
    /* the strips appear at once with the press; the samples rise out of the
       bottom strip to their places, each in its own vertical lane */
    for (let i = 0; i < N_DATA; i++) {
      const col = subColour(colors, Y[i]);
      const b = at("bottom", i), l = at("left", i);
      dot(ctx, colors, b[0], b[1] + ((i % 5) - 2) * 3, 1.8, col, false);
      dot(ctx, colors, l[0] + ((i % 5) - 2) * 3, l[1], 1.8, col, false);
    }
    for (let i = 0; i < N_DATA; i++) {
      const q = at("pts", i), b = at("bottom", i);
      const y = lerp(b[1], q[1], rise);
      if (y > L.y + L.s && rise < 1) continue;
      dot(ctx, colors, q[0], y, 3, subColour(colors, Y[i]));
    }
    if (rise >= 1) txt(ctx, colors, `r = ${f2(V.r)}`, L.x + L.s - 6, L.y + 20, { fill: colors.ink1, align: "right", weight: "600" });
  }

  /* beside it: PLS against the benchmark, then each block's row of weights */
  if (found && rise >= 1) {
    const width = w - L.side - 4;
    drawTrade(ctx, colors, L.side, L.y + 30, width, [
      [S.rowR, f2(V.r), f2(V.ref.r)], [S.rowKept(BLOCK_NAME[P.a]), pct(V.keptA), pct(V.ref.keptA)], [S.rowKept(BLOCK_NAME[P.b]), pct(V.keptB), pct(V.ref.keptB)]]);
    drawWeights(ctx, colors, L.side, L.y + 154, width, P.a, V.wA, V.topA);
    drawWeights(ctx, colors, L.side, L.y + 230, width, P.b, V.wB, V.topB);
  }

  if (pointer && found && rise >= 1) {
    let hov = -1, best = 64;
    to.pts.forEach((q, i) => { const d = (q[0] - pointer.x) ** 2 + (q[1] - pointer.y) ** 2; if (d < best) { best = d; hov = i; } });
    if (hov >= 0) {
      ring(ctx, to.pts[hov][0], to.pts[hov][1], 6, colors.ink1);
      hoverLabel(ctx, colors, S.hovData(SUBTYPES[Y[hov]], BLOCK_NAME[P.a], f2(V.t[hov]), BLOCK_NAME[P.b], f2(V.u[hov])), pointer.x, pointer.y, w);
    }
  }
}

/* ==================================================== stages and easing */

const stepsOf = (stage, st) => (stage === "n-integration" ? st.blocks.loopEnd + 3 : stage === "factorization" ? 4 : stage === "p-integration" ? 3 : 1);
const durOf = (stage, n, st) => {
  if (stage === "data") return 1600;
  if (stage === "n-integration") return n > st.blocks.loopEnd ? 450 : 1400;
  if (stage === "p-integration") return n === 1 ? 1100 : 450;
  return n === 1 ? 1200 : n === 4 ? 1600 : 450;
};
const EASE_MS = 900;
const shownStep = (anim, stage) => (anim.n[stage] ?? 0) - (anim.stage === stage && anim.t < 1 ? 1 : 0);
const inFlight = (anim, stage) => (anim.stage === stage && anim.t < 1 ? anim.t : null);
const ezOf = (anim, page) => (anim.ez && anim.ez.page === page && anim.ez.t < 1 ? anim.ez : null);
const complete = (anim, stage, st) => (anim.n[stage] ?? 0) >= stepsOf(stage, st);
const formulaKey = (params, anim, st) => {
  if (params.page === "data") return "pls";
  if (params.page === "factorization") return "factor1";
  if (params.page === "p-integration") return "stack";
  const after = shownStep(anim, "n-integration") - st.blocks.loopEnd;
  return after >= 3 ? "shortcut" : after >= 1 ? "factorN" : "loop";
};
const TRACED_ON = { param: "page", oneOf: ["factorization", "n-integration"] };

/* ------------------------------------------------------------- widget */

defineWidget({
  slug: "shared-components",
  status: "draft",
  title: "Multi-omics: Shared Components",
  subtitle: S.subtitle,
  credit: "Data: TCGA Research Network (PanCanAtlas UCEC), via cBioPortal",
  layout: "side",
  height: (params) => ({ factorization: H_FACTOR, "n-integration": H_N, "p-integration": H_P }[params.page] ?? H_DATA),
  pointer: true,

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, groupHeads: true, default: "factorization", display: true },
    pair: { type: "segmented", label: S.pairLabel, detail: S.pairDetail, options: PAIR_OPTS, default: PAIR_OPTS[0].value, display: true, when: ON("data") },
    sample: { type: "int", label: S.sampleLabel, detail: S.sampleDetail, min: 1, max: N_CONCEPT, default: TRACED, display: true, when: TRACED_ON },
    /* authoring escape hatch, first render only: presses already made on the page the link opens */
    shown: { type: "int", min: 0, max: SLOTS, default: 0, hidden: true },
  },

  /* a legend reads params only, so the marks that arrive with presses (the dashed benchmark, the hollow rebuilt points) are named on the canvas */
  legend: ({ params }) => {
    const subs = [{ token: "cluster-a", label: S.sub[0], mark: "dot" }, { token: "cluster-b", label: S.sub[1], mark: "dot" }];
    const ramp = [{ token: "value-low", label: "low value", mark: "bar" }, { token: "value-high", label: "high value", mark: "bar" }];
    if (params.page === "data") return SUBTYPES.map((s, i) => ({ token: `cluster-${"abcd"[i]}`, label: s, mark: "dot" }));
    return [...subs, { token: "highlight", label: S.arrow, mark: "line" }, ...ramp];
  },

  compute: ({ rng }) => ({ blocks: makeBlocks(rng), studies: makeStudies(rng) }),

  /* a click on a dot or on a matrix row picks the traced sample */
  regions: ({ w, params, state, anim }) => {
    if (!state) return [];
    const st = state.blocks, out = [];
    const dotAt = (q, i, where) => out.push({ x: q[0] - 4, y: q[1] - 4, w: 8, h: 8, set: { sample: i + 1 }, label: `sample ${i + 1} in ${where}` });
    if (params.page === "factorization") {
      const L = factorLayout(w), px = toPxOf(L.P, st.span);
      st.order.forEach((i, r) => out.push({ x: L.m.X, y: L.my + r * L.rh, w: L.m.E + 2 * L.cw - L.m.X, h: L.rh, set: { sample: i + 1 }, label: `row of sample ${i + 1}` }));
      st.A.forEach((q, i) => dotAt(px(q[0], q[1]), i, "mRNA"));
      return out;
    }
    if (params.page !== "n-integration") return [];
    const Lm = nLayout(w), k = Math.min(anim?.n?.["n-integration"] ?? 0, st.loopEnd + 3), F = nView(st, k).frame;
    const pa = toPxOf(Lm.A, st.span), pb = toPxOf(Lm.B, st.span), ps = toPxOf(Lm.S, st.sspan);
    const { my, rh, mA, mB, cw } = Lm;
    st.order.forEach((i, r) => {
      out.push({ x: mA.X, y: my + r * rh, w: 5 * cw + 14, h: rh, set: { sample: i + 1 }, label: `row of sample ${i + 1}` });
      out.push({ x: mB.E, y: my + r * rh, w: mB.X + 2 * cw - mB.E, h: rh, set: { sample: i + 1 }, label: `row of sample ${i + 1}` });
    });
    st.A.forEach((q, i) => dotAt(pa(q[0], q[1]), i, "mRNA"));
    st.B.forEach((q, i) => dotAt(pb(q[0], q[1]), i, "methylation"));
    if (F.t && F.u) F.t.forEach((t, i) => dotAt(ps(t, F.u[i]), i, "scores"));
    return out;
  },

  animation: {
    stepLabel: S.stepLabel,
    stepTitle: S.stepTitle,
    /* each press is read once: Step alone (play-only-for-motion-or-repetition) */
    runLabel: null,

    init: ({ params, state, fromScratch }) => {
      const stage = params.page;
      const anim = { stage, n: {}, t: 1, dur: 1400, halt: false, ez: null, last: { ...params } };
      anim.n[stage] = fromScratch ? 0 : clamp(Number(params.shown) || 0, 0, stepsOf(stage, state));
      anim.beat = anim.n[stage];
      anim.done = complete(anim, stage, state);
      return anim;
    },

    advance: (anim, { dt, state }) => {
      /* a press a page switch interrupted ends here, before the new page's (mid-press-page-switch) */
      if (anim.halt) { anim.halt = false; return false; }
      const stage = anim.stage;
      if (anim.ez && anim.ez.t < 1) anim.ez.t = Math.min(1, anim.ez.t + dt / EASE_MS);
      /* an ease core started runs the press in flight on with it, and never starts a new one */
      if (anim.mode === "ease") {
        if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
        anim.done = complete(anim, stage, state) && anim.t >= 1;
        return anim.t < 1 || (anim.ez != null && anim.ez.t < 1);
      }
      if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
      else if ((anim.n[stage] ?? 0) < stepsOf(stage, state)) {
        anim.n[stage] = (anim.n[stage] ?? 0) + 1;
        anim.dur = durOf(stage, anim.n[stage], state);
        anim.t = 0;
      }
      anim.beat = anim.n[stage] ?? 0;
      anim.done = complete(anim, stage, state) && anim.t >= 1;
      if (anim.t >= 1 && anim.ez) anim.ez.t = 1;
      return anim.t < 1;
    },

    rebuild: (anim, { params, state }) => {
      const stage = params.page, was = anim.stage;
      /* only a page change ends a press in flight (mid-press-page-switch); a new traced sample does not */
      if (stage !== was && anim.t < 1) { anim.t = 1; anim.halt = true; }
      /* a change of Pair on TCGA UCEC, once component 1 is found, eases from the pair it leaves */
      if (stage === was && stage === "data" && complete(anim, "data", state) && params.pair !== anim.last.pair) {
        anim.ez = { page: "data", params: { ...anim.last }, t: 0 };
        anim.easing = true;
      } else if (stage !== was) anim.ez = null;
      anim.last = { ...params };
      anim.stage = stage;
      anim.beat = anim.n[stage] ?? 0;
      anim.done = complete(anim, stage, state) && anim.t >= 1;
    },
  },

  draw({ ctx, colors, w, params, state, anim, pointer }) {
    renderFormula(formulaKey(params, anim, state));
    if (params.page === "factorization") drawFactorization(ctx, colors, w, params, state.blocks, anim, pointer);
    else if (params.page === "n-integration") drawN(ctx, colors, w, params, state.blocks, anim, pointer);
    else if (params.page === "p-integration") drawP(ctx, colors, w, params, state.studies, anim, pointer);
    else drawData(ctx, colors, w, params, anim, pointer);
  },

  readout({ params, state, anim }) {
    const page = params.page, n = shownStep(anim, page);
    if (page === "factorization") {
      const F = state.blocks.fac;
      return [
        { label: S.tileK1, value: n >= 1 ? pct(F.kept1) : S.tileWait, note: S.tileKNote },
        { label: S.tileK2, value: n >= 4 ? pct(1) : S.tileWait, note: S.tileKNote },
        { label: S.tileShape, value: n >= 1 ? `80 × ${n >= 4 ? 2 : 1} · 2 × ${n >= 4 ? 2 : 1}` : S.tileWait, note: S.tileShapeNote },
      ];
    }
    if (page === "n-integration") {
      const st = state.blocks, F0 = nView(st, clamp(n, 0, st.loopEnd + 3)).frame;
      return [
        { label: S.tileR, value: F0.r != null ? f2(F0.r) : S.tileWait, note: S.tileRNote },
        { label: S.tileCov, value: F0.cv != null ? f2(F0.cv) : S.tileWait, note: S.tileCovNote },
        { label: S.tileKept(S.blockA), value: F0.keptA != null ? pct(F0.keptA) : S.tileWait, note: S.tileKeptNote },
        { label: S.tileKept(S.blockB), value: F0.keptB != null ? pct(F0.keptB) : S.tileWait, note: S.tileKeptNote },
      ];
    }
    if (page === "p-integration") {
      const pt = state.studies;
      return [
        { label: S.tileN, value: `${N_STUDY} + ${N_STUDY}`, note: n >= 1 ? "stacked into one table" : "two tables" },
        { label: S.tileW, value: n >= 2 ? `(${pair2(pt.w)})` : S.tileWait, note: S.tileWNote },
        { label: S.tileSub, value: n >= 3 ? f2(pt.rSub) : S.tileWait, note: S.tileSubNote },
      ];
    }
    const V = dataView(params.pair);
    return [
      { label: S.tileR, value: n >= 1 ? f2(V.r) : S.tileWait, note: S.tileRNote },
      { label: S.tileKept(BLOCK_NAME[V.P.a]), value: n >= 1 ? pct(V.keptA) : S.tileWait, note: S.tileKeptNote },
      { label: S.tileKept(BLOCK_NAME[V.P.b]), value: n >= 1 ? pct(V.keptB) : S.tileWait, note: S.tileKeptNote },
    ];
  },

  summary({ params, state, anim }) {
    const page = params.page, n = shownStep(anim, page);
    if (page === "factorization") return `One simulated block, mRNA: 80 samples, 2 genes, written as X ≈ T·Wᵀ; ${n} of 4 presses; sample ${params.sample} traced.`;
    if (page === "n-integration") {
      const st = state.blocks, F0 = nView(st, clamp(n, 0, st.loopEnd + 3)).frame;
      return `Two simulated blocks on the same 80 samples, each block's scatter above its matrix; sample ${params.sample} traced. ${n} of ${st.loopEnd + 3} presses${F0.r != null ? `; the scores correlate ${f2(F0.r)}` : ""}.`;
    }
    if (page === "p-integration") return `Two simulated studies with the same two genes, ${n >= 1 ? "stacked into one table" : "as two tables"}; ${n >= 2 ? "one w for both" : "no w yet"}.`;
    const V = dataView(params.pair);
    return `The lesson's ${BLOCK_NAME[V.P.a]} and ${BLOCK_NAME[V.P.b]} blocks, 405 samples coloured by subtype. ${n >= 1 ? `PLS component 1 scores plotted against each other; correlation ${f2(V.r)}, against ${f2(V.ref.r)} for the largest-variance directions.` : "No component found yet."}`;
  },
});
