/* ============================================================================
   Widget 99 · Multi-omics: Shared Components (`shared-components`) — PHM5003
   10, 01 cell 2 (X ≈ T·Wᵀ, and N-integration's max Σ cov(T₁ⱼ, T₂ⱼ)), 02 cell 0
   (DIABLO's latent variables) and 03 cells 12–13 (pls(X$mRNA, X$meth, ncomp
   = 1) and the correlation of its two score vectors).

   The misconception (catalogue § The multi-omics arc, slot 99): a block's
   component is its largest variation. PCA takes the direction of largest
   variance within one block, which may have little to do with the other
   blocks measured on the same samples; PLS takes, in each block, the
   direction whose scores covary most with the other block's. Measured on the
   lesson's own blocks (`_lab/multiomics-measure.R shared`): each block's PC1
   correlates 0.37 · 0.51 · 0.47 with the other's; PLS component 1 0.89 ·
   0.89 · 0.78, keeping 1–2 points less of each block's variance.

   TWO PAGES under Step, his calls from `_lab/multiomics-arc-mock.html`
   (2026-10-10, "all recommendations"):

     CONCEPT  two blocks of two features each, so a direction can be drawn:
              the same 80 samples, two subtypes. Each block has a large spread
              of its own and a smaller one, carrying the subtype difference,
              shared with the other block. Find component 1 draws the loading
              vector in each block, drops every sample onto it, and plots the
              two scores against each other.
     DATA     the lesson's 405 training samples, Pair over the three pairs
              03 cell 13 correlates. The same press fills each block's score
              strip and raises the samples into the scatter of one score
              against the other, coloured by subtype.

   Method (PCA · PLS) is one control on both pages and, once component 1 is
   found, a change of Method or Pair eases every mark to the other reading.

   Nothing is fitted on the page for Data: data.js (generated by
   `_lab/multiomics-measure.R widget99`) holds the scores and the variance
   shares. The Concept blocks are simulated here, and their components are
   exact 2 × 2 eigenvectors.
   ========================================================================= */

import { defineWidget, mathmlRenders } from "../core/index.js";
import { SUBTYPES, Y, BLOCKS, PAIRS } from "./data.js";

const PAGES = [{ value: "concept", label: "Concept" }, { value: "data", label: "Data" }];
const METHODS = [
  { value: "pca", label: "PCA", detail: "each block on its own: the direction of largest variance" },
  { value: "pls", label: "PLS", detail: "each block against the other: the directions whose scores covary most" },
];
const SHORT = { mRNA: "mRNA", meth: "meth", rppa: "RPPA" };
const PAIR_OPTS = PAIRS.map((p) => ({ value: `${p.a}-${p.b}`.toLowerCase(), label: `${SHORT[p.a]}–${SHORT[p.b]}` }));
const ON = (page) => ({ param: "page", equals: page });
const BLOCK_NAME = { mRNA: "mRNA", meth: "Methylation", rppa: "RPPA" };
const BLOCK_UNIT = { mRNA: "genes", meth: "CpG sites", rppa: "proteins" };
const N_DATA = Y.length;

/* ------------------------------------------------------------- strings */

const S = {
  subtitle:
    "Principal component analysis summarises one omics block by its direction of largest variance, which need not be related to the other blocks measured on the same samples. " +
    "Partial least squares chooses, in each block, the direction whose scores covary most with the other block's, so the two blocks' components agree. " +
    "Multi-omics integration methods such as DIABLO are built on this second kind of component.",
  pageLabel: "Step",
  methodLabel: "Method",
  pairLabel: "Pair",
  pairDetail: "two of the three blocks, measured on the same 405 samples",
  stepLabel: "Find component 1",
  stepTitle: {
    param: "method",
    labels: {
      pca: "In each block, find the direction of largest variance and give every sample its score along it",
      pls: "In each block, find the direction whose scores covary most with the other block's, and give every sample its score along it",
    },
    default: "Find component 1",
  },

  /* Concept */
  blockA: "mRNA",
  blockB: "Methylation",
  axesA: ["gene 1", "gene 2"],
  axesB: ["CpG 1", "CpG 2"],
  scores: "Scores",
  scoreX: "mRNA score",
  scoreY: "methylation score",
  sub: ["Subtype 1", "Subtype 2"],
  arrow: "component 1",
  caption: {
    pca: "PCA: in each block, the direction along which its samples vary most. The other block plays no part.",
    pls: "PLS: in each block, the direction whose scores covary most with the other block's scores.",
  },
  before: "80 samples, each measured in both blocks",

  /* Data */
  dims: (b) => `${BLOCK_NAME[b]}: ${N_DATA} samples × ${BLOCKS[b].features.toLocaleString("en-US")} ${BLOCK_UNIT[b]}`,
  strip: (b) => `${BLOCK_NAME[b]} component 1`,
  dataBefore: "Component 1 gives each sample one score per block.",
  table: ["", "PCA", "PLS"],
  rowR: "correlation r",
  rowVar: (name) => `${name} variance`,

  /* tiles */
  tileR: "Correlation of the scores",
  tileRNote: "between the two blocks' component 1",
  tileVar: (b) => `${b} variance kept`,
  tileVarNote: "share of the block's total variance",
  tileWait: "—",

  hovConcept: (i, g) => `sample ${i + 1} · ${g}`,
  hovData: (st, a, ta, b, tb) => `${st} · ${a} ${ta} · ${b} ${tb}`,
  sumConcept: (m, on, r) => `Two simulated blocks of two features, 80 samples in two subtypes. ${on ? `${m.toUpperCase()} component 1 drawn in each block; the two blocks' scores correlate ${r}.` : "No component found yet."}`,
  sumData: (a, b, m, on, r) => `The lesson's ${a} and ${b} blocks, 405 samples coloured by subtype. ${on ? `${m.toUpperCase()} component 1 scores plotted against each other; correlation ${r}.` : "No component found yet."}`,

  mathNote: {
    pca: "w is chosen within one block; the other block does not enter.",
    pls: "One pair (w₁, w₂) for the two blocks together: the first of the components that maximise Σ cov(T₁ⱼ, T₂ⱼ).",
  },
};

/* --------------------------------------------------------- formula card */

const MATHML = mathmlRenders();
const MATH = {
  pca: {
    math: '<math display="block"><mrow><mi>t</mi><mo>=</mo><mi>X</mi><mi>w</mi><mo>,</mo><mspace width="1em"/><munder><mo>max</mo><mrow><mo>‖</mo><mi>w</mi><mo>‖</mo><mo>=</mo><mn>1</mn></mrow></munder><mspace width="0.3em"/><mtext>var</mtext><mo>(</mo><mi>t</mi><mo>)</mo></mrow></math>',
    plain: "t = X w,   max over ‖w‖ = 1 of var(t)",
  },
  pls: {
    math: '<math display="block"><mrow><mi>t</mi><mo>=</mo><msub><mi>X</mi><mn>1</mn></msub><msub><mi>w</mi><mn>1</mn></msub><mo>,</mo><mspace width="0.6em"/><mi>u</mi><mo>=</mo><msub><mi>X</mi><mn>2</mn></msub><msub><mi>w</mi><mn>2</mn></msub><mo>,</mo><mspace width="1em"/><munder><mo>max</mo><mrow><mo>‖</mo><msub><mi>w</mi><mn>1</mn></msub><mo>‖</mo><mo>=</mo><mo>‖</mo><msub><mi>w</mi><mn>2</mn></msub><mo>‖</mo><mo>=</mo><mn>1</mn></mrow></munder><mspace width="0.3em"/><mtext>cov</mtext><mo>(</mo><mi>t</mi><mo>,</mo><mi>u</mi><mo>)</mo></mrow></math>',
    plain: "t = X₁w₁,  u = X₂w₂,   max over ‖w₁‖ = ‖w₂‖ = 1 of cov(t, u)",
  },
};
let mathHost = null, mathKey = null;
function renderFormula(method) {
  if (!mathHost) {
    const figure = document.querySelector("#widget .w-figure");
    if (!figure || !figure.parentNode) return;
    mathHost = document.createElement("div");
    mathHost.className = "w-math";
    figure.parentNode.insertBefore(mathHost, figure);
  }
  if (mathKey === method) return;
  mathKey = method;
  const F = MATH[method];
  mathHost.innerHTML = `<div class="w-math-eq"><span style="color:var(--ink-2)">${MATHML ? F.math : F.plain}</span></div><div class="w-math-note">${S.mathNote[method]}</div>`;
}

/* ------------------------------------------------------------- helpers */

const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
const seg = (t, a, b) => clamp((t - a) / (b - a), 0, 1);
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - ((-2 * t + 2) ** 3) / 2);
const lerp = (a, b, t) => a + (b - a) * t;
const mean = (v) => v.reduce((s, x) => s + x, 0) / v.length;
function corr(a, b) {
  const ma = mean(a), mb = mean(b);
  let sab = 0, saa = 0, sbb = 0;
  for (let i = 0; i < a.length; i++) { sab += (a[i] - ma) * (b[i] - mb); saa += (a[i] - ma) ** 2; sbb += (b[i] - mb) ** 2; }
  return sab / Math.sqrt(saa * sbb);
}
const f2 = (v) => v.toFixed(2);
const pct = (v) => `${(100 * v).toFixed(1)}%`;

function txt(ctx, colors, s, x, y, { size = colors.fsSm, fill = colors.ink2, align = "left", baseline = "alphabetic", weight = "" } = {}) {
  ctx.save(); ctx.font = `${weight ? weight + " " : ""}${size} ${colors.font}`; ctx.fillStyle = fill;
  ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
function line(ctx, x1, y1, x2, y2, col, w = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = w; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.restore();
}
function dot(ctx, colors, x, y, r, fill, edge = true) {
  ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.fillStyle = fill; ctx.fill();
  if (edge) { ctx.lineWidth = 1; ctx.strokeStyle = colors.surface; ctx.stroke(); }
}
function ring(ctx, x, y, r, col) {
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.lineWidth = 2; ctx.strokeStyle = col; ctx.stroke(); ctx.restore();
}
function frame(ctx, colors, x, y, w, h) {
  ctx.save(); ctx.strokeStyle = colors.axis; ctx.lineWidth = 1; ctx.strokeRect(x + 0.5, y + 0.5, w - 1, h - 1); ctx.restore();
}
function arrowHead(ctx, x0, y0, x1, y1, col, head) {
  const a = Math.atan2(y1 - y0, x1 - x0);
  ctx.save(); ctx.fillStyle = col; ctx.beginPath(); ctx.moveTo(x1, y1);
  ctx.lineTo(x1 - head * Math.cos(a - 0.42), y1 - head * Math.sin(a - 0.42));
  ctx.lineTo(x1 - head * Math.cos(a + 0.42), y1 - head * Math.sin(a + 0.42));
  ctx.closePath(); ctx.fill(); ctx.restore();
}
/** a component's direction has no sign: drawn double-headed, as pca's are */
function axisArrow(ctx, x0, y0, x1, y1, col) {
  line(ctx, x0, y0, x1, y1, col, 2.2);
  arrowHead(ctx, x0, y0, x1, y1, col, 8); arrowHead(ctx, x1, y1, x0, y0, col, 8);
}
function vText(ctx, colors, s, x, y, opts) {
  ctx.save(); ctx.translate(x, y); ctx.rotate(-Math.PI / 2); txt(ctx, colors, s, 0, 0, { align: "center", ...opts }); ctx.restore();
}
function hoverLabel(ctx, colors, str, x, y, w) {
  ctx.save(); ctx.font = `600 ${colors.fsXs} ${colors.font}`;
  const tw = ctx.measureText(str).width; ctx.restore();
  const bx = Math.max(4, Math.min(w - tw - 14, x + 10)), by = Math.max(4, y - 26);
  ctx.save(); ctx.fillStyle = colors.surface; ctx.fillRect(bx, by, tw + 10, 18);
  ctx.strokeStyle = colors.ink3; ctx.strokeRect(bx + 0.5, by + 0.5, tw + 9, 17); ctx.restore();
  txt(ctx, colors, str, bx + 5, by + 9.5, { size: colors.fsXs, fill: colors.ink1, baseline: "middle", weight: "600" });
}
const subColour = (colors, g) => colors.clusters[g];
/** words laid into lines no wider than `maxW`, `lh` apart */
function wrapText(ctx, colors, str, x, y, maxW, lh, opts = {}) {
  ctx.save(); ctx.font = `${opts.size ?? colors.fsSm} ${colors.font}`;
  const lines = []; let cur = "";
  for (const word of str.split(" ")) {
    const tryLine = cur ? `${cur} ${word}` : word;
    if (ctx.measureText(tryLine).width > maxW && cur) { lines.push(cur); cur = word; } else cur = tryLine;
  }
  if (cur) lines.push(cur);
  ctx.restore();
  lines.forEach((l, i) => txt(ctx, colors, l, x, y + i * lh, { fill: colors.ink2, ...opts }));
  return lines.length;
}


/** the two methods side by side, the current one framed: what PLS gains in
   agreement and gives up in variance, on whichever page */
function drawTrade(ctx, colors, x, y, width, method, rows) {
  const cw = 52, rh = 22, lw = Math.max(0, width - 2 * cw);
  const fill = (m) => (method === m ? colors.ink1 : colors.ink3);
  txt(ctx, colors, S.table[1], x + lw + cw / 2, y, { align: "center", fill: fill("pca"), weight: "600" });
  txt(ctx, colors, S.table[2], x + lw + cw * 1.5, y, { align: "center", fill: fill("pls"), weight: "600" });
  rows.forEach((r, i) => {
    const yy = y + (i + 1) * rh;
    txt(ctx, colors, r[0], x, yy, { size: colors.fsXs, fill: colors.ink2 });
    txt(ctx, colors, r[1], x + lw + cw / 2, yy, { align: "center", fill: fill("pca") });
    txt(ctx, colors, r[2], x + lw + cw * 1.5, yy, { align: "center", fill: fill("pls") });
  });
  const cx = x + lw + (method === "pca" ? 0 : cw);
  ctx.save(); ctx.strokeStyle = colors.highlight; ctx.lineWidth = 2;
  ctx.strokeRect(cx + 3.5, y - 16, cw - 6, rows.length * rh + 24); ctx.restore();
}

/* ======================================================== CONCEPT blocks */

/* Two blocks on the same samples. In each, the shared axis carries the
   subtype difference (±0.85 plus noise) and is the SMALLER spread; a private
   axis, unrelated to the other block, is the larger (sd 1.6). Measured on the
   draft's seed: PCA keeps ~75% of each block and its scores correlate ~0.2;
   PLS keeps ~25% and they correlate ~0.9. The angles keep the four axes
   apart on screen, so no arrow lies along a feature axis. */
const N_CONCEPT = 80;
const ANG = { a: [62, -28], b: [18, 108] };
const unitAt = (deg) => [Math.cos((deg * Math.PI) / 180), Math.sin((deg * Math.PI) / 180)];

function topEig2(a, b, d) {
  const tr = a + d, det = a * d - b * b, l = tr / 2 + Math.sqrt(Math.max(0, (tr * tr) / 4 - det));
  const v = Math.abs(b) > 1e-12 ? [l - d, b] : a >= d ? [1, 0] : [0, 1];
  const n = Math.hypot(v[0], v[1]);
  return [v[0] / n, v[1] / n];
}
const project = (X, d) => X.map((p) => p[0] * d[0] + p[1] * d[1]);
const flip = (d) => [-d[0], -d[1]];

function makeConcept(rng) {
  const ua = unitAt(ANG.a[0]), va = unitAt(ANG.a[1]), ub = unitAt(ANG.b[0]), vb = unitAt(ANG.b[1]);
  const g = [], A = [], B = [];
  for (let i = 0; i < N_CONCEPT; i++) {
    const grp = i % 2;
    const s = (grp ? 0.85 : -0.85) + 0.35 * rng.normal();
    const a = 1.6 * rng.normal(), b = 1.6 * rng.normal();
    g.push(grp);
    A.push([0, 1].map((j) => s * ua[j] + a * va[j] + 0.2 * rng.normal()));
    B.push([0, 1].map((j) => s * ub[j] + b * vb[j] + 0.2 * rng.normal()));
  }
  const centre = (X) => { const m = [0, 1].map((j) => mean(X.map((p) => p[j]))); return X.map((p) => [p[0] - m[0], p[1] - m[1]]); };
  const Ac = centre(A), Bc = centre(B);
  const cross = (X, Z) => { const M = [[0, 0], [0, 0]]; X.forEach((x, i) => { for (let r = 0; r < 2; r++) for (let c = 0; c < 2; c++) M[r][c] += x[r] * Z[i][c]; }); return M; };
  const CA = cross(Ac, Ac), CB = cross(Bc, Bc), M = cross(Ac, Bc);
  /* PLS's first pair: the top singular vectors of X₁ᵀX₂ */
  const MMt = [M[0][0] ** 2 + M[0][1] ** 2, M[0][0] * M[1][0] + M[0][1] * M[1][1], M[1][0] ** 2 + M[1][1] ** 2];
  const w1 = topEig2(MMt[0], MMt[1], MMt[2]);
  let w2 = [M[0][0] * w1[0] + M[1][0] * w1[1], M[0][1] * w1[0] + M[1][1] * w1[1]];
  const n2 = Math.hypot(w2[0], w2[1]); w2 = [w2[0] / n2, w2[1] / n2];
  /* Signs: subtype 2 scores positive in PLS block 1; then each method's
     second direction makes its scores correlate positively, and PCA's first
     agrees with PLS's, so a switch of method moves the samples the least. */
  const dirs = { pls: [w1, w2], pca: [topEig2(CA[0][0], CA[0][1], CA[1][1]), topEig2(CB[0][0], CB[0][1], CB[1][1])] };
  const tPls = project(Ac, dirs.pls[0]);
  if (mean(tPls.filter((_, i) => g[i])) < 0) { dirs.pls[0] = flip(dirs.pls[0]); dirs.pls[1] = flip(dirs.pls[1]); }
  if (dirs.pca[0][0] * dirs.pls[0][0] + dirs.pca[0][1] * dirs.pls[0][1] < 0) dirs.pca[0] = flip(dirs.pca[0]);
  const tot = (X) => X.reduce((s, p) => s + p[0] ** 2 + p[1] ** 2, 0);
  const view = {};
  for (const m of ["pca", "pls"]) {
    const t = project(Ac, dirs[m][0]);
    let u = project(Bc, dirs[m][1]);
    if (corr(t, u) < 0) { dirs[m][1] = flip(dirs[m][1]); u = u.map((x) => -x); }
    view[m] = { dirs: dirs[m], t, u, r: corr(t, u), varA: t.reduce((s, x) => s + x * x, 0) / tot(Ac), varB: u.reduce((s, x) => s + x * x, 0) / tot(Bc) };
  }
  const span = 1.08 * Math.max(...Ac.flat().map(Math.abs), ...Bc.flat().map(Math.abs));
  const sspan = 1.08 * Math.max(...["pca", "pls"].flatMap((m) => [...view[m].t, ...view[m].u].map(Math.abs)));
  return { g, A: Ac, B: Bc, view, span, sspan };
}

/* --------------------------------------------------------- Concept layout *
 * Two rows at every width: the two blocks side by side, the scores under the
 * first with the caption beside it. Three across shrank each panel to 88px in
 * the harness's 550px canvas (draft, 2026-10-10). The height is a constant,
 * read by `height` and `draw` alike.                                         */
const C = { top: 26, padL: 30, gap: 44, padR: 10, sMax: 220, rowGap: 58 };
function conceptLayout(w) {
  const s = Math.floor(Math.min(C.sMax, (w - C.padL - C.padR - C.gap) / 2));
  const x0 = C.padL, x1 = x0 + s + C.gap, y1 = C.top + s + C.rowGap;
  return { s, panels: [{ x: x0, y: C.top, s }, { x: x1, y: C.top, s }, { x: x0, y: y1, s }], text: { x: x1, y: y1, w: Math.max(120, w - x1 - C.padR) } };
}
const H_CONCEPT = C.top + 2 * C.sMax + C.rowGap + 30;

/** pixel positions of every mark for one reading (method) of the Concept page */
function conceptMarks(L, st, method) {
  const V = st.view[method], [PA, PB, PS] = L.panels;
  const toPx = (P, span, x, y) => [P.x + P.s / 2 + (x / span) * (P.s / 2), P.y + P.s / 2 - (y / span) * (P.s / 2)];
  const foot = (X, d, k) => { const t = X[k][0] * d[0] + X[k][1] * d[1]; return [t * d[0], t * d[1]]; };
  return {
    arrows: [[PA, V.dirs[0]], [PB, V.dirs[1]]].map(([P, d]) => {
      const R = 0.92 * st.span;
      return [toPx(P, st.span, -R * d[0], -R * d[1]), toPx(P, st.span, R * d[0], R * d[1])];
    }),
    feetA: st.A.map((_, k) => toPx(PA, st.span, ...foot(st.A, V.dirs[0], k))),
    feetB: st.B.map((_, k) => toPx(PB, st.span, ...foot(st.B, V.dirs[1], k))),
    scores: V.t.map((t, k) => toPx(PS, st.sspan, t, V.u[k])),
  };
}
const lerpPt = (a, b, t) => [lerp(a[0], b[0], t), lerp(a[1], b[1], t)];
/** a mark set eased from the reading the rail left (`ez`) to the current one */
function blendMarks(from, to, t) {
  if (!from || t >= 1) return to;
  return {
    arrows: to.arrows.map((ar, i) => blendAxis(from.arrows[i], ar, t)),
    feetA: to.feetA.map((p, k) => lerpPt(from.feetA[k], p, t)),
    feetB: to.feetB.map((p, k) => lerpPt(from.feetB[k], p, t)),
    scores: to.scores.map((p, k) => lerpPt(from.scores[k], p, t)),
  };
}
/** an axis turns the short way: it has no sign, so a half-turn is no turn */
function blendAxis(a, b, t) {
  const c = lerpPt(a[0], a[1], 0.5), L = Math.hypot(b[1][0] - b[0][0], b[1][1] - b[0][1]) / 2;
  let a0 = Math.atan2(a[1][1] - a[0][1], a[1][0] - a[0][0]), a1 = Math.atan2(b[1][1] - b[0][1], b[1][0] - b[0][0]);
  let d = a1 - a0;
  while (d > Math.PI / 2) d -= Math.PI;
  while (d < -Math.PI / 2) d += Math.PI;
  const ang = a0 + d * t;
  return [[c[0] - L * Math.cos(ang), c[1] - L * Math.sin(ang)], [c[0] + L * Math.cos(ang), c[1] + L * Math.sin(ang)]];
}

function drawConcept(ctx, colors, w, params, st, anim, pointer) {
  const L = conceptLayout(w), [PA, PB, PS] = L.panels;
  const beat = shownStep(anim, "concept"), t = inFlight(anim, "concept");
  const found = beat >= 1 || t != null;
  const drop = t != null ? ease(seg(t, 0, 0.75)) : 1;
  const scoresOn = beat >= 1 || (t != null && t >= 0.75);
  const toPx = (P, x, y) => [P.x + P.s / 2 + (x / st.span) * (P.s / 2), P.y + P.s / 2 - (y / st.span) * (P.s / 2)];
  const ez = ezOf(anim, "concept");
  const M = blendMarks(ez ? conceptMarks(L, st, ez.params.method) : null, conceptMarks(L, st, params.method), ez ? ease(ez.t) : 1);

  [[PA, S.blockA, S.axesA], [PB, S.blockB, S.axesB], [PS, S.scores, [S.scoreX, S.scoreY]]].forEach(([P, name, ax]) => {
    txt(ctx, colors, name, P.x, P.y - 10, { fill: colors.ink1, weight: "600" });
    frame(ctx, colors, P.x, P.y, P.s, P.s);
    txt(ctx, colors, ax[0], P.x + P.s / 2, P.y + P.s + 15, { size: colors.fsXs, fill: colors.ink3, align: "center" });
    vText(ctx, colors, ax[1], P.x - 8, P.y + P.s / 2, { size: colors.fsXs, fill: colors.ink3 });
  });

  /* pointer: the nearest sample in any panel, ringed in all three */
  let hov = -1;
  if (pointer) {
    let best = 81;
    const tryPts = (pts) => pts.forEach((p, k) => { const d = (p[0] - pointer.x) ** 2 + (p[1] - pointer.y) ** 2; if (d < best) { best = d; hov = k; } });
    tryPts(st.A.map((p) => toPx(PA, p[0], p[1])));
    tryPts(st.B.map((p) => toPx(PB, p[0], p[1])));
    if (scoresOn) tryPts(M.scores);
  }

  if (found) M.arrows.forEach(([p0, p1]) => axisArrow(ctx, p0[0], p0[1], p1[0], p1[1], colors.highlight));

  [[PA, st.A, M.feetA], [PB, st.B, M.feetB]].forEach(([P, X, feet]) => {
    X.forEach((p, k) => {
      const [x, y] = toPx(P, p[0], p[1]);
      if (found) {
        const [fx, fy] = lerpPt([x, y], feet[k], drop);
        if (drop < 1) line(ctx, x, y, fx, fy, colors.ink3, 1);
        dot(ctx, colors, fx, fy, 2.6, subColour(colors, st.g[k]), false);
      }
      dot(ctx, colors, x, y, 4, subColour(colors, st.g[k]));
    });
  });
  if (scoresOn) M.scores.forEach((p, k) => dot(ctx, colors, p[0], p[1], 4, subColour(colors, st.g[k])));
  if (scoresOn) {
    const r = st.view[params.method].r;
    txt(ctx, colors, `r = ${f2(r)}`, PS.x + PS.s - 6, PS.y + 16, { fill: colors.ink1, align: "right", weight: "600" });
  }

  const nl = wrapText(ctx, colors, found ? S.caption[params.method] : S.before, L.text.x, L.text.y + 14, L.text.w, 18);
  if (scoresOn) {
    const VP = st.view.pca, VL = st.view.pls;
    drawTrade(ctx, colors, L.text.x, L.text.y + 14 + nl * 18 + 30, L.text.w, params.method, [
      [S.rowR, f2(VP.r), f2(VL.r)], [S.rowVar(S.blockA), pct(VP.varA), pct(VL.varA)], [S.rowVar(S.blockB), pct(VP.varB), pct(VL.varB)]]);
  }

  if (hov >= 0) {
    const pts = [toPx(PA, ...st.A[hov]), toPx(PB, ...st.B[hov])].concat(scoresOn ? [M.scores[hov]] : []);
    pts.forEach((p) => ring(ctx, p[0], p[1], 7, colors.ink1));
    hoverLabel(ctx, colors, S.hovConcept(hov, S.sub[st.g[hov]]), pointer.x, pointer.y, w);
  }
}

/* =========================================================== DATA page */

const pairOf = (key) => PAIRS.find((p) => `${p.a}-${p.b}`.toLowerCase() === key);
/** one reading of the Data page: the two score vectors, PCA's oriented to agree with PLS's */
const DATA_VIEW = {};
function dataView(pairKey, method) {
  const k = `${pairKey}|${method}`;
  if (DATA_VIEW[k]) return DATA_VIEW[k];
  const P = pairOf(pairKey);
  let t = P.t, u = P.u, varA = P.varA, varB = P.varB;
  if (method === "pca") {
    t = BLOCKS[P.a].pc1; u = BLOCKS[P.b].pc1; varA = BLOCKS[P.a].var; varB = BLOCKS[P.b].var;
    /* a component has no sign: turned so the two scores correlate positively, as PLS's do */
    if (corr(t, u) < 0) u = u.map((x) => -x);
  }
  const both = (m, key) => (m === "pca" ? BLOCKS[P[key]].pc1 : P[key === "a" ? "t" : "u"]);
  const xs = 1.08 * Math.max(...both("pca", "a").map(Math.abs), ...P.t.map(Math.abs));
  const ys = 1.08 * Math.max(...both("pca", "b").map(Math.abs), ...P.u.map(Math.abs));
  DATA_VIEW[k] = { P, t, u, varA, varB, r: corr(t, u), xs, ys };
  return DATA_VIEW[k];
}

const D = { top: 34, x0: 66, sMax: 260, strip: 22, gapStrip: 8 };
function dataLayout(w) {
  const s = Math.min(D.sMax, Math.floor(w - D.x0 - 240));
  return { s, x: D.x0, y: D.top, side: D.x0 + s + 34 };
}
const H_DATA = D.top + D.sMax + D.gapStrip + D.strip + 40;

function dataMarks(L, V) {
  const sx = (v) => L.x + L.s / 2 + (v / V.xs) * (L.s / 2), sy = (v) => L.y + L.s / 2 - (v / V.ys) * (L.s / 2);
  const stripY = L.y + L.s + D.gapStrip + D.strip / 2, stripX = L.x - D.gapStrip - D.strip / 2;
  return {
    pts: V.t.map((t, k) => [sx(t), sy(V.u[k])]),
    bottom: V.t.map((t) => [sx(t), stripY]),
    left: V.u.map((u) => [stripX, sy(u)]),
  };
}

function drawData(ctx, colors, w, params, anim, pointer) {
  const L = dataLayout(w), V = dataView(params.pair, params.method), P = V.P;
  const beat = shownStep(anim, "data"), t = inFlight(anim, "data");
  const found = beat >= 1 || t != null;
  const rise = t != null ? ease(seg(t, 0.15, 1)) : 1;
  const ez = ezOf(anim, "data");
  const to = dataMarks(L, V);
  const from = ez ? dataMarks(L, dataView(ez.params.pair, ez.params.method)) : null;
  const k = ez ? ease(ez.t) : 1;
  const at = (key, i) => (from ? lerpPt(from[key][i], to[key][i], k) : to[key][i]);

  txt(ctx, colors, S.dims(P.a), L.x - D.gapStrip - D.strip, 14, { fill: colors.ink2 });
  txt(ctx, colors, S.dims(P.b), L.x - D.gapStrip - D.strip, 28, { fill: colors.ink2 });

  frame(ctx, colors, L.x, L.y + 4, L.s, L.s - 4);
  frame(ctx, colors, L.x, L.y + L.s + D.gapStrip, L.s, D.strip);
  frame(ctx, colors, L.x - D.gapStrip - D.strip, L.y + 4, D.strip, L.s - 4);
  txt(ctx, colors, S.strip(P.a), L.x + L.s / 2, L.y + L.s + D.gapStrip + D.strip + 15, { size: colors.fsXs, fill: colors.ink3, align: "center" });
  vText(ctx, colors, S.strip(P.b), L.x - D.gapStrip - D.strip - 8, L.y + L.s / 2, { size: colors.fsXs, fill: colors.ink3 });

  if (!found) {
    txt(ctx, colors, S.dataBefore, L.x + L.s / 2, L.y + L.s / 2, { fill: colors.ink3, align: "center", baseline: "middle" });
  } else {
    /* the strips appear at once with the press; the samples rise out of the
       bottom strip to their places, each in its own vertical lane */
    for (let i = 0; i < N_DATA; i++) {
      const col = subColour(colors, Y[i]);
      const b = at("bottom", i), l = at("left", i);
      dot(ctx, colors, b[0], b[1] + ((i % 5) - 2) * 3, 1.8, col, false);
      dot(ctx, colors, l[0] + ((i % 5) - 2) * 3, l[1], 1.8, col, false);
    }
    for (let i = 0; i < N_DATA; i++) {
      const p = at("pts", i), b = at("bottom", i);
      const y = lerp(b[1], p[1], rise);
      if (y > L.y + L.s && rise < 1) continue;
      dot(ctx, colors, p[0], y, 3, subColour(colors, Y[i]));
    }
    if (rise >= 1) txt(ctx, colors, `r = ${f2(V.r)}`, L.x + L.s - 6, L.y + 20, { fill: colors.ink1, align: "right", weight: "600" });
  }

  /* the trade, both methods side by side, once a component is found */
  if (found && rise >= 1) {
    const VP = dataView(params.pair, "pca"), VL = dataView(params.pair, "pls");
    drawTrade(ctx, colors, L.side, L.y + 30, w - L.side - 4, params.method, [
      [S.rowR, f2(VP.r), f2(VL.r)], [S.rowVar(BLOCK_NAME[P.a]), pct(VP.varA), pct(VL.varA)], [S.rowVar(BLOCK_NAME[P.b]), pct(VP.varB), pct(VL.varB)]]);
  }

  if (pointer && found && rise >= 1) {
    let hov = -1, best = 64;
    to.pts.forEach((p, i) => { const d = (p[0] - pointer.x) ** 2 + (p[1] - pointer.y) ** 2; if (d < best) { best = d; hov = i; } });
    if (hov >= 0) {
      ring(ctx, to.pts[hov][0], to.pts[hov][1], 6, colors.ink1);
      hoverLabel(ctx, colors, S.hovData(SUBTYPES[Y[hov]], BLOCK_NAME[P.a], f2(V.t[hov]), BLOCK_NAME[P.b], f2(V.u[hov])), pointer.x, pointer.y, w);
    }
  }
}

/* ==================================================== stages and easing */

const STEPS = { concept: 1, data: 1 };
const DUR = { concept: 1400, data: 1600 };
const EASE_MS = 900;
const TWEENED = ["method", "pair"];
const shownStep = (anim, stage) => (anim.n[stage] ?? 0) - (anim.stage === stage && anim.t < 1 ? 1 : 0);
const inFlight = (anim, stage) => (anim.stage === stage && anim.t < 1 ? anim.t : null);
const ezOf = (anim, stage) => (anim.ez && anim.ez.stage === stage && anim.ez.t < 1 ? anim.ez : null);

/* ------------------------------------------------------------- widget */

defineWidget({
  slug: "shared-components",
  status: "draft",
  title: "Multi-omics: Shared Components",
  subtitle: S.subtitle,
  credit: "Data: TCGA Research Network (PanCanAtlas UCEC), via cBioPortal",
  layout: "side",
  height: (params) => (params.page === "concept" ? H_CONCEPT : H_DATA),
  pointer: true,

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "concept", display: true },
    pair: { type: "segmented", label: S.pairLabel, detail: S.pairDetail, options: PAIR_OPTS, default: PAIR_OPTS[0].value, display: true, when: ON("data") },
    method: { type: "segmented", label: S.methodLabel, options: METHODS, default: "pca", display: true },
    /* authoring escape hatch, first render only: the press already made on the page the link opens */
    shown: { type: "int", min: 0, max: 1, default: 0, hidden: true },
  },

  legend: ({ params }) => (params.page === "concept"
    ? [
      { token: "cluster-a", label: S.sub[0], mark: "dot" },
      { token: "cluster-b", label: S.sub[1], mark: "dot" },
      { token: "highlight", label: S.arrow, mark: "line" },
    ]
    : SUBTYPES.map((s, i) => ({ token: `cluster-${"abcd"[i]}`, label: s, mark: "dot" }))),

  compute: ({ rng }) => ({ concept: makeConcept(rng) }),

  animation: {
    stepLabel: S.stepLabel,
    stepTitle: S.stepTitle,
    /* one press a page, read once: Step alone (play-only-for-motion-or-repetition) */
    runLabel: null,

    init: ({ params, fromScratch }) => {
      const stage = params.page;
      const anim = { stage, n: { concept: 0, data: 0 }, t: 1, dur: DUR[stage], halt: false, ez: null, last: { ...params } };
      anim.n[stage] = fromScratch ? 0 : Math.max(0, Math.min(STEPS[stage], Number(params.shown) || 0));
      anim.beat = anim.n[stage];
      anim.done = anim.n[stage] >= STEPS[stage];
      return anim;
    },

    advance: (anim, { dt }) => {
      /* a press a page switch interrupted ends here, before the new page's (mid-press-page-switch) */
      if (anim.halt) { anim.halt = false; return false; }
      const stage = anim.stage;
      if (anim.ez && anim.ez.t < 1) anim.ez.t = Math.min(1, anim.ez.t + dt / EASE_MS);
      /* an ease core started runs the press in flight on with it, and never starts a new one */
      if (anim.mode === "ease") {
        if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
        anim.done = anim.n[stage] >= STEPS[stage] && anim.t >= 1;
        return anim.t < 1 || (anim.ez != null && anim.ez.t < 1);
      }
      if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
      else if (anim.n[stage] < STEPS[stage]) {
        anim.n[stage] += 1;
        anim.dur = DUR[stage];
        anim.t = 0;
      }
      anim.beat = anim.n[stage];
      anim.done = anim.n[stage] >= STEPS[stage] && anim.t >= 1;
      if (anim.t >= 1 && anim.ez) anim.ez.t = 1;
      return anim.t < 1;
    },

    rebuild: (anim, { params }) => {
      const stage = params.page;
      /* only a page change ends a press in flight (mid-press-page-switch) */
      if (stage !== anim.stage && anim.t < 1) { anim.t = 1; anim.halt = true; }
      /* a rail control on the same page, once component 1 is found, eases from the reading it leaves */
      if (stage === anim.stage && anim.n[stage] >= 1 && TWEENED.some((k) => params[k] !== anim.last[k])) {
        anim.ez = { stage, params: { ...anim.last }, t: 0 };
        anim.easing = true;
      } else if (stage !== anim.stage) anim.ez = null;
      anim.last = { ...params };
      anim.stage = stage;
      anim.beat = anim.n[stage];
      anim.done = anim.n[stage] >= STEPS[stage] && anim.t >= 1;
    },
  },

  draw({ ctx, colors, w, params, state, anim, pointer }) {
    renderFormula(params.method);
    if (params.page === "concept") drawConcept(ctx, colors, w, params, state.concept, anim, pointer);
    else drawData(ctx, colors, w, params, anim, pointer);
  },

  readout({ params, state, anim }) {
    const on = shownStep(anim, params.page) >= 1;
    if (params.page === "concept") {
      const V = state.concept.view[params.method];
      return [
        { label: S.tileR, value: on ? f2(V.r) : S.tileWait, note: S.tileRNote },
        { label: S.tileVar(S.blockA), value: on ? pct(V.varA) : S.tileWait, note: S.tileVarNote },
        { label: S.tileVar(S.blockB), value: on ? pct(V.varB) : S.tileWait, note: S.tileVarNote },
      ];
    }
    const V = dataView(params.pair, params.method);
    return [
      { label: S.tileR, value: on ? f2(V.r) : S.tileWait, note: S.tileRNote },
      { label: S.tileVar(BLOCK_NAME[V.P.a]), value: on ? pct(V.varA) : S.tileWait, note: S.tileVarNote },
      { label: S.tileVar(BLOCK_NAME[V.P.b]), value: on ? pct(V.varB) : S.tileWait, note: S.tileVarNote },
    ];
  },

  summary({ params, state, anim }) {
    const on = shownStep(anim, params.page) >= 1;
    if (params.page === "concept") return S.sumConcept(params.method, on, f2(state.concept.view[params.method].r));
    const V = dataView(params.pair, params.method);
    return S.sumData(BLOCK_NAME[V.P.a], BLOCK_NAME[V.P.b], params.method, on, f2(V.r));
  },
});
