/* ============================================================================
   Widget 99 · Multi-omics: Shared Components (`shared-components`) — PHM5003
   10, 01 cell 2 (X ≈ T·Wᵀ; N- and P-integration; N-integration's max Σ
   cov(T₁ⱼ, T₂ⱼ)), 02 cell 0 (DIABLO's latent variables) and 03 cells 12–13
   (pls(X$mRNA, X$meth, ncomp = 1) and the correlation of its two scores).

   The misconception (catalogue § The multi-omics arc, slot 99): a block's
   component is its largest variation. PCA takes the direction of largest
   variance within one block, which may have little to do with the other
   blocks measured on the same samples; PLS takes, in each block, the
   direction whose scores covary most with the other block's. Measured on the
   lesson's own blocks (`_lab/multiomics-measure.R shared`): each block's PC1
   correlates 0.37 · 0.51 · 0.47 with the other's; PLS component 1 0.89 ·
   0.89 · 0.78, rebuilding 1–2 points less of each block.

   THREE PAGES under Step. The draft had two; round 1 (his "show how PLS is
   done ... matrix factorization", and "does it help to illustrate N- and
   P-integration") added the iteration and the Factorize page, every call his
   from `_lab/shared-components-pls-mock.html` ("all recommendations"):

     CONCEPT    two blocks of two features each, so a direction can be drawn:
                the same 80 samples, two subtypes; each block has a large
                spread of its own and a smaller one, carrying the subtype
                difference, shared with the other. PCA: one press, Find
                component 1. PLS: the presses mixOmics' own loop makes —
                Start (methylation's arrow anywhere), then Update mRNA and
                Update methylation in turn, each block's weights becoming the
                covariances of its features with the OTHER block's scores,
                until neither arrow turns. mixOmics starts from the SVD of
                X₁ᵀX₂, where the loop has nothing left to do; the start here is
                80° off so the rule can be seen (measured: 2–4 rounds).
     FACTORIZE  the same blocks as matrices, rows sorted by subtype: Score
                (t = Xw), Rebuild (t cᵀ, c = Xᵀt / tᵀt, mixOmics' deflation),
                Subtract (E = X − t cᵀ, where component 2 is found). Above it,
                N-integration (these blocks, side by side) against
                P-integration (drawn only: the lesson never runs it).
     DATA       the lesson's 405 training samples, Pair over the three pairs
                03 cell 13 correlates; one press fills each block's score
                strip and raises the samples into the scatter; beside it the
                two methods side by side, and each block's row of weights.

   "Kept" means one thing on every page: the share of a block that t cᵀ
   rebuilds. For PCA it is PC1's share of the variance.

   Nothing is fitted on the page for Data: data.js (generated by
   `_lab/multiomics-measure.R widget99`) holds the scores, weights and kept
   shares. The Concept blocks are simulated here; their PCA directions are
   exact 2 × 2 eigenvectors and their PLS directions the loop's end.
   ========================================================================= */

import { defineWidget, mathmlRenders } from "../core/index.js";
import { SUBTYPES, Y, BLOCKS, PAIRS } from "./data.js";

const PAGES = [{ value: "concept", label: "Concept" }, { value: "factorize", label: "Factorize" }, { value: "data", label: "Data" }];
const METHODS = [
  { value: "pca", label: "PCA", detail: "each block on its own: the direction of largest variance" },
  { value: "pls", label: "PLS", detail: "each block against the other: the directions whose scores covary most" },
];
const SHORT = { mRNA: "mRNA", meth: "meth", rppa: "RPPA" };
const PAIR_OPTS = PAIRS.map((p) => ({ value: `${p.a}-${p.b}`.toLowerCase(), label: `${SHORT[p.a]}–${SHORT[p.b]}` }));
const ON = (page) => ({ param: "page", equals: page });
const BLOCK_NAME = { mRNA: "mRNA", meth: "Methylation", rppa: "RPPA" };
const BLOCK_UNIT = { mRNA: "genes", meth: "CpG sites", rppa: "proteins" };
const N_DATA = Y.length;
const MAX_ROUNDS = 5;

/* ------------------------------------------------------------- strings */

const S = {
  subtitle:
    "Principal component analysis summarises one omics block by its direction of largest variance, which need not be related to the other blocks measured on the same samples. " +
    "Partial least squares chooses, in each block, the direction whose scores covary most with the other block's, so the two blocks' components agree. " +
    "Multi-omics integration methods such as DIABLO are built on this second kind of component.",
  pageLabel: "Step",
  methodLabel: "Method",
  pairLabel: "Pair",
  pairDetail: "two of the three blocks, measured on the same 405 samples",

  /* Concept */
  blockA: "mRNA",
  blockB: "Methylation",
  axesA: ["gene 1", "gene 2"],
  axesB: ["CpG 1", "CpG 2"],
  featA: ["gene 1", "gene 2"],
  featB: ["CpG 1", "CpG 2"],
  scores: "Scores",
  scoreX: "mRNA score t",
  scoreY: "methylation score u",
  sub: ["Subtype 1", "Subtype 2"],
  arrow: "component 1",
  before: "80 samples, each measured in both blocks.",
  caption: {
    pca: "PCA: in each block, the direction along which its samples vary most. The other block plays no part.",
    plsBefore: "PLS finds the two directions in turn, each from the other block's scores.",
    start: "Start: methylation's arrow points in an arbitrary direction. Each sample's methylation score u is its position along it.",
    updA: "Update mRNA: each gene's weight becomes its covariance with the methylation scores u, which sets mRNA's arrow and its scores t.",
    updB: "Update methylation: each CpG site's weight becomes its covariance with the mRNA scores t, which sets methylation's arrow and its scores u.",
    done: "Another round changes neither arrow: these are PLS's directions for component 1. The covariance of t and u rose with every press; their correlation need not.",
  },
  covHead: { a: "covariance with u", b: "covariance with t" },

  /* Factorize */
  nHead: ["N-integration", "the same samples, different features"],
  nNote: "these two blocks, side by side; each has its own w, and the scores are made to agree",
  pHead: ["P-integration", "the same features, different samples"],
  pNote: "studies stacked; one w for every study. Not used here",
  sameRows: "80 samples",
  sameCols: "same features",
  study: ["study 1", "study 2"],
  mX: "X", mT: "t", mC: "cᵀ", mE: "E",
  wLine: (w) => `w = (${w[0].toFixed(2)}, ${w[1].toFixed(2)})`,
  cLine: (c) => `c = (${c[0].toFixed(2)}, ${c[1].toFixed(2)})`,
  eLine: (k) => `E holds ${(100 * (1 - k)).toFixed(0)}% of X; component 2 is found there`,
  keyLow: "low value",
  keyHigh: "high value",

  /* Data */
  dims: (b) => `${BLOCK_NAME[b]}: ${N_DATA} samples × ${BLOCKS[b].features.toLocaleString("en-US")} ${BLOCK_UNIT[b]}`,
  strip: (b) => `${BLOCK_NAME[b]} component 1`,
  dataBefore: "Component 1 gives each sample one score per block.",
  table: ["", "PCA", "PLS"],
  rowR: "correlation r",
  rowKept: (name) => `${name} kept`,
  weights: (b) => `${BLOCK_NAME[b]} w: ${BLOCKS[b].features.toLocaleString("en-US")} weights`,

  /* tiles */
  tileR: "Correlation of the scores",
  tileRNote: "t and u, the two blocks' component 1",
  tileCov: "Covariance of the scores",
  tileCovNote: "what PLS makes as large as it can",
  tileKept: (b) => `${b} kept`,
  tileKeptNote: "share of the block that t cᵀ rebuilds",
  tileWait: "—",

  hovConcept: (i, g) => `sample ${i + 1} · ${g}`,
  hovData: (st, a, ta, b, tb) => `${st} · ${a} ${ta} · ${b} ${tb}`,
  hovRow: (i, g) => `sample ${i + 1} · ${g}`,
};

const plsLabel = (n) => (n === 0 ? "Start" : n % 2 === 1 ? "Update mRNA" : "Update methylation");
const plsTitle = (n) => (n === 0
  ? "Point methylation's arrow in an arbitrary direction and score the samples along it"
  : n % 2 === 1
    ? "Set each gene's weight to its covariance with the methylation scores u"
    : "Set each CpG site's weight to its covariance with the mRNA scores t");
const beats = (fn) => Object.fromEntries(Array.from({ length: 2 + 2 * MAX_ROUNDS }, (_, n) => [n, fn(n)]));
/* the loop's own press counts, so the finished button names that, not one more update (set in makeConcept) */
const PLS_LABELS = beats(plsLabel), PLS_TITLES = beats(plsTitle);

S.stepLabel = {
  param: "page",
  labels: {
    concept: { param: "method", labels: { pca: "Find component 1", pls: { anim: "beat", labels: PLS_LABELS, default: "Converged" } }, default: "Find component 1" },
    factorize: { anim: "beat", labels: { 0: "Score", 1: "Rebuild", 2: "Subtract" }, default: "Subtract" },
    data: "Find component 1",
  },
  default: "Find component 1",
};
const FIND_TITLE = {
  pca: "In each block, find the direction of largest variance and give every sample its score along it",
  pls: "In each block, find the direction whose scores covary most with the other block's, and give every sample its score along it",
};
S.stepTitle = {
  param: "page",
  labels: {
    concept: { param: "method", labels: { pca: FIND_TITLE.pca, pls: { anim: "beat", labels: PLS_TITLES, default: "Another round would change neither arrow" } }, default: FIND_TITLE.pca },
    factorize: { anim: "beat", labels: { 0: "Score each sample: t = Xw", 1: "Rebuild the block from the scores: t cᵀ, with c = Xᵀt / tᵀt", 2: "Subtract the rebuilt part: E = X − t cᵀ" }, default: "Subtract the rebuilt part: E = X − t cᵀ" },
    data: { param: "method", labels: FIND_TITLE, default: FIND_TITLE.pca },
  },
  default: FIND_TITLE.pca,
};

/* --------------------------------------------------------- formula card */

const MATHML = mathmlRenders();
const mi = (s) => `<mi>${s}</mi>`, mo = (s) => `<mo>${s}</mo>`, sub = (a, b) => `<msub><mi>${a}</mi><mn>${b}</mn></msub>`;
const supT = (s) => `<msup>${s}<mi>T</mi></msup>`, gap = (em) => `<mspace width="${em}em"/>`;
const MATH = {
  pca: {
    math: `<math display="block"><mrow>${mi("t")}${mo("=")}${mi("X")}${mi("w")}${mo(",")}${gap(1)}<munder><mo>max</mo><mrow>${mo("‖")}${mi("w")}${mo("‖")}${mo("=")}<mn>1</mn></mrow></munder>${gap(0.3)}<mtext>var</mtext>${mo("(")}${mi("t")}${mo(")")}</mrow></math>`,
    plain: "t = X w,   max over ‖w‖ = 1 of var(t)",
    note: "w is chosen within one block; the other block does not enter.",
  },
  pls: {
    math: `<math display="block"><mrow>${mi("t")}${mo("=")}${sub("X", 1)}${sub("w", 1)}${mo(",")}${gap(0.6)}${mi("u")}${mo("=")}${sub("X", 2)}${sub("w", 2)}${mo(",")}${gap(1)}<munder><mo>max</mo><mrow>${mo("‖")}${sub("w", 1)}${mo("‖")}${mo("=")}${mo("‖")}${sub("w", 2)}${mo("‖")}${mo("=")}<mn>1</mn></mrow></munder>${gap(0.3)}<mtext>cov</mtext>${mo("(")}${mi("t")}${mo(",")}${mi("u")}${mo(")")}</mrow></math>`,
    plain: "t = X₁w₁,  u = X₂w₂,   max over ‖w₁‖ = ‖w₂‖ = 1 of cov(t, u)",
    note: "One pair (w₁, w₂) for the two blocks together: the first of the components that maximise Σ cov(T₁ⱼ, T₂ⱼ).",
  },
  loop: {
    math: `<math display="block"><mrow>${sub("w", 1)}${mo("∝")}${supT(sub("X", 1))}${mi("u")}${mo(",")}${gap(1.2)}${sub("w", 2)}${mo("∝")}${supT(sub("X", 2))}${mi("t")}</mrow></math>`,
    plain: "w₁ ∝ X₁ᵀu,    w₂ ∝ X₂ᵀt",
    note: "Each block's weights are its features' covariances with the other block's scores, scaled to length 1. Repeated until neither changes, they maximise cov(t, u).",
  },
  factor: {
    math: `<math display="block"><mrow>${mi("X")}${mo("≈")}${mi("t")}${supT(mi("c"))}${mo("+")}${mi("E")}${mo(",")}${gap(1)}${mi("t")}${mo("=")}${mi("X")}${mi("w")}${mo(",")}${gap(0.6)}${mi("c")}${mo("=")}<mfrac><mrow>${supT(mi("X"))}${mi("t")}</mrow><mrow>${supT(mi("t"))}${mi("t")}</mrow></mfrac></mrow></math>`,
    plain: "X ≈ t cᵀ + E,   t = X w,   c = Xᵀt / tᵀt",
    note: "Component 2 is found in E the same way; stacking the components gives X ≈ T·Wᵀ, the scores times the loadings. For PCA, c = w.",
  },
};
let mathHost = null, mathKey = null;
function renderFormula(key) {
  if (!mathHost) {
    const figure = document.querySelector("#widget .w-figure");
    if (!figure || !figure.parentNode) return;
    mathHost = document.createElement("div");
    mathHost.className = "w-math";
    figure.parentNode.insertBefore(mathHost, figure);
  }
  if (mathKey === key) return;
  mathKey = key;
  const F = MATH[key];
  mathHost.innerHTML = `<div class="w-math-eq"><span style="color:var(--ink-2)">${MATHML ? F.math : F.plain}</span></div><div class="w-math-note">${F.note}</div>`;
}
const formulaKey = (params) => (params.page === "factorize" ? "factor" : params.page === "concept" && params.method === "pls" ? "loop" : params.method);

/* ------------------------------------------------------------- helpers */

const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
const seg = (t, a, b) => clamp((t - a) / (b - a), 0, 1);
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - ((-2 * t + 2) ** 3) / 2);
const lerp = (a, b, t) => a + (b - a) * t;
const lerpPt = (a, b, t) => [lerp(a[0], b[0], t), lerp(a[1], b[1], t)];
const mean = (v) => v.reduce((s, x) => s + x, 0) / v.length;
function corr(a, b) {
  const ma = mean(a), mb = mean(b);
  let sab = 0, saa = 0, sbb = 0;
  for (let i = 0; i < a.length; i++) { sab += (a[i] - ma) * (b[i] - mb); saa += (a[i] - ma) ** 2; sbb += (b[i] - mb) ** 2; }
  return sab / Math.sqrt(saa * sbb);
}
const f2 = (v) => v.toFixed(2);
const pct = (v) => `${(100 * v).toFixed(1)}%`;

function txt(ctx, colors, s, x, y, { size = colors.fsSm, fill = colors.ink2, align = "left", baseline = "alphabetic", weight = "" } = {}) {
  ctx.save(); ctx.font = `${weight ? weight + " " : ""}${size} ${colors.font}`; ctx.fillStyle = fill;
  ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
function line(ctx, x1, y1, x2, y2, col, w = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = w; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.restore();
}
function dot(ctx, colors, x, y, r, fill, edge = true) {
  ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.fillStyle = fill; ctx.fill();
  if (edge) { ctx.lineWidth = 1; ctx.strokeStyle = colors.surface; ctx.stroke(); }
}
function ring(ctx, x, y, r, col) {
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2); ctx.lineWidth = 2; ctx.strokeStyle = col; ctx.stroke(); ctx.restore();
}
function frame(ctx, colors, x, y, w, h, col = colors.axis) {
  ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = 1; ctx.strokeRect(x + 0.5, y + 0.5, w - 1, h - 1); ctx.restore();
}
function arrowHead(ctx, x0, y0, x1, y1, col, head) {
  const a = Math.atan2(y1 - y0, x1 - x0);
  ctx.save(); ctx.fillStyle = col; ctx.beginPath(); ctx.moveTo(x1, y1);
  ctx.lineTo(x1 - head * Math.cos(a - 0.42), y1 - head * Math.sin(a - 0.42));
  ctx.lineTo(x1 - head * Math.cos(a + 0.42), y1 - head * Math.sin(a + 0.42));
  ctx.closePath(); ctx.fill(); ctx.restore();
}
/** a component's direction has no sign: drawn double-headed, as pca's are */
function axisArrow(ctx, p0, p1, col) {
  line(ctx, p0[0], p0[1], p1[0], p1[1], col, 2.2);
  arrowHead(ctx, p0[0], p0[1], p1[0], p1[1], col, 8); arrowHead(ctx, p1[0], p1[1], p0[0], p0[1], col, 8);
}
function vText(ctx, colors, s, x, y, opts) {
  ctx.save(); ctx.translate(x, y); ctx.rotate(-Math.PI / 2); txt(ctx, colors, s, 0, 0, { align: "center", ...opts }); ctx.restore();
}
function hoverLabel(ctx, colors, str, x, y, w) {
  ctx.save(); ctx.font = `600 ${colors.fsXs} ${colors.font}`;
  const tw = ctx.measureText(str).width; ctx.restore();
  const bx = Math.max(4, Math.min(w - tw - 14, x + 10)), by = Math.max(4, y - 26);
  ctx.save(); ctx.fillStyle = colors.surface; ctx.fillRect(bx, by, tw + 10, 18);
  ctx.strokeStyle = colors.ink3; ctx.strokeRect(bx + 0.5, by + 0.5, tw + 9, 17); ctx.restore();
  txt(ctx, colors, str, bx + 5, by + 9.5, { size: colors.fsXs, fill: colors.ink1, baseline: "middle", weight: "600" });
}
const subColour = (colors, g) => colors.clusters[g];
/** words laid into lines no wider than `maxW`, `lh` apart; returns the line count */
function wrapText(ctx, colors, str, x, y, maxW, lh, opts = {}) {
  ctx.save(); ctx.font = `${opts.weight ? opts.weight + " " : ""}${opts.size ?? colors.fsSm} ${colors.font}`;
  const lines = []; let cur = "";
  for (const word of str.split(" ")) {
    const tryLine = cur ? `${cur} ${word}` : word;
    if (ctx.measureText(tryLine).width > maxW && cur) { lines.push(cur); cur = word; } else cur = tryLine;
  }
  if (cur) lines.push(cur);
  ctx.restore();
  lines.forEach((l, i) => txt(ctx, colors, l, x, y + i * lh, { fill: colors.ink2, ...opts }));
  return lines.length;
}
/* the value ramp, --c-value-low through --surface-3 to --c-value-high. A
   panel drawn in it colours nothing by identity: subtypes are ink brackets */
const hex = (c) => { const m = String(c).trim().match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : null; };
function valueColour(colors, v) {
  const t = clamp(v, -1, 1), a = hex(colors.surface3), b = hex(t < 0 ? colors.valueLow : colors.valueHigh);
  if (!a || !b) return t < 0 ? colors.valueLow : colors.valueHigh;
  return `rgb(${a.map((x, i) => Math.round(x + (b[i] - x) * Math.abs(t))).join(",")})`;
}

/** the two methods side by side, the current one framed; a column whose
   method is not found yet reads — */
function drawTrade(ctx, colors, x, y, width, method, rows, found = { pca: true, pls: true }) {
  const cw = 52, rh = 22, lw = Math.max(0, width - 2 * cw);
  const fill = (m) => (method === m ? colors.ink1 : colors.ink3);
  txt(ctx, colors, S.table[1], x + lw + cw / 2, y, { align: "center", fill: fill("pca"), weight: "600" });
  txt(ctx, colors, S.table[2], x + lw + cw * 1.5, y, { align: "center", fill: fill("pls"), weight: "600" });
  rows.forEach((r, i) => {
    const yy = y + (i + 1) * rh;
    txt(ctx, colors, r[0], x, yy, { size: colors.fsXs, fill: colors.ink2 });
    txt(ctx, colors, found.pca ? r[1] : S.tileWait, x + lw + cw / 2, yy, { align: "center", fill: fill("pca") });
    txt(ctx, colors, found.pls ? r[2] : S.tileWait, x + lw + cw * 1.5, yy, { align: "center", fill: fill("pls") });
  });
  const cx = x + lw + (method === "pca" ? 0 : cw);
  ctx.save(); ctx.strokeStyle = colors.highlight; ctx.lineWidth = 2;
  ctx.strokeRect(cx + 3.5, y - 16, cw - 6, rows.length * rh + 24); ctx.restore();
}

/* ======================================================== CONCEPT blocks */

/* Two blocks on the same samples. In each, the shared axis carries the
   subtype difference (±0.85 plus noise) and is the SMALLER spread; a private
   axis, unrelated to the other block, is the larger (sd 1.6). PCA keeps
   ~75% of each block and its scores correlate ~0.1; PLS ~30% and ~0.9. The
   angles keep the four axes apart on screen. */
const N_CONCEPT = 80;
const ANG = { a: [62, -28], b: [18, 108] };
const unitAt = (deg) => [Math.cos((deg * Math.PI) / 180), Math.sin((deg * Math.PI) / 180)];
const unit2 = (v) => { const n = Math.hypot(v[0], v[1]); return [v[0] / n, v[1] / n]; };
const rot = (v, deg) => { const c = Math.cos((deg * Math.PI) / 180), s = Math.sin((deg * Math.PI) / 180); return [c * v[0] - s * v[1], s * v[0] + c * v[1]]; };
const angleBetween = (a, b) => Math.acos(clamp(Math.abs(a[0] * b[0] + a[1] * b[1]), 0, 1)) * 180 / Math.PI;

function topEig2(a, b, d) {
  const tr = a + d, det = a * d - b * b, l = tr / 2 + Math.sqrt(Math.max(0, (tr * tr) / 4 - det));
  const v = Math.abs(b) > 1e-12 ? [l - d, b] : a >= d ? [1, 0] : [0, 1];
  return unit2(v);
}
const project = (X, d) => X.map((p) => p[0] * d[0] + p[1] * d[1]);
const flip = (d) => [-d[0], -d[1]];
/** each feature's covariance with a score vector: Xᵀs / n */
const covWith = (X, s) => [0, 1].map((j) => X.reduce((acc, p, i) => acc + p[j] * s[i], 0) / X.length);
/** the share of X that t cᵀ rebuilds, c = Xᵀt / tᵀt (mixOmics' deflation) */
function keptBy(X, t) {
  const tt = t.reduce((s, v) => s + v * v, 0), c = [0, 1].map((j) => X.reduce((s, p, i) => s + p[j] * t[i], 0) / tt);
  let e = 0, x = 0;
  X.forEach((p, i) => { for (let j = 0; j < 2; j++) { e += (p[j] - t[i] * c[j]) ** 2; x += p[j] ** 2; } });
  return { kept: 1 - e / x, c };
}

function makeConcept(rng) {
  const ua = unitAt(ANG.a[0]), va = unitAt(ANG.a[1]), ub = unitAt(ANG.b[0]), vb = unitAt(ANG.b[1]);
  const g = [], A0 = [], B0 = [];
  for (let i = 0; i < N_CONCEPT; i++) {
    const grp = i % 2;
    const s = (grp ? 0.85 : -0.85) + 0.35 * rng.normal();
    const a = 1.6 * rng.normal(), b = 1.6 * rng.normal();
    g.push(grp);
    A0.push([0, 1].map((j) => s * ua[j] + a * va[j] + 0.2 * rng.normal()));
    B0.push([0, 1].map((j) => s * ub[j] + b * vb[j] + 0.2 * rng.normal()));
  }
  const centre = (X) => { const m = [0, 1].map((j) => mean(X.map((p) => p[j]))); return X.map((p) => [p[0] - m[0], p[1] - m[1]]); };
  const A = centre(A0), B = centre(B0);
  const cross = (X, Z) => { const M = [[0, 0], [0, 0]]; X.forEach((x, i) => { for (let r = 0; r < 2; r++) for (let c = 0; c < 2; c++) M[r][c] += x[r] * Z[i][c]; }); return M; };
  const CA = cross(A, A), CB = cross(B, B);

  /* PLS: mixOmics' loop, run to its end from a start 80° off the answer.
     Signs: subtype 2 scores positive on mRNA, and the loop's start chosen so
     its end agrees, so every frame keeps one orientation. */
  const loop = (start) => {
    let w2 = start, u = project(B, w2);
    const frames = [{}, { w2, u }];
    for (let r = 0; r < 40; r++) {
      const c1 = covWith(A, u), w1 = unit2(c1), t = project(A, w1);
      const prev2 = w2;
      const c2 = covWith(B, t); w2 = unit2(c2); u = project(B, w2);
      const prev1 = frames.at(-1).w1;
      if (r < MAX_ROUNDS) {
        frames.push({ w1, t, w2: prev2, u: project(B, prev2), cov: { block: "a", v: c1 } });
        frames.push({ w1, t, w2, u, cov: { block: "b", v: c2 } });
      }
      if (prev1 && angleBetween(prev1, w1) < 0.5 && angleBetween(prev2, w2) < 0.5) break;
    }
    /* trim rounds after the arrows stopped: the press that changes nothing is the reader's to see once */
    let end = frames.length - 1;
    while (end > 4 && angleBetween(frames[end].w1, frames[end - 2].w1) < 0.5 && angleBetween(frames[end].w2, frames[end - 2].w2) < 0.5) end -= 2;
    return frames.slice(0, end + 1);
  };
  let frames = loop([0, 1]);
  const fin = frames.at(-1);
  let start = unit2(rot(fin.w2, 80));
  frames = loop(start);
  if (mean(frames.at(-1).t.filter((_, i) => g[i])) < 0) { start = flip(start); frames = loop(start); }
  const pls = { w1: frames.at(-1).w1, w2: frames.at(-1).w2 };
  for (let n = frames.length - 1; n < 2 + 2 * MAX_ROUNDS; n++) { PLS_LABELS[n] = "Converged"; PLS_TITLES[n] = "Another round would change neither arrow"; }

  let pa = topEig2(CA[0][0], CA[0][1], CA[1][1]), pb = topEig2(CB[0][0], CB[0][1], CB[1][1]);
  if (pa[0] * pls.w1[0] + pa[1] * pls.w1[1] < 0) pa = flip(pa);
  if (corr(project(A, pa), project(B, pb)) < 0) pb = flip(pb);

  const finish = (f) => {
    if (f.w1) { const k = keptBy(A, f.t); f.keptA = k.kept; f.cA = k.c; }
    if (f.w2) { const k = keptBy(B, f.u); f.keptB = k.kept; f.cB = k.c; }
    if (f.t && f.u) { f.r = corr(f.t, f.u); f.cv = f.t.reduce((acc, v, i) => acc + v * f.u[i], 0) / f.t.length; }
    return f;
  };
  const pcaFrames = [{}, { w1: pa, t: project(A, pa), w2: pb, u: project(B, pb) }].map(finish);
  frames = frames.map(finish);
  const span = 1.08 * Math.max(...A.flat().map(Math.abs), ...B.flat().map(Math.abs));
  const all = [...pcaFrames, ...frames].filter((f) => f.t || f.u).flatMap((f) => [...(f.t ?? []), ...(f.u ?? [])]);
  const sspan = 1.08 * Math.max(...all.map(Math.abs));
  const order = [...A.keys()].sort((i, j) => g[i] - g[j] || i - j);
  return { g, A, B, frames: { pca: pcaFrames, pls: frames }, span, sspan, order };
}
const finalOf = (st, m) => st.frames[m].at(-1);

/* --------------------------------------------------------- Concept layout *
 * Two rows at every width: the two blocks side by side, the scores under the
 * first with the caption beside it. Three across shrank each panel to 88px in
 * the harness's 550px canvas (draft, 2026-10-10).                           */
const C = { top: 26, padL: 30, gap: 44, padR: 10, sMax: 220, rowGap: 58 };
function conceptLayout(w) {
  const s = Math.floor(Math.min(C.sMax, (w - C.padL - C.padR - C.gap) / 2));
  const x0 = C.padL, x1 = x0 + s + C.gap, y1 = C.top + s + C.rowGap;
  return { s, panels: [{ x: x0, y: C.top, s }, { x: x1, y: C.top, s }, { x: x0, y: y1, s }], text: { x: x1, y: y1 - 18, w: Math.max(120, w - x1 - C.padR) } };
}
const H_CONCEPT = C.top + 2 * C.sMax + C.rowGap + 30;

/** pixel positions of every mark in one frame of the Concept page */
function conceptMarks(L, st, F) {
  const [PA, PB, PS] = L.panels;
  const toPx = (P, span, x, y) => [P.x + P.s / 2 + (x / span) * (P.s / 2), P.y + P.s / 2 - (y / span) * (P.s / 2)];
  const R = 0.92 * st.span;
  const arrowOf = (P, d) => (d ? [toPx(P, st.span, -R * d[0], -R * d[1]), toPx(P, st.span, R * d[0], R * d[1])] : null);
  const feetOf = (P, X, d) => (d ? X.map((p) => { const t = p[0] * d[0] + p[1] * d[1]; return toPx(P, st.span, t * d[0], t * d[1]); }) : null);
  return {
    arrowA: arrowOf(PA, F.w1), arrowB: arrowOf(PB, F.w2),
    feetA: feetOf(PA, st.A, F.w1), feetB: feetOf(PB, st.B, F.w2),
    scores: F.t && F.u ? F.t.map((t, k) => toPx(PS, st.sspan, t, F.u[k])) : null,
  };
}
/** an axis turns the short way: it has no sign, so a half-turn is no turn */
function blendAxis(a, b, t) {
  const c = lerpPt(a[0], a[1], 0.5), L = Math.hypot(b[1][0] - b[0][0], b[1][1] - b[0][1]) / 2;
  const a0 = Math.atan2(a[1][1] - a[0][1], a[1][0] - a[0][0]), a1 = Math.atan2(b[1][1] - b[0][1], b[1][0] - b[0][0]);
  let d = a1 - a0;
  while (d > Math.PI / 2) d -= Math.PI;
  while (d < -Math.PI / 2) d += Math.PI;
  const ang = a0 + d * t;
  return [[c[0] - L * Math.cos(ang), c[1] - L * Math.sin(ang)], [c[0] + L * Math.cos(ang), c[1] + L * Math.sin(ang)]];
}

/* One press moves the page from frame k−1 to frame k, in two moves, never
   overlapping (tweens-move-in-lanes): an arrow that exists turns (0–0.45),
   then the feet slide along their perpendiculars and the scores move to
   their new places (0.45–1). An arrow that did not exist appears at once and
   its samples drop onto it; scores that did not exist appear at 0.8. */
function drawConcept(ctx, colors, w, params, st, anim, pointer) {
  const L = conceptLayout(w), [PA, PB, PS] = L.panels;
  const stage = stageOf(params), frames = st.frames[params.method];
  const k = anim.n[stage] ?? 0, p = inFlight(anim, stage);
  const cur = frames[Math.min(k, frames.length - 1)], prev = p != null && k > 0 ? frames[k - 1] : null;
  const toPx = (P, x, y) => [P.x + P.s / 2 + (x / st.span) * (P.s / 2), P.y + P.s / 2 - (y / st.span) * (P.s / 2)];
  let M = conceptMarks(L, st, cur);
  const turn = p != null ? ease(seg(p, 0, 0.45)) : 1, slide = p != null ? ease(seg(p, 0.45, 1)) : 1;
  const ez = ezOf(anim, "concept");
  if (ez) {
    /* a switch of Method between two finished readings eases from the one it leaves */
    const from = conceptMarks(L, st, finalOf(st, ez.params.method)), e = ease(ez.t);
    M = {
      arrowA: blendAxis(from.arrowA, M.arrowA, e), arrowB: blendAxis(from.arrowB, M.arrowB, e),
      feetA: M.feetA.map((q, i) => lerpPt(from.feetA[i], q, e)), feetB: M.feetB.map((q, i) => lerpPt(from.feetB[i], q, e)),
      scores: M.scores.map((q, i) => lerpPt(from.scores[i], q, e)),
    };
  }
  const P0 = prev ? conceptMarks(L, st, prev) : null;

  [[PA, S.blockA, S.axesA], [PB, S.blockB, S.axesB], [PS, S.scores, [S.scoreX, S.scoreY]]].forEach(([P, name, ax]) => {
    txt(ctx, colors, name, P.x, P.y - 10, { fill: colors.ink1, weight: "600" });
    frame(ctx, colors, P.x, P.y, P.s, P.s);
    txt(ctx, colors, ax[0], P.x + P.s / 2, P.y + P.s + 15, { size: colors.fsXs, fill: colors.ink3, align: "center" });
    vText(ctx, colors, ax[1], P.x - 8, P.y + P.s / 2, { size: colors.fsXs, fill: colors.ink3 });
  });

  const arrowNow = (key) => (M[key] && P0 && P0[key] ? blendAxis(P0[key], M[key], turn) : M[key]);
  ["arrowA", "arrowB"].forEach((key) => { const a = arrowNow(key); if (a) axisArrow(ctx, a[0], a[1], colors.highlight); });

  const scoresNow = M.scores && P0?.scores ? M.scores.map((q, i) => lerpPt(P0.scores[i], q, slide)) : M.scores;
  const scoresOn = !!M.scores && (P0?.scores || p == null || p >= 0.8);

  [[PA, st.A, "feetA"], [PB, st.B, "feetB"]].forEach(([P, X, key]) => {
    X.forEach((pt, i) => {
      const [x, y] = toPx(P, pt[0], pt[1]);
      if (M[key]) {
        let foot = M[key][i];
        if (P0 && P0[key]) foot = lerpPt(P0[key][i], foot, slide);
        else if (p != null) { const drop = ease(seg(p, 0.1, 0.8)); const fx = lerp(x, foot[0], drop), fy = lerp(y, foot[1], drop); if (drop < 1) line(ctx, x, y, fx, fy, colors.ink3, 1); foot = [fx, fy]; }
        dot(ctx, colors, foot[0], foot[1], 2.6, subColour(colors, st.g[i]), false);
      }
      dot(ctx, colors, x, y, 4, subColour(colors, st.g[i]));
    });
  });
  if (scoresOn) {
    scoresNow.forEach((q, i) => dot(ctx, colors, q[0], q[1], 4, subColour(colors, st.g[i])));
    const r = P0?.scores && p != null ? lerp(prev.r, cur.r, slide) : cur.r;
    const cv = P0?.scores && p != null ? lerp(prev.cv, cur.cv, slide) : cur.cv;
    txt(ctx, colors, `r = ${f2(r)}`, PS.x + PS.s - 6, PS.y + 16, { fill: colors.ink1, align: "right", weight: "600" });
    txt(ctx, colors, `cov = ${f2(cv)}`, PS.x + PS.s - 6, PS.y + 32, { fill: colors.ink2, align: "right" });
  }

  /* the text beside the scores: what this press did, its covariances, and once done the two methods side by side */
  const T = L.text, done = k >= frames.length - 1;
  let cap;
  if (params.method === "pca") cap = k === 0 ? S.before : S.caption.pca;
  else cap = k === 0 ? `${S.before} ${S.caption.plsBefore}` : done ? S.caption.done : k === 1 ? S.caption.start : k % 2 === 0 ? S.caption.updA : S.caption.updB;
  const nl = wrapText(ctx, colors, cap, T.x, T.y, T.w, 17);
  if (params.method === "pls" && cur.cov && !done) drawCov(ctx, colors, T.x, T.y + nl * 17 + 14, T.w, cur.cov);
  const found = { pca: (anim.n["concept-pca"] ?? 0) >= 1, pls: (anim.n["concept-pls"] ?? 0) >= st.frames.pls.length - 1 };
  if (found.pca || found.pls) {
    const FP = finalOf(st, "pca"), FL = finalOf(st, "pls");
    drawTrade(ctx, colors, T.x, PS.y + PS.s - 66, T.w, params.method,
      [[S.rowR, f2(FP.r), f2(FL.r)], [S.rowKept(S.blockA), pct(FP.keptA), pct(FL.keptA)], [S.rowKept(S.blockB), pct(FP.keptB), pct(FL.keptB)]], found);
  }

  /* pointer: the nearest sample in any panel, ringed in all three */
  if (pointer) {
    let hov = -1, best = 81;
    const tryPts = (pts) => pts.forEach((q, i) => { const d = (q[0] - pointer.x) ** 2 + (q[1] - pointer.y) ** 2; if (d < best) { best = d; hov = i; } });
    tryPts(st.A.map((q) => toPx(PA, q[0], q[1])));
    tryPts(st.B.map((q) => toPx(PB, q[0], q[1])));
    if (scoresOn && p == null) tryPts(scoresNow);
    if (hov >= 0) {
      [toPx(PA, ...st.A[hov]), toPx(PB, ...st.B[hov])].concat(scoresOn && p == null ? [scoresNow[hov]] : []).forEach((q) => ring(ctx, q[0], q[1], 7, colors.ink1));
      hoverLabel(ctx, colors, S.hovConcept(hov, S.sub[st.g[hov]]), pointer.x, pointer.y, w);
    }
  }
}

/** the covariance of each feature with the other block's scores: the two numbers that set the arrow */
function drawCov(ctx, colors, x, y, width, cov) {
  const names = cov.block === "a" ? S.featA : S.featB;
  txt(ctx, colors, S.covHead[cov.block], x, y, { size: colors.fsXs, fill: colors.ink1, weight: "600" });
  /* zero in the middle of the bar area, so a negative covariance never runs into its label */
  const m = Math.max(...cov.v.map(Math.abs)) || 1, bw = Math.min(110, width - 110), cx = x + 56 + bw / 2;
  cov.v.forEach((v, i) => {
    const yy = y + 8 + i * 18;
    txt(ctx, colors, names[i], x, yy + 10, { size: colors.fsXs });
    line(ctx, cx, yy, cx, yy + 13, colors.axis);
    ctx.save(); ctx.fillStyle = colors.ink2; ctx.fillRect(v >= 0 ? cx : cx + (v / m) * (bw / 2), yy + 2, Math.abs(v / m) * (bw / 2), 10); ctx.restore();
    txt(ctx, colors, f2(v), x + 56 + bw + 8, yy + 10, { size: colors.fsXs, fill: colors.ink1 });
  });
}

/* ========================================================= FACTORIZE page */

/* The Concept blocks as matrices, 80 rows sorted by subtype (ink brackets:
   a panel coloured by value colours nothing by identity), each with its
   score column, its two loadings and its remainder. Above, the two ways
   01 cell 2 lines matrices up: N, these blocks; P, drawn only. */
const F = { top: 8, band: 138, mTop: 186, rh: 3, cw: 15 };
const H_FACTOR = F.mTop + 80 * F.rh + 58;

function drawFactorize(ctx, colors, w, params, st, anim, pointer) {
  const n = shownStep(anim, "factorize");
  const fin = finalOf(st, params.method);
  /* the band: N, these blocks; P, the contrast, drawn only */
  const half = (w - 30) / 2, nx = 10, px = nx + half + 20, by = F.top + 44, bh = 40;
  txt(ctx, colors, S.nHead[0], nx, F.top + 12, { fill: colors.ink1, weight: "600" });
  txt(ctx, colors, S.nHead[1], nx, F.top + 28, { size: colors.fsXs, fill: colors.ink2 });
  txt(ctx, colors, S.pHead[0], px, F.top + 12, { fill: colors.ink3, weight: "600" });
  txt(ctx, colors, S.pHead[1], px, F.top + 28, { size: colors.fsXs, fill: colors.ink3 });
  const bw = Math.min(64, (half - 90) / 2);
  txt(ctx, colors, S.sameRows, nx, by + bh / 2 + 4, { size: colors.fsXs, fill: colors.ink3 });
  const nb = nx + 76;
  const bw2 = Math.max(bw, 76);
  frame(ctx, colors, nb, by, bw, bh, colors.ink2); frame(ctx, colors, nb + bw, by, bw2, bh, colors.ink2);
  txt(ctx, colors, S.blockA, nb + bw / 2, by + bh / 2 + 4, { align: "center", size: colors.fsXs, fill: colors.ink1 });
  txt(ctx, colors, S.blockB, nb + bw + bw2 / 2, by + bh / 2 + 4, { align: "center", size: colors.fsXs, fill: colors.ink1 });
  wrapText(ctx, colors, S.nNote, nx, by + bh + 18, half, 14, { size: colors.fsXs });
  frame(ctx, colors, px, by - 6, 2 * bw, bh / 2 + 3, colors.ink3); frame(ctx, colors, px, by + bh / 2 - 3, 2 * bw, bh / 2 + 3, colors.ink3);
  txt(ctx, colors, S.study[0], px + bw, by + bh / 4 + 2, { align: "center", size: colors.fsXs, fill: colors.ink3 });
  txt(ctx, colors, S.study[1], px + bw, by + bh * 0.75 + 2, { align: "center", size: colors.fsXs, fill: colors.ink3 });
  txt(ctx, colors, S.sameCols, px + 2 * bw + 8, by + bh / 2 + 4, { size: colors.fsXs, fill: colors.ink3 });
  wrapText(ctx, colors, S.pNote, px, by + bh + 18, half, 14, { size: colors.fsXs, fill: colors.ink3 });
  line(ctx, 10, F.band, w - 10, F.band, colors.grid);

  /* the matrices */
  const blocks = [
    { X: st.A, t: fin.t, wv: fin.w1, c: fin.cA, kept: fin.keptA, name: S.blockA },
    { X: st.B, t: fin.u, wv: fin.w2, c: fin.cB, kept: fin.keptB, name: S.blockB },
  ];
  const y0 = F.mTop, rh = F.rh, cw = F.cw, H = 80 * rh;
  const colW = (w - 20) / 2;
  let hovRow = -1;
  blocks.forEach((B, bi) => {
    const x0 = 10 + bi * colW + 26;
    const m = Math.max(...B.X.flat().map(Math.abs)), tm = Math.max(...B.t.map(Math.abs)), cm = Math.max(...B.c.map(Math.abs));
    const xs = { X: x0, t: x0 + 2 * cw + 26, c: x0 + 3 * cw + 34, E: x0 + 5 * cw + 60 };
    txt(ctx, colors, B.name, x0 - 20, y0 - 30, { fill: colors.ink1, weight: "600" });
    const column = (x, vals, scale) => vals.forEach((v, r) => { ctx.fillStyle = valueColour(colors, v / scale); ctx.fillRect(x, y0 + r * rh, cw, rh); });
    st.order.forEach((i, r) => { for (let j = 0; j < 2; j++) { ctx.fillStyle = valueColour(colors, B.X[i][j] / m); ctx.fillRect(xs.X + j * cw, y0 + r * rh, cw, rh); } });
    frame(ctx, colors, xs.X, y0, 2 * cw, H);
    txt(ctx, colors, S.mX, xs.X + cw, y0 - 8, { align: "center", fill: colors.ink1, weight: "600" });
    /* subtype brackets, ink */
    [0, 1].forEach((g) => {
      const ra = st.order.findIndex((i) => st.g[i] === g), rb = ra + st.order.filter((i) => st.g[i] === g).length;
      line(ctx, x0 - 6, y0 + ra * rh + 2, x0 - 6, y0 + rb * rh - 2, colors.ink2, 1.5);
      vText(ctx, colors, S.sub[g], x0 - 12, y0 + ((ra + rb) / 2) * rh, { size: colors.fsXs, fill: colors.ink2 });
    });
    if (n >= 1) {
      txt(ctx, colors, S.wLine(B.wv), x0 - 20, y0 + H + 16, { size: colors.fsXs, fill: colors.ink2 });
      column(xs.t, st.order.map((i) => B.t[i]), tm);
      frame(ctx, colors, xs.t, y0, cw, H);
      txt(ctx, colors, S.mT, xs.t + cw / 2, y0 - 8, { align: "center", fill: colors.ink1, weight: "600" });
    }
    if (n >= 2) {
      txt(ctx, colors, "≈", xs.t - 13, y0 + H / 2 + 5, { align: "center", fill: colors.ink1, size: colors.fsMd });
      for (let j = 0; j < 2; j++) { ctx.fillStyle = valueColour(colors, B.c[j] / cm); ctx.fillRect(xs.c + j * cw, y0, cw - 1, cw - 1); }
      frame(ctx, colors, xs.c, y0, 2 * cw, cw);
      txt(ctx, colors, S.mC, xs.c + cw, y0 - 8, { align: "center", fill: colors.ink1, weight: "600" });
      txt(ctx, colors, S.cLine(B.c), x0 - 20, y0 + H + 31, { size: colors.fsXs, fill: colors.ink2 });
    }
    if (n >= 3) {
      txt(ctx, colors, "+", xs.E - 14, y0 + H / 2 + 5, { align: "center", fill: colors.ink1, size: colors.fsMd });
      st.order.forEach((i, r) => { for (let j = 0; j < 2; j++) { ctx.fillStyle = valueColour(colors, (B.X[i][j] - B.t[i] * B.c[j]) / m); ctx.fillRect(xs.E + j * cw, y0 + r * rh, cw, rh); } });
      frame(ctx, colors, xs.E, y0, 2 * cw, H);
      txt(ctx, colors, S.mE, xs.E + cw, y0 - 8, { align: "center", fill: colors.ink1, weight: "600" });
      wrapText(ctx, colors, S.eLine(B.kept), x0 - 20, y0 + H + 46, colW - 16, 14, { size: colors.fsXs });
    }
    if (pointer && pointer.x >= x0 && pointer.x <= x0 + colW - 30 && pointer.y >= y0 && pointer.y < y0 + H) hovRow = Math.floor((pointer.y - y0) / rh);
  });
  if (hovRow >= 0) {
    const i = st.order[hovRow];
    line(ctx, 10, y0 + hovRow * rh + rh / 2, w - 10, y0 + hovRow * rh + rh / 2, colors.ink1, 1, [2, 3]);
    hoverLabel(ctx, colors, S.hovRow(i, S.sub[st.g[i]]), pointer.x, pointer.y, w);
  }
}

/* =========================================================== DATA page */

const pairOf = (key) => PAIRS.find((p) => `${p.a}-${p.b}`.toLowerCase() === key);
/** one reading of the Data page: the two score vectors, PCA's oriented to agree with PLS's */
const DATA_VIEW = {};
function dataView(pairKey, method) {
  const k = `${pairKey}|${method}`;
  if (DATA_VIEW[k]) return DATA_VIEW[k];
  const P = pairOf(pairKey);
  let t = P.t, u = P.u, keptA = P.keptA, keptB = P.keptB, wA = P.wA, wB = P.wB, topA = P.topA, topB = P.topB;
  if (method === "pca") {
    t = BLOCKS[P.a].pc1; u = BLOCKS[P.b].pc1; keptA = BLOCKS[P.a].kept; keptB = BLOCKS[P.b].kept;
    wA = BLOCKS[P.a].w; wB = BLOCKS[P.b].w; topA = BLOCKS[P.a].top; topB = BLOCKS[P.b].top;
    /* a component has no sign: turned so the two scores correlate positively, as PLS's do */
    if (corr(t, u) < 0) { u = u.map((x) => -x); wB = wB.map((x) => -x); topB = { name: topB.name, value: topB.value.map((x) => -x) }; }
  }
  const xs = 1.08 * Math.max(...BLOCKS[P.a].pc1.map(Math.abs), ...P.t.map(Math.abs));
  const ys = 1.08 * Math.max(...BLOCKS[P.b].pc1.map(Math.abs), ...P.u.map(Math.abs));
  DATA_VIEW[k] = { P, t, u, keptA, keptB, wA, wB, topA, topB, r: corr(t, u), xs, ys };
  return DATA_VIEW[k];
}

const D = { top: 34, x0: 66, sMax: 260, strip: 22, gapStrip: 8 };
function dataLayout(w) {
  const s = Math.min(D.sMax, Math.floor(w - D.x0 - 240));
  return { s, x: D.x0, y: D.top, side: D.x0 + s + 34 };
}
const H_DATA = D.top + D.sMax + D.gapStrip + D.strip + 40;

function dataMarks(L, V) {
  const sx = (v) => L.x + L.s / 2 + (v / V.xs) * (L.s / 2), sy = (v) => L.y + L.s / 2 - (v / V.ys) * (L.s / 2);
  const stripY = L.y + L.s + D.gapStrip + D.strip / 2, stripX = L.x - D.gapStrip - D.strip / 2;
  return {
    pts: V.t.map((t, k) => [sx(t), sy(V.u[k])]),
    bottom: V.t.map((t) => [sx(t), stripY]),
    left: V.u.map((u) => [stripX, sy(u)]),
  };
}

/** a block's weights as one row of cells, thousands wide, and its largest named */
function drawWeights(ctx, colors, x, y, width, b, wv, top) {
  txt(ctx, colors, S.weights(b), x, y, { size: colors.fsXs, fill: colors.ink1, weight: "600" });
  /* scaled by three standard deviations, not the largest: a few large weights would leave the row grey */
  const m = 3 * Math.sqrt(wv.reduce((s, v) => s + v * v, 0) / wv.length) || 1, cw = width / wv.length;
  for (let j = 0; j < wv.length; j++) { ctx.fillStyle = valueColour(colors, wv[j] / m); ctx.fillRect(x + j * cw, y + 6, Math.max(cw, 0.6), 10); }
  frame(ctx, colors, x, y + 6, width, 10);
  top.name.slice(0, 3).forEach((nm, i) => txt(ctx, colors, `${nm}  ${top.value[i] > 0 ? "+" : ""}${top.value[i].toFixed(3)}`, x, y + 30 + i * 13, { size: colors.fsXs, fill: colors.ink2 }));
}

function drawData(ctx, colors, w, params, anim, pointer) {
  const L = dataLayout(w), V = dataView(params.pair, params.method), P = V.P;
  const beat = shownStep(anim, "data"), t = inFlight(anim, "data");
  const found = beat >= 1 || t != null;
  const rise = t != null ? ease(seg(t, 0.15, 1)) : 1;
  const ez = ezOf(anim, "data");
  const to = dataMarks(L, V);
  const from = ez ? dataMarks(L, dataView(ez.params.pair, ez.params.method)) : null;
  const e = ez ? ease(ez.t) : 1;
  const at = (key, i) => (from ? lerpPt(from[key][i], to[key][i], e) : to[key][i]);

  txt(ctx, colors, S.dims(P.a), L.x - D.gapStrip - D.strip, 14, { fill: colors.ink2 });
  txt(ctx, colors, S.dims(P.b), L.x - D.gapStrip - D.strip, 28, { fill: colors.ink2 });

  frame(ctx, colors, L.x, L.y + 4, L.s, L.s - 4);
  frame(ctx, colors, L.x, L.y + L.s + D.gapStrip, L.s, D.strip);
  frame(ctx, colors, L.x - D.gapStrip - D.strip, L.y + 4, D.strip, L.s - 4);
  txt(ctx, colors, S.strip(P.a), L.x + L.s / 2, L.y + L.s + D.gapStrip + D.strip + 15, { size: colors.fsXs, fill: colors.ink3, align: "center" });
  vText(ctx, colors, S.strip(P.b), L.x - D.gapStrip - D.strip - 8, L.y + L.s / 2, { size: colors.fsXs, fill: colors.ink3 });

  if (!found) {
    txt(ctx, colors, S.dataBefore, L.x + L.s / 2, L.y + L.s / 2, { fill: colors.ink3, align: "center", baseline: "middle" });
  } else {
    /* the strips appear at once with the press; the samples rise out of the
       bottom strip to their places, each in its own vertical lane */
    for (let i = 0; i < N_DATA; i++) {
      const col = subColour(colors, Y[i]);
      const b = at("bottom", i), l = at("left", i);
      dot(ctx, colors, b[0], b[1] + ((i % 5) - 2) * 3, 1.8, col, false);
      dot(ctx, colors, l[0] + ((i % 5) - 2) * 3, l[1], 1.8, col, false);
    }
    for (let i = 0; i < N_DATA; i++) {
      const q = at("pts", i), b = at("bottom", i);
      const y = lerp(b[1], q[1], rise);
      if (y > L.y + L.s && rise < 1) continue;
      dot(ctx, colors, q[0], y, 3, subColour(colors, Y[i]));
    }
    if (rise >= 1) txt(ctx, colors, `r = ${f2(V.r)}`, L.x + L.s - 6, L.y + 20, { fill: colors.ink1, align: "right", weight: "600" });
  }

  /* beside it: the two methods side by side, then each block's row of weights */
  if (found && rise >= 1) {
    const VP = dataView(params.pair, "pca"), VL = dataView(params.pair, "pls"), width = w - L.side - 4;
    drawTrade(ctx, colors, L.side, L.y + 30, width, params.method, [
      [S.rowR, f2(VP.r), f2(VL.r)], [S.rowKept(BLOCK_NAME[P.a]), pct(VP.keptA), pct(VL.keptA)], [S.rowKept(BLOCK_NAME[P.b]), pct(VP.keptB), pct(VL.keptB)]]);
    drawWeights(ctx, colors, L.side, L.y + 150, width, P.a, V.wA, V.topA);
    drawWeights(ctx, colors, L.side, L.y + 228, width, P.b, V.wB, V.topB);
  }

  if (pointer && found && rise >= 1) {
    let hov = -1, best = 64;
    to.pts.forEach((q, i) => { const d = (q[0] - pointer.x) ** 2 + (q[1] - pointer.y) ** 2; if (d < best) { best = d; hov = i; } });
    if (hov >= 0) {
      ring(ctx, to.pts[hov][0], to.pts[hov][1], 6, colors.ink1);
      hoverLabel(ctx, colors, S.hovData(SUBTYPES[Y[hov]], BLOCK_NAME[P.a], f2(V.t[hov]), BLOCK_NAME[P.b], f2(V.u[hov])), pointer.x, pointer.y, w);
    }
  }
}

/* ==================================================== stages and easing */

/* Concept keeps one progress per Method: PLS's presses are its own loop,
   and a reader switching to PCA mid-loop finds PCA where they left it. */
const stageOf = (params) => (params.page === "concept" ? `concept-${params.method}` : params.page);
const stepsOf = (stage, st) => (stage === "concept-pls" ? st.concept.frames.pls.length - 1 : stage === "factorize" ? 3 : 1);
const durOf = (stage) => (stage === "factorize" ? 450 : stage === "data" ? 1600 : 1400);
const EASE_MS = 900;
const shownStep = (anim, stage) => (anim.n[stage] ?? 0) - (anim.stage === stage && anim.t < 1 ? 1 : 0);
const inFlight = (anim, stage) => (anim.stage === stage && anim.t < 1 ? anim.t : null);
const ezOf = (anim, page) => (anim.ez && anim.ez.page === page && anim.ez.t < 1 ? anim.ez : null);
const complete = (anim, stage, st) => (anim.n[stage] ?? 0) >= stepsOf(stage, st);

/* ------------------------------------------------------------- widget */

defineWidget({
  slug: "shared-components",
  status: "draft",
  title: "Multi-omics: Shared Components",
  subtitle: S.subtitle,
  credit: "Data: TCGA Research Network (PanCanAtlas UCEC), via cBioPortal",
  layout: "side",
  height: (params) => (params.page === "concept" ? H_CONCEPT : params.page === "factorize" ? H_FACTOR : H_DATA),
  pointer: true,

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "concept", display: true },
    pair: { type: "segmented", label: S.pairLabel, detail: S.pairDetail, options: PAIR_OPTS, default: PAIR_OPTS[0].value, display: true, when: ON("data") },
    method: { type: "segmented", label: S.methodLabel, options: METHODS, default: "pca", display: true },
    /* authoring escape hatch, first render only: presses already made on the page the link opens */
    shown: { type: "int", min: 0, max: 1 + 2 * MAX_ROUNDS, default: 0, hidden: true },
  },

  legend: ({ params }) => (params.page === "concept"
    ? [
      { token: "cluster-a", label: S.sub[0], mark: "dot" },
      { token: "cluster-b", label: S.sub[1], mark: "dot" },
      { token: "highlight", label: S.arrow, mark: "line" },
    ]
    : params.page === "factorize"
      ? [{ token: "value-low", label: S.keyLow, mark: "bar" }, { token: "value-high", label: S.keyHigh, mark: "bar" }]
      : SUBTYPES.map((s, i) => ({ token: `cluster-${"abcd"[i]}`, label: s, mark: "dot" }))),

  compute: ({ rng }) => ({ concept: makeConcept(rng) }),

  animation: {
    stepLabel: S.stepLabel,
    stepTitle: S.stepTitle,
    /* each press is read once: Step alone (play-only-for-motion-or-repetition) */
    runLabel: null,

    init: ({ params, state, fromScratch }) => {
      const stage = stageOf(params);
      const anim = { stage, n: {}, t: 1, dur: durOf(stage), halt: false, ez: null, last: { ...params } };
      anim.n[stage] = fromScratch ? 0 : clamp(Number(params.shown) || 0, 0, stepsOf(stage, state));
      anim.beat = anim.n[stage];
      anim.done = complete(anim, stage, state);
      return anim;
    },

    advance: (anim, { dt, state }) => {
      /* a press a page switch interrupted ends here, before the new page's (mid-press-page-switch) */
      if (anim.halt) { anim.halt = false; return false; }
      const stage = anim.stage;
      if (anim.ez && anim.ez.t < 1) anim.ez.t = Math.min(1, anim.ez.t + dt / EASE_MS);
      /* an ease core started runs the press in flight on with it, and never starts a new one */
      if (anim.mode === "ease") {
        if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
        anim.done = complete(anim, stage, state) && anim.t >= 1;
        return anim.t < 1 || (anim.ez != null && anim.ez.t < 1);
      }
      if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
      else if ((anim.n[stage] ?? 0) < stepsOf(stage, state)) {
        anim.n[stage] = (anim.n[stage] ?? 0) + 1;
        anim.dur = durOf(stage);
        anim.t = 0;
      }
      anim.beat = anim.n[stage] ?? 0;
      anim.done = complete(anim, stage, state) && anim.t >= 1;
      if (anim.t >= 1 && anim.ez) anim.ez.t = 1;
      return anim.t < 1;
    },

    rebuild: (anim, { params, state }) => {
      const stage = stageOf(params), was = anim.stage;
      /* only a change of stage ends a press in flight (mid-press-page-switch) */
      if (stage !== was && anim.t < 1) { anim.t = 1; anim.halt = true; }
      /* eases from the reading the rail left: on Data once a component is
         found, on Concept between two finished Methods */
      const samePage = params.page === anim.last.page;
      const eases = samePage && (
        (params.page === "data" && complete(anim, "data", state) && (params.method !== anim.last.method || params.pair !== anim.last.pair)) ||
        (params.page === "concept" && stage !== was && complete(anim, was, state) && complete(anim, stage, state)));
      if (eases) { anim.ez = { page: params.page, params: { ...anim.last }, t: 0 }; anim.easing = true; }
      else if (!samePage || stage !== was) anim.ez = null;
      anim.last = { ...params };
      anim.stage = stage;
      anim.beat = anim.n[stage] ?? 0;
      anim.done = complete(anim, stage, state) && anim.t >= 1;
    },
  },

  draw({ ctx, colors, w, params, state, anim, pointer }) {
    renderFormula(formulaKey(params));
    if (params.page === "concept") drawConcept(ctx, colors, w, params, state.concept, anim, pointer);
    else if (params.page === "factorize") drawFactorize(ctx, colors, w, params, state.concept, anim, pointer);
    else drawData(ctx, colors, w, params, anim, pointer);
  },

  readout({ params, state, anim }) {
    const stage = stageOf(params);
    if (params.page === "concept") {
      const frames = state.concept.frames[params.method], F0 = frames[Math.min(shownStep(anim, stage), frames.length - 1)];
      return [
        { label: S.tileR, value: F0.r != null ? f2(F0.r) : S.tileWait, note: S.tileRNote },
        { label: S.tileCov, value: F0.cv != null ? f2(F0.cv) : S.tileWait, note: S.tileCovNote },
        { label: S.tileKept(S.blockA), value: F0.keptA != null ? pct(F0.keptA) : S.tileWait, note: S.tileKeptNote },
        { label: S.tileKept(S.blockB), value: F0.keptB != null ? pct(F0.keptB) : S.tileWait, note: S.tileKeptNote },
      ];
    }
    if (params.page === "factorize") {
      const n = shownStep(anim, stage), fin = finalOf(state.concept, params.method);
      return [
        { label: S.tileR, value: n >= 1 ? f2(fin.r) : S.tileWait, note: S.tileRNote },
        { label: S.tileKept(S.blockA), value: n >= 2 ? pct(fin.keptA) : S.tileWait, note: S.tileKeptNote },
        { label: S.tileKept(S.blockB), value: n >= 2 ? pct(fin.keptB) : S.tileWait, note: S.tileKeptNote },
      ];
    }
    const on = shownStep(anim, stage) >= 1, V = dataView(params.pair, params.method);
    return [
      { label: S.tileR, value: on ? f2(V.r) : S.tileWait, note: S.tileRNote },
      { label: S.tileKept(BLOCK_NAME[V.P.a]), value: on ? pct(V.keptA) : S.tileWait, note: S.tileKeptNote },
      { label: S.tileKept(BLOCK_NAME[V.P.b]), value: on ? pct(V.keptB) : S.tileWait, note: S.tileKeptNote },
    ];
  },

  summary({ params, state, anim }) {
    const stage = stageOf(params), n = shownStep(anim, stage);
    if (params.page === "concept") {
      const frames = state.concept.frames[params.method], F0 = frames[Math.min(n, frames.length - 1)];
      return `Two simulated blocks of two features, 80 samples in two subtypes. ${params.method.toUpperCase()}, ${n} of ${frames.length - 1} presses${F0.r != null ? `; the scores correlate ${f2(F0.r)}` : ""}.`;
    }
    if (params.page === "factorize") return `The two simulated blocks as matrices, ${params.method.toUpperCase()} component 1: ${["nothing yet", "the scores t", "t cᵀ rebuilding each block", "the remainder E"][n]}.`;
    const V = dataView(params.pair, params.method);
    return `The lesson's ${BLOCK_NAME[V.P.a]} and ${BLOCK_NAME[V.P.b]} blocks, 405 samples coloured by subtype. ${n >= 1 ? `${params.method.toUpperCase()} component 1 scores plotted against each other; correlation ${f2(V.r)}.` : "No component found yet."}`;
  },
});
