"""Generates `widgets/attention/weights.js`, the trained weights widget 83
reads, and `_lab/attention-reference.json`, what torch computes from them on
the widget's four sentences, which `attention-verify.mjs` holds the JS forward
to.

The model is the language arc's base tiny BERT (D 48, 4 heads of 12, 2 post-LN
blocks, masked-token pretraining on the synthetic clinical notes, 3,000 steps,
seed 0) — the same instance `attention-measure.py --export` drew the mock from.
Widget 83 reads block 1 only, whose input is x~ = token row + position row, so
the file carries the token and position tables and block 1's Q, K, V
projections; W_O and the rest of the block are 84's.

Run:  python widgets/_lab/attention-weights.py      (about 30 s)
A GENERATED FILE: regenerate after any change to the grammar, the model or
the training, then run `node widgets/_lab/attention-verify.mjs`.
"""
import importlib.util, json, math
from pathlib import Path
import torch

here = Path(__file__).parent
spec = importlib.util.spec_from_file_location("am", here / "attention-measure.py")
AM = importlib.util.module_from_spec(spec); spec.loader.exec_module(AM)
A = AM.A

LMAX = 16  # the Mask page pads to 16
SENTENCES = ["treated with aspirin for chest pain", "treated with [MASK] for chest pain",
             "patient presented with fever . yellow discharge from wound",
             "no nausea reported . planned discharge home today"]

mdl = AM.build(48, 4, 2, 0); AM.pretrain_log(mdl, A.make_corpus(0, 20000), 3000, 0)
b = mdl.blocks[0].att
r6 = lambda t: [round(float(x), 6) for x in t.reshape(-1).tolist()]
W = {"vocab": A.VOCAB, "D": 48, "H": b.H, "dk": b.dk, "Lmax": LMAX,
     "tok": r6(mdl.tok.weight), "pos": r6(mdl.pos.weight[:LMAX]),
     "Wq": r6(b.q.weight), "bq": r6(b.q.bias), "Wk": r6(b.k.weight), "bk": r6(b.k.bias),
     "Wv": r6(b.v.weight), "bv": r6(b.v.bias)}

# the reference, from the ROUNDED weights, so the verify compares arithmetic, not rounding
def T(key, *shape): return torch.tensor(W[key]).reshape(*shape)
tok, pos = T("tok", len(A.VOCAB), 48), T("pos", LMAX, 48)
Wq, bq, Wk, bk, Wv, bv = T("Wq", 48, 48), T("bq", 48), T("Wk", 48, 48), T("bk", 48), T("Wv", 48, 48), T("bv", 48)
ref = []
for s in SENTENCES:
    toks = ["[CLS]"] + s.split() + ["[SEP]"]
    for L in (len(toks), LMAX):
        ids = [A.ID[t] for t in toks] + [A.PAD] * (L - len(toks))
        x = tok[ids] + pos[:L]
        sh = lambda t: t.view(L, 4, 12).transpose(0, 1)
        q, k, v = sh(x @ Wq.T + bq), sh(x @ Wk.T + bk), sh(x @ Wv.T + bv)
        sc = q @ k.transpose(-1, -2)
        a = (sc / math.sqrt(12)).softmax(-1)
        ref.append({"tokens": toks, "L": L, "alpha": a.tolist(), "alpha_unscaled": sc.softmax(-1).tolist(),
                    "v": v.tolist(), "z": (a @ v).tolist()})

src = ("/* GENERATED by widgets/_lab/attention-weights.py — do not edit by hand.\n"
       "   The language arc's tiny BERT (D 48, 4 heads of 12, 2 blocks, masked-token\n"
       "   pretraining on the synthetic clinical notes, 3,000 steps, seed 0): the token\n"
       "   and position tables and block 1's Q, K and V projections, torch's layout\n"
       "   (weight[out][in], row-major). */\n"
       f"export const WEIGHTS = {json.dumps(W, separators=(',', ':'))};\n")
(here.parent / "attention").mkdir(exist_ok=True)
(here.parent / "attention" / "weights.js").write_text(src, encoding="utf-8", newline="\n")
(here / "attention-reference.json").write_text(json.dumps(ref), encoding="utf-8", newline="\n")
print(f"wrote widgets/attention/weights.js ({len(src):,} bytes) and _lab/attention-reference.json")
