"""Writes widgets/graph-representation/data.js: caffeine, written three ways.

Run:  python widgets/_lab/graph-representation-data.py   (RDKit 2026.03.6)

The widget draws, it does not parse: RDKit supplies, for each string, the
atoms in the order the string names them, the five features 09-2 cell 11
stores (atomic number, aromatic, hybridization as RDKit's enum number,
hydrogens, formal charge), the bonds in the order mol.GetBonds() yields them
(cell 12's loop), and where each atom's characters sit in the string. One
2-D drawing is made for the first string and every other string's atoms are
placed by matching them to it, so the picture never moves while the tables
renumber. Regenerate after changing anything here; the file is committed.
"""
import json, os, re
from rdkit import Chem
from rdkit.Chem import rdDepictor

rdDepictor.SetPreferCoordGen(True)
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "graph-representation", "data.js")
TOKEN = re.compile(r"(\[[^\]]+]|Br|Cl|B|C|N|O|S|P|F|I|b|c|n|o|s|p|\(|\)|\.|=|#|-|\+|\\|/|:|~|@|\?|>|\*|\$|%[0-9]{2}|[0-9])")
ATOMISH = re.compile(r"^(\[.*]|Br|Cl|B|C|N|O|S|P|F|I|b|c|n|o|s|p|\*)$")

FIRST = "Cn1cnc2n(C)c(=O)n(C)c(=O)c12"                       # 09-2 cell 6
ref = Chem.MolFromSmiles(FIRST)
rdDepictor.Compute2DCoords(ref)
conf = ref.GetConformer()
XY = [(conf.GetAtomPosition(i).x, -conf.GetAtomPosition(i).y) for i in range(ref.GetNumAtoms())]

canonical = Chem.MolToSmiles(ref)
# A third string that starts from an oxygen, chosen from RDKit's random
# writes by a fixed rule (the shortest, then alphabetical), so reruns agree.
pool = set()
for k in range(20000):
    s = Chem.MolToSmiles(ref, doRandom=True)
    if s.startswith("O="):
        pool.add(s)
other = sorted(pool, key=lambda s: (len(s), s))[0]

def variant(smi):
    m = Chem.MolFromSmiles(smi)
    match = m.GetSubstructMatch(ref)           # match[ref atom] = this string's atom
    assert len(match) == ref.GetNumAtoms(), smi
    where = {mi: ri for ri, mi in enumerate(match)}
    toks, pos, chars = TOKEN.findall(smi), 0, []
    assert "".join(toks) == smi
    for t in toks:
        if ATOMISH.match(t):
            chars.append([pos, len(t)])
        pos += len(t)
    assert len(chars) == m.GetNumAtoms()
    atoms = []
    for a in m.GetAtoms():
        x, y = XY[where[a.GetIdx()]]
        atoms.append({
            "el": a.GetSymbol(),
            "x": [a.GetAtomicNum(), int(a.GetIsAromatic()), int(a.GetHybridization()), a.GetTotalNumHs(), a.GetFormalCharge()],
            "xy": [round(x, 3), round(y, 3)],
            "char": chars[a.GetIdx()],
        })
    bonds = [[b.GetBeginAtomIdx(), b.GetEndAtomIdx(), str(b.GetBondType())] for b in m.GetBonds()]
    return {"smiles": smi, "atoms": atoms, "bonds": bonds}

data = {"first": variant(FIRST), "canonical": variant(canonical), "other": variant(other)}
for k, v in data.items():
    gaps = [abs(i - j) for i, j, _ in v["bonds"]]
    print(f"{k:10s} {v['smiles']:32s} atoms {len(v['atoms'])} bonds {len(v['bonds'])} furthest {max(gaps)} non-adjacent {sum(g > 1 for g in gaps)}")

body = json.dumps(data, separators=(",", ":"))
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* GENERATED by widgets/_lab/graph-representation-data.py with RDKit 2026.03.6 — do not edit.\n"
            "   Caffeine written three ways: the atoms in each string's order with 09-2 cell 11's five\n"
            "   features, the bonds in mol.GetBonds() order, each atom's characters, one shared drawing. */\n")
    f.write(f"export const CAFFEINE = {body};\n")
print("wrote", os.path.relpath(OUT), os.path.getsize(OUT), "bytes")
