// Writes widgets/imputation/forest-table.js: the random forest's value for every
// hole, seeds 1–SEEDS × the two Minimum measured filters, in centi-log2, holes in
// row-major order over the filtered matrix (engine.fillFromHoles reads them back).
// The forest takes 2–4 s a run at 600 proteins (catalogue § Slot 89, measured
// 2026-10-07), too slow for compute; everything else the page runs live.
// Also prints each seed's numbers, for picking a typical default seed.
//
//   node widgets/_lab/imputation-table.mjs          (about 3 min)
//
// Regenerate after any change to engine.js's simulation or forest.
import { writeFileSync } from "node:fs";
import { makeRng } from "../core/rng.js";
import * as E from "../imputation/engine.js";

const SEEDS = 20;
const out = {};
const rows = [];
const t0 = Date.now();
for (let s = 1; s <= SEEDS; s += 1) {
  const sim = E.simulateMatrix(makeRng(s));
  out[s] = {};
  const r = { seed: s };
  for (const filter of E.KEEP_LEVELS) {
    const keep = E.keepRows(sim.obs, filter);
    const obs = keep.map((p) => sim.obs[p]);
    const F = E.imputeForest(obs, makeRng(E.forestSeed(s, filter)));
    out[s][filter] = E.holesOf(F, obs);
    const sf = E.score(sim, keep, E.fillFromHoles(obs, out[s][filter]));
    const sk = E.score(sim, keep, E.imputeKnn(obs));
    const sm = E.score(sim, keep, E.imputeMin(obs));
    r[filter] = { forestFdr: sf.fdr, forestAbs: sf.absentFc, knnFdr: sk.fdr, knnAbs: sk.absentFc, minAbs: sm.absentFc, missing: obs.flat().filter(Number.isNaN).length / (obs.length * E.N) };
  }
  rows.push(r);
  process.stdout.write(`seed ${s}: forest FDR ${(100 * r.any.forestFdr).toFixed(1)}% absent ${r.any.forestAbs.toFixed(2)} · kNN FDR ${(100 * r.any.knnFdr).toFixed(1)}% absent ${r.any.knnAbs.toFixed(2)} · min absent ${r.any.minAbs.toFixed(2)} · missing ${(100 * r.any.missing).toFixed(1)}% · 50%: forest ${(100 * r["50"].forestFdr).toFixed(1)}% kNN ${(100 * r["50"].knnFdr).toFixed(1)}%  (${((Date.now() - t0) / 1000).toFixed(0)} s)\n`);
}
// a typical seed: every number nearest its median across seeds, each scaled by its spread
const keys = [["any", "forestFdr"], ["any", "forestAbs"], ["any", "knnFdr"], ["any", "knnAbs"], ["any", "minAbs"], ["any", "missing"], ["50", "forestFdr"], ["50", "knnFdr"]];
const med = (a) => { const s = [...a].sort((x, y) => x - y); return (s[(s.length - 1) >> 1] + s[s.length >> 1]) / 2; };
const dist = rows.map((r) => keys.reduce((d, [f, k]) => {
  const all = rows.map((x) => x[f][k]), m = med(all), sp = med(all.map((v) => Math.abs(v - m))) || 1;
  return d + Math.abs(r[f][k] - m) / sp;
}, 0));
const typical = rows[dist.indexOf(Math.min(...dist))].seed;
console.log(`typical seed: ${typical} (distances ${dist.map((d, i) => `${i + 1}:${d.toFixed(1)}`).join(" ")})`);

const body = Object.entries(out).map(([s, v]) => `"${s}":{${E.KEEP_LEVELS.map((k) => `"${k}":[${v[k].join(",")}]`).join(",")}}`).join(",\n");
writeFileSync(new URL("../imputation/forest-table.js", import.meta.url),
  `/* GENERATED by widgets/_lab/imputation-table.mjs — do not edit.
   missForest (samples as variables, 40 trees) on seeds 1–${SEEDS}, at every
   filter level (${E.KEEP_LEVELS.join(", ")}): the value it puts in each hole, in hundredths of a log2
   unit, holes in row-major order over the filtered matrix. Regenerate after
   any change to engine.js's simulation or forest. Typical seed: ${typical}. */
export const FOREST_SEEDS = ${SEEDS};
export const TYPICAL_SEED = ${typical};
export const FOREST = {
${body}
};
`);
console.log("wrote widgets/imputation/forest-table.js");
