"""Slot 97: generate widgets/scaffold-split/data.js.

Run after scaffold-split-measure.py gcn <seed> for seeds 42-51:
    python widgets/_lab/scaffold-split-data.py
Needs RDKit and scikit-learn; reads _lab/graph-fingat-training.csv (untracked)
and _lab/scaffold-split-gcn-<seed>.json.

EVERY ROW OF THE LESSON'S df, NOT EVERY PARSED MOLECULE. Cell 24 gives the one
SMILES RDKit cannot parse the scaffold "" and cell 28 splits all 2,335 rows, so
the printed parts (1960 / 202 / 173 at SEED 42) count it; the grid draws it in
the "" block with the acyclic molecules, where the lesson's grouping puts it.
The GCN's scores drop it, as MoleculeDataset does.

DERIVED NUMBERS ONLY (his call 5.1, 2026-10-10): a group size and its actives,
a label and a part per row in the grid's order, the GCN's score per seed. No
SMILES leave this script except the four drawn molecules' atoms and bonds.
"""
import csv, json, os

import numpy as np
from rdkit import Chem, RDLogger
from rdkit.Chem import AllChem, rdDepictor
from rdkit.Chem.Scaffolds import MurckoScaffold

RDLogger.DisableLog("rdApp.*")
rdDepictor.SetPreferCoordGen(True)
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "scaffold-split", "data.js")

import importlib.util
spec = importlib.util.spec_from_file_location("m", os.path.join(HERE, "scaffold-split-measure.py"))
M = importlib.util.module_from_spec(spec); spec.loader.exec_module(M)
SEEDS = list(range(42, 52))
assert M.SEEDS == SEEDS, "re-run scaffold-split-measure.py on seeds 42-51"

N = len(M.Y)
SCAF, Y = M.SCAF, M.Y

# ---- the grid's order: groups largest first, actives first inside a group
from collections import defaultdict
by = defaultdict(list)
for i in range(N):
    by[SCAF[i]].append(i)
groups = sorted(by.items(), key=lambda kv: (-len(kv[1]), kv[0]))
order = []
for _, ix in groups:
    order += sorted(ix, key=lambda i: (-Y[i], i))
pos = {i: k for k, i in enumerate(order)}
gidx = {s: k for k, (s, _) in enumerate(groups)}
GROUPS = [[len(ix), int(Y[ix].sum())] for _, ix in groups]
NAMED = {"benzene": gidx["c1ccccc1"], "empty": gidx[""]}

# ---- the four drawn molecules, each pair on its scaffold's coordinates
def draw(mol, template):
    m = Chem.Mol(mol)
    AllChem.GenerateDepictionMatching2DStructure(m, template)
    conf = m.GetConformer()
    keep = set(m.GetSubstructMatch(MurckoScaffold.GetScaffoldForMol(m)))
    return {"atoms": [[a.GetSymbol(), round(conf.GetAtomPosition(i).x, 3), round(-conf.GetAtomPosition(i).y, 3), int(i in keep)]
                      for i, a in enumerate(m.GetAtoms())],
            "bonds": [[b.GetBeginAtomIdx(), b.GetEndAtomIdx(), str(b.GetBondType()).split(".")[-1][0]] for b in m.GetBonds()]}

def example(rows, names):
    out = []
    for r, nm in zip(rows, names):
        mol = M.MOLS[r]
        sc = MurckoScaffold.GetScaffoldForMol(mol)
        rdDepictor.Compute2DCoords(sc)
        d = draw(mol, sc)
        d.update({"name": nm, "y": int(Y[r]), "group": gidx[SCAF[r]]})
        out.append(d)
    return out

EXAMPLES = {"indoles": example([682, 1192], ["3-methylindole", "tryptamine"]),
            "quinolones": example([61, 35], ["ciprofloxacin", "norfloxacin"])}

# ---- the splits, and what each test set shares with its training set
SPLITS, STATS = {}, {}
for kind, fn in M.SPLITS.items():
    SPLITS[kind], STATS[kind] = {}, {}
    for seed in SEEDS:
        tr, va, te = fn(seed)
        a = ["0"] * N
        for code, ix in (("1", va), ("2", te)):
            for i in ix:
                a[pos[i]] = code
        SPLITS[kind][seed] = "".join(a)
        trs, tra = set(SCAF[tr]), set(SCAF[tr[Y[tr] == 1]])
        act = te[Y[te] == 1]
        g = json.load(open(os.path.join(HERE, f"scaffold-split-gcn-{seed}.json"), encoding="utf-8"))[kind]
        STATS[kind][seed] = {
            "n": [int(len(tr)), int(len(va)), int(len(te))],
            "act": [int(Y[tr].sum()), int(Y[va].sum()), int(Y[te].sum())],
            "shared": int(sum(SCAF[i] in trs for i in te)),
            "sharedAct": int(sum(SCAF[i] in tra for i in act)),
            "f1": g["test_macro_f1"], "auc": g["test_auc"],
        }

FILE = {"rows": N, "actives": int(Y.sum()), "scaffolds": len(groups), "singletons": sum(1 for g in GROUPS if g[0] == 1)}
assert STATS["scaffold"][42]["n"] == [1960, 202, 173], STATS["scaffold"][42]["n"]

def js(v):
    return json.dumps(v, separators=(",", ":"))

body = f"""/* GENERATED by widgets/_lab/scaffold-split-data.py — do not edit by hand.
   The lesson's file (09-2 cell 20: 2,335 molecules, Activity against E. coli;
   Stokes et al., Cell 2020, via FinGAT) reduced to derived numbers: no SMILES
   except the four molecules drawn on the Scaffold page. */

/** the file as cell 24-26 group it */
export const FILE = {js(FILE)};
/** one entry a scaffold, largest first: [molecules, actives] */
export const GROUPS = {js(GROUPS)};
/** the two groups the grid names */
export const NAMED = {js(NAMED)};
/** Activity per row, in the grid's order (group by group, actives first) */
export const LABELS = "{''.join(str(int(Y[i])) for i in order)}";
/** the part per row in the grid's order, 0 train · 1 validation · 2 test, per split and seed */
export const SPLITS = {js(SPLITS)};
/** per split and seed: parts' sizes and actives, test rows sharing a scaffold with training
    (and test actives sharing one with a training active), the lesson's GCN's test macro F1 and AUC */
export const STATS = {js(STATS)};
/** atoms [element, x, y, in the scaffold], bonds [i, j, S|D|T|A] */
export const EXAMPLES = {js(EXAMPLES)};
"""
os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write(body)
print("wrote", os.path.relpath(OUT), os.path.getsize(OUT), "bytes")
for kind in STATS:
    f1 = [STATS[kind][s]["f1"] for s in SEEDS]
    print(kind, "mean F1", round(sum(f1) / len(f1), 3), "test n", sorted(STATS[kind][s]["n"][2] for s in SEEDS))
