"""Writes widgets/shap/model.js — page 2's pinned engine.

    python widgets/_lab/shap-page2-ref.py        (run from the repo root)

WHY v(S) AND NOT THE MODEL. Page 2 needs the notebook's own random forest, and
that forest is 35,326 nodes / 798 KB of JSON — unshippable. But the widget only
ever needs v(S) for one of the 60 held-out patients, and that is 60 x 8 numbers.
Pinning the VALUE FUNCTION instead of the model makes the notebook's actual `rf`
usable, exactly, in about 6 KB. The cost is that a reader picks a patient rather
than inventing one, which is the honest constraint anyway: every dot is a real
person.

Depth, not tree count, is where the interaction lives — 25/50/100/300 trees at
unlimited depth all give a per-ordering spread near 0.16, and capping at depth 6
halves it. So a "small forest" is not a faithful stand-in, and pinning v(S)
avoids having to argue about one.

ONE MODEL SHIPS, AND IT IS THE FOREST (Kenneth, 2026-09-01: "you can use only
one model for simplicity"). The logistic regression is still FITTED here and its
collapse still MEASURED and printed, because that measurement is what decided
the widget's shape — but it is not written into model.js, because page 1 already
lets a reader produce the same case by hand: set the three pair sliders to zero
and all six walks agree exactly. That IS a linear model. A second engine on
page 2 would be a second demonstration of a lesson page 1 owns.

No pandas: the CSV is twelve columns of numbers and Y/N, and `csv` reads it in
the same row order, so the stratified split is bit-identical. One less thing to
have installed.
"""
import csv, json
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score, classification_report

CSV = "C:/Users/Admin/Downloads/PHM5005 AY2025-26 - Notebooks/_scratch/heart_failure_alpha.csv"
F = ["age", "ejection_fraction", "serum_creatinine"]

with open(CSV, newline="", encoding="utf-8") as fh:
    rows = list(csv.DictReader(fh))
X = np.array([[float(r[c]) for c in F] for r in rows])
y = np.array([1 if r["DEATH_EVENT"] == "Y" else 0 for r in rows])

Xtr_r, Xte_r, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
sc = StandardScaler().fit(Xtr_r)
Xtr, Xte = sc.transform(Xtr_r), sc.transform(Xte_r)

lr = LogisticRegression(class_weight="balanced", random_state=42).fit(Xtr, ytr)
rf = RandomForestClassifier(class_weight="balanced", n_estimators=300, max_depth=None,
                            n_jobs=-1, random_state=42).fit(Xtr, ytr)

SUB = [(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]
KEYS = ["-", "0", "1", "2", "01", "02", "12", "012"]
PERMS = [(0, 1, 2), (0, 2, 1), (1, 0, 2), (1, 2, 0), (2, 0, 1), (2, 1, 0)]


def vrow(f, x):
    """v(S) = the model's average output over the training set with the features
    in S held at this patient's values — INTERVENTIONAL SHAP, which is what
    `shap.Explainer(model, X_background)` defaults to."""
    out = []
    for S in SUB:
        Z = Xtr.copy()
        for k in S:
            Z[:, k] = x[k]
        out.append(round(float(f(Z).mean()), 6))
    return out


def spread(row):
    """The widest a single feature's marginal contribution gets across the six
    orders of arrival. Zero means every ordering agrees and the averaging in the
    Shapley value is doing no work."""
    idx = {k: i for i, k in enumerate(KEYS)}
    per = [[] for _ in range(3)]
    for perm in PERMS:
        cur, S = row[0], []
        for i in perm:
            S.append(i)
            nxt = row[idx["".join(map(str, sorted(S)))]]
            per[i].append(nxt - cur)
            cur = nxt
    return max(max(c) - min(c) for c in per)


V_rf = [vrow(lambda Z: rf.predict_proba(Z)[:, 1], Xte[i]) for i in range(len(Xte))]

payload = {
    "source": "heart_failure_alpha.csv · 299 patients (Chicco & Jurman 2020) · notebook 04-5's own split",
    "features": F,
    "labels": ["Age", "Ejection fraction", "Serum creatinine"],
    "short": ["Age", "EF", "Cr"],
    "units": ["years", "%", "mg/dL"],
    "keys": KEYS,
    "nTrain": int(len(Xtr)),
    "rf": {"trees": 300, "depth": None,
           "auc": round(float(roc_auc_score(yte, rf.predict_proba(Xte)[:, 1])), 6)},
    "patients": [{"raw": [float(v) for v in Xte_r[i]], "died": int(yte[i])}
                 for i in range(len(Xte))],
    "v": V_rf,
}
js = ("/* GENERATED by widgets/_lab/shap-page2-ref.py — do not edit by hand.\n"
      "   v(S) for all eight coalitions x 60 held-out patients under the random\n"
      "   forest notebook 04-5 declares and never fits. The forest itself is\n"
      "   35,326 nodes / 798 KB of JSON; its value function is this. */\n"
      "export const DATA = " + json.dumps(payload, separators=(",", ":")) + ";\n")
open("widgets/shap/model.js", "w", encoding="utf-8").write(js)
print("wrote widgets/shap/model.js  %.1f KB" % (len(js) / 1024))

# --- what is NOT shipped, but is why the widget looks the way it does --------
V_lrm = [vrow(lambda Z: lr.decision_function(Z), Xte[i]) for i in range(len(Xte))]
V_lrp = [vrow(lambda Z: lr.predict_proba(Z)[:, 1], Xte[i]) for i in range(len(Xte))]
print("\nAUC on the 60 held out:  lr %.4f   rf %.4f"
      % (roc_auc_score(yte, lr.predict_proba(Xte)[:, 1]), payload["rf"]["auc"]))
print("widest disagreement between the six orders, per patient:")
for name, VV, scale in (("lr, log-odds  (the notebook's own)", V_lrm, 1),
                        ("lr, probability", V_lrp, 100),
                        ("rf, probability  (SHIPPED)", V_rf, 100)):
    s = sorted(spread(r) * scale for r in VV)
    print("  %-34s min %6.3f  median %6.3f  max %6.3f%s"
          % (name, s[0], s[30], s[-1], " points" if scale == 100 else ""))
print("  -> on the notebook's own model and scale it is EXACTLY zero for all 60,")
print("     which is why 04-5 can print phi_i = beta_i (x_i - xbar_i) and never")
print("     need an ordering. Page 1's three pair sliders at zero are that case.")
print("\nnotebook cell 7's report, for the 3-feature lr:")
print(classification_report(yte, lr.predict(Xte), digits=3))
