"""Writes widgets/_lab/shap-train.js — v(S) for the 239 TRAINING patients.

    python widgets/_lab/shap-train-ref.py        (run from the repo root)

FOR A MOCKUP ONLY, and deliberately not folded into `shap-page2-ref.py` until
the question it exists to answer is settled: should the global explanation be
computed on the data the forest was FITTED on, or on the data it was held out
from? The shipped `model.js` uses the test set, because 04-5 does
(`explainer = shap.Explainer(model, X_train)` then `explainer(X_test)`, and both
the beeswarm and the waterfall come from that one array).

Note what is NOT in question: X_train is the BACKGROUND either way. Every v(S)
here and in the shipped file is the forest's mean output over the 239 training
rows with the features in S pinned. The choice is only over WHICH patients get
explained.

One wrinkle worth knowing if this ships: a training patient is inside its own
background set, so it influences its own baseline by 1/239. The SHAP library has
the same property when you pass the same frame twice; it is not a defect, but it
is a thing to be able to answer.
"""
import csv, json, time
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score

CSV = "C:/Users/Admin/Downloads/PHM5005 AY2025-26 - Notebooks/_scratch/heart_failure_alpha.csv"
F = ["age", "ejection_fraction", "serum_creatinine"]

rows = list(csv.DictReader(open(CSV, newline="", encoding="utf-8")))
X = np.array([[float(r[c]) for c in F] for r in rows])
y = np.array([1 if r["DEATH_EVENT"] == "Y" else 0 for r in rows])
Xtr_r, Xte_r, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
sc = StandardScaler().fit(Xtr_r)
Xtr, Xte = sc.transform(Xtr_r), sc.transform(Xte_r)

rf = RandomForestClassifier(class_weight="balanced", n_estimators=300, max_depth=None,
                            n_jobs=-1, random_state=42).fit(Xtr, ytr)

SUB = [(), (0,), (1,), (2,), (0, 1), (0, 2), (1, 2), (0, 1, 2)]
KEYS = ["-", "0", "1", "2", "01", "02", "12", "012"]


def vrow(x):
    out = []
    for S in SUB:
        Z = Xtr.copy()
        for k in S:
            Z[:, k] = x[k]
        out.append(round(float(rf.predict_proba(Z)[:, 1].mean()), 6))
    return out


t0 = time.time()
V = [vrow(Xtr[i]) for i in range(len(Xtr))]
secs = time.time() - t0

payload = {
    "note": "the 239 TRAINING patients, explained against the same background",
    "keys": KEYS,
    "auc_train": round(float(roc_auc_score(ytr, rf.predict_proba(Xtr)[:, 1])), 6),
    "auc_test": round(float(roc_auc_score(yte, rf.predict_proba(Xte)[:, 1])), 6),
    "patients": [{"raw": [float(v) for v in Xtr_r[i]], "died": int(ytr[i])}
                 for i in range(len(Xtr))],
    "v": V,
}
js = ("/* GENERATED by widgets/_lab/shap-train-ref.py — mockup data, not shipped. */\n"
      "export const TRAIN = " + json.dumps(payload, separators=(",", ":")) + ";\n")
open("widgets/_lab/shap-train.js", "w", encoding="utf-8").write(js)
print("wrote widgets/_lab/shap-train.js  %.1f KB   (%d patients, %.0f s to compute)"
      % (len(js) / 1024, len(V), secs))
print("forest AUC:  train %.4f   test %.4f" % (payload["auc_train"], payload["auc_test"]))
