/* ============================================================================
   Widget 85 · Language: Pre-training and Adapting (`adapting`) — PHM5005 08-1
   cells 4 and 13–19, 08-2 cells 3 and 19–65. DRAFT, 2026-10-01 (catalogue
   § Slot 85, measured in `_lab/clinical-text-measure.py`, mocked in
   `_lab/clinical-text-mock.html`, every pick the recommendation).

   His note at 84's ship: 84 shows the trained heads' RESULTS; this widget shows
   the training — first the self-supervised pretraining that made 84's model,
   then a head trained on labelled notes, three ways.

     PRETRAINING   unlabelled notes with tokens hidden, each hidden token its own
                   target (08-1 cell 4); the lesson's "treated with [MASK] for
                   chest pain" read at seven checkpoints, a press each (his pick
                   over Play), and the held-out accuracy line drawn through every
                   checkpoint passed. Its last checkpoint IS 84's model: the table
                   generator asserts the weights are equal bit for bit.
     ADAPTING      four of the labelled notes; his adapt figure as three columns,
                   transfer · full fine-tuning · LoRA, the parts that train filled
                   in the way's colour and bracketed Trainable (LoRA's A Bᵀ drawn
                   INSIDE the backbone beside Q and V, peft's default for BERT, not
                   as a box between backbone and head: notebook finding 9); one
                   Train press runs the 400 steps and the held-out accuracy curves
                   grow together, from scratch a fourth line (his pick).

   WHAT THE STAGE CAN SAY, measured on 84's base with the [CLS] row (catalogue
   § Slot 85): on Finding asserted all four ways are near the top from 16 notes
   and transfer stops a few points short; on Drug for the wrong symptom transfer
   stays at chance at every size while the fine-tunings climb and scratch does
   not. Ruled out, so nothing here claims it: transfer winning at small n (a
   mean-pooling number), forgetting (none at these rates), and a drug the
   labels never name.

   NOTHING TRAINS IN THE BROWSER: every number is read from `table.js`,
   GENERATED by `_lab/adapting-table.py` (torch; one run per setting, seed 0) and
   checked by `_lab/adapting-verify.mjs`. Regenerate the table after any change
   to the grammar, 84's base or the training.

   Ways --c-group-a / -b / -c (three parallel branches), scratch
   --c-reference, frozen parts --surface-3. A hidden token's original is the
   truth the prediction is scored on: --c-reference too, on the other page.
   EACH PAGE KEEPS ITS OWN PLACE (`anim.p[page]`); a switch mid-press finishes
   the press and `halt` ends the loop (widget 70's rule). Tweens only move
   (his rule, 2026-09-26): the accuracy line draws out, the curves grow; text
   and bars switch at once.
   ========================================================================= */

import { defineWidget } from "../core/index.js";
import { TABLE } from "./table.js";

const PAGES = [
  { value: "pretraining", label: "Pretraining", detail: "Self-supervised: tokens hidden in unlabelled notes, each prediction scored against the hidden token." },
  { value: "adapting", label: "Adapting", detail: "The pretrained model, a new head and labelled notes, trained three ways." },
];
const TASKS = [
  { value: "outcome", label: "Finding asserted", detail: "1 when the note asserts an abnormal finding, 0 otherwise." },
  { value: "match", label: "Wrong drug", detail: "1 when a drug is given for a symptom it does not treat, 0 when it treats it. Every pretraining note paired a drug with its own symptom." },
];
const SIZES = ["16", "64", "256", "1024"];
const WAYS = [
  { key: "transfer", name: "Transfer learning", short: "Transfer", color: "groupA" },
  { key: "full", name: "Full fine-tuning", short: "Full", color: "groupB" },
  { key: "lora", name: "LoRA (PEFT)", short: "LoRA", color: "groupC" },
];
const SCRATCH = { key: "scratch", name: "From scratch", short: "From scratch", color: "reference" };
/* the seven checkpoints a press reaches (his pick); the line passes through all thirteen in the table */
const PRESS = [0, 25, 100, 200, 500, 750, 3000];
const PRE = TABLE.pretrain, LAST = PRE[PRE.length - 1].step;
const STEPS = TABLE.steps, EVERY = TABLE.every, POINTS = STEPS / EVERY;
const BACKBONE = TABLE.trains.full - TABLE.trains.transfer;
const LABELS = { outcome: ["negative", "positive"], match: ["right drug", "wrong drug"] };
const PROBE = ["treated", "with", "[MASK]", "for", "chest", "pain"];
/* the grammar's two drugs for chest pain (language-arc-measure.py SYM_DRUG) */
const CHEST = ["aspirin", "nitrate"];

/* ================================================================== copy */

const S = {
  title: "Deep Learning - Language: Pre-training and Adapting",
  subtitle: "Pretraining needs no labels: tokens are hidden in unlabelled text and the model learns to predict them, which is how it comes "
    + "to hold what the words mean together. Adapting adds a head and trains on labelled examples: transfer learning trains the head "
    + "alone, full fine-tuning every weight, and LoRA a small low-rank update beside frozen weights. Training the head alone works when "
    + "the pretrained vectors already separate the classes, and fails when they do not.",
  pageLabel: "Stage",
  taskLabel: "Task",
  sizeLabel: "Labelled notes",
  sizeDetail: "The notes every way is trained on: 400 steps of 16, Adam at 5e-3 (transfer), 1e-3 (LoRA) and 3e-4 (full, scratch).",
  step: { pretraining: "Next checkpoint", adapting: "Train" },
  stepTitle: { pretraining: "Show the model after more pretraining steps", adapting: "Train the heads on the labelled notes, 400 steps" },
  wait: "—",

  maskedHead: "Unlabelled notes, each token hidden with probability 0.15",
  maskedNote: "No one labels these notes: the word under each [MASK] is the target its prediction is scored against.",
  probeHead: (s) => (s === null ? "A masked sentence" : `A masked sentence after ${s.toLocaleString("en-US")} training steps`),
  probeNote: "the five most likely tokens at [MASK]",
  probeWait: "Next checkpoint shows the model at step 0, its weights still random.",
  accHead: "Masked tokens predicted right, 2,000 held-out notes",
  accAxis: "pretraining step (square-root scale)",
  /* each line says what its checkpoint shows, read from the table; none claims a reason */
  preLine: (k, at) => {
    const [a, b] = at.top, drugs = at.top.filter(([t]) => CHEST.includes(t)).reduce((s, [, p]) => s + p, 0);
    return [
      `Step 0: random weights; the most likely token, ${a[0]}, gets ${a[1].toFixed(2)}.`,
      `After 25 steps the most likely are ${a[0]} and ${b[0]}, and no drug.`,
      `After 100 steps still ${a[0]} and ${b[0]}; held-out accuracy ${pct(at.mlm)}.`,
      `After 200 steps a drug comes first, ${a[0]}, not one given for chest pain.`,
      `After 500 steps aspirin and nitrate, the drugs given for chest pain in these notes, come first.`,
      `Aspirin and nitrate together: ${drugs.toFixed(2)} of the probability.`,
      `The finished pretrained model. Its vectors are where Adapting starts.`,
    ][k];
  },

  notesHead: (n) => `Labelled notes: ${Number(n).toLocaleString("en-US")} for training, 1,000 held out`,
  notesNote: "A new head is trained to output each note's label from its [CLS] vector.",
  waysHead: "What each way trains",
  backbone: "Backbone", head: "Head 48 → 2", frozen: "frozen", trainable: "Trainable", lora: "A Bᵀ",
  trains: (n) => `trains ${n.toLocaleString("en-US")}`,
  share: (p) => `${p} of the model`,
  scratchNote: (n) => `From scratch: the same network, random weights, all ${n.toLocaleString("en-US")} trained`,
  curveHead: (n) => `Held-out accuracy while training on ${Number(n).toLocaleString("en-US")} labelled notes`,
  curveAxis: "training step",
  floor: (task, p) => (task === "outcome" ? `every note called positive: ${p}` : `chance: ${p}`),
  /* read from the run on screen, so it holds at every size and task */
  adaptLine: (done, task, run, base) => {
    if (!done) return "Train runs 400 steps on the labelled notes, each way from the same start.";
    const end = (k) => run[k][run[k].length - 1], best = Math.max(end("full"), end("lora"));
    if (best - base <= 0.03) return `With these few notes no way gets far from chance: the fine-tunings ${pct(best)}, the head alone ${pct(end("transfer"))}.`;
    return Math.abs(end("transfer") - base) <= 0.03
      ? `The head alone ends at ${pct(end("transfer"))}, near chance; the fine-tunings, which change the vectors, reach ${pct(best)}.`
      : `The head alone ends at ${pct(end("transfer"))}; the fine-tunings, which change the vectors, reach ${pct(best)}.`;
  },

  tileStep: "Step", tileStepNote: "pretraining steps so far",
  tileMlm: "Masked tokens right", tileMlmNote: "on 2,000 held-out notes",
  tileTop: "At [MASK]", tileTopNote: "the most likely token",
  tileWayNote: (n) => `trains ${n.toLocaleString("en-US")}`,
  sum: (page, n, max) => `${page}: ${n} of ${max} presses.`,
};

/* ============================================================ drawing kit */

const PAD = 12;
const pct = (v) => `${Math.round(100 * v)}%`;
const cap = (c) => `600 ${c.fsSm} ${c.font}`;
const small = (c) => `${c.fsXs} ${c.font}`;
const smallBold = (c) => `600 ${c.fsXs} ${c.font}`;
const body = (c) => `${c.fsSm} ${c.font}`;
const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - 2 * (1 - t) * (1 - t));
function txt(ctx, s, x, y, { font, fill, align = "left", baseline = "middle" }) {
  ctx.save(); ctx.font = font; ctx.fillStyle = fill; ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
const textW = (ctx, font, s) => { ctx.save(); ctx.font = font; const w = ctx.measureText(s).width; ctx.restore(); return w; };
function line(ctx, pts, stroke, lw = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); pts.forEach(([x, y], i) => (i ? ctx.lineTo(x, y) : ctx.moveTo(x, y))); ctx.stroke(); ctx.restore();
}
/** a row of tokens; `box(i)` fills a token's background, `under(i)` writes a line beneath it */
function tokenRow(ctx, c, toks, x, y, { box = () => null, under = () => null } = {}) {
  let cx = x;
  toks.forEach((t, i) => {
    const w0 = textW(ctx, body(c), t), u0 = under(i), w = u0 ? Math.max(w0, textW(ctx, small(c), u0)) : w0, b = box(i);
    if (b) { ctx.fillStyle = b; ctx.fillRect(cx - 3, y - 10, w + 6, 20); }
    txt(ctx, t, cx + (w - w0) / 2, y, { font: body(c), fill: c.ink1 });
    if (u0) txt(ctx, u0, cx + w / 2, y + 17, { font: small(c), fill: c.reference, align: "center" });
    cx += w + 10;
  });
}
function axisY(ctx, c, x, y0, h, ticks, at) {
  for (const v of ticks) {
    const y = at(v); line(ctx, [[x, y], [x + 0, y]], c.grid);
    txt(ctx, pct(v), x - 6, y, { font: small(c), fill: c.ink3, align: "right" });
  }
}

/* ============================================================ the pages */

/* geometry shared by drawing and the height: one function each, so they cannot disagree */
const PRE_H = 530, ADAPT_H = 670;
const preChart = (w) => ({ x: PAD + 40, y: 372, w: w - 2 * PAD - 70, h: 96 });
const adaptChart = (w) => ({ x: PAD + 40, y: 404, w: w - 2 * PAD - 160, h: 190 });
const sx = (ch, s) => ch.x + ch.w * Math.sqrt(s / LAST);

function drawPretraining(ctx, c, w, pg) {
  /* 1 · the targets */
  txt(ctx, S.maskedHead, PAD, 16, { font: cap(c), fill: c.ink1 });
  TABLE.masked.forEach((m, i) => tokenRow(ctx, c, m.tokens.map((t, j) => (m.hidden.includes(j) ? "[MASK]" : t)), PAD + 8, 44 + i * 38,
    { box: (j) => (m.hidden.includes(j) ? c.surface3 : null), under: (j) => (m.hidden.includes(j) ? m.tokens[j] : null) }));
  txt(ctx, S.maskedNote, PAD, 160, { font: small(c), fill: c.ink3 });

  /* 2 · the probe: what a press shows switches at once; the line draws out */
  const k = pg.n - 1, at = k >= 0 ? PRE.find((r) => r.step === PRESS[k]) : null;
  txt(ctx, S.probeHead(at ? at.step : null), PAD, 196, { font: cap(c), fill: c.ink1 });
  tokenRow(ctx, c, PROBE, PAD + 8, 224, { box: (j) => (PROBE[j] === "[MASK]" ? c.surface3 : null) });
  if (!at) txt(ctx, S.probeWait, PAD + 8, 264, { font: body(c), fill: c.ink2 });
  else {
    txt(ctx, S.probeNote, w - PAD, 224, { font: small(c), fill: c.ink3, align: "right" });
    const bx = PAD + 118, bw = w - 2 * PAD - 170;
    at.top.forEach(([t, p], i) => {
      const y = 252 + i * 18;
      txt(ctx, t, bx - 8, y, { font: body(c), fill: c.ink1, align: "right" });
      ctx.fillStyle = c.empirical; ctx.fillRect(bx, y - 6, Math.max(1, bw * p), 12);
      txt(ctx, p.toFixed(2), bx + bw * p + 6, y, { font: small(c), fill: c.ink2 });
    });
  }

  /* 3 · held-out accuracy, the line through every checkpoint passed */
  const ch = preChart(w), Y = (v) => ch.y + ch.h - v * ch.h;
  txt(ctx, S.accHead, PAD, ch.y - 22, { font: cap(c), fill: c.ink1 });
  for (const v of [0, 0.5, 1]) { line(ctx, [[ch.x, Y(v)], [ch.x + ch.w, Y(v)]], c.grid); txt(ctx, pct(v), ch.x - 6, Y(v), { font: small(c), fill: c.ink3, align: "right" }); }
  for (const s of [0, 100, 500, 1000, 3000]) txt(ctx, s.toLocaleString("en-US"), sx(ch, s), ch.y + ch.h + 12, { font: small(c), fill: c.ink3, align: "center" });
  txt(ctx, S.accAxis, ch.x + ch.w, ch.y + ch.h + 28, { font: small(c), fill: c.ink3, align: "right" });
  if (at) {
    const from = k > 0 ? PRESS[k - 1] : 0, cut = sx(ch, from) + (sx(ch, at.step) - sx(ch, from)) * ease(pg.t);
    const pts = PRE.filter((r) => r.step <= at.step).map((r) => [sx(ch, r.step), Y(r.mlm)]);
    const drawn = []; let end = pts[0];
    for (let i = 0; i < pts.length; i++) {
      if (pts[i][0] <= cut) { drawn.push(pts[i]); end = pts[i]; continue; }
      const a = pts[i - 1], b = pts[i], f = (cut - a[0]) / (b[0] - a[0]);
      end = [cut, a[1] + (b[1] - a[1]) * f]; drawn.push(end); break;
    }
    line(ctx, drawn, c.empirical, 2);
    ctx.fillStyle = c.empirical; ctx.beginPath(); ctx.arc(end[0], end[1], 4, 0, 2 * Math.PI); ctx.fill();
    if (pg.t >= 1) txt(ctx, pct(at.mlm), end[0] + 8, end[1] - 10, { font: smallBold(c), fill: c.ink1 });
  }
  txt(ctx, at ? S.preLine(k, at) : "", PAD, PRE_H - 14, { font: body(c), fill: c.ink2 });
}

function drawAdapting(ctx, c, w, params, state, pg) {
  /* 1 · the labelled notes */
  txt(ctx, S.notesHead(params.notes), PAD, 16, { font: cap(c), fill: c.ink1 });
  state.notes.forEach(([t, y], i) => {
    const yy = 44 + i * 24, lab = `${y} ${LABELS[params.task][y]}`;
    ctx.save(); ctx.strokeStyle = c.ink3; ctx.strokeRect(PAD + 8.5, yy - 9.5, 92, 19); ctx.restore();
    txt(ctx, lab, PAD + 54, yy, { font: small(c), fill: c.ink1, align: "center" });
    txt(ctx, t, PAD + 112, yy, { font: body(c), fill: c.ink1 });
  });
  txt(ctx, S.notesNote, PAD, 146, { font: small(c), fill: c.ink3 });

  /* 2 · his adapt figure, a column a way */
  txt(ctx, S.waysHead, PAD, 182, { font: cap(c), fill: c.ink1 });
  const colW = (w - 2 * PAD) / 3, bw = Math.min(118, colW - 46), top = 206, bbH = 64, hdH = 22;
  WAYS.forEach((way, i) => {
    const col = c[way.color], x = PAD + i * colW + 34, n = TABLE.trains[way.key], backT = way.key === "full";
    txt(ctx, way.name, x + bw / 2, top, { font: smallBold(c), fill: c.ink1, align: "center" });
    const by = top + 14;
    ctx.fillStyle = backT ? col : c.surface3; ctx.fillRect(x, by, bw, bbH);
    txt(ctx, S.backbone, x + bw / 2, by + 18, { font: smallBold(c), fill: backT ? c.surface : c.ink2, align: "center" });
    txt(ctx, backT ? BACKBONE.toLocaleString("en-US") : `${BACKBONE.toLocaleString("en-US")} ${S.frozen}`, x + bw / 2, by + 34,
      { font: small(c), fill: backT ? c.surface : c.ink3, align: "center" });
    if (way.key === "lora") [0, 1].forEach((j) => {
      const lw = (bw - 24) / 2, lx = x + 8 + j * (lw + 8);
      ctx.fillStyle = col; ctx.fillRect(lx, by + bbH - 18, lw, 13);
      txt(ctx, S.lora, lx + lw / 2, by + bbH - 11.5, { font: small(c), fill: c.surface, align: "center" });
    });
    const hy = by + bbH + 4;
    ctx.fillStyle = col; ctx.fillRect(x, hy, bw, hdH);
    txt(ctx, S.head, x + bw / 2, hy + hdH / 2, { font: smallBold(c), fill: c.surface, align: "center" });
    /* the Trainable bracket, his figure's */
    const t0 = backT ? by : way.key === "lora" ? by + bbH - 20 : hy, t1 = hy + hdH;
    line(ctx, [[x - 6, t0], [x - 11, t0], [x - 11, t1], [x - 6, t1]], c.ink1, 1.5);
    ctx.save(); ctx.translate(x - 19, (t0 + t1) / 2); ctx.rotate(-Math.PI / 2);
    txt(ctx, S.trainable, 0, 0, { font: smallBold(c), fill: c.ink1, align: "center" }); ctx.restore();
    txt(ctx, S.trains(n), x + bw / 2, t1 + 14, { font: smallBold(c), fill: col, align: "center" });
    const p = n / (BACKBONE + n - (backT ? BACKBONE : 0));
    txt(ctx, S.share(p < 0.01 ? `${(100 * p).toFixed(1)}%` : pct(p)), x + bw / 2, t1 + 28, { font: small(c), fill: c.ink3, align: "center" });
  });
  const sy = top + 14 + 64 + 4 + 22 + 50;
  line(ctx, [[PAD + 8, sy], [PAD + 26, sy]], c.reference, 2, [5, 3]);
  txt(ctx, S.scratchNote(TABLE.trains.scratch), PAD + 32, sy, { font: small(c), fill: c.ink2 });

  /* 3 · the curves, grown by the Train press */
  const ch = adaptChart(w), Y = (v) => ch.y + ch.h - ((v - 0.4) / 0.6) * ch.h, X = (i) => ch.x + ch.w * i / POINTS;
  txt(ctx, S.curveHead(params.notes), PAD, ch.y - 24, { font: cap(c), fill: c.ink1 });
  for (const v of [0.4, 0.6, 0.8, 1]) { line(ctx, [[ch.x, Y(v)], [ch.x + ch.w, Y(v)]], c.grid); txt(ctx, pct(v), ch.x - 6, Y(v), { font: small(c), fill: c.ink3, align: "right" }); }
  for (let s = 0; s <= STEPS; s += 100) txt(ctx, String(s), X(s / EVERY), ch.y + ch.h + 12, { font: small(c), fill: c.ink3, align: "center" });
  txt(ctx, S.curveAxis, ch.x + ch.w, ch.y + ch.h + 28, { font: small(c), fill: c.ink3, align: "right" });
  const fy = Y(state.base);
  line(ctx, [[ch.x, fy], [ch.x + ch.w, fy]], c.ink3, 1, [3, 3]);
  txt(ctx, S.floor(params.task, pct(state.base)), ch.x + ch.w, fy + 10, { font: small(c), fill: c.ink3, align: "right" });

  const upto = progress(pg);
  if (upto > 0) {
    const ends = [];
    for (const way of [...WAYS, SCRATCH]) {
      const cv = state.run[way.key], last = Math.floor(upto), f = upto - last;
      const pts = cv.slice(0, last + 1).map((v, i) => [X(i), Y(v)]);
      if (f > 0 && last < POINTS) pts.push([X(last + f), Y(cv[last] + (cv[last + 1] - cv[last]) * f)]);
      line(ctx, pts, c[way.color], 2, way === SCRATCH ? [5, 3] : null);
      const e = pts[pts.length - 1]; ends.push({ x: e[0], y: e[1], v: cv[Math.min(POINTS, Math.round(upto))], way });
    }
    ends.sort((a, b) => a.y - b.y);
    for (let i = 1; i < ends.length; i++) ends[i].y = Math.max(ends[i].y, ends[i - 1].y + 13);
    for (const e of ends) txt(ctx, `${pct(e.v)} ${e.way.short}`, e.x + 6, e.y, { font: smallBold(c), fill: c[e.way.color] });
  }
  txt(ctx, S.adaptLine(pg.n > 0 && pg.t >= 1, params.task, state.run, state.base), PAD, ADAPT_H - 14, { font: body(c), fill: c.ink2 });
}

/* ============================================================ animation */

const MAX = { pretraining: PRESS.length, adapting: 1 };
const MS = { pretraining: 700, adapting: 4000 };
const pageOf = (anim, params) => anim.p[params.page];
/** how far along the 400 steps the curves are, in table points */
const progress = (pg) => (pg.n === 0 ? 0 : POINTS * pg.t);
function settle(anim, params) {
  const pg = pageOf(anim, params);
  anim.key = params.page;
  anim.done = pg.n >= MAX[params.page] && pg.t >= 1;
}

defineWidget({
  slug: "adapting",
  status: "draft",
  title: S.title,
  subtitle: S.subtitle,
  layout: "side",
  height: ({ page }) => (page === "adapting" ? ADAPT_H : PRE_H),

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "pretraining", display: true },
    task: { type: "segmented", label: S.taskLabel, options: TASKS, default: "outcome", when: { param: "page", equals: "adapting" } },
    notes: { type: "choice", label: S.sizeLabel, detail: S.sizeDetail, options: SIZES.map((v) => ({ value: v, label: Number(v).toLocaleString("en-US") })),
      default: "256", when: { param: "page", equals: "adapting" } },
    /* authoring escape hatch, first render only: presses already made on the page opened */
    shown: { type: "int", min: 0, max: 7, default: 0, hidden: true },
  },

  legend: [],

  compute: ({ params }) => ({
    run: TABLE.adapt[params.task][params.notes],
    base: TABLE.base[params.task],
    notes: TABLE.notes[params.task],
  }),

  animation: {
    stepLabel: { param: "page", labels: S.step, default: S.step.pretraining },
    stepTitle: { param: "page", labels: S.stepTitle, default: S.stepTitle.pretraining },
    /* no Play: Pretraining's presses are each read, and Adapting's one press is the whole run (his picks) */
    runLabel: null,
    init: ({ params, fromScratch }) => {
      const anim = { p: { pretraining: { n: 0, t: 1 }, adapting: { n: 0, t: 1 } }, moving: false, halt: false };
      if (!fromScratch) anim.p[params.page].n = Math.max(0, Math.min(MAX[params.page], Number(params.shown) || 0));
      settle(anim, params);
      return anim;
    },
    advance: (anim, { dt, params }) => {
      if (anim.halt) { anim.halt = false; anim.moving = false; settle(anim, params); return false; }
      const pg = pageOf(anim, params);
      let more;
      if (pg.t < 1) { pg.t = Math.min(1, pg.t + dt / MS[params.page]); more = pg.t < 1; }
      else if (pg.n < MAX[params.page]) { pg.n += 1; pg.t = 0; more = true; }
      else more = false;
      anim.moving = more;
      settle(anim, params);
      return more;
    },
    rebuild: (anim, { params }) => {
      /* a press belongs to the page it started on: a switch mid-press finishes it (widget 70's rule) */
      if (anim.moving && params.page !== anim.key) {
        for (const pg of Object.values(anim.p)) pg.t = 1;
        anim.halt = true;
      }
      settle(anim, params);
    },
  },

  draw({ ctx, colors, w, params, state, anim }) {
    const pg = pageOf(anim, params);
    if (params.page === "adapting") drawAdapting(ctx, colors, w, params, state, pg);
    else drawPretraining(ctx, colors, w, pg);
  },

  readout({ params, state, anim }) {
    const pg = pageOf(anim, params);
    if (params.page === "pretraining") {
      const k = pg.t >= 1 ? pg.n - 1 : pg.n - 2, at = k >= 0 ? PRE.find((r) => r.step === PRESS[k]) : null;
      return [
        { label: S.tileStep, value: at ? `${at.step.toLocaleString("en-US")} of ${LAST.toLocaleString("en-US")}` : S.wait, note: S.tileStepNote },
        { label: S.tileMlm, value: at ? pct(at.mlm) : S.wait, note: S.tileMlmNote },
        { label: S.tileTop, value: at ? `${at.top[0][0]} ${at.top[0][1].toFixed(2)}` : S.wait, note: S.tileTopNote },
      ];
    }
    const upto = progress(pg), i = Math.min(POINTS, Math.round(upto));
    return [...WAYS, SCRATCH].map((way) => ({
      label: way.short, value: upto > 0 ? pct(state.run[way.key][i]) : S.wait, note: S.tileWayNote(TABLE.trains[way.key]),
    }));
  },

  summary({ params, anim }) {
    return S.sum(PAGES.find((p) => p.value === params.page).label, pageOf(anim, params).n, MAX[params.page]);
  },
});
