/* ============================================================================
   Widget 84 · Language: Transformer (`transformer`) — PHM5005 08-1 cells 2–3,
   Transformer Architecture and Transformer Tasks. DRAFT, rebuilt 2026-09-27
   to the replan and simplified the same day (catalogue § Slot 84).

   Three pages BY ARCHITECTURE, his framing, 08-1 cell 3's three families:

     ENCODER          the masked-token model on the lesson's sentence. A press
                      enters the next token: it glides in, then an outline steps
                      down EVERY row, whose weights are computed again, and a bar
                      beside each earlier row is how far that token's final vector
                      moved. The chosen word's arcs, drawn on the sentence as his
                      output figure draws them (a loop for itself, an arc to each
                      other token, thickness by weight), reach forward and back.
     DECODER          the next-token model, the same figure in the same place:
                      each key after its query masked, so a press computes only the
                      new row, the earlier rows' weights stay the same numbers and
                      their bars read 0; the chosen word keeps its loop and its
                      arcs back.
     ENCODER–DECODER  the DNA -> protein model, his two-stack figure on top and a
                      leader from each attention box to its matrix. A press writes
                      the next amino acid: both decoder matrices gain a row, and
                      lines from the new amino acid run down to the nucleotides it
                      reads, thickness by weight.

   HIS SIMPLIFICATION (2026-09-27, `_lab/transformer-steps-mock.html`): one
   example, no toggles ("toggling gets confusing what i'm looking at"); tokens
   entering a press at a time with the scores updated after; his arcs; no
   next-token softmax (the diagram's loop says the output is fed back). The
   diagram is joined to its matrix by a leader line, the stacks filled in his
   figures' blue (--c-group-a, encoder) and orange (--c-group-b, decoder), and
   every token label in the hue of the stack it came from.

   THE BARS MEASURE THE FINAL VECTOR, not block 1's weights: a row's block-1
   weights can barely move (aspirin 0.001 when [SEP] enters), which would read as
   the decoder's zero; its final vector moves 1.53–14.92 on every press.

   THE MODELS ARE TRAINED AND ONLY READ (model.js, weights generated by
   `_lab/transformer-weights.py`, held to torch by `_lab/transformer-verify.mjs`).

   EACH PAGE KEEPS ITS OWN PLACE: `anim.p[page]` counts its presses, since a
   page is a display parameter (invariant 3). A press belongs to the page it
   started on: a switch mid-press finishes it and `halt` ends the loop
   (widget 70's rule, 2026-09-19).
   ========================================================================= */

import { defineWidget, mathmlRenders } from "../core/index.js";
import * as M from "./model.js";

const PAGES = [{ value: "encoder", label: "Encoder" }, { value: "decoder", label: "Decoder" }, { value: "encoder-decoder", label: "Encoder–decoder" }];
const ON = (page) => ({ param: "page", equals: page });
const SELF = { any: [ON("encoder"), ON("decoder")] };
const TOKENS = M.tokensOf(M.SENTENCE), N = TOKENS.length;

/* ================================================================== copy */

const S = {
  title: "Deep Learning - Language: Transformer",
  subtitle: "Encoders and decoders are built from the same blocks and differ in which tokens each query may attend to. In an encoder "
    + "every token attends to the whole sequence, so each token's vector depends on the tokens after it; in a decoder a token attends "
    + "only to the tokens before it, which lets the output be generated one token at a time. An encoder–decoder adds cross-attention: "
    + "queries from the output so far, keys and values from the encoded input.",
  pageLabel: "Step",
  queryLabel: "Query", queryDetail: "The token whose weights are drawn as arcs on the sentence; a click on a token chooses it too.",
  step: { encoder: "Next token", decoder: "Next token", "encoder-decoder": "Next amino acid" },
  stepTitle: { encoder: "Add the sentence's next token and compute the weights", decoder: "Add the sentence's next token and compute the weights",
    "encoder-decoder": "Compute the next amino acid from the gene and the protein so far" },
  runLabel: "Play", runTitle: "Run the rest",
  wait: "—",

  /* the stacks, as his figures label them */
  enc: "Encoder", dec: "Decoder", ffn: "Feed forward", selfAtt: "Self-attention", masked: ["Masked self-", "attention"], cross: "Cross-attention",
  embedding: "Embedding", times: "× 2",
  encIn: "Input sequence", encOut: "Representation", decIn: "Tokens so far", decOut: "Next token",
  geneIn: "The gene (DNA)", protIn: "The protein so far", protOut: "Next amino acid",

  /* pages 1–2 */
  queryCap: (t) => `${t}: its weights as arcs`, notYet: (t) => `${t} has not entered yet`,
  sources: (who) => `queries (rows) and keys (columns): the ${who}'s tokens`,
  moved: ["moved", "this press"],
  rule: { encoder: "Every query attends to every key, so every row is computed again.",
          decoder: "The keys after each query are masked, so only the new token's row is computed." },
  firstWait: "Next token adds the first token",
  eg: { encoder: "e.g. BERT · understanding: classification, named entity recognition, de-identification",
        decoder: "e.g. GPT · generation: language modelling, text generation, dialogue",
        "encoder-decoder": "e.g. T5, BART · sequence to sequence: translation, summarisation, image → text" },

  /* page 3 */
  encRows: "rows and columns: the gene", decRows: "rows and columns: the protein so far",
  crossCols: "keys and values (columns): the encoder's output", crossRows: "queries (rows): the decoder",
  written: "the protein written so far, each amino acid over its codon",
  xWait: "Next amino acid adds the first row",

  tileTokens: "Tokens", tileTokensNote: "entered so far",
  tileMoved: "Earlier tokens moved", tileMovedNote: "on the last press, of those already there",
  tileMax: "Largest move", tileMaxNote: "how far an earlier token's final vector moved",
  tileAmino: "Amino acids", tileAminoNote: "written so far",
  tileProt: "Protein", tileProtNote: "the amino acids written",
  tileCodon: "On its own codon", tileCodonNote: "the newest row's weight on its three nucleotides",
  sum: (page, n, max) => `${page}: ${n} of ${max} computed.`,
};

/* ============================================================ the card */

const MATHML = mathmlRenders();
let cardHost = null, cardKey = null;
const mi = (s) => `<mi>${s}</mi>`, mo = (s) => `<mo>${s}</mo>`;
const sub = (v, s) => `<msub>${mi(v)}${mi(s)}</msub>`;
const SOFT = (inner) => `<msub>${mi("softmax")}${mi("j")}</msub>${mo("(")}${inner}${mo(")")}`;
const QK = `<mfrac><mrow>${sub("q", "i")}${mo("·")}${sub("k", "j")}</mrow><msqrt>${sub("d", "k")}</msqrt></mfrac>`;
const MATH = {
  encoder: `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(QK)}</mrow></math>`,
  decoder: `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(`${QK}${mo("+")}${sub("m", "ij")}`)}</mrow></math>`,
  "encoder-decoder": `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(QK)}</mrow></math>`,
};
const PLAIN = { encoder: "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ)", decoder: "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ + mᵢⱼ)", "encoder-decoder": "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ)" };
const NOTE = {
  encoder: "i and j: the encoder's tokens, every j", decoder: "mᵢⱼ = −∞ for j > i, else 0",
  "encoder-decoder": "in cross-attention, i: the decoder's tokens, j: the encoder's",
};
function renderCard(params) {
  const figure = document.querySelector("#widget .w-figure");
  if (!figure || !figure.parentNode) return;
  const which = params.page;
  if (!cardHost) { cardHost = document.createElement("div"); cardHost.className = "w-math"; cardHost.style.minHeight = "2.4em"; figure.parentNode.insertBefore(cardHost, figure); cardKey = null; }
  if (which === cardKey) return;
  cardKey = which;
  cardHost.innerHTML = `<div class="w-math-eq" style="min-height:0">${MATHML ? MATH[which] : `<span>${PLAIN[which]}</span>`}`
    + `<span style="color:var(--ink-3);font-size:var(--fs-xs)">&nbsp;&nbsp;${NOTE[which]}</span></div>`;
}

/* ============================================================ drawing kit */

const PAD_L = 12, PAD_R = 12;
const rgb = (c) => { const m = String(c).match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : [128, 128, 128]; };
const mixRgb = (a, b, t) => a.map((x, i) => Math.round(x + (b[i] - x) * Math.max(0, Math.min(1, t))));
const css = (p) => `rgb(${p.join(",")})`;
const lum = (p) => (0.2126 * p[0] + 0.7152 * p[1] + 0.0722 * p[2]) / 255;
/* a weight on one ramp from --surface-3 to --c-magnitude; √ so small weights still show */
const weightRgb = (colors, w) => mixRgb(rgb(colors.surface3), rgb(colors.magnitude), Math.sqrt(w));
/** the ink that reads on a fill: whichever of ink and surface is further from it in luminance */
const inkOn = (colors, p) => (Math.abs(lum(p) - lum(rgb(colors.ink1))) > Math.abs(lum(p) - lum(rgb(colors.surface))) ? colors.ink1 : colors.surface);
const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2);
const lerp = (a, b, t) => a + (b - a) * t;
const mono = (colors) => `${colors.fsXs} ${colors.mono}`;
const cap = (colors) => `600 ${colors.fsSm} ${colors.font}`;
const small = (colors) => `${colors.fsXs} ${colors.font}`;

function txt(ctx, s, x, y, { font, fill, align = "left", baseline = "middle" }) {
  ctx.save(); ctx.font = font; ctx.fillStyle = fill; ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
function poly(ctx, pts, stroke, lw = 1.5, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); pts.forEach(([x, y], i) => (i ? ctx.lineTo(x, y) : ctx.moveTo(x, y))); ctx.stroke(); ctx.restore();
}
function arrow(ctx, x1, y1, x2, y2, stroke, lw = 1.2) {
  poly(ctx, [[x1, y1], [x2, y2]], stroke, lw);
  const a = Math.atan2(y2 - y1, x2 - x1);
  ctx.save(); ctx.fillStyle = stroke; ctx.beginPath(); ctx.moveTo(x2, y2);
  ctx.lineTo(x2 - 6 * Math.cos(a - 0.45), y2 - 6 * Math.sin(a - 0.45)); ctx.lineTo(x2 - 6 * Math.cos(a + 0.45), y2 - 6 * Math.sin(a + 0.45)); ctx.fill(); ctx.restore();
}
function rect(ctx, x, y, w, h, stroke, lw = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash); ctx.strokeRect(x, y, w, h); ctx.restore();
}
const textW = (ctx, font, s) => { ctx.save(); ctx.font = font; const w = ctx.measureText(s).width; ctx.restore(); return w; };
function rotated(ctx, s, x, y, opts) { ctx.save(); ctx.translate(x, y); ctx.rotate(-Math.PI / 2); txt(ctx, s, 0, 0, opts); ctx.restore(); }

/* ----------------------------------------------------------- the stacks */

/* ONE STACK, AS HIS FIGURES DRAW IT: the output at the top, the block's boxes in a
   dashed frame marked × 2, the embedding, the input at the bottom; every box filled
   in the stack's hue, the one joined to a matrix outlined in ink. Returns each box's
   rectangle by key, and the stack's bottom. */
const SK = { bh: 26, bh2: 34, gap: 14 };
/** a stack's height with `n1` one-line and `n2` two-line boxes in its frame */
const stackHeight = (n1, n2) => 8 + 20 + n1 * SK.bh + n2 * SK.bh2 + (n1 + n2 - 1) * SK.gap + 14 + 20 + SK.bh + 26 + 4;
function stack(ctx, colors, x, top, w, hue, { title, blocks, hot, input, output }) {
  const r = {}, ink = inkOn(colors, rgb(hue));
  const draw = (key, lines, y, h) => {
    ctx.fillStyle = hue; ctx.fillRect(x, y, w, h);
    if (hot.includes(key)) rect(ctx, x - 1.5, y - 1.5, w + 3, h + 3, colors.ink1, 2);
    [].concat(lines).forEach((l, i, all) => txt(ctx, l, x + w / 2, y + h / 2 + (i - (all.length - 1) / 2) * 12, { font: small(colors), fill: ink, align: "center" }));
    r[key] = { x, y, w, h };
  };
  let y = top;
  txt(ctx, output, x + w / 2, y, { font: small(colors), fill: colors.ink2, align: "center" }); y += 8;
  arrow(ctx, x + w / 2, y + 14, x + w / 2, y + 3, colors.ink3); y += 20;
  const fTop = y - 4;
  blocks.forEach(([key, lines], i) => {
    const h = [].concat(lines).length > 1 ? SK.bh2 : SK.bh;
    draw(key, lines, y, h);
    if (i > 0) { const up = r[blocks[i - 1][0]]; arrow(ctx, x + w / 2, y - 1, x + w / 2, up.y + up.h + 2, colors.ink3); }
    y += h + (i < blocks.length - 1 ? SK.gap : 0);
  });
  rect(ctx, x - 7, fTop, w + 14, y - fTop + 4, colors.reference, 1.3, [4, 3]);
  txt(ctx, S.times, x + w + 7, fTop - 8, { font: small(colors), fill: colors.reference, align: "right" });
  y += 14; arrow(ctx, x + w / 2, y + 14, x + w / 2, y + 2, colors.ink3); y += 20;
  draw("embedding", S.embedding, y, SK.bh); y += SK.bh;
  arrow(ctx, x + w / 2, y + 16, x + w / 2, y + 2, colors.ink3); y += 26;
  txt(ctx, input, x + w / 2, y, { font: small(colors), fill: colors.ink2, align: "center" });
  rotated(ctx, title, x - 16, (fTop + r.embedding.y) / 2, { font: cap(colors), fill: colors.ink1, align: "center" });
  r.bottom = y + 4;
  return r;
}

/** weights as a grid: rows over columns, labels in their sources' hues; a null cell blank */
function matrix(ctx, colors, cell, R, K, rt, ct, x0, y0, cs, { rowHue, colHue, rowOn = () => true, colOn = () => true, colLabels = true, rowLabels = true, digits = true }) {
  const font = mono(colors), gap = cs > 5 ? 1 : 0;
  if (colLabels) ct.forEach((t, j) => rotated(ctx, t, x0 + j * cs + cs / 2, y0 - 5, { font, fill: colOn(j) ? colHue : colors.ink3, align: "left" }));
  for (let i = 0; i < R; i++) {
    if (rowLabels) txt(ctx, rt[i], x0 - 5, y0 + i * cs + cs / 2, { font, fill: rowOn(i) ? rowHue : colors.ink3, align: "right" });
    for (let j = 0; j < K; j++) {
      const x = x0 + j * cs, y = y0 + i * cs, v = cell(i, j), p = v === null ? null : weightRgb(colors, v);
      ctx.fillStyle = p ? css(p) : colors.surface2; ctx.fillRect(x, y, cs - gap, cs - gap);
      if (p && digits && cs >= 22) txt(ctx, v.toFixed(2).replace(/^0/, ""), x + cs / 2 - 0.5, y + cs / 2, { font, fill: inkOn(colors, p), align: "center" });
    }
  }
  rect(ctx, x0 - 0.5, y0 - 0.5, K * cs, R * cs, colors.ink2);
  return { x0, y0, w: K * cs, h: R * cs };
}
/* the newest row outlined, gliding down from the last one */
function rowOutline(ctx, colors, m, ch, n, t) {
  if (n < 1) return;
  const y = n >= 2 ? lerp(n - 2, n - 1, ease(t)) : n - 1;
  rect(ctx, m.x0 - 2.5, m.y0 + y * ch - 2, m.w + 4, ch + 3, colors.ink1, 1.5, [3, 3]);
}

/* ================================================= pages 1–2: Encoder and Decoder */

/* A PRESS IS A TOKEN ENTERING (his ask: "show how tokens enter then the scores get
   updated"). Two beats: the token glides in from the right along the sentence (the
   only thing that moves, in the empty lane past the last token), then the weights:
   in the encoder an outline steps down every row, each switching to its new weights
   and gaining its bar as the outline reaches it; in the decoder the outline goes to
   the new row alone, and the earlier rows' bars read 0 at once. */
const GLIDE = 0.35;
const SELF_MS = { step: 1400, run: 800 }, ENCDEC_MS = { step: 520, run: 300 };
const PG = { top: 16, sy: 128, labH: 66, stackW: 108 };
const pgGeom = (w) => {
  const sx = PAD_L + 24, sw = Math.min(PG.stackW, Math.round(w * 0.22)), r0 = sx + sw + 44, slot = (w - PAD_R - r0) / N;
  const x0 = r0 + 62, cs = Math.max(14, Math.min(26, Math.floor((w - PAD_R - 58 - x0) / N)));
  const mTop = PG.sy + 36 + PG.labH, mBot = mTop + N * cs;
  return { sx, sw, r0, slot, x0, cs, mTop, mBot, bx: x0 + N * cs + 6 };
};
const heightSelf = (w) => pgGeom(w).mBot + 16 + 20 + 20 + 14;
/** where the tokens stand: centred in their slots, every other one lifted a line where the slots are narrower than the words */
function slotsOf(ctx, colors, g) {
  const crowded = TOKENS.some((t) => textW(ctx, mono(colors), t) + 6 > g.slot);
  return TOKENS.map((_, j) => ({ x: g.r0 + j * g.slot + g.slot / 2, y: PG.sy - (crowded && j % 2 ? 13 : 0) }));
}
/** a press's beats: the glide `e`, and how many rows show their new weights */
function selfPhase(pg, enc) {
  const n = pg.n;
  if (n === 0 || pg.t >= 1) return { n, e: 1, gliding: false, done: n, cursor: -1 };
  if (pg.t < GLIDE) return { n, e: ease(pg.t / GLIDE), gliding: true, done: enc ? 0 : n - 1, cursor: -1 };
  const u = (pg.t - GLIDE) / (1 - GLIDE);
  if (!enc) return { n, e: 1, gliding: false, done: n - 1, cursor: n - 1 };
  const cursor = Math.min(n - 1, Math.floor(u * n));
  return { n, e: 1, gliding: false, done: cursor, cursor };
}

function drawSelf(ctx, colors, w, params, state, pg) {
  const enc = params.page === "encoder", hue = enc ? colors.groupA : colors.groupB, who = enc ? "encoder" : "decoder";
  const E = enc ? state.enc : state.dec, g = pgGeom(w), ph = selfPhase(pg, enc), { n } = ph, q = Number(params.query) - 1;
  const attKey = enc ? "self" : "masked";
  const st = stack(ctx, colors, g.sx, PG.top, g.sw, hue, {
    title: enc ? S.enc : S.dec, hot: [attKey], input: enc ? S.encIn : S.decIn, output: enc ? S.encOut : S.decOut,
    blocks: [["ffn", S.ffn], [attKey, enc ? S.selfAtt : S.masked]],
  });
  /* the rows as they stand at this beat: row i shows the new run once the outline has passed it */
  const runOf = (i) => (i < ph.done || (!enc && i < n - 1) ? n : n - 1);
  const cellOf = (i, j) => {
    if (i >= n) return null;
    const k = runOf(i);
    if (i >= k || j >= k || (!enc && j > i)) return null;
    return E.runs[k].alpha[i][j];
  };
  /* the sentence, the newest token gliding in */
  const slots = slotsOf(ctx, colors, g);
  txt(ctx, n > q ? S.queryCap(TOKENS[q]) : S.notYet(TOKENS[q]), g.r0, PG.top, { font: small(colors), fill: colors.ink3 });
  for (let j = 0; j < n; j++) {
    const s = slots[j], x = ph.gliding && j === n - 1 ? lerp(w - PAD_R, s.x, ph.e) : s.x;
    txt(ctx, TOKENS[j], x, s.y, { font: j === q ? `600 ${colors.fsXs} ${colors.mono}` : mono(colors), fill: j === q ? colors.ink1 : hue, align: "center" });
  }
  if (n === 0) txt(ctx, S.firstWait, g.r0, PG.sy, { font: small(colors), fill: colors.ink3 });
  /* the query's arcs, his figure's: a loop below for itself, an arc above to each other token */
  const kq = q < n ? runOf(q) : 0;
  if (q < kq) {
    const row = E.runs[kq].alpha[q], a = slots[q];
    row.forEach((wt, j) => {
      if ((!enc && j > q) || wt < 0.004) return;
      const p = weightRgb(colors, 0.3 + 0.7 * wt), lw = 0.8 + 8 * wt;
      ctx.save(); ctx.strokeStyle = css(p); ctx.lineWidth = lw; ctx.beginPath();
      if (j === q) ctx.arc(a.x, a.y + 19, 8, 0, 2 * Math.PI);
      else { const b = slots[j], hgt = Math.min(84, 14 + 10 * Math.abs(j - q)); ctx.moveTo(a.x, a.y - 9); ctx.bezierCurveTo(a.x, a.y - 9 - hgt, b.x, b.y - 9 - hgt, b.x, b.y - 10); }
      ctx.stroke(); ctx.restore();
    });
  }
  /* the matrix, joined to the attention box */
  const m = matrix(ctx, colors, cellOf, N, N, TOKENS, TOKENS, g.x0, g.mTop, g.cs, { rowHue: hue, colHue: hue, rowOn: (i) => i < n, colOn: (j) => j < n });
  const b = st[attKey], bx = g.x0 - 60, lx = g.x0 - 66;
  poly(ctx, [[b.x + b.w + 3, b.y + b.h / 2], [lx, b.y + b.h / 2], [lx, g.mTop + m.h / 2], [bx, g.mTop + m.h / 2]], colors.ink1, 1.5);
  poly(ctx, [[bx, g.mTop], [bx, g.mTop + m.h]], colors.ink1, 1.5);
  if (ph.cursor >= 0) rect(ctx, g.x0 - 2.5, g.mTop + ph.cursor * g.cs - 2, m.w + 4, g.cs + 3, colors.ink1, 1.5, [3, 3]);
  /* how far each earlier token's final vector moved on this press */
  S.moved.forEach((s, i) => txt(ctx, s, g.bx, g.mTop - 22 + i * 12, { font: small(colors), fill: colors.ink3 }));
  const room = w - PAD_R - g.bx - 26;
  if (n >= 2) for (let i = 0; i < n - 1; i++) {
    if (enc && i >= ph.done && pg.t < 1) continue;
    if (!enc && ph.gliding) continue;
    const v = E.move[n][i], len = Math.min(room, v * (room / 15)), y = g.mTop + i * g.cs;
    ctx.fillStyle = hue; ctx.fillRect(g.bx, y + 6, len, g.cs - 12);
    txt(ctx, v.toFixed(1), g.bx + len + 3, y + g.cs / 2, { font: mono(colors), fill: colors.ink1 });
  }
  txt(ctx, S.sources(who), PAD_L, g.mBot + 16, { font: small(colors), fill: hue });
  txt(ctx, S.rule[params.page], PAD_L, g.mBot + 36, { font: small(colors), fill: colors.ink2 });
  txt(ctx, S.eg[params.page], PAD_L, g.mBot + 56, { font: small(colors), fill: colors.ink3 });
}

/* ===================================================== page 3: Encoder–decoder */

/* HIS TWO-STACK FIGURE ON TOP, three leaders down: the encoder's self-attention to
   the gene × gene matrix, the decoder's masked self-attention to the protein's
   triangle, and cross-attention to the cross matrix, whose columns are the encoder's
   output (blue) and rows the decoder's queries (amber). A press writes the next
   amino acid over its codon, lines from it down to the nucleotides it reads, and
   both decoder matrices gain a row. One gene (his pick of one example). */
const XD = { ce: 7, cd: 14, cross: 20 };
const xdGeom = (w) => {
  const top = 22, encX = PAD_L + 58, encW = Math.min(112, Math.round(w * 0.2)), decW = Math.min(124, Math.round(w * 0.23));
  const decX = Math.round(Math.min(w * 0.6, w - PAD_R - 70 - decW));
  /* the encoder's stack sits lower by the decoder's extra box, so both embeddings line up */
  const encTop = top + (stackHeight(2, 1) - stackHeight(2, 0));
  const mTop = top + stackHeight(2, 1) + 12;
  const cc = Math.max(12, Math.min(XD.cross, Math.floor((w - PAD_R - 40 - 96) / 18)));
  const cy = mTop + 36 + 7 * XD.cd + 118;
  return { top, encTop, encX, encW, decX, decW, mTop, cc, cy, eg: cy + 6 * cc + 36 };
};
const heightEncDec = (w) => xdGeom(w).eg + 14;

function drawEncDec(ctx, colors, w, params, state, pg) {
  const g = xdGeom(w), T = state.dna, nt = T.dna.split(""), prot = ["[BOS]", ...T.protein], R = pg.n;
  const blue = colors.groupA, amber = colors.groupB;
  const Se = stack(ctx, colors, g.encX, g.encTop, g.encW, blue, {
    title: S.enc, hot: ["self"], input: S.geneIn, output: S.encOut, blocks: [["ffn", S.ffn], ["self", S.selfAtt]] });
  const Sd = stack(ctx, colors, g.decX, g.top, g.decW, amber, {
    title: S.dec, hot: ["masked", "cross"], input: S.protIn, output: S.protOut, blocks: [["ffn", S.ffn], ["cross", S.cross], ["masked", S.masked]] });
  /* the encoder's output into the decoder's cross-attention, as his figure */
  const cr = Sd.cross, ox = g.encX + g.encW / 2, midX = Math.round((g.encX + g.encW + g.decX) / 2 + 6);
  poly(ctx, [[ox, g.encTop - 8], [ox, g.top - 14], [midX, g.top - 14], [midX, cr.y + cr.h / 2]], blue, 1.5);
  arrow(ctx, midX, cr.y + cr.h / 2, cr.x - 22, cr.y + cr.h / 2, blue, 1.5);
  /* the encoder's attention over the gene */
  const E = M.meanHeads(T.enc[1]);
  const me = matrix(ctx, colors, (i, j) => E[i][j], 18, 18, nt, nt, 30, g.mTop + 16, XD.ce, { rowHue: blue, colHue: blue, colLabels: false, rowLabels: false, digits: false });
  txt(ctx, S.encRows, 24, g.mTop, { font: small(colors), fill: blue });
  const se = Se.self;
  poly(ctx, [[se.x - 3, se.y + se.h / 2], [PAD_L + 4, se.y + se.h / 2], [PAD_L + 4, me.y0 + me.h / 2], [me.x0 - 4, me.y0 + me.h / 2]], colors.ink1, 1.5);
  /* the decoder's masked attention over the protein so far */
  const Ds = M.meanHeads(T.self[1]), dx = Math.round(g.decX - 20);
  const md = matrix(ctx, colors, (i, j) => (i < R && j <= i ? Ds[i][j] : null), 7, 7, prot, prot, dx, g.mTop + 40, XD.cd,
    { rowHue: amber, colHue: amber, rowOn: (i) => i < R, colOn: (j) => j < R, digits: false });
  txt(ctx, S.decRows, dx - 50, g.mTop, { font: small(colors), fill: amber });
  rowOutline(ctx, colors, md, XD.cd, R, pg.t);
  const ms = Sd.masked, rx1 = w - PAD_R - 22, rx2 = w - PAD_R - 6;
  poly(ctx, [[ms.x + ms.w + 3, ms.y + ms.h / 2], [rx1, ms.y + ms.h / 2], [rx1, md.y0 + md.h / 2], [md.x0 + md.w + 4, md.y0 + md.h / 2]], colors.ink1, 1.5);
  /* the protein written over its codons, lines from the newest down to the nucleotides it reads */
  const cc = g.cc, cx = PAD_L + 84, cy = g.cy, X = M.crossMean(T), yP = cy - 78, yN = cy - 10;
  const colX = (j) => cx + j * cc + cc / 2, aaX = (r) => cx + (3 * r + 1.5) * cc;
  txt(ctx, S.crossCols, cx, cy - 100, { font: small(colors), fill: blue });
  for (let r = 0; r < R; r++) txt(ctx, T.protein[r], aaX(r), yP, { font: `600 ${colors.fsSm} ${colors.mono}`, fill: amber, align: "center" });
  if (R > 0) X[R - 1].forEach((wt, j) => {
    if (wt < 0.01) return;
    ctx.save(); ctx.strokeStyle = css(weightRgb(colors, 0.3 + 0.7 * wt)); ctx.lineWidth = 0.8 + 8 * wt;
    ctx.beginPath(); ctx.moveTo(aaX(R - 1), yP + 9); ctx.lineTo(colX(j), yN - 18); ctx.stroke(); ctx.restore();
  });
  T.codons.forEach((_, k) => poly(ctx, [[cx + 3 * k * cc + 2, yN - 12.5], [cx + 3 * k * cc + 3 * cc - 3, yN - 12.5]], colors.ink3, 1));
  nt.forEach((c, j) => txt(ctx, c, colX(j), yN, { font: mono(colors), fill: blue, align: "center" }));
  const rows = prot.slice(0, 6).map((p, r) => `${p} → ${r < R ? prot[r + 1] : "?"}`);
  const mx = matrix(ctx, colors, (i, j) => (i < R ? X[i][j] : null), 6, 18, rows, nt, cx, cy, cc, { rowHue: amber, colHue: blue, rowOn: (i) => i < R, colLabels: false, digits: false });
  rowOutline(ctx, colors, mx, cc, R, pg.t);
  txt(ctx, S.crossRows, PAD_L, mx.y0 + mx.h + 14, { font: small(colors), fill: amber });
  poly(ctx, [[cr.x + cr.w + 3, cr.y + cr.h / 2], [rx2, cr.y + cr.h / 2], [rx2, mx.y0 + mx.h / 2], [mx.x0 + mx.w + 4, mx.y0 + mx.h / 2]], colors.ink1, 1.5);
  if (R === 0) txt(ctx, S.xWait, cx + 8, cy + 3 * cc, { font: small(colors), fill: colors.ink3 });
  txt(ctx, S.eg[params.page], PAD_L, g.eg, { font: small(colors), fill: colors.ink3 });
}

/* ============================================================ the widget */

const maxOf = (page) => (page === "encoder-decoder" ? 6 : N);
const msOf = (page, mode) => (page === "encoder-decoder" ? ENCDEC_MS : SELF_MS)[mode === "run" ? "run" : "step"];
const pageOf = (anim, params) => anim.p[params.page];
function settle(anim, params) {
  anim.page = params.page;
  const pg = anim.p[params.page];
  anim.done = pg.n >= maxOf(params.page) && pg.t >= 1;
}

/* memoised: compute() is pure, and nothing here depends on a parameter */
let STAGE = null;
const stage = () => (STAGE ??= { enc: M.entering("base"), dec: M.entering("causal"), dna: M.translate(M.GENES[0]) });

defineWidget({
  slug: "transformer",
  status: "draft",
  title: S.title,
  subtitle: S.subtitle,
  layout: "side",
  height: ({ page, w }) => (page === "encoder-decoder" ? heightEncDec(w) : heightSelf(w)),

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "encoder", display: true },
    query: {
      type: "select", label: S.queryLabel, detail: S.queryDetail, display: true, when: SELF,
      options: TOKENS.map((t, i) => ({ value: String(i + 1), label: `${i + 1} · ${t}` })), default: "4",
    },
    /* authoring escape hatch, first render only: presses already made on the page opened */
    shown: { type: "int", min: 0, max: 8, default: 0, hidden: true },
  },

  legend: [],

  /* a click on an entered token of the sentence chooses the query; the geometry from the
     width and the page's press count alone (core validates the table before compute runs) */
  regions: ({ w, params, anim }) => {
    if (params.page === "encoder-decoder" || !anim?.p) return [];
    const g = pgGeom(w), n = anim.p[params.page].n;
    return TOKENS.slice(0, n).map((t, j) => ({ x: g.r0 + j * g.slot, y: PG.sy - 26, w: g.slot, h: 40, set: { query: String(j + 1) }, label: t }));
  },

  compute: () => stage(),

  animation: {
    stepLabel: { param: "page", labels: S.step, default: S.step.encoder },
    stepTitle: { param: "page", labels: S.stepTitle, default: S.stepTitle.encoder },
    runLabel: S.runLabel,
    runTitle: S.runTitle,
    init: ({ params, fromScratch }) => {
      const anim = { p: { encoder: { n: 0, t: 1 }, decoder: { n: 0, t: 1 }, "encoder-decoder": { n: 0, t: 1 } }, moving: false, halt: false };
      if (!fromScratch) anim.p[params.page].n = Math.max(0, Math.min(maxOf(params.page), Number(params.shown) || 0));
      settle(anim, params);
      return anim;
    },
    advance: (anim, { dt, params }) => {
      /* the loop a page switch left running for the other page's press ends here */
      if (anim.halt) { anim.halt = false; anim.moving = false; settle(anim, params); return false; }
      const pg = anim.p[params.page], max = maxOf(params.page), ms = msOf(params.page, anim.mode);
      let more;
      if (pg.t < 1) { pg.t = Math.min(1, pg.t + dt / ms); more = pg.t < 1 || (anim.mode === "run" && pg.n < max); }
      else if (pg.n < max) { pg.n += 1; pg.t = 0; more = true; }
      else more = false;
      anim.moving = more;
      settle(anim, params);
      return more;
    },
    rebuild: (anim, { params }) => {
      /* A PRESS BELONGS TO THE PAGE IT STARTED ON (widget 70's rule): a switch
         mid-press finishes it, and `halt` ends the loop at its next frame. Only
         while a press moves: set otherwise, it would swallow the reader's next press. */
      if (anim.moving && params.page !== anim.page) {
        for (const pg of Object.values(anim.p)) pg.t = 1;
        anim.halt = true;
      }
      settle(anim, params);
    },
  },

  draw({ ctx, colors, w, params, state, anim }) {
    renderCard(params);
    if (params.page === "encoder-decoder") drawEncDec(ctx, colors, w, params, state, pageOf(anim, params));
    else drawSelf(ctx, colors, w, params, state, pageOf(anim, params));
  },

  readout({ params, state, anim }) {
    const pg = pageOf(anim, params), k = pg.t >= 1 ? pg.n : pg.n - 1;
    if (params.page === "encoder-decoder") {
      const A = M.crossMean(state.dna), r = pg.n - 1;
      return [
        { label: S.tileAmino, value: `${Math.max(0, k)} of 6`, note: S.tileAminoNote },
        { label: S.tileProt, value: k > 0 ? state.dna.protein.slice(0, k).join("") : S.wait, note: S.tileProtNote },
        { label: S.tileCodon, value: r >= 0 ? (A[r][3 * r] + A[r][3 * r + 1] + A[r][3 * r + 2]).toFixed(2) : S.wait, note: S.tileCodonNote },
      ];
    }
    const E = params.page === "encoder" ? state.enc : state.dec, mv = pg.n >= 2 && pg.t >= 1 ? E.move[pg.n] : null;
    const top = mv ? mv.indexOf(Math.max(...mv)) : -1;
    return [
      { label: S.tileTokens, value: `${Math.max(0, k)} of ${N}`, note: S.tileTokensNote },
      { label: S.tileMoved, value: mv ? `${mv.filter((v) => v > 0).length} of ${mv.length}` : S.wait, note: S.tileMovedNote },
      { label: S.tileMax, value: !mv ? S.wait : mv[top] > 0 ? `${TOKENS[top]} ${mv[top].toFixed(1)}` : "0.0", note: S.tileMaxNote },
    ];
  },

  summary({ params, anim }) {
    const pg = pageOf(anim, params);
    return S.sum(PAGES.find((p) => p.value === params.page).label, pg.n, maxOf(params.page));
  },
});
