/* ============================================================================
   Widget 84 · Language: Transformer (`transformer`) — PHM5005 08-1 cells 2–4,
   Transformer Architecture, Transformer Tasks and Pre-training. DRAFT, rebuilt
   2026-09-29 to split training from inference, and 2026-09-30 into his block's
   sections under a map of his figure (catalogue § Slot 84).

   Three pages BY ARCHITECTURE (his framing), and on the two with a decoder a
   PHASE, Training · Generation (his pick A, 2026-09-29,
   `_lab/transformer-phases-mock.html`):

     ENCODER          Training: the lesson's own masked sentence (08-1 cell 4,
                      "treated with [MASK] for chest pain"): every row reads every
                      token; the [MASK] row's prediction is the one training
                      scores. Prediction (his ask, 2026-09-30: an encoder has no
                      generation): the sentence read whole, the same encoder
                      frozen, and a head trained afterwards on its vectors gives
                      every token a tag — other, drug, finding, negated finding
                      (measured, `_lab/transformer-task-measure.py`: 94.9% from
                      the token + position vector, where "chest" asserted and
                      denied are one row; 99.7% after block 1).
     DECODER          Training: the whole sentence, each row's true next token and
                      the probability the model gives it. Generation: the lesson's
                      prompt read a token at a time, then each prediction fed back.
     ENCODER–DECODER  the DNA -> protein model: the encoder's pass over the gene
                      once, then the decoder a row at a time, its masked
                      self-attention, its cross-attention over the gene, its output.

   THE LAYOUT (his picks, 2026-09-30, `_lab/transformer-layout-mock.html` and
   `_lab/transformer-overview-mock.html`): his block's boxes as SECTION HEADS read
   top to bottom (L3, no leader lines), his figure small in the top-right corner as
   the MAP, a number on each box and its section; a PRESS carries one row through
   the block a box at a time, the box it has reached ringed on the map and on its
   section; the OUTPUT LAYER, Linear + softmax, as the row's six largest
   probabilities. Hover rings a box and its section both ways, and on a token or a
   cell picks the row whose arcs or lines are drawn.

   WHY TRAINING GOES A ROW A PRESS, THOUGH IT IS ONE PASS (his "one-pass looks
   strange now"; measured, `_lab/transformer-phases-measure.mjs`): one pass over the
   whole sequence gives every row and every next-token distribution EXACTLY what a
   token at a time gives — the mask is why training runs in parallel. The press shows
   the rows one at a time and the caption says one pass computes them together.
   Generation is sequential because each output is the next input (10-3 cell 45).

   Encoder --c-group-a, decoder --c-group-b, every token label in its stack's hue;
   weights on the --c-magnitude ramp, so nothing here is --c-highlight: what the
   press is at is ringed in ink.

   THE MODELS ARE TRAINED AND ONLY READ (model.js, weights generated by
   `_lab/transformer-weights.py`, held to torch by `_lab/transformer-verify.mjs`).
   EACH PAGE AND PHASE KEEPS ITS OWN PLACE (`anim.p[key]`); a switch mid-press
   finishes the press and `halt` ends the loop (widget 70's rule).
   ========================================================================= */

import { defineWidget, mathmlRenders } from "../core/index.js";
import * as M from "./model.js";

const PAGES = [{ value: "encoder", label: "Encoder" }, { value: "decoder", label: "Decoder" }, { value: "encoder-decoder", label: "Encoder–decoder" }];
const TOKENS = M.tokensOf(M.SENTENCE), N = TOKENS.length, MASK_AT = 3;
const PROMPT = "treated with aspirin for";

/* ================================================================== copy */

const S = {
  title: "Deep Learning - Language: Transformer",
  subtitle: "Encoders and decoders are built from the same blocks and differ in which tokens each query may attend to. In an encoder "
    + "every token attends to the whole sequence, so each token's vector depends on the tokens after it; in a decoder a token attends "
    + "only to the tokens before it, which lets the output be generated one token at a time. An encoder–decoder adds cross-attention: "
    + "queries from the output so far, keys and values from the encoded input.",
  pageLabel: "Step",
  phaseLabel: "Phase",
  /* the Encoder has no generation: its second phase is prediction, a task read from its vectors (his ask, 2026-09-30) */
  phaseOpts: {
    encoder: [{ value: "training", label: "Training", detail: "Masked-token pretraining: tokens hidden at random, each prediction scored against the hidden original." },
      { value: "prediction", label: "Prediction", detail: "The pretrained encoder, unchanged, and a head trained afterwards on its vectors: a tag for every token, or a class for the sentence." }],
    decoder: [{ value: "training", label: "Training", detail: "The whole sequence in one pass, each row scored on the true next token." },
      { value: "generation", label: "Generation", detail: "One token a step, each output fed back as the next input." }],
  },
  step: { encoder: "Next token", decoder: "Next token", "encoder-decoder": "Next amino acid" },
  stepTitle: { encoder: "Carry the next token's row through the block",
    decoder: { param: "phase", labels: { training: "Carry the next token's row through the block", generation: "Compute the next token and feed it back" } },
    "encoder-decoder": { param: "phase", labels: { training: "Carry the next row through the decoder", generation: "Compute the next amino acid and feed it back" } } },
  taskLabel: "Task",
  taskOpts: [{ value: "tokens", label: "Tokens", detail: "A tag for every word: other, drug, finding or negated finding." },
    { value: "sentence", label: "Sentence", detail: "The [CLS] row's final vector as the sentence's embedding, read by a head: negative or positive." }],
  runLabel: "Play", runTitle: "Run the rest",
  wait: "—",

  /* the boxes, as his figures label them, and Linear + softmax on top */
  ffn: "Feed forward", selfAtt: "Self-attention", masked: ["Masked self-", "attention"], maskedOne: "Masked self-attention", cross: "Cross-attention",
  embedding: "Embedding", linear: "Linear + softmax", times: "× 2",
  encIn: "Input sequence", encOut: "Predicted token", tagOut: "Tag per token", clsOut: "Negative / positive", poolBox: "Pooling: [CLS]", pooling: "Pooling", decIn: "Tokens so far", decOut: "Next token",
  geneIn: "The gene", protIn: "Protein so far", protOut: "Next amino acid",

  /* the sections' notes */
  note1: (v) => (v.tagging || v.sentence ? "the sentence, nothing hidden" : v.enc ? "the sentence, one token masked" : !v.gen ? "the whole sentence, given"
    : v.pr.n < v.k0 ? "the prompt" : "the prompt and the tokens fed back"),
  note2enc: "each row: its weights over every token", note2dec: "each row: over the tokens up to it",
  blockNote: (b) => [`block ${b},`, "mean of 4 heads"],
  note3: "the same small network on each row alone",
  note4: (n, what) => `a probability for each of the ${n} ${what}`, note4tag: (n) => `a new head: a probability for each of the ${n} tags`,
  tagHead: "tag", note4pool: "the [CLS] row's final vector: the sentence's embedding", note5cls: "a new head: negative or positive",
  vecCap: "the embedding: [CLS]'s 48 numbers, each a bar up or down from 0",
  outCls: (c) => `the sentence: ${c}, the more likely (positive: an abnormal finding is asserted)`, tokensWord: "tokens", aminoWord: "amino acids",
  gene: "the gene", encRows: "rows and columns: the gene", note5: "each protein row reads the gene",
  crossRows: "rows: protein", crossCols: "columns: gene",

  /* the output layer's titles */
  outMask: (t) => `the [MASK] row: the six largest; the masked token (${t}) in ink`,
  outTrain: (q, t) => `the row of ${q}: the six largest; the true next token (${t}) in ink`,
  outPrompt: (q, t) => `the row of ${q}: the six largest; the prompt's next token (${t}) in ink`,
  outGen: (q, t) => `the row of ${q}: the six largest; ${t}, the most likely, is fed back`,
  outTrainX: (q, t) => `the row of ${q}: the six largest; the true next amino acid (${t}) in ink`,
  outGenX: (q, t) => `the row of ${q}: the six largest; ${t}, the most likely, is fed back`,
  noTag: (q) => `the row of ${q}: not a word, so no tag`,
  outTag: (q, t) => `the row of ${q}: ${t}, the most likely tag`,
  notScored: (q) => `the row of ${q}: not scored; training predicts only the masked token`,

  /* the line under the figure */
  line: (params, v, state) => {
    const n = v.pr.n;
    if (n === 0) return v.gen ? "Next token reads the prompt's first token." : "Next token carries the first row through the block.";
    if (v.sentence) return v.pr.n <= N ? "Each row goes through the block. The last press takes the [CLS] row's final vector as the sentence's embedding and classifies it."
      : "Before attention the [CLS] row carries nothing of the note: a head on it scores 79%, the share of positive notes. After two blocks, 98%.";
    if (v.tagging) return "The pretrained encoder, unchanged, and a head trained afterwards on tagged notes: each row's vector gives its token's tag. One pass tags every token; a press shows one.";
    if (v.enc) return `Every row reads every token. One pass computes all ${N} rows together; a press shows one.`;
    if (!v.gen) return `Each row reads only the tokens up to it. One pass computes all ${N} rows together; a press shows one.`;
    const G = state.decG, r = v.pr.r;
    if (r < G.promptLen - 1) return "Reading the prompt: the token after each is given.";
    if (r === G.tokens.length - 2 && !v.pr.beat) return `The most likely next token is “${G.tokens[r + 1]}”, so generation stops.`;
    return "Generating: the most likely token is fed back as the next input, and only its row is computed.";
  },
  xLine: (params, pr, T) => {
    if (pr.n === 0) return params.phase === "training" ? "Next amino acid encodes the gene, then carries the first row through the decoder."
      : "Next amino acid encodes the gene, then computes the first amino acid.";
    if (pr.beat === 1 || pr.beat === 2) return "The encoder's pass over the whole gene, computed once.";
    if (params.phase === "training") return "The true protein is the decoder's input. One pass computes every row together; a press shows one.";
    if (pr.n === XD.rows && !pr.beat) return `The protein is written: ${T.protein.join("")}.`;
    return "Generating: the most likely amino acid is fed back as the next input.";
  },
  weightOf: (q, k, v) => `${q}'s weight on ${k}: ${v.toFixed(2)}`,
  eg: { encoder: "e.g. BERT · understanding: classification, named entity recognition, de-identification",
        decoder: "e.g. GPT · generation: language modelling, text generation, dialogue",
        "encoder-decoder": "e.g. T5, BART · sequence to sequence: translation, summarisation, image → text" },

  tileRows: "Rows", tileRowsNote: "computed, a press a row",
  tileMask: "[MASK]", tileMaskNote: "the masked row's most likely token",
  tileClass: "Class", tileClassNote: "the sentence, from its [CLS] row",
  tileTag: "Tag", tileTagNote: "the newest row's most likely tag",
  tileKeys: "Keys per row", tileKeysNote: "every token of the sentence",
  tileTarget: "Target", tileTargetNote: "the newest row's true next token, its probability",
  tileTargetNoteX: "the newest row's true amino acid, its probability",
  tileKeysRow: "Keys", tileKeysRowNote: "the newest row's: the tokens up to it",
  tileGen: "Tokens", tileGenNote: "the prompt and those fed back",
  tileNext: "Next token", tileNextNote: "the most likely, fed back",
  tileProt: "Protein", tileProtNote: "the amino acids written",
  tileCodon: "On its own codon", tileCodonNote: "the newest row's weight on its three nucleotides",
  sum: (page, n, max) => `${page}: ${n} of ${max} rows computed.`,
};

/* ============================================================ the card */

const MATHML = mathmlRenders();
let cardHost = null, cardKey = null;
const mi = (s) => `<mi>${s}</mi>`, mo = (s) => `<mo>${s}</mo>`;
const sub = (v, s) => `<msub>${mi(v)}${mi(s)}</msub>`;
const SOFT = (inner) => `<msub>${mi("softmax")}${mi("j")}</msub>${mo("(")}${inner}${mo(")")}`;
const QK = `<mfrac><mrow>${sub("q", "i")}${mo("·")}${sub("k", "j")}</mrow><msqrt>${sub("d", "k")}</msqrt></mfrac>`;
const MATH = {
  encoder: `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(QK)}</mrow></math>`,
  decoder: `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(`${QK}${mo("+")}${sub("m", "ij")}`)}</mrow></math>`,
  "encoder-decoder": `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(QK)}</mrow></math>`,
};
const PLAIN = { encoder: "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ)", decoder: "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ + mᵢⱼ)", "encoder-decoder": "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ)" };
const NOTE = {
  encoder: "i and j: the encoder's tokens, every j", decoder: "mᵢⱼ = −∞ for j > i, else 0",
  "encoder-decoder": "in cross-attention, i: the decoder's tokens, j: the encoder's",
};
function renderCard(params) {
  const figure = document.querySelector("#widget .w-figure");
  if (!figure || !figure.parentNode) return;
  const which = params.page;
  if (!cardHost) { cardHost = document.createElement("div"); cardHost.className = "w-math"; cardHost.style.minHeight = "2.4em"; figure.parentNode.insertBefore(cardHost, figure); cardKey = null; }
  if (which === cardKey) return;
  cardKey = which;
  cardHost.innerHTML = `<div class="w-math-eq" style="min-height:0">${MATHML ? MATH[which] : `<span>${PLAIN[which]}</span>`}`
    + `<span style="color:var(--ink-3);font-size:var(--fs-xs)">&nbsp;&nbsp;${NOTE[which]}</span></div>`;
}

/* ============================================================ drawing kit */

const PAD_L = 12, PAD_R = 12;
const rgb = (c) => { const m = String(c).match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : [128, 128, 128]; };
const mixRgb = (a, b, t) => a.map((x, i) => Math.round(x + (b[i] - x) * Math.max(0, Math.min(1, t))));
const css = (p) => `rgb(${p.join(",")})`;
const lum = (p) => (0.2126 * p[0] + 0.7152 * p[1] + 0.0722 * p[2]) / 255;
/* a weight on one ramp from --surface-3 to --c-magnitude; √ so small weights still show */
const weightRgb = (colors, w) => mixRgb(rgb(colors.surface3), rgb(colors.magnitude), Math.sqrt(w));
/** the ink that reads on a fill: whichever of ink and surface is further from it in luminance */
const inkOn = (colors, p) => (Math.abs(lum(p) - lum(rgb(colors.ink1))) > Math.abs(lum(p) - lum(rgb(colors.surface))) ? colors.ink1 : colors.surface);
const mono = (colors) => `${colors.fsXs} ${colors.mono}`;
const monoBold = (colors) => `600 ${colors.fsXs} ${colors.mono}`;
const cap = (colors) => `600 ${colors.fsSm} ${colors.font}`;
const small = (colors) => `${colors.fsXs} ${colors.font}`;

function txt(ctx, s, x, y, { font, fill, align = "left", baseline = "middle" }) {
  ctx.save(); ctx.font = font; ctx.fillStyle = fill; ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
function poly(ctx, pts, stroke, lw = 1.5, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); pts.forEach(([x, y], i) => (i ? ctx.lineTo(x, y) : ctx.moveTo(x, y))); ctx.stroke(); ctx.restore();
}
function arrow(ctx, x1, y1, x2, y2, stroke, lw = 1.2) {
  poly(ctx, [[x1, y1], [x2, y2]], stroke, lw);
  const a = Math.atan2(y2 - y1, x2 - x1);
  ctx.save(); ctx.fillStyle = stroke; ctx.beginPath(); ctx.moveTo(x2, y2);
  ctx.lineTo(x2 - 6 * Math.cos(a - 0.45), y2 - 6 * Math.sin(a - 0.45)); ctx.lineTo(x2 - 6 * Math.cos(a + 0.45), y2 - 6 * Math.sin(a + 0.45)); ctx.fill(); ctx.restore();
}
function rect(ctx, x, y, w, h, stroke, lw = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash); ctx.strokeRect(x, y, w, h); ctx.restore();
}
const textW = (ctx, font, s) => { ctx.save(); ctx.font = font; const w = ctx.measureText(s).width; ctx.restore(); return w; };
function rotated(ctx, s, x, y, opts) { ctx.save(); ctx.translate(x, y); ctx.rotate(-Math.PI / 2); txt(ctx, s, 0, 0, opts); ctx.restore(); }
function head(ctx, x, y, ang, size, col) {
  ctx.save(); ctx.fillStyle = col; ctx.beginPath(); ctx.moveTo(x, y);
  ctx.lineTo(x - size * Math.cos(ang - 0.45), y - size * Math.sin(ang - 0.45)); ctx.lineTo(x - size * Math.cos(ang + 0.45), y - size * Math.sin(ang + 0.45)); ctx.fill(); ctx.restore();
}

/* ------------------------------------------------------ his figure, as a map */

/* HIS FIGURE, SMALL, IN THE TOP-RIGHT CORNER (his pick O2, 2026-09-30,
   `_lab/transformer-overview-mock.html`): the page below takes it apart into
   sections read top to bottom, and a number ties each box to its section, so no
   leader is needed (his "maybe we don't need the lines"). The map keeps his
   orientation, the input at the bottom. During a press the box the row has reached
   is ringed in ink, on the map and on its section's number; at rest, pointing at a
   box or at a section rings both. His feed-back arrow is drawn in Generation only:
   training feeds nothing back. A box's number sits on its left edge, half out, and
   the label moves right to clear it: the gaps between boxes are narrower than a
   number, and the widest label ("Linear + softmax", 81 px at --fs-xs) leaves 91 px
   room for 5. 91 is also the widest that keeps page 3's three columns at 547. */
const MP = { bw: 91, bh: 20, bh2: 30, pad: 12, shift: 5 };
/* the one-stack map keeps 14 px right of its feed-back arrow for the word riding it ("pain" is 28 px);
   page 3's riders are single letters */
const MAP1_W = MP.pad + MP.bw + 20 + 14, MAP2_W = MP.pad + MP.bw + 22 + MP.bw + 20;
const bold = (colors) => `600 ${colors.fsXs} ${colors.font}`;

/** the number that ties a box to its section: the box's hue, ringed in ink when lit */
function badge(ctx, colors, x, y, k, hue, lit) {
  ctx.save();
  ctx.beginPath(); ctx.arc(x, y, 8, 0, 2 * Math.PI); ctx.fillStyle = colors.surface; ctx.fill();
  ctx.beginPath(); ctx.arc(x, y, 6.5, 0, 2 * Math.PI); ctx.fillStyle = hue; ctx.fill();
  if (lit) { ctx.beginPath(); ctx.arc(x, y, 8.2, 0, 2 * Math.PI); ctx.strokeStyle = colors.ink1; ctx.lineWidth = 2; ctx.stroke(); }
  ctx.restore();
  txt(ctx, String(k), x, y + 0.5, { font: bold(colors), fill: inkOn(colors, rgb(hue)), align: "center" });
}
function mapBox(ctx, colors, b, lines, hue, k, lit, ring = lit) {
  ctx.fillStyle = hue; ctx.fillRect(b.x, b.y, b.w, b.h);
  if (ring) rect(ctx, b.x - 1.5, b.y - 1.5, b.w + 3, b.h + 3, colors.ink1, 2);
  const lx = b.x + b.w / 2 + (k ? MP.shift : 0);
  [].concat(lines).forEach((l, i, all) => txt(ctx, l, lx, b.y + b.h / 2 + (i - (all.length - 1) / 2) * 12, { font: small(colors), fill: inkOn(colors, rgb(hue)), align: "center" }));
  if (!k) return;
  /* on the box's hue a number needs its own ground: the surface, the number in ink */
  const x = b.x, y = b.y + b.h / 2;
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, 7, 0, 2 * Math.PI); ctx.fillStyle = colors.surface; ctx.fill();
  if (lit) { ctx.strokeStyle = colors.ink1; ctx.lineWidth = 2; ctx.stroke(); }
  ctx.restore();
  txt(ctx, String(k), x, y + 0.5, { font: bold(colors), fill: colors.ink1, align: "center" });
}
function feedBack(ctx, colors, lit, x, yTop, yIn, lx, outHalf, inHalf, motion, hue) {
  const on = lit.has("back"), c = on ? colors.ink1 : colors.ink3, lw = on ? 2 : 1.2;
  const pts = [[x + outHalf + 4, yTop], [lx, yTop], [lx, yIn], [x + inHalf + 4, yIn]];
  poly(ctx, pts.slice(0, 3), c, lw);
  arrow(ctx, lx, yIn, pts[3][0], yIn, c, lw);
  /* THE CHOSEN TOKEN RIDES HIS FEED-BACK ARROW from the output to the input (the arrow is
     its lane, nothing else lies on it), on a chip of the surface so it reads over the line */
  if (motion?.token) {
    const font = monoBold(colors), tw = textW(ctx, font, motion.token.text), half = tw / 2 + 4;
    /* its path stops half a chip short of each end, so the chip never covers the labels the arrow joins */
    const ride = [[pts[0][0] + half, pts[0][1]], pts[1], pts[2], [pts[3][0] + half, pts[3][1]]];
    const [px, py] = along(ride, motion.token.e);
    ctx.fillStyle = colors.surface; ctx.fillRect(px - tw / 2 - 3, py - 8, tw + 6, 16);
    txt(ctx, motion.token.text, px, py, { font, fill: hue, align: "center" });
  }
}
/** the point a fraction `e` of the way along a polyline */
function along(pts, e) {
  const seg = pts.slice(1).map((p, i) => Math.hypot(p[0] - pts[i][0], p[1] - pts[i][1])), total = seg.reduce((a, b) => a + b, 0);
  let d = Math.max(0, Math.min(1, e)) * total;
  for (let i = 0; i < seg.length; i++) {
    if (d <= seg[i] || i === seg.length - 1) { const u = seg[i] ? Math.min(1, d / seg[i]) : 1; return [pts[i][0] + (pts[i + 1][0] - pts[i][0]) * u, pts[i][1] + (pts[i + 1][1] - pts[i][1]) * u]; }
    d -= seg[i];
  }
  return pts[pts.length - 1];
}
/* THE RING TRAVELS from one box to the next along the arrow between them (his "tween where
   appropriate", 2026-09-30); between boxes no arrow joins (page 3's encoder to the decoder's
   embedding) it moves at once */
function travellingRing(ctx, colors, boxes, glide) {
  if (!glide || glide.e >= 1) return;
  const a = boxes[glide.from], b = boxes[glide.to], e = glide.e, l = (p, q) => p + (q - p) * e;
  rect(ctx, l(a.x, b.x) - 1.5, l(a.y, b.y) - 1.5, l(a.w, b.w) + 3, l(a.h, b.h) + 3, colors.ink1, 2);
}
const ringOn = (lit, motion, k) => lit.has(k) && !(motion?.glide && motion.glide.e < 1 && motion.glide.to === k);
const ioLabel = (colors, on) => ({ font: on ? bold(colors) : small(colors), fill: on ? colors.ink1 : colors.ink2, align: "center" });

/** one stack, his encoder or decoder figure with Linear + softmax on top: its boxes by number, and a draw */
function mapOne(x, y, enc, outLabel, pool = false) {
  /* with `pool`, 08-3 cell 4's order: the block, Pooling, then Linear + softmax */
  const bx = x + MP.pad, cx = bx + MP.bw / 2, B = (yy, h = MP.bh) => ({ x: bx, y: yy, w: MP.bw, h });
  const out = B(y + 22), pl = pool ? B(y + 56) : null, bT = y + 54 + (pool ? 34 : 0), ffn = B(bT + 8), att = B(bT + 42, enc ? MP.bh : MP.bh2);
  const bB = att.y + att.h + 8, emb = B(bB + 16), inY = bB + 58;
  const boxes = pool ? { 1: emb, 2: att, 3: ffn, 4: pl, 5: out } : { 1: emb, 2: att, 3: ffn, 4: out };
  return { boxes, x, y, w: MAP1_W, bottom: inY + 8, draw(ctx, colors, lit, gen, motion) {
    const hue = enc ? colors.groupA : colors.groupB, f = small(colors);
    txt(ctx, outLabel, cx, y + 6, ioLabel(colors, lit.has("back")));
    arrow(ctx, cx, out.y - 1, cx, y + 13, colors.ink3);
    if (pool) { arrow(ctx, cx, pl.y - 1, cx, out.y + out.h + 3, colors.ink3); arrow(ctx, cx, bT - 1, cx, pl.y + pl.h + 3, colors.ink3); }
    else arrow(ctx, cx, bT - 1, cx, out.y + out.h + 3, colors.ink3);
    arrow(ctx, cx, att.y - 1, cx, ffn.y + ffn.h + 3, colors.ink3);
    rect(ctx, bx - 12, bT, MP.bw + 18, bB - bT, colors.reference, 1.3, [4, 3]);
    txt(ctx, S.times, bx + MP.bw + 6, bB + 8, { font: f, fill: colors.reference, align: "right" });
    arrow(ctx, cx, emb.y - 1, cx, bB + 3, colors.ink3);
    arrow(ctx, cx, inY - 7, cx, emb.y + emb.h + 3, colors.ink3);
    txt(ctx, enc ? S.encIn : S.decIn, cx, inY, { font: f, fill: colors.ink2, align: "center" });
    (pool ? [[1, S.embedding], [2, S.selfAtt], [3, S.ffn], [4, S.poolBox], [5, S.linear]] : [[1, S.embedding], [2, enc ? S.selfAtt : S.masked], [3, S.ffn], [4, S.linear]]).forEach(([k, l]) => mapBox(ctx, colors, boxes[k], l, hue, k, lit.has(k), ringOn(lit, motion, k)));
    travellingRing(ctx, colors, boxes, motion?.glide);
    if (gen) feedBack(ctx, colors, lit, cx, y + 6, inY, bx + MP.bw + 16, textW(ctx, f, S.decOut) / 2, textW(ctx, f, S.decIn) / 2, motion, hue);
  } };
}
/** his two-stack figure: the encoder lower, its frame ending where the decoder's does, the representation into cross-attention */
function mapTwo(x, y) {
  const ex = x + MP.pad, dx = ex + MP.bw + 22, ecx = ex + MP.bw / 2, dcx = dx + MP.bw / 2;
  const D = (yy, h = MP.bh) => ({ x: dx, y: yy, w: MP.bw, h }), E = (yy) => ({ x: ex, y: yy, w: MP.bw, h: MP.bh });
  const out = D(y + 22), bT = y + 54, ffn = D(bT + 8), cross = D(bT + 36), masked = D(bT + 64, MP.bh2);
  const bB = masked.y + masked.h + 8, demb = D(bB + 16), inY = bB + 58;
  const eself = E(bB - 8 - MP.bh), effn = E(eself.y - 8 - MP.bh), eT = effn.y - 8, eemb = E(bB + 16);
  const boxes = { 1: eemb, 2: eself, 3: demb, 4: masked, 5: cross, 6: ffn, 7: out };
  return { boxes, x, y, w: MAP2_W, bottom: inY + 8, draw(ctx, colors, lit, gen, motion) {
    const blue = colors.groupA, amber = colors.groupB, f = small(colors), ry = (ffn.y + ffn.h + cross.y) / 2;
    txt(ctx, S.protOut, dcx, y + 6, ioLabel(colors, lit.has("back")));
    arrow(ctx, dcx, out.y - 1, dcx, y + 13, colors.ink3);
    arrow(ctx, dcx, bT - 1, dcx, out.y + out.h + 3, colors.ink3);
    arrow(ctx, dcx, masked.y - 1, dcx, cross.y + cross.h + 3, colors.ink3);
    rect(ctx, dx - 12, bT, MP.bw + 18, bB - bT, colors.reference, 1.3, [4, 3]);
    rect(ctx, ex - 12, eT, MP.bw + 18, bB - eT, colors.reference, 1.3, [4, 3]);
    txt(ctx, S.times, dx + MP.bw + 6, bB + 8, { font: f, fill: colors.reference, align: "right" });
    txt(ctx, S.times, ex + MP.bw + 6, bB + 8, { font: f, fill: colors.reference, align: "right" });
    for (const [cx, emb] of [[dcx, demb], [ecx, eemb]]) { arrow(ctx, cx, emb.y - 1, cx, bB + 3, colors.ink3); arrow(ctx, cx, inY - 7, cx, emb.y + emb.h + 3, colors.ink3); }
    arrow(ctx, ecx, eself.y - 1, ecx, effn.y + effn.h + 3, colors.ink3);
    txt(ctx, S.protIn, dcx, inY, { font: f, fill: colors.ink2, align: "center" });
    txt(ctx, S.geneIn, ecx, inY, { font: f, fill: colors.ink2, align: "center" });
    /* the encoder's output, once, into the decoder's frame at cross-attention */
    const on = lit.has(5);
    poly(ctx, [[ecx, eT - 1], [ecx, ry]], on ? colors.ink1 : blue, on ? 2 : 1.5);
    arrow(ctx, ecx, ry, dx - 14, ry, on ? colors.ink1 : blue, on ? 2 : 1.5);
    [[1, S.embedding, blue], [2, S.selfAtt, blue], [3, S.embedding, amber], [4, S.masked, amber], [5, S.cross, amber], [6, S.ffn, amber], [7, S.linear, amber]]
      .forEach(([k, l, hue]) => mapBox(ctx, colors, boxes[k], l, hue, k, lit.has(k), ringOn(lit, motion, k)));
    mapBox(ctx, colors, effn, S.ffn, blue, 0, false);
    travellingRing(ctx, colors, boxes, motion?.glide);
    if (gen) feedBack(ctx, colors, lit, dcx, y + 6, inY, dx + MP.bw + 16, textW(ctx, f, S.protOut) / 2, textW(ctx, f, S.protIn) / 2, motion, amber);
  } };
}
const inBox = (p, b) => p.x >= b.x - 2 && p.x <= b.x + b.w + 2 && p.y >= b.y - 2 && p.y <= b.y + b.h + 2;

/* ----------------------------------------------------------- the sections */

/** a section's head: its number, its box's name (a line or two), a note after it */
function sectionHead(ctx, colors, x, y, k, name, hue, note, lit) {
  badge(ctx, colors, x + 8, y, k, hue, lit);
  const lines = [].concat(name);
  lines.forEach((l, i) => txt(ctx, l, x + 21, y + i * 14, { font: cap(colors), fill: colors.ink1 }));
  if (note) txt(ctx, note, x + 21 + textW(ctx, cap(colors), lines[0]) + 8, y, { font: small(colors), fill: colors.ink3 });
}
/** a line of text broken at spaces to fit a width */
function wrap(ctx, font, s, width) {
  const words = s.split(" "), lines = [];
  let cur = "";
  for (const wd of words) { const t = cur ? `${cur} ${wd}` : wd; if (cur && textW(ctx, font, t) > width) { lines.push(cur); cur = wd; } else cur = t; }
  if (cur) lines.push(cur);
  return lines;
}
/** a matrix of weights: rows over columns, labels in their sources' hues; a null cell blank */
function matrix(ctx, colors, cell, R, K, rt, ct, x0, y0, cs, { rowHue, colHue, rowOn = () => true, colOn = () => true, colLabels = true, rowLabels = true, digits = true }) {
  const font = mono(colors), gap = cs > 7 ? 1 : 0.5;
  if (colLabels) ct.forEach((t, j) => { if (colOn(j)) rotated(ctx, t, x0 + j * cs + cs / 2, y0 - 5, { font, fill: colHue, align: "left" }); });
  for (let i = 0; i < R; i++) {
    if (rowLabels && rowOn(i)) txt(ctx, rt[i], x0 - 5, y0 + i * cs + cs / 2, { font, fill: rowHue, align: "right" });
    for (let j = 0; j < K; j++) {
      const x = x0 + j * cs, y = y0 + i * cs, v = cell(i, j), p = v === null ? null : weightRgb(colors, v);
      ctx.fillStyle = p ? css(p) : colors.surface2; ctx.fillRect(x, y, cs - gap, cs - gap);
      if (p && digits && cs >= 22) txt(ctx, v.toFixed(2).replace(/^0/, ""), x + cs / 2 - 0.5, y + cs / 2, { font, fill: inkOn(colors, p), align: "center" });
    }
  }
  rect(ctx, x0 - 0.5, y0 - 0.5, K * cs, R * cs, colors.ink2);
  return { x0, y0, w: K * cs, h: R * cs };
}
const rowRing = (ctx, colors, m, r, cs) => rect(ctx, m.x0 - 2.5, m.y0 + r * cs - 2, m.w + 4, cs + 3, colors.ink1, 1.5, [3, 3]);
/* THE OUTPUT LAYER (his "we may need to show the final prediction layer and the
   softmax"; six largest, his pick): the row's vector through Linear, softmax over
   the vocabulary, the six largest as bars; the target (training) or the token
   chosen (generation) in ink and filled in the stack's hue. */
const OUT = { rows: 6, pitch: 16, bar: 12, maxBar: 300 };
const outHeight = 14 + OUT.rows * OUT.pitch;
function outputPanel(ctx, colors, probs, vocab, mark, x, y, w, title, hue, grow = 1) {
  txt(ctx, title, x, y, { font: small(colors), fill: colors.ink3 });
  const order = probs.map((p, i) => [p, vocab[i]]).sort((a, b) => b[0] - a[0]).slice(0, OUT.rows);
  const lw = Math.max(...order.map(([, t]) => textW(ctx, monoBold(colors), t))), lx = x + lw + 8, bmax = Math.min(OUT.maxBar, w - lw - 8 - 50);
  order.forEach(([p, t], k) => {
    const yy = y + 12 + k * OUT.pitch, on = t === mark, bw = Math.max(1, p * bmax * grow);
    txt(ctx, t, lx - 6, yy + OUT.bar / 2, { font: on ? monoBold(colors) : mono(colors), fill: on ? colors.ink1 : colors.ink2, align: "right" });
    ctx.fillStyle = on ? hue : colors.surface3; ctx.fillRect(lx, yy, bw, OUT.bar);
    txt(ctx, p.toFixed(3), lx + bw + 4, yy + OUT.bar / 2, { font: mono(colors), fill: colors.ink2 });
  });
}

/* ------------------------------------------------------------ a press, by beats */

/* A PRESS CARRIES ONE ROW THROUGH THE BLOCK, A BOX AT A TIME (his "animate the token
   one at a time", 2026-09-30; the lit box his pick): the row's part in each section
   appears as the press reaches that box — nothing moves, each part appears at once
   (tweens move only). On page 3 the first press runs the encoder (1, 2) and every
   later one starts at the decoder (3): the gene is encoded once. In Generation a
   press ends on his feed-back arrow, the chosen token entering the input. Training
   is still one pass (measured, `_lab/transformer-phases-measure.mjs`): the press
   shows its rows one at a time and the caption says so. */
const BEAT = 380, WEIGHT = { back: 2 };   // the feed-back beat is a journey, twice a box's
/* what a beat's tweens run over: the first 60% of it, eased, so each part settles before the next box */
const settleIn = (u) => ease(Math.min(1, u / 0.6));
const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2);
/* the boxes an arrow joins, which the ring travels between */
const JOINED = new Set(["1>2", "2>3", "3>4", "4>5", "5>6", "6>7"]);
function beatsOf(params, state, n) {
  if (params.page === "encoder-decoder") {
    const b = n === 1 ? [1, 2, 3, 4, 5, 6, 7] : [3, 4, 5, 6, 7];
    return params.phase === "generation" && n < XD.rows ? [...b, "back"] : b;
  }
  /* the sentence class: a row a press through the block, then one press to pool and classify */
  if (params.page === "encoder" && params.phase === "prediction" && params.task === "sentence") return n <= N ? [1, 2, 3] : [4, 5];
  const gen = params.page === "decoder" && params.phase === "generation", r = n - 1;
  return gen && r >= state.decG.promptLen - 1 ? [1, 2, 3, 4, "back"] : [1, 2, 3, 4];
}
/** where the page's press stands: the row, the beat it is at (null at rest), and whether a box is reached */
function pressOf(params, state, pg, xd = false) {
  const n = pg.n, beats = n > 0 ? beatsOf(params, state, n) : [], moving = n > 0 && pg.t < 1;
  const wts = beats.map((b) => WEIGHT[b] ?? 1), total = wts.reduce((a, b) => a + b, 0);
  let bi = beats.length, u = 1;
  if (moving) { let d = pg.t * total; bi = 0; while (bi < beats.length - 1 && d >= wts[bi]) { d -= wts[bi]; bi += 1; } u = Math.min(1, d / wts[bi]); }
  const beat = moving ? beats[bi] : null, prev = moving && bi > 0 ? beats[bi - 1] : null;
  /* page 3's encoder boxes (1, 2) and decoder boxes (3 on) sit in two stacks: 2 to 3 is no arrow */
  const joined = prev !== null && typeof beat === "number" && JOINED.has(`${prev}>${beat}`) && !(xd && prev === 2);
  return { n, r: n - 1, beat, u, moving, reached: (k) => !moving || bi >= beats.indexOf(k),
    grow: (k) => (beat === k ? settleIn(u) : 1),
    motion: { glide: joined ? { from: prev, to: beat, e: settleIn(u) } : null, token: null } };
}

/* A VECTOR AS BARS up and down from a line, in ink: the signed colour ramp starts in the
   encoder's own blue (`_lab/transformer-sentence-mock.html`); `grow` is how far they have risen */
function vectorBars(ctx, colors, v, x, y, w, h, grow = 1) {
  const m = Math.max(...v.map(Math.abs)), bw = w / v.length;
  poly(ctx, [[x, y], [x + w, y]], colors.ink3, 1);
  ctx.fillStyle = colors.ink2;
  v.forEach((a, i) => { const hh = (a / m) * h * grow; ctx.fillRect(x + i * bw + 0.5, hh >= 0 ? y - hh : y, Math.max(1, bw - 1), Math.abs(hh)); });
}
/** the first `t` of a cubic Bézier, as its three later control points (de Casteljau) */
function splitBezier([P0, P1, P2, P3], t) {
  const l = (p, q) => [p[0] + (q[0] - p[0]) * t, p[1] + (q[1] - p[1]) * t];
  const a = l(P0, P1), b = l(P1, P2), c = l(P2, P3), ab = l(a, b), bc = l(b, c);
  return [a, ab, l(ab, bc)];
}

/* ================================================= pages 1–2: Encoder and Decoder */

/* THE SECTIONS, TOP TO BOTTOM IN THE BLOCK'S ORDER (his L3): 1 Embedding over the
   sentence and the current row's arcs (his output figure's glyph: a loop for
   itself, arcs above to later tokens and below to earlier ones); 2 the attention
   matrix; 3 Feed forward, a line; 4 Linear + softmax, the row's six largest. The map
   sits in the top-right corner while the sentence still has 44 px a token beside
   it, else beside the matrix. */
const P12 = { top: 8, lab: 50, colLab: 50, notes: 92, cs: 24 };
const TAG_COL = 60;
function selfLayout(w, enc, mode = "") {
  const tagging = mode === "tags", sentence = mode === "sentence";
  const mapTop = (w - PAD_L - PAD_R - MAP1_W - 12) / N >= 44;
  const right1 = mapTop ? w - PAD_R - MAP1_W - 12 : w - PAD_R;
  const y1 = P12.top + 8, sy = y1 + 16 + (enc ? 52 : 34), slot = (right1 - PAD_L) / N, y2 = sy + 58;
  const x0 = PAD_L + P12.lab, notesBeside = mapTop && !tagging;   // the tags take the room beside the rows
  const avail = (notesBeside ? w - PAD_R - P12.notes : mapTop ? w - PAD_R - TAG_COL : w - PAD_R - MAP1_W - 12 - (tagging ? TAG_COL : 0)) - x0;
  const cs = Math.max(14, Math.min(P12.cs, Math.floor(avail / N)));
  const mTop = y2 + 16 + P12.colLab, mBot = mTop + N * cs;
  const map = mapOne(w - PAD_R - MAP1_W + 4, mapTop ? P12.top : y2 - 8, enc, tagging ? S.tagOut : sentence ? S.clsOut : enc ? S.encOut : S.decOut, sentence);
  const y3 = Math.max(mBot + (notesBeside ? 20 : 36), mapTop ? 0 : map.bottom + 12), y4 = y3 + 22;
  /* the sentence class: 4 Pooling (the embedding's bars about a line at vy), 5 Linear + softmax over two classes */
  const vy = y4 + 44, y5 = y4 + 78, yo = sentence ? y5 + 20 : y4 + 20;
  const yc = yo + (sentence ? 12 + 2 * OUT.pitch : outHeight) + 14;
  const secs = { 1: { x: 0, y: y1 - 10, w: right1, h: y2 - y1 }, 2: { x: 0, y: y2 - 10, w: mapTop ? w : map.x, h: y3 - y2 }, 3: { x: 0, y: y3 - 10, w, h: 22 },
    4: { x: 0, y: y4 - 10, w, h: (sentence ? y5 : yc) - y4 }, ...(sentence ? { 5: { x: 0, y: y5 - 10, w, h: yc - y5 } } : {}) };
  return { mapTop, map, y1, sy, slot, y2, x0, cs, mTop, mBot, notesBeside, y3, y4, vy, y5, yo, yc, eg: yc + 32, height: yc + 46, secs };
}
const modeOf = (params) => (params.page !== "encoder" || params.phase !== "prediction" ? "" : params.task === "sentence" ? "sentence" : "tags");
const heightSelf = (w, enc, mode) => selfLayout(w, enc, mode).height;

/** what a self-attention page shows at this press */
function selfView(state, params, pg) {
  const enc = params.page === "encoder", gen = !enc && params.phase === "generation", pr = pressOf(params, state, pg), r = pr.r;
  const rowIn = r >= 0 && pr.reached(2), outIn = r >= 0 && pr.reached(4), rows = rowIn ? pr.n : Math.max(0, pr.n - 1);
  if (enc && params.phase === "prediction" && params.task === "sentence") {
    /* rows a press through the block; press N + 1 pools the [CLS] row and classifies it */
    const E = state.encP, pooling = pr.n > N;
    return { enc, gen, sentence: true, pr, toks: E.tokens, shown: N, rows: pooling ? N : rows, rowIn: !pooling && rowIn, A: E.A, masked: false,
      arcRow: pooling && pr.reached(4) ? 0 : null, arcBeat: pooling ? 4 : 2, poolIn: pooling && pr.reached(4), headIn: pooling && pr.reached(5), cls: E.h0, probs: E.cls };
  }
  if (enc && params.phase === "prediction") {
    /* [CLS] and [SEP] are not words: the head was trained on word rows only, so they get no tag */
    const E = state.encP, word = (i) => !E.tokens[i].startsWith("["), tagOf = (i) => { const p = E.tags[i]; return M.TAGS[p.indexOf(Math.max(...p))]; };
    return { enc, gen, tagging: true, pr, toks: E.tokens, shown: N, rows, rowIn, outIn, A: E.A, masked: false, tagOf, word,
      tagsDone: outIn ? pr.n : Math.max(0, pr.n - 1),
      out: outIn && word(r) ? { probs: E.tags[r], mark: tagOf(r), title: S.outTag(E.tokens[r], tagOf(r)), vocab: M.TAGS } : null,
      noTag: outIn && !word(r) };
  }
  if (enc) {
    const E = state.enc;
    return { enc, gen, pr, toks: E.tokens, shown: N, rows, rowIn, outIn, A: E.A, masked: false,
      out: outIn && r === MASK_AT ? { probs: E.probs, mark: E.target, title: S.outMask(E.target) } : null, notScored: outIn && r !== MASK_AT };
  }
  if (!gen) {
    const D = state.decT;
    return { enc, gen, pr, toks: D.tokens, shown: N, rows, rowIn, outIn, A: D.A, masked: true,
      out: outIn ? { probs: D.probs[r], mark: D.tokens[r + 1], title: S.outTrain(D.tokens[r], D.tokens[r + 1]) } : null };
  }
  const G = state.decG, k0 = G.promptLen, back = r >= k0 - 1 && !pr.moving;   // in only once it has ridden the arrow
  const shown = Math.min(G.tokens.length, Math.max(k0, back ? pr.n + 1 : pr.n));
  const out = outIn ? (r < k0 - 1 ? { probs: G.probs[r], mark: G.tokens[r + 1], title: S.outPrompt(G.tokens[r], G.tokens[r + 1]) }
    : { probs: G.probs[r], mark: G.tokens[r + 1], title: S.outGen(G.tokens[r], G.tokens[r + 1]) }) : null;
  return { enc, gen, pr, toks: G.tokens, shown, rows, rowIn, outIn, A: G.A, masked: true, out, k0 };
}

function drawSelf(ctx, colors, w, params, state, pg, pointer) {
  const v = selfView(state, params, pg), L = selfLayout(w, v.enc, modeOf(params)), enc = v.enc, hue = enc ? colors.groupA : colors.groupB;
  const toks = v.toks, T = toks.length, pr = v.pr, cellOf = (i, j) => (i < v.rows && (!v.masked || j <= i) ? v.A[i][j] : null);
  const slots = toks.map((_, j) => ({ x: PAD_L + j * L.slot + L.slot / 2, y: L.sy }));
  const cs = L.cs;
  /* hover, at rest: a box or a section rings both; a token or a cell picks the arcs' row */
  let hovBox = 0, hovRow = -1, hovCol = -1;
  if (pointer && !pr.beat) {
    for (const [k, b] of Object.entries(L.map.boxes)) if (inBox(pointer, b)) hovBox = +k;
    if (!hovBox) for (const [k, s] of Object.entries(L.secs)) if (inBox(pointer, s)) hovBox = +k;
    if (Math.abs(pointer.y - L.sy) < 14) { const j = Math.floor((pointer.x - PAD_L) / L.slot); if (j >= 0 && j < v.rows) hovRow = j; }
    const ci = Math.floor((pointer.y - L.mTop) / cs), cj = Math.floor((pointer.x - L.x0) / cs);
    if (ci >= 0 && ci < T && cj >= 0 && cj < T && cellOf(ci, cj) !== null) { hovRow = ci; hovCol = cj; }
  }
  const lit = new Set(pr.beat ? [pr.beat] : hovBox ? [hovBox] : []);
  const motion = { ...pr.motion, token: pr.beat === "back" ? { text: toks[pr.r + 1], e: ease(pr.u) } : null };
  L.map.draw(ctx, colors, lit, v.gen, motion);

  /* 1 · Embedding, the sentence and one row's arcs */
  sectionHead(ctx, colors, PAD_L, L.y1, 1, S.embedding, hue, S.note1(v), lit.has(1));
  const arcRow = hovRow >= 0 ? hovRow : v.arcRow ?? (v.rowIn ? pr.r : -1);
  /* THE ARCS DRAW OUT FROM THE QUERY to each key while the press is at the attention box
     (`g` the share drawn, the arrowhead riding the tip); each arc is its own lane */
  const g = hovRow >= 0 ? 1 : pr.grow(v.arcBeat ?? 2);
  const arc = (i, j, wt, on) => {
    const col = on ? colors.ink1 : css(weightRgb(colors, 0.35 + 0.65 * wt)), lw = on ? Math.max(1.8, 1 + 2.5 * wt) : 1 + 2.5 * wt, size = 5 + lw, a = slots[i];
    ctx.save(); ctx.strokeStyle = col; ctx.lineWidth = lw; ctx.beginPath();
    if (j === i) {
      const cy = a.y - 24, rr = 9, a0 = Math.PI * 0.65, t1 = Math.PI * 0.35 + 2 * Math.PI, end = a0 + (t1 - 0.25 - a0) * g, th = end + 0.25;
      ctx.arc(a.x, cy, rr, a0, end); ctx.stroke(); ctx.restore();
      head(ctx, a.x + rr * Math.cos(th), cy + rr * Math.sin(th), th + Math.PI / 2, size, col);
      return;
    }
    const b = slots[j], d = Math.abs(j - i), up = j > i;
    const hgt = up ? Math.min(L.sy - L.y1 - 30, 16 + 6 * d) : Math.min(46, 12 + 7 * d), y0 = up ? a.y - 9 : a.y + 8, x0 = up ? a.x + 12 : a.x - 4, x1 = up ? b.x - 4 : b.x + 4, sg = up ? -1 : 1;
    const P = [[x0, y0], [x0, y0 + sg * hgt], [x1, y0 + sg * hgt], [x1, y0 + sg * size * 0.7]], [Q1, Q2, Q3] = splitBezier(P, g);
    ctx.moveTo(x0, y0); ctx.bezierCurveTo(Q1[0], Q1[1], Q2[0], Q2[1], Q3[0], Q3[1]); ctx.stroke(); ctx.restore();
    const dx = Q3[0] - Q2[0], dy = Q3[1] - Q2[1], len = Math.hypot(dx, dy) || 1, ang = len > 0.01 ? Math.atan2(dy, dx) : (up ? Math.PI / 2 : -Math.PI / 2);
    head(ctx, Q3[0] + (dx / len) * size * 0.7, Q3[1] + (dy / len) * size * 0.7, ang, size, col);
  };
  if (arcRow >= 0) {
    for (let j = 0; j < T; j++) { const wv = cellOf(arcRow, j); if (wv !== null && wv >= 0.02 && j !== hovCol) arc(arcRow, j, wv, false); }
    if (hovCol >= 0) arc(arcRow, hovCol, cellOf(arcRow, hovCol), true);
  }
  for (let j = 0; j < v.shown; j++) txt(ctx, toks[j], slots[j].x, slots[j].y, { font: j === arcRow ? monoBold(colors) : mono(colors), fill: j === arcRow ? colors.ink1 : hue, align: "center" });

  /* 2 · the attention matrix */
  sectionHead(ctx, colors, PAD_L, L.y2, 2, enc ? S.selfAtt : S.maskedOne, hue, enc ? S.note2enc : S.note2dec, lit.has(2));
  const m = matrix(ctx, colors, cellOf, T, T, toks, toks, L.x0, L.mTop, cs, { rowHue: hue, colHue: hue, rowOn: (i) => i < v.shown, colOn: (j) => j < v.shown });
  if (arcRow >= 0) rowRing(ctx, colors, m, arcRow, cs);
  if (hovCol >= 0) rect(ctx, L.x0 + hovCol * cs - 1, L.mTop + arcRow * cs - 1, cs + 1, cs + 1, colors.ink1, 2);
  /* prediction: each row's tag beside it, once the press has reached the head */
  if (v.tagging) {
    txt(ctx, S.tagHead, m.x0 + m.w + 10, m.y0 - 10, { font: small(colors), fill: colors.ink3 });
    for (let i = 0; i < v.tagsDone; i++) {
      if (!v.word(i)) continue;
      const t = v.tagOf(i), on = t !== "other";
      txt(ctx, t, m.x0 + m.w + 10, m.y0 + i * cs + cs / 2, { font: on ? monoBold(colors) : mono(colors), fill: on ? colors.ink1 : colors.ink3 });
    }
  }
  if (L.notesBeside) S.blockNote(1).forEach((s, i) => txt(ctx, s, m.x0 + m.w + 10, m.y0 + 8 + i * 13, { font: small(colors), fill: colors.ink3 }));
  else txt(ctx, S.blockNote(1).join(" "), PAD_L, L.mBot + 16, { font: small(colors), fill: colors.ink3 });

  /* 3 · Feed forward; 4 · Linear + softmax */
  sectionHead(ctx, colors, PAD_L, L.y3, 3, S.ffn, hue, S.note3, lit.has(3));
  if (v.sentence) {
    /* 4 · Pooling: the [CLS] row's final vector, the sentence's embedding; 5 · the head over two classes */
    sectionHead(ctx, colors, PAD_L, L.y4, 4, S.pooling, hue, S.note4pool, lit.has(4));
    if (v.poolIn) {
      txt(ctx, S.vecCap, PAD_L, L.y4 + 18, { font: small(colors), fill: colors.ink3 });
      vectorBars(ctx, colors, v.cls, PAD_L, L.vy, Math.min(384, w - PAD_L - PAD_R), 16, pr.grow(4));
    }
    sectionHead(ctx, colors, PAD_L, L.y5, 5, S.linear, hue, S.note5cls, lit.has(5));
    if (v.headIn) { const c = M.CLASSES[v.probs.indexOf(Math.max(...v.probs))];
      outputPanel(ctx, colors, v.probs, M.CLASSES, c, PAD_L, L.yo, w - PAD_L - PAD_R, S.outCls(c), hue, pr.grow(5)); }
  } else sectionHead(ctx, colors, PAD_L, L.y4, 4, S.linear, hue, v.tagging ? S.note4tag(M.TAGS.length) : S.note4(M.VOCAB.length, S.tokensWord), lit.has(4));
  if (v.out) outputPanel(ctx, colors, v.out.probs, v.out.vocab ?? M.VOCAB, v.out.mark, PAD_L, L.yo, w - PAD_L - PAD_R, v.out.title, hue, pr.grow(4));
  else if (v.noTag) txt(ctx, S.noTag(toks[pr.r]), PAD_L, L.yo, { font: small(colors), fill: colors.ink3 });
  else if (v.notScored) txt(ctx, S.notScored(toks[pr.r]), PAD_L, L.yo, { font: small(colors), fill: colors.ink3 });

  /* the line under: the hovered cell's weight, else what a press does */
  const line = hovCol >= 0 ? S.weightOf(toks[arcRow], toks[hovCol], cellOf(arcRow, hovCol)) : S.line(params, v, state);
  wrap(ctx, small(colors), line, w - PAD_L - PAD_R).slice(0, 2).forEach((l, i) => txt(ctx, l, PAD_L, L.yc + i * 14, { font: small(colors), fill: hovCol >= 0 ? colors.ink1 : colors.ink2 }));
  txt(ctx, S.eg[params.page], PAD_L, L.eg, { font: small(colors), fill: colors.ink3 });
}

/* ===================================================== page 3: Encoder–decoder */

/* HIS TWO-STACK FIGURE AS THE MAP, AND SEVEN SECTIONS: the encoder's column (1 the
   gene, 2 its self-attention, 18 × 18) beside the decoder's (3 the protein so far,
   4 its masked self-attention), then across the page 5 cross-attention — the
   decoder's inputs over the codons they read, one row's lines to the nucleotides,
   the matrix, rows the protein and columns the gene — 6 Feed forward and 7 Linear +
   softmax over the amino acids. Where the two columns and the map will not fit side
   by side the decoder's column goes under the encoder's, and on the narrowest
   canvas the map goes on top. */
const XD = { rows: 6, ce: 6, cd: 13, pitch: 9, ecolW: 166, dcolW: 116, dLab: 36 };
function xdLayout(w) {
  const wide = w >= PAD_L + XD.ecolW + 6 + XD.dcolW + 4 + MAP2_W + 6, mid = !wide && w >= PAD_L + XD.ecolW + 10 + MAP2_W + 6;
  const map = mapTwo(wide || mid ? w - 6 - MAP2_W : Math.max(0, Math.round((w - MAP2_W) / 2)), 8);
  const top = wide || mid ? 8 : map.bottom + 8;
  const e = { x: PAD_L, h1: top + 8 }; e.gy = e.h1 + 22; e.h2 = e.gy + 22; e.my = e.h2 + 12; e.note = e.my + 18 * XD.ce + 12; e.bottom = e.note + 8;
  const dTop = wide ? top : e.bottom + 6, d = { x: wide ? PAD_L + XD.ecolW + 6 : PAD_L, h3: dTop + 8 };
  d.ty = d.h3 + 22; d.h4 = d.ty + 22; d.my = d.h4 + 26; d.bottom = d.my + XD.rows * XD.cd;
  const y5 = Math.max(e.bottom, d.bottom, wide || mid ? map.bottom : 0) + 14;
  const cc = Math.max(11, Math.min(20, Math.floor((w - PAD_L - PAD_R - 44 - 96) / 18))), cx = PAD_L + 44;
  const yQ = y5 + 22, yN = yQ + 40, cy = yN + 12, y6 = cy + XD.rows * cc + 18, y7 = y6 + 22, yo = y7 + 20, yc = yo + outHeight + 14;
  const secs = { 1: { x: 0, y: e.h1 - 10, w: e.x + XD.ecolW, h: e.h2 - e.h1 }, 2: { x: 0, y: e.h2 - 10, w: e.x + XD.ecolW, h: e.bottom - e.h2 },
    3: { x: d.x, y: d.h3 - 10, w: XD.dcolW, h: d.h4 - d.h3 }, 4: { x: d.x, y: d.h4 - 10, w: XD.dcolW, h: d.bottom - d.h4 + 4 },
    5: { x: 0, y: y5 - 10, w, h: y6 - y5 }, 6: { x: 0, y: y6 - 10, w, h: 22 }, 7: { x: 0, y: y7 - 10, w, h: yc - y7 } };
  return { map, e, d, y5, cc, cx, yQ, yN, cy, y6, y7, yo, yc, eg: yc + 32, height: yc + 46, secs };
}
const heightEncDec = (w) => xdLayout(w).height;

function drawEncDec(ctx, colors, w, params, state, pg, pointer) {
  const L = xdLayout(w), training = params.phase === "training", gen = !training, T = state.dna, nt = T.dna.split(""), prot = ["[BOS]", ...T.protein];
  const pr = pressOf(params, state, pg, true), r = pr.r, blue = colors.groupA, amber = colors.groupB;
  const encIn = pr.n >= 2 || (pr.n === 1 && pr.reached(2));
  const selfIn = r >= 0 && pr.reached(4), crossIn = r >= 0 && pr.reached(5), outIn = r >= 0 && pr.reached(7);
  const inShown = training ? XD.rows : Math.min(XD.rows, Math.max(1, r >= 0 && !pr.moving && r < XD.rows - 1 ? pr.n + 1 : pr.n));
  const E = M.meanHeads(T.enc[1]), Ds = M.meanHeads(T.self[1]), X = M.crossMean(T), ins = prot.slice(0, XD.rows);
  const rowsS = selfIn ? pr.n : Math.max(0, pr.n - 1), rowsC = crossIn ? pr.n : Math.max(0, pr.n - 1);
  const selfCell = (i, j) => (i < rowsS && j <= i ? Ds[i][j] : null), crossCell = (i, j) => (i < rowsC ? X[i][j] : null);
  const cc = L.cc, cx = L.cx;

  /* hover, at rest: a box or a section; a cell of either decoder matrix */
  let hovBox = 0, hov = null;
  if (pointer && !pr.beat) {
    for (const [k, b] of Object.entries(L.map.boxes)) if (inBox(pointer, b)) hovBox = +k;
    if (!hovBox) for (const [k, s] of Object.entries(L.secs)) if (inBox(pointer, s)) hovBox = +k;
    const ci = Math.floor((pointer.y - L.cy) / cc), cj = Math.floor((pointer.x - cx) / cc);
    if (ci >= 0 && ci < XD.rows && cj >= 0 && cj < 18 && crossCell(ci, cj) !== null) hov = { m: "cross", i: ci, j: cj };
    const dx0 = L.d.x + XD.dLab, si = Math.floor((pointer.y - L.d.my) / XD.cd), sj = Math.floor((pointer.x - dx0) / XD.cd);
    if (si >= 0 && si < XD.rows && sj >= 0 && sj < XD.rows && selfCell(si, sj) !== null) hov = { m: "self", i: si, j: sj };
  }
  const lit = new Set(pr.beat ? [pr.beat] : hovBox ? [hovBox] : []);
  L.map.draw(ctx, colors, lit, gen, { ...pr.motion, token: pr.beat === "back" ? { text: prot[r + 1], e: ease(pr.u) } : null });

  /* 1, 2 · the encoder's column */
  const e = L.e, gx = (j) => e.x + 4 + j * XD.pitch + XD.pitch / 2;
  sectionHead(ctx, colors, e.x, e.h1, 1, S.embedding, blue, S.gene, lit.has(1));
  nt.forEach((c, j) => txt(ctx, c, gx(j), e.gy, { font: mono(colors), fill: blue, align: "center" }));
  for (let k = 0; k < 6; k++) poly(ctx, [[gx(3 * k) - XD.pitch / 2 + 1.5, e.gy + 9], [gx(3 * k + 2) + XD.pitch / 2 - 1.5, e.gy + 9]], colors.ink3, 1);
  sectionHead(ctx, colors, e.x, e.h2, 2, S.selfAtt, blue, "", lit.has(2));
  matrix(ctx, colors, (i, j) => (encIn ? E[i][j] : null), 18, 18, nt, nt, e.x + 4, e.my, XD.ce, { rowHue: blue, colHue: blue, colLabels: false, rowLabels: false, digits: false });
  txt(ctx, S.encRows, e.x, e.note, { font: small(colors), fill: blue });

  /* 3, 4 · the decoder's column */
  const d = L.d;
  sectionHead(ctx, colors, d.x, d.h3, 3, S.embedding, amber, "", lit.has(3));
  let tx = d.x + 4;
  ins.forEach((t, i) => { if (i < inShown) txt(ctx, t, tx, d.ty, { font: i === r && selfIn ? monoBold(colors) : mono(colors), fill: i === r && selfIn ? colors.ink1 : amber }); tx += textW(ctx, mono(colors), t) + 7; });
  sectionHead(ctx, colors, d.x, d.h4, 4, S.masked, amber, "", lit.has(4));
  const md = matrix(ctx, colors, selfCell, XD.rows, XD.rows, ins, ins, d.x + XD.dLab, d.my, XD.cd, { rowHue: amber, colHue: amber, colLabels: false, rowOn: (i) => i < inShown, digits: false });
  if (selfIn && !hov) rowRing(ctx, colors, md, r, XD.cd);
  if (hov?.m === "self") rect(ctx, md.x0 + hov.j * XD.cd - 1, md.y0 + hov.i * XD.cd - 1, XD.cd + 1, XD.cd + 1, colors.ink1, 2);

  /* 5 · cross-attention: the inputs over the codons they read, one row's lines to the gene, the matrix */
  sectionHead(ctx, colors, PAD_L, L.y5, 5, S.cross, amber, S.note5, lit.has(5));
  const colX = (j) => cx + j * cc + cc / 2, qX = (q) => cx + (3 * q + 1.5) * cc;
  const lineRow = hov?.m === "cross" ? hov.i : crossIn ? r : -1, litJ = hov?.m === "cross" ? hov.j : -1;
  for (let q = 0; q < XD.rows; q++) if (q < inShown) txt(ctx, ins[q], qX(q), L.yQ, { font: q === lineRow ? monoBold(colors) : mono(colors), fill: q === lineRow ? colors.ink1 : amber, align: "center" });
  if (lineRow >= 0) {
    const drawLine = (j, on) => {
      const v = crossCell(lineRow, j);
      if (v === null || (!on && v < 0.01)) return;
      ctx.save(); ctx.strokeStyle = on ? colors.ink1 : css(weightRgb(colors, 0.35 + 0.65 * v)); ctx.lineWidth = on ? Math.max(1.8, 1 + 2.5 * v) : 1 + 2.5 * v;
      /* drawn out from the query to the gene while the press is at cross-attention */
      const g = on || hov ? 1 : pr.grow(5), x0 = qX(lineRow), y0 = L.yQ + 9;
      ctx.beginPath(); ctx.moveTo(x0, y0); ctx.lineTo(x0 + (colX(j) - x0) * g, y0 + (L.yN - 16 - y0) * g); ctx.stroke(); ctx.restore();
    };
    for (let j = 0; j < 18; j++) if (j !== litJ) drawLine(j, false);
    if (litJ >= 0) drawLine(litJ, true);
  }
  for (let k = 0; k < 6; k++) poly(ctx, [[cx + 3 * k * cc + 2, L.yN - 10.5], [cx + 3 * k * cc + 3 * cc - 3, L.yN - 10.5]], colors.ink3, 1);
  nt.forEach((c, j) => txt(ctx, c, colX(j), L.yN, { font: mono(colors), fill: blue, align: "center" }));
  const mx = matrix(ctx, colors, crossCell, XD.rows, 18, ins, nt, cx, L.cy, cc, { rowHue: amber, colHue: blue, rowOn: (i) => i < inShown, colLabels: false, digits: false });
  if (lineRow >= 0) rowRing(ctx, colors, mx, lineRow, cc);
  if (hov?.m === "cross") rect(ctx, mx.x0 + hov.j * cc - 1, mx.y0 + hov.i * cc - 1, cc + 1, cc + 1, colors.ink1, 2);
  [[S.blockNote(2)[0], colors.ink3], [S.blockNote(2)[1], colors.ink3], [S.crossRows, amber], [S.crossCols, blue]].forEach(([s, c], i) => txt(ctx, s, mx.x0 + mx.w + 8, mx.y0 + 8 + i * 13, { font: small(colors), fill: c }));

  /* 6 · Feed forward; 7 · Linear + softmax over the amino acids */
  const aminos = M.TGT.filter((t) => !t.startsWith("[")).length;
  sectionHead(ctx, colors, PAD_L, L.y6, 6, S.ffn, amber, S.note3, lit.has(6));
  sectionHead(ctx, colors, PAD_L, L.y7, 7, S.linear, amber, S.note4(aminos, S.aminoWord), lit.has(7));
  if (outIn) outputPanel(ctx, colors, T.probs[r], M.TGT, prot[r + 1], PAD_L, L.yo, w - PAD_L - PAD_R, training ? S.outTrainX(ins[r], prot[r + 1]) : S.outGenX(ins[r], prot[r + 1]), amber, pr.grow(7));

  const line = hov ? S.weightOf(ins[hov.i], hov.m === "cross" ? `${nt[hov.j]} (nucleotide ${hov.j + 1})` : ins[hov.j], (hov.m === "cross" ? X : Ds)[hov.i][hov.j])
    : S.xLine(params, pr, T);
  wrap(ctx, small(colors), line, w - PAD_L - PAD_R).slice(0, 2).forEach((l, i) => txt(ctx, l, PAD_L, L.yc + i * 14, { font: small(colors), fill: hov ? colors.ink1 : colors.ink2 }));
  txt(ctx, S.eg[params.page], PAD_L, L.eg, { font: small(colors), fill: colors.ink3 });
}

/* ============================================================ the widget */

const keyOf = (params) => `${params.page}:${params.phase}${params.page === "encoder" && params.phase === "prediction" ? `:${params.task}` : ""}`;
const maxOf = (params, state) => (params.page === "encoder" ? N + (modeOf(params) === "sentence" ? 1 : 0) : params.page === "decoder" ? (params.phase === "training" ? N - 1 : state.decG.tokens.length - 1) : XD.rows);
const msOf = (params, state, mode, n) => beatsOf(params, state, Math.max(1, n)).length * BEAT * (mode === "run" ? 0.5 : 1);
const pageOf = (anim, params) => anim.p[keyOf(params)];
function settle(anim, params, state) {
  anim.key = keyOf(params);
  const pg = anim.p[anim.key];
  anim.done = pg.n >= maxOf(params, state) && pg.t >= 1;
}

/* memoised: compute() is pure, and nothing here depends on a parameter */
let STAGE = null;
function stage() {
  if (STAGE) return STAGE;
  /* the encoder: the lesson's masked sentence, one pass; the [MASK] row's prediction */
  const masked = TOKENS.map((t, i) => (i === MASK_AT ? "[MASK]" : t)), fe = M.forward("base", masked);
  const enc = { tokens: masked, A: M.meanHeads(fe.alpha[0]), probs: M.nextTokens("base", fe.h[MASK_AT]), target: TOKENS[MASK_AT] };
  /* the decoder in training: the whole sentence, one pass, every row's next-token distribution */
  const fd = M.forward("causal", TOKENS);
  const decT = { tokens: TOKENS, A: M.meanHeads(fd.alpha[0]), probs: TOKENS.slice(1).map((_, i) => M.nextTokens("causal", fd.h[i])) };
  /* the decoder in generation: the prompt, then each prediction fed back. One pass over the finished
     sequence gives every row a token-at-a-time run gives (the mask; measured), so it is read once */
  const gen = M.generate(PROMPT), fg = M.forward("causal", gen.tokens);
  const decG = { tokens: gen.tokens, promptLen: gen.steps[0].context.length, A: M.meanHeads(fg.alpha[0]), probs: gen.tokens.slice(1).map((_, i) => M.nextTokens("causal", fg.h[i])) };
  /* the encoder in prediction: the sentence read whole, each final vector through the tag head */
  const fp = M.forward("base", TOKENS);
  const encP = { tokens: TOKENS, A: M.meanHeads(fp.alpha[0]), tags: fp.h.map((row) => M.tagsOf(row)), h0: fp.h[0], cls: M.classOf(fp.h[0]) };
  STAGE = { enc, encP, decT, decG, dna: M.translate(M.GENES[0]) };
  return STAGE;
}

defineWidget({
  slug: "transformer",
  status: "draft",
  title: S.title,
  subtitle: S.subtitle,
  layout: "side",
  height: ({ page, phase, task, w }) => (page === "encoder-decoder" ? heightEncDec(w) : heightSelf(w, page === "encoder", modeOf({ page, phase, task }))),

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "encoder", display: true },
    phase: { type: "segmented", label: S.phaseLabel, options: (v) => (v.page === "encoder" ? S.phaseOpts.encoder : S.phaseOpts.decoder), optionsFrom: ["page"],
      default: "training", display: true },
    task: { type: "segmented", label: S.taskLabel, options: S.taskOpts, default: "tokens", display: true,
      when: { all: [{ param: "page", equals: "encoder" }, { param: "phase", equals: "prediction" }] } },
    /* authoring escape hatch, first render only: presses already made on the page opened */
    shown: { type: "int", min: 0, max: 9, default: 0, hidden: true },
  },

  legend: [],
  /* hover: a box or a section rings both; a token or a cell shows that row's arcs or lines */
  pointer: true,

  compute: () => stage(),

  animation: {
    stepLabel: { param: "page", labels: S.step, default: S.step.encoder },
    stepTitle: { param: "page", labels: S.stepTitle, default: S.stepTitle.encoder },
    runLabel: S.runLabel,
    runTitle: S.runTitle,
    init: ({ params, state, fromScratch }) => {
      const anim = { p: Object.fromEntries(["encoder:training", "encoder:prediction:tokens", "encoder:prediction:sentence", "decoder:training", "decoder:generation", "encoder-decoder:training", "encoder-decoder:generation"].map((k) => [k, { n: 0, t: 1 }])), moving: false, halt: false };
      if (!fromScratch) anim.p[keyOf(params)].n = Math.max(0, Math.min(maxOf(params, state), Number(params.shown) || 0));
      settle(anim, params, state);
      return anim;
    },
    advance: (anim, { dt, params, state }) => {
      /* the loop a page or phase switch left running for the other one's press ends here */
      if (anim.halt) { anim.halt = false; anim.moving = false; settle(anim, params, state); return false; }
      const pg = anim.p[keyOf(params)], max = maxOf(params, state);
      let more;
      if (pg.t < 1) { pg.t = Math.min(1, pg.t + dt / msOf(params, state, anim.mode, pg.n)); more = pg.t < 1 || (anim.mode === "run" && pg.n < max); }
      else if (pg.n < max) { pg.n += 1; pg.t = 0; more = true; }
      else more = false;
      anim.moving = more;
      settle(anim, params, state);
      return more;
    },
    rebuild: (anim, { params, state }) => {
      /* A PRESS BELONGS TO THE PAGE AND PHASE IT STARTED ON (widget 70's rule): a switch
         mid-press finishes it, and `halt` ends the loop at its next frame. Only while a
         press moves: set otherwise, it would swallow the reader's next press. */
      if (anim.moving && keyOf(params) !== anim.key) {
        for (const pg of Object.values(anim.p)) pg.t = 1;
        anim.halt = true;
      }
      settle(anim, params, state);
    },
  },

  draw({ ctx, colors, w, params, state, anim, pointer }) {
    renderCard(params);
    if (params.page === "encoder-decoder") drawEncDec(ctx, colors, w, params, state, pageOf(anim, params), pointer);
    else drawSelf(ctx, colors, w, params, state, pageOf(anim, params), pointer);
  },

  readout({ params, state, anim }) {
    const pg = pageOf(anim, params), k = pg.t >= 1 ? pg.n : pg.n - 1, r = k - 1, max = maxOf(params, state);
    const rowsTile = { label: S.tileRows, value: `${Math.max(0, k)} of ${max}`, note: S.tileRowsNote };
    if (modeOf(params) === "sentence") {
      const E = state.encP, c = E.cls.indexOf(Math.max(...E.cls));
      return [
        { label: S.tileRows, value: `${Math.min(Math.max(0, k), N)} of ${N}`, note: S.tileRowsNote },
        { label: S.tileClass, value: k > N ? `${M.CLASSES[c]} ${E.cls[c].toFixed(2)}` : S.wait, note: S.tileClassNote },
        { label: S.tileKeys, value: `${N}`, note: S.tileKeysNote },
      ];
    }
    if (params.page === "encoder" && params.phase === "prediction") {
      const E = state.encP, p = r >= 0 && !E.tokens[r].startsWith("[") ? E.tags[r] : null;
      return [
        rowsTile,
        { label: S.tileTag, value: p ? `${M.TAGS[p.indexOf(Math.max(...p))]} ${Math.max(...p).toFixed(2)}` : S.wait, note: S.tileTagNote },
        { label: S.tileKeys, value: `${N}`, note: S.tileKeysNote },
      ];
    }
    if (params.page === "encoder") {
      const E = state.enc, top = E.probs.indexOf(Math.max(...E.probs));
      return [
        rowsTile,
        { label: S.tileMask, value: k > MASK_AT ? `${M.VOCAB[top]} ${E.probs[top].toFixed(2)}` : S.wait, note: S.tileMaskNote },
        { label: S.tileKeys, value: `${N}`, note: S.tileKeysNote },
      ];
    }
    if (params.page === "decoder" && params.phase === "training") {
      const D = state.decT, t = r >= 0 ? D.tokens[r + 1] : null;
      return [
        rowsTile,
        { label: S.tileTarget, value: t ? `${t} ${D.probs[r][M.VOCAB.indexOf(t)].toFixed(2)}` : S.wait, note: S.tileTargetNote },
        { label: S.tileKeysRow, value: r >= 0 ? `${r + 1}` : S.wait, note: S.tileKeysRowNote },
      ];
    }
    if (params.page === "decoder") {
      const G = state.decG, genR = r >= G.promptLen - 1, shownN = Math.max(G.promptLen, genR ? k + 1 : k), p = r >= 0 ? G.probs[r] : null;
      return [
        { label: S.tileGen, value: `${Math.min(shownN, G.tokens.length)} of ${G.tokens.length}`, note: S.tileGenNote },
        rowsTile,
        { label: S.tileNext, value: p && genR ? `${G.tokens[r + 1]} ${Math.max(...p).toFixed(2)}` : S.wait, note: S.tileNextNote },
      ];
    }
    const T = state.dna, A = M.crossMean(T), codon = r >= 0 ? (A[r][3 * r] + A[r][3 * r + 1] + A[r][3 * r + 2]).toFixed(2) : S.wait;
    if (params.phase === "training") {
      const t = r >= 0 ? T.protein[r] : null;
      return [
        rowsTile,
        { label: S.tileTarget, value: t ? `${t} ${T.probs[r][M.TGT.indexOf(t)].toFixed(2)}` : S.wait, note: S.tileTargetNoteX },
        { label: S.tileCodon, value: codon, note: S.tileCodonNote },
      ];
    }
    return [
      rowsTile,
      { label: S.tileProt, value: k > 0 ? T.protein.slice(0, k).join("") : S.wait, note: S.tileProtNote },
      { label: S.tileCodon, value: codon, note: S.tileCodonNote },
    ];
  },

  summary({ params, state, anim }) {
    const pg = pageOf(anim, params);
    return S.sum(PAGES.find((p) => p.value === params.page).label, pg.n, maxOf(params, state));
  },
});
