/* ============================================================================
   Widget 84 · Language: Transformer (`transformer`) — PHM5005 08-1 cells 2–3,
   Transformer Architecture and Transformer Tasks. DRAFT, rebuilt 2026-09-27
   to the replan (catalogue § Slot 84, *REPLANNED*).

   Three pages BY ARCHITECTURE, his framing ("so we go by architecture?
   encoder, decoder, encoder-decoder? but inside each, we show how attention is
   different?"), 08-1 cell 3's three families in the lesson's order:

     ENCODER          the masked-token model. His encoder figure at the left,
                      its self-attention box joined by a leader to the weights
                      matrix (every key); a Sentence and a Replace toggle
                      swap one later token, and a bar under each earlier
                      token's column is how far its final vector moves. No
                      Step: an encoder does not generate (his yes).
     DECODER          the next-token model, the same figure in the same place:
                      the keys after each query masked, and the same bars now
                      exactly 0. Below it, generation from the lesson's prompt,
                      the page's Step: the next token's probabilities, the
                      largest fed back, stopping at the first ".".
     ENCODER–DECODER  the DNA -> protein model, his two-stack figure on top and
                      a leader from each of its three attention boxes to its
                      matrix: the encoder's over the gene, the decoder's masked
                      one over the protein so far, and cross-attention, rows from
                      the decoder and columns from the encoder. A press adds an
                      amino acid. Keys: One vector draws 10-2's template, the gene
                      pooled to one key, weight 1 whatever the query.

   THE DIAGRAM IS JOINED TO THE MATRIX (his ask for the draft, 2026-09-27,
   `_lab/transformer-diagram-mock.html`: a leader line, the diagram at the left
   on pages 1–2 and on top on page 3, the boxes filled as his figures). Every
   token label takes the hue of the stack it came from — encoder --c-group-a,
   decoder --c-group-b, his figures' blue and orange — so a matrix's edges say
   where its rows and columns come from. The weights are the mean of the four
   heads on every page (his pick: the two models' heads are different heads).

   THE MODELS ARE TRAINED AND ONLY READ (model.js, weights generated by
   `_lab/transformer-weights.py`, held to torch by `_lab/transformer-verify.mjs`).

   EACH PAGE KEEPS ITS OWN PLACE: `anim.p[page]` counts its presses, since a
   page is a display parameter (invariant 3). A press belongs to the page it
   started on: a switch mid-press finishes it and `halt` ends the loop
   (widget 70's rule, 2026-09-19).
   ========================================================================= */

import { defineWidget, mathmlRenders } from "../core/index.js";
import * as M from "./model.js";

const PAGES = [{ value: "encoder", label: "Encoder" }, { value: "decoder", label: "Decoder" }, { value: "encoder-decoder", label: "Encoder–decoder" }];
const ON = (page) => ({ param: "page", equals: page });
const SELF = { any: [ON("encoder"), ON("decoder")] };

/* ================================================================== copy */

const S = {
  title: "Deep Learning - Language: Transformer",
  subtitle: "Encoders and decoders are built from the same blocks and differ in which tokens each query may attend to. In an encoder "
    + "every token attends to the whole sequence, so each token's vector depends on the tokens after it; in a decoder a token attends "
    + "only to the tokens before it, which lets the output be generated one token at a time. An encoder–decoder adds cross-attention: "
    + "queries from the output so far, keys and values from the encoded input.",
  pageLabel: "Step",
  sentenceLabel: "Sentence", sentenceDetail: "Synthetic clinical notes; the tokens after the arrow replace the later ones.",
  replaceLabel: "Replace", replaceDetail: "The sentence as written, or with its later tokens replaced.",
  replaceOpts: [{ value: "original", label: "Original" }, { value: "replaced", label: "Replaced" }],
  geneLabel: "Gene", geneDetail: "Six codons of DNA, read by a model trained to write out the protein.",
  keysLabel: "Keys", keysDetail: "The gene as 18 nucleotide tokens, or pooled to one vector.",
  keysOpts: [{ value: "every", label: "Every nucleotide" }, { value: "one", label: "One vector" }],
  step: { decoder: "Next token", "encoder-decoder": "Next amino acid" },
  stepTitle: { decoder: "Compute the next token's probabilities and feed the largest back", "encoder-decoder": "Compute the next amino acid from the gene and the protein so far" },
  runLabel: "Play", runTitle: "Run the rest",
  wait: "—",

  /* the stacks, as his figures label them */
  enc: "Encoder", dec: "Decoder", ffn: "Feed forward", selfAtt: "Self-attention", masked: ["Masked self-", "attention"], cross: "Cross-attention",
  embedding: "Embedding", times: "× 2",
  encIn: "Input sequence", encOut: "Representation", decIn: "Tokens so far", decOut: "Next token",
  geneIn: "The gene (DNA)", protIn: "The protein so far", protOut: "Next amino acid",

  /* pages 1–2 */
  keysOf: (who) => `keys (columns): the ${who}'s tokens`, queriesOf: (who) => `queries (rows): the ${who}'s tokens`,
  meanNote: "block 1, mean of 4 heads",
  moveHead: "How far each earlier token's final vector moves",
  moveWait: "Replace: Replaced draws the bars",
  eg: { encoder: "e.g. BERT · understanding: classification, named entity recognition, de-identification",
        decoder: "e.g. GPT · generation: language modelling, text generation, dialogue",
        "encoder-decoder": "e.g. T5, BART · sequence to sequence: translation, summarisation, image → text" },
  gen: "Generation, the output fed back", genNext: (t) => `next after "${t}"`, genArrow: "→ ?",
  genWait: "Next token computes the probabilities for the token after the prompt",

  /* page 3 */
  encRows: "rows and columns: the gene", decRows: "rows and columns: the protein so far",
  crossCols: "keys and values (columns): the encoder's output", crossRows: "queries (rows): the decoder",
  pooled: ["the gene as", "one vector"],
  oneNote: ["Softmax over one key is 1 whatever the query:", "every row reads the same vector, so the", "protein's queries change nothing."],
  xWait: "Next amino acid adds the first row",

  tileReplaced: "Replaced", tileReplacedNote: "the later tokens swapped",
  tileMoved: "Earlier tokens moved", tileMovedNote: "of those before the first swapped token",
  tileMax: "Largest move", tileMaxNote: "the distance an earlier token's final vector moved",
  tileNext: "Next token", tileNextNote: "the largest probability",
  tileAmino: "Amino acids", tileAminoNote: "written so far",
  tileCodon: "On its own codon", tileCodonNote: "the newest row's weight on its three nucleotides",
  tileKeys: "Keys per query", tileKeysNote: "what each row of cross-attention reads",
  sum: (page, n, max) => `${page}: ${n} of ${max} computed.`,
};

/* ============================================================ the card */

const MATHML = mathmlRenders();
let cardHost = null, cardKey = null;
const mi = (s) => `<mi>${s}</mi>`, mo = (s) => `<mo>${s}</mo>`;
const sub = (v, s) => `<msub>${mi(v)}${mi(s)}</msub>`;
const SOFT = (inner) => `<msub>${mi("softmax")}${mi("j")}</msub>${mo("(")}${inner}${mo(")")}`;
const QK = `<mfrac><mrow>${sub("q", "i")}${mo("·")}${sub("k", "j")}</mrow><msqrt>${sub("d", "k")}</msqrt></mfrac>`;
const MATH = {
  encoder: `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(QK)}</mrow></math>`,
  decoder: `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(`${QK}${mo("+")}${sub("m", "ij")}`)}</mrow></math>`,
  "encoder-decoder": `<math><mrow>${sub("α", "ij")}${mo("=")}${SOFT(QK)}</mrow></math>`,
};
const PLAIN = { encoder: "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ)", decoder: "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ + mᵢⱼ)", "encoder-decoder": "αᵢⱼ = softmaxⱼ(qᵢ·kⱼ / √dₖ)" };
const NOTE = {
  encoder: "i and j: the encoder's tokens, every j", decoder: "mᵢⱼ = −∞ for j > i, else 0",
  "encoder-decoder": "in cross-attention, i: the decoder's tokens, j: the encoder's",
};
function renderCard(params) {
  const figure = document.querySelector("#widget .w-figure");
  if (!figure || !figure.parentNode) return;
  const which = params.page;
  if (!cardHost) { cardHost = document.createElement("div"); cardHost.className = "w-math"; cardHost.style.minHeight = "2.4em"; figure.parentNode.insertBefore(cardHost, figure); cardKey = null; }
  if (which === cardKey) return;
  cardKey = which;
  cardHost.innerHTML = `<div class="w-math-eq" style="min-height:0">${MATHML ? MATH[which] : `<span>${PLAIN[which]}</span>`}`
    + `<span style="color:var(--ink-3);font-size:var(--fs-xs)">&nbsp;&nbsp;${NOTE[which]}</span></div>`;
}

/* ============================================================ drawing kit */

const PAD_L = 12, PAD_R = 12;
const rgb = (c) => { const m = String(c).match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : [128, 128, 128]; };
const mixRgb = (a, b, t) => a.map((x, i) => Math.round(x + (b[i] - x) * Math.max(0, Math.min(1, t))));
const css = (p) => `rgb(${p.join(",")})`;
const lum = (p) => (0.2126 * p[0] + 0.7152 * p[1] + 0.0722 * p[2]) / 255;
/* a weight on one ramp from --surface-3 to --c-magnitude; √ so small weights still show */
const weightRgb = (colors, w) => mixRgb(rgb(colors.surface3), rgb(colors.magnitude), Math.sqrt(w));
/** the ink that reads on a fill: whichever of ink and surface is further from it in luminance */
const inkOn = (colors, p) => (Math.abs(lum(p) - lum(rgb(colors.ink1))) > Math.abs(lum(p) - lum(rgb(colors.surface))) ? colors.ink1 : colors.surface);
const ease = (t) => (t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2);
const lerp = (a, b, t) => a + (b - a) * t;
const mono = (colors) => `${colors.fsXs} ${colors.mono}`;
const cap = (colors) => `600 ${colors.fsSm} ${colors.font}`;
const small = (colors) => `${colors.fsXs} ${colors.font}`;

function txt(ctx, s, x, y, { font, fill, align = "left", baseline = "middle" }) {
  ctx.save(); ctx.font = font; ctx.fillStyle = fill; ctx.textAlign = align; ctx.textBaseline = baseline; ctx.fillText(s, x, y); ctx.restore();
}
function poly(ctx, pts, stroke, lw = 1.5, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); pts.forEach(([x, y], i) => (i ? ctx.lineTo(x, y) : ctx.moveTo(x, y))); ctx.stroke(); ctx.restore();
}
function arrow(ctx, x1, y1, x2, y2, stroke, lw = 1.2) {
  poly(ctx, [[x1, y1], [x2, y2]], stroke, lw);
  const a = Math.atan2(y2 - y1, x2 - x1);
  ctx.save(); ctx.fillStyle = stroke; ctx.beginPath(); ctx.moveTo(x2, y2);
  ctx.lineTo(x2 - 6 * Math.cos(a - 0.45), y2 - 6 * Math.sin(a - 0.45)); ctx.lineTo(x2 - 6 * Math.cos(a + 0.45), y2 - 6 * Math.sin(a + 0.45)); ctx.fill(); ctx.restore();
}
function rect(ctx, x, y, w, h, stroke, lw = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = lw; if (dash) ctx.setLineDash(dash); ctx.strokeRect(x, y, w, h); ctx.restore();
}
const textW = (ctx, font, s) => { ctx.save(); ctx.font = font; const w = ctx.measureText(s).width; ctx.restore(); return w; };
function rotated(ctx, s, x, y, opts) { ctx.save(); ctx.translate(x, y); ctx.rotate(-Math.PI / 2); txt(ctx, s, 0, 0, opts); ctx.restore(); }

/* ----------------------------------------------------------- the stacks */

/* ONE STACK, AS HIS FIGURES DRAW IT: the output at the top, the block's boxes in a
   dashed frame marked × 2, the embedding, the input at the bottom; every box filled
   in the stack's hue, the one joined to a matrix outlined in ink. Returns each box's
   rectangle by key, and the stack's bottom. */
const SK = { bh: 26, bh2: 34, gap: 14 };
/** a stack's height with `n1` one-line and `n2` two-line boxes in its frame */
const stackHeight = (n1, n2) => 8 + 20 + n1 * SK.bh + n2 * SK.bh2 + (n1 + n2 - 1) * SK.gap + 14 + 20 + SK.bh + 26 + 4;
function stack(ctx, colors, x, top, w, hue, { title, blocks, hot, input, output }) {
  const r = {}, fill = rgb(hue), ink = inkOn(colors, fill);
  const draw = (key, lines, y, h) => {
    ctx.fillStyle = hue; ctx.fillRect(x, y, w, h);
    if (hot.includes(key)) rect(ctx, x - 1.5, y - 1.5, w + 3, h + 3, colors.ink1, 2);
    [].concat(lines).forEach((l, i, all) => txt(ctx, l, x + w / 2, y + h / 2 + (i - (all.length - 1) / 2) * 12, { font: small(colors), fill: ink, align: "center" }));
    r[key] = { x, y, w, h };
  };
  let y = top;
  txt(ctx, output, x + w / 2, y, { font: small(colors), fill: colors.ink2, align: "center" }); y += 8;
  arrow(ctx, x + w / 2, y + 14, x + w / 2, y + 3, colors.ink3); y += 20;
  const fTop = y - 4;
  blocks.forEach(([key, lines], i) => {
    const h = [].concat(lines).length > 1 ? SK.bh2 : SK.bh;
    draw(key, lines, y, h);
    if (i > 0) { const up = r[blocks[i - 1][0]]; arrow(ctx, x + w / 2, y - 1, x + w / 2, up.y + up.h + 2, colors.ink3); }
    y += h + (i < blocks.length - 1 ? SK.gap : 0);
  });
  rect(ctx, x - 7, fTop, w + 14, y - fTop + 4, colors.reference, 1.3, [4, 3]);
  txt(ctx, S.times, x + w + 7, fTop - 8, { font: small(colors), fill: colors.reference, align: "right" });
  y += 14; arrow(ctx, x + w / 2, y + 14, x + w / 2, y + 2, colors.ink3); y += 20;
  draw("embedding", S.embedding, y, SK.bh); y += SK.bh;
  arrow(ctx, x + w / 2, y + 16, x + w / 2, y + 2, colors.ink3); y += 26;
  txt(ctx, input, x + w / 2, y, { font: small(colors), fill: colors.ink2, align: "center" });
  rotated(ctx, title, x - 16, (fTop + r.embedding.y) / 2, { font: cap(colors), fill: colors.ink1, align: "center" });
  r.bottom = y + 4;
  return r;
}

/* ------------------------------------------------------------ a matrix */

/** weights as a grid: rows over columns, labels in their sources' hues; `rows` limits the
    filled rows (the rest blank), `causal` leaves the keys after each query blank */
function matrix(ctx, colors, A, rt, ct, x0, y0, cs, { rowHue, colHue, causal = false, rows = A.length, colLabels = true, rowLabels = true, digits = true } = {}) {
  const font = mono(colors);
  if (colLabels) ct.forEach((t, j) => rotated(ctx, t, x0 + j * cs + cs / 2, y0 - 5, { font, fill: colHue, align: "left" }));
  const gap = cs > 5 ? 1 : 0;
  for (let i = 0; i < A.length; i++) {
    if (rowLabels) txt(ctx, rt[i], x0 - 5, y0 + i * cs + cs / 2, { font, fill: i < rows ? rowHue : colors.ink3, align: "right" });
    for (let j = 0; j < A[i].length; j++) {
      const x = x0 + j * cs, y = y0 + i * cs, blank = (causal && j > i) || i >= rows;
      const p = blank ? null : weightRgb(colors, A[i][j]);
      ctx.fillStyle = p ? css(p) : colors.surface2; ctx.fillRect(x, y, cs - gap, cs - gap);
      if (p && digits && cs >= 22) txt(ctx, A[i][j].toFixed(2).replace(/^0/, ""), x + cs / 2 - 0.5, y + cs / 2, { font, fill: inkOn(colors, p), align: "center" });
    }
  }
  rect(ctx, x0 - 0.5, y0 - 0.5, A[0].length * cs, A.length * cs, colors.ink2);
  return { x0, y0, w: A[0].length * cs, h: A.length * cs };
}

/* the newest filled row outlined, gliding down from the last one */
function rowOutline(ctx, colors, m, ch, n, t) {
  if (n < 1) return;
  const y = n >= 2 ? lerp(n - 2, n - 1, ease(t)) : n - 1;
  rect(ctx, m.x0 - 2.5, m.y0 + y * ch - 2, m.w + 4, ch + 3, colors.ink1, 1.5, [3, 3]);
}

/* ================================================= pages 1–2: Encoder and Decoder */

/* THE SAME FIGURE ON BOTH PAGES, IN THE SAME PLACE, so the page switch is the
   comparison: the stack at the left, a leader from its attention box to a bracket
   on the matrix's rows, the matrix of the sentence as the Replace toggle has it,
   and under each earlier token's column how far its final vector moved. The tokens
   that differ are framed in ink on both versions. One scale for the bars on both
   pages, so the decoder's zeros read against the encoder's. */
const PG = { top: 16, labH: 70, stackW: 118, moveH: 50, movePx: 50 / 12 };
const pgGeom = (w, L) => {
  const sx = PAD_L + 24, sw = Math.min(PG.stackW, Math.round(w * 0.24)), x0 = sx + sw + 104;
  const cs = Math.max(16, Math.min(28, Math.floor((w - PAD_R - x0) / L)));
  const matTop = PG.top + 16 + PG.labH, matBot = matTop + L * cs, moveTop = matBot + 34;
  return { sx, sw, x0, cs, matTop, matBot, moveTop, eg: moveTop + 14 + PG.moveH + 30 };
};
const LMAX = Math.max(...M.PAIRS.flat().map((s) => M.tokensOf(s).length));
const heightSelf = (w) => pgGeom(w, LMAX).eg + 14;
const GEN = { gap: 30, ctx: 24, lane: 42, cap: 60, bars: 72, pitch: 18, barH: 14 };
const heightDecoder = (w) => heightSelf(w) + GEN.gap + GEN.bars + 5 * GEN.pitch + 10;

function drawSelf(ctx, colors, w, params, state) {
  const enc = params.page === "encoder", hue = enc ? colors.groupA : colors.groupB, who = enc ? "encoder" : "decoder";
  const R = enc ? state.encRep : state.decRep, shown = params.replace === "replaced" ? R.replaced : R.original;
  const g = pgGeom(w, LMAX), { sx, sw, x0, cs, matTop, matBot, moveTop } = g, L = shown.tokens.length;
  const attKey = enc ? "self" : "masked";
  const st = stack(ctx, colors, sx, PG.top, sw, hue, {
    title: enc ? S.enc : S.dec, hot: [attKey], input: enc ? S.encIn : S.decIn, output: enc ? S.encOut : S.decOut,
    blocks: [["ffn", S.ffn], [attKey, enc ? S.selfAtt : S.masked]],
  });
  /* the matrix, its sources along two edges */
  const m = matrix(ctx, colors, shown.alpha, shown.tokens, shown.tokens, x0, matTop, cs, { rowHue: hue, colHue: hue, causal: !enc });
  txt(ctx, S.keysOf(who), x0, PG.top, { font: small(colors), fill: hue });
  rotated(ctx, S.queriesOf(who), x0 - 78, matTop + m.h / 2, { font: small(colors), fill: hue, align: "center" });
  /* the tokens that differ between the two versions, framed */
  rect(ctx, x0 + R.first * cs - 1.5, matTop - 1.5, (L - R.first) * cs + 2, L * cs + 2, colors.ink1, 1.5, [4, 3]);
  rect(ctx, x0 - 1.5, matTop + R.first * cs - 1.5, L * cs + 2, (L - R.first) * cs + 2, colors.ink1, 1.5, [4, 3]);
  /* the leader: the attention box to a bracket on the rows */
  const b = st[attKey], bx = x0 - 92, lx = x0 - 98;
  poly(ctx, [[b.x + b.w + 3, b.y + b.h / 2], [lx, b.y + b.h / 2], [lx, matTop + m.h / 2], [bx, matTop + m.h / 2]], colors.ink1, 1.5);
  poly(ctx, [[bx, matTop], [bx, matTop + m.h]], colors.ink1, 1.5);
  txt(ctx, S.meanNote, x0, matBot + 12, { font: small(colors), fill: colors.ink3 });
  /* how far each earlier token moved: the same scale on both pages */
  txt(ctx, S.moveHead, sx - 16, moveTop, { font: small(colors), fill: colors.ink2 });
  const base = moveTop + 14 + PG.moveH, on = params.replace === "replaced";
  for (let i = 0; i < R.first; i++) {
    const x = x0 + i * cs;
    ctx.fillStyle = colors.surface2; ctx.fillRect(x + 3, moveTop + 14, cs - 7, PG.moveH);
    if (!on) continue;
    const h = Math.min(PG.moveH, R.move[i] * PG.movePx);
    ctx.fillStyle = hue; ctx.fillRect(x + 3, base - h, cs - 7, h);
    /* a value wider than its column: every other one a line lower, so none overlaps its neighbour */
    const lab = R.move[i].toFixed(2), low = textW(ctx, mono(colors), lab) > cs - 3 && i % 2 === 1;
    txt(ctx, lab, x + cs / 2, base + (low ? 21 : 10), { font: mono(colors), fill: colors.ink1, align: "center" });
  }
  poly(ctx, [[x0, base + 0.5], [x0 + R.first * cs, base + 0.5]], colors.grid, 1);
  if (!on) txt(ctx, S.moveWait, x0, base + 10, { font: small(colors), fill: colors.ink3 });
  txt(ctx, S.eg[params.page], PAD_L, g.eg, { font: small(colors), fill: colors.ink3 });
}

/* GENERATION, THE DECODER PAGE'S STEP (his pick: below the figure, the lesson's
   prompt only). A press reads the tokens so far, prints the next token's five
   largest probabilities, and the largest glides up to the end of the line: up
   its own column, along a lane under the line, then into place — clear of the
   words already there (Kenneth, 2026-09-19: nothing moves over marks in place). */
const GLIDE_AT = 0.35;
const DEC_MS = { step: 900, run: 520 }, ENCDEC_MS = { step: 520, run: 300 };
function drawGeneration(ctx, colors, w, state, pg) {
  const y0 = heightSelf(w) + GEN.gap, gen = state.gen, n = pg.n, st = n > 0 ? gen.steps[n - 1] : null, landed = pg.t >= 1;
  const u = landed ? 1 : Math.max(0, (pg.t - GLIDE_AT) / (1 - GLIDE_AT)), promptLen = 1 + M.PROMPT.split(" ").length;
  txt(ctx, S.gen, PAD_L, y0, { font: cap(colors), fill: colors.ink1 });
  const toks = st ? (landed ? [...st.context, st.next] : st.context) : gen.steps[0].context;
  const cy = y0 + GEN.ctx;
  let x = PAD_L;
  toks.slice(1).forEach((t, i) => {
    txt(ctx, t, x, cy, { font: mono(colors), fill: i + 1 >= promptLen ? colors.groupB : colors.ink1 });
    x += textW(ctx, mono(colors), t) + 8;
  });
  if (!st || landed) txt(ctx, S.genArrow, x, cy, { font: small(colors), fill: colors.ink3 });
  const lx = PAD_L + 110, bmax = w - PAD_R - lx - 90, by = (r) => y0 + GEN.bars + r * GEN.pitch;
  if (!st) { txt(ctx, S.genWait, PAD_L, by(0) + GEN.barH / 2, { font: small(colors), fill: colors.ink3 }); return; }
  txt(ctx, S.genNext(st.context.at(-1)), lx, y0 + GEN.cap, { font: small(colors), fill: colors.ink3 });
  const order = st.probs.map((p, i) => [p, i]).sort((a, b) => b[0] - a[0]).slice(0, 5);
  order.forEach(([p, i], r) => {
    const y = by(r), word = M.VOCAB[i];
    if (!(r === 0 && u > 0 && !landed)) txt(ctx, word, lx - 6, y + GEN.barH / 2, { font: mono(colors), fill: r ? colors.ink2 : colors.ink1, align: "right" });
    ctx.fillStyle = r ? colors.surface3 : colors.groupB; ctx.fillRect(lx, y, Math.max(1, p * bmax), GEN.barH);
    txt(ctx, p.toFixed(3), lx + Math.max(1, p * bmax) + 5, y + GEN.barH / 2, { font: mono(colors), fill: colors.ink2 });
  });
  if (u > 0 && !landed) {
    const fx = lx - 6 - textW(ctx, mono(colors), st.next), fy = by(0) + GEN.barH / 2, lane = y0 + GEN.lane;
    const legs = [fy - lane, Math.abs(x - fx), lane - cy], total = legs[0] + legs[1] + legs[2];
    let d = ease(u) * total, gx = fx, gy = fy;
    if (d <= legs[0]) gy = fy - d;
    else if ((d -= legs[0]) <= legs[1]) { gy = lane; gx = lerp(fx, x, d / legs[1]); }
    else { d -= legs[1]; gx = x; gy = lane - d; }
    txt(ctx, st.next, gx, gy, { font: mono(colors), fill: colors.groupB });
  }
  /* his figure's loop: from the chosen bar round to the input */
  const rx = w - PAD_R - 4, ry = by(0) + GEN.barH / 2, ay = cy - 14, ax = x + textW(ctx, small(colors), S.genArrow) / 2;
  poly(ctx, [[lx + Math.max(1, order[0][0] * bmax) + 44, ry], [rx, ry], [rx, ay], [ax, ay]], colors.grid, 1.2);
  arrow(ctx, ax, ay, ax, cy - 8, colors.grid);
}

/* ===================================================== page 3: Encoder–decoder */

/* HIS TWO-STACK FIGURE ON TOP, three leaders down: the encoder's self-attention to
   the gene × gene matrix, the decoder's masked self-attention to the protein's
   triangle, and cross-attention to the cross matrix, whose columns are the encoder's
   output (blue) and rows the decoder's queries (amber). A press writes the next
   amino acid: both decoder matrices gain a row. Keys: One vector draws the gene
   pooled to one key, which is what 10-2 cell 5's template does. */
const XD = { ce: 7, cd: 15, crossGap: 62, cross: 20 };
const xdGeom = (w) => {
  const top = 22, encX = PAD_L + 58, encW = Math.min(112, Math.round(w * 0.2)), decW = Math.min(124, Math.round(w * 0.23));
  const decX = Math.round(Math.min(w * 0.6, w - PAD_R - 70 - decW));
  /* the encoder's stack sits lower by the decoder's extra box, so both embeddings line up */
  const encTop = top + (stackHeight(2, 1) - stackHeight(2, 0));
  const mTop = top + stackHeight(2, 1) + 18;
  const cc = Math.max(12, Math.min(XD.cross, Math.floor((w - PAD_R - 40 - 96) / 18)));
  const cy = mTop + 40 + 7 * XD.cd + XD.crossGap;
  return { top, encTop, encX, encW, decX, decW, mTop, cc, cy, eg: cy + 6 * cc + 44 };
};
const heightEncDec = (w) => xdGeom(w).eg + 14;

function drawEncDec(ctx, colors, w, params, state, pg) {
  const g = xdGeom(w), T = state.dna, nt = T.dna.split(""), prot = ["[BOS]", ...T.protein], R = pg.n, one = params.keys === "one";
  const blue = colors.groupA, amber = colors.groupB;
  const Se = stack(ctx, colors, g.encX, g.encTop, g.encW, blue, {
    title: S.enc, hot: ["self"], input: S.geneIn, output: S.encOut, blocks: [["ffn", S.ffn], ["self", S.selfAtt]] });
  const Sd = stack(ctx, colors, g.decX, g.top, g.decW, amber, {
    title: S.dec, hot: ["masked", "cross"], input: S.protIn, output: S.protOut, blocks: [["ffn", S.ffn], ["cross", S.cross], ["masked", S.masked]] });
  /* the encoder's output into the decoder's cross-attention, as his figure */
  const cr = Sd.cross, ox = g.encX + g.encW / 2, midX = Math.round((g.encX + g.encW + g.decX) / 2 + 6);
  poly(ctx, [[ox, g.encTop - 8], [ox, g.top - 14], [midX, g.top - 14], [midX, cr.y + cr.h / 2]], blue, 1.5);
  arrow(ctx, midX, cr.y + cr.h / 2, cr.x - 22, cr.y + cr.h / 2, blue, 1.5);
  /* the encoder's attention over the gene */
  const E = M.meanHeads(T.enc[1]), me = matrix(ctx, colors, E, nt, nt, 30, g.mTop + 16, XD.ce, { rowHue: blue, colHue: blue, colLabels: false, rowLabels: false, digits: false });
  txt(ctx, S.encRows, 24, g.mTop, { font: small(colors), fill: blue });
  const se = Se.self;
  poly(ctx, [[se.x - 3, se.y + se.h / 2], [PAD_L + 4, se.y + se.h / 2], [PAD_L + 4, me.y0 + me.h / 2], [me.x0 - 4, me.y0 + me.h / 2]], colors.ink1, 1.5);
  /* the decoder's masked attention over the protein so far */
  const Ds = M.meanHeads(T.self[1]), dx = Math.round(g.decX - 20);
  const md = matrix(ctx, colors, Ds, prot, prot, dx, g.mTop + 40, XD.cd, { rowHue: amber, colHue: amber, causal: true, rows: R, digits: false });
  txt(ctx, S.decRows, dx - 50, g.mTop, { font: small(colors), fill: amber });
  rowOutline(ctx, colors, md, XD.cd, R, pg.t);
  const ms = Sd.masked, rx1 = w - PAD_R - 22, rx2 = w - PAD_R - 6;
  poly(ctx, [[ms.x + ms.w + 3, ms.y + ms.h / 2], [rx1, ms.y + ms.h / 2], [rx1, md.y0 + md.h / 2], [md.x0 + md.w + 4, md.y0 + md.h / 2]], colors.ink1, 1.5);
  /* cross-attention: the protein's rows over the gene's columns, or over one pooled key */
  const cx = PAD_L + 84, cy = g.cy, ch = g.cc, rows = prot.slice(0, 6).map((p, r) => `${p} → ${r < R ? prot[r + 1] : "?"}`);
  let mx;
  if (!one) {
    const cc = g.cc;
    T.codons.forEach((c, k) => {
      const x0 = cx + 3 * k * cc;
      poly(ctx, [[x0 + 2, cy - 22.5], [x0 + 3 * cc - 3, cy - 22.5]], colors.ink3, 1);
      txt(ctx, c, x0 + 1.5 * cc, cy - 30, { font: mono(colors), fill: colors.ink3, align: "center" });
    });
    nt.forEach((c, j) => txt(ctx, c, cx + j * cc + cc / 2, cy - 10, { font: mono(colors), fill: blue, align: "center" }));
    mx = matrix(ctx, colors, M.crossMean(T).slice(0, 6), rows, nt, cx, cy, cc, { rowHue: amber, colHue: blue, rows: R, colLabels: false, digits: false });
  } else {
    /* one key, drawn as one column wide enough for its weight: every filled row is 1.00 */
    const kw = 48;
    S.pooled.forEach((s, i) => txt(ctx, s, cx + kw / 2, cy - 26 + i * 13, { font: small(colors), fill: blue, align: "center" }));
    rows.forEach((t, r) => {
      txt(ctx, t, cx - 5, cy + r * ch + ch / 2, { font: mono(colors), fill: r < R ? amber : colors.ink3, align: "right" });
      const p = r < R ? weightRgb(colors, 1) : null;
      ctx.fillStyle = p ? css(p) : colors.surface2; ctx.fillRect(cx, cy + r * ch, kw - 1, ch - 1);
      if (p) txt(ctx, "1.00", cx + kw / 2, cy + r * ch + ch / 2, { font: mono(colors), fill: inkOn(colors, p), align: "center" });
    });
    rect(ctx, cx - 0.5, cy - 0.5, kw, 6 * ch, colors.ink2);
    mx = { x0: cx, y0: cy, w: kw, h: 6 * ch };
    S.oneNote.forEach((s, i) => txt(ctx, s, cx + kw + 20, cy + 14 + i * 16, { font: small(colors), fill: colors.ink2 }));
  }
  rowOutline(ctx, colors, mx, ch, R, pg.t);
  txt(ctx, S.crossCols, cx, cy - 48, { font: small(colors), fill: blue });
  txt(ctx, S.crossRows, PAD_L, mx.y0 + mx.h + 14, { font: small(colors), fill: amber });
  poly(ctx, [[cr.x + cr.w + 3, cr.y + cr.h / 2], [rx2, cr.y + cr.h / 2], [rx2, mx.y0 + mx.h / 2], [mx.x0 + mx.w + 4, mx.y0 + mx.h / 2]], colors.ink1, 1.5);
  if (R === 0 && !one) txt(ctx, S.xWait, cx + 8, cy + 3 * ch, { font: small(colors), fill: colors.ink3 });
  txt(ctx, S.eg[params.page], PAD_L, g.eg, { font: small(colors), fill: colors.ink3 });
}

/* ============================================================ the widget */

const maxOf = (page, state) => (page === "decoder" ? state.gen.steps.length : page === "encoder-decoder" ? 6 : 0);
const msOf = (page, mode) => (page === "decoder" ? DEC_MS : ENCDEC_MS)[mode === "run" ? "run" : "step"];
const pageOf = (anim, params) => anim.p[params.page] ?? { n: 0, t: 1 };
function settle(anim, params, state) {
  anim.page = params.page;
  anim.inert = params.page === "encoder";
  const pg = anim.p[params.page];
  anim.done = pg ? pg.n >= maxOf(params.page, state) && pg.t >= 1 : false;
}

/* memoised: compute() is pure, and each part depends on the parameter named or on nothing */
const MEMO = { enc: {}, dec: {}, gen: null, dna: {} };
function stage(params) {
  const k = Number(params.sentence) - 1;
  MEMO.enc[k] ??= M.replace("base", k);
  MEMO.dec[k] ??= M.replace("causal", k);
  MEMO.gen ??= M.generate(M.PROMPT);
  MEMO.dna[params.gene] ??= M.translate(M.GENES[Number(params.gene) - 1]);
  return { encRep: MEMO.enc[k], decRep: MEMO.dec[k], gen: MEMO.gen, dna: MEMO.dna[params.gene] };
}

defineWidget({
  slug: "transformer",
  status: "draft",
  title: S.title,
  subtitle: S.subtitle,
  layout: "side",
  height: ({ page, w }) => (page === "decoder" ? heightDecoder(w) : page === "encoder-decoder" ? heightEncDec(w) : heightSelf(w)),

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "encoder", display: true },
    sentence: {
      type: "select", label: S.sentenceLabel, detail: S.sentenceDetail, display: true, when: SELF,
      options: M.PAIRS.map(([a, b], i) => {
        const ta = a.split(" "), tb = b.split(" "), f = ta.findIndex((t, j) => t !== tb[j]);
        return { value: String(i + 1), label: `${a} → ${tb.slice(f).join(" ")}` };
      }), default: "1",
    },
    replace: { type: "segmented", label: S.replaceLabel, detail: S.replaceDetail, options: S.replaceOpts, default: "original", display: true, when: SELF },
    gene: {
      type: "select", label: S.geneLabel, detail: S.geneDetail, display: true, when: ON("encoder-decoder"),
      options: M.GENES.map((g, i) => ({ value: String(i + 1), label: M.codons(g).join(" ") })), default: "1",
    },
    keys: { type: "segmented", label: S.keysLabel, detail: S.keysDetail, options: S.keysOpts, default: "every", display: true, when: ON("encoder-decoder") },
    /* authoring escape hatch, first render only: presses already made on the page opened */
    shown: { type: "int", min: 0, max: 8, default: 0, hidden: true },
  },

  legend: [],

  compute: ({ params }) => stage(params),

  animation: {
    stepLabel: { param: "page", labels: S.step, default: S.step.decoder },
    stepTitle: { param: "page", labels: S.stepTitle, default: S.stepTitle.decoder },
    runLabel: S.runLabel,
    runTitle: S.runTitle,
    init: ({ params, state, fromScratch }) => {
      const anim = { p: { decoder: { n: 0, t: 1 }, "encoder-decoder": { n: 0, t: 1 } }, gene: params.gene, moving: false, halt: false };
      const pg = anim.p[params.page];
      if (pg && !fromScratch) pg.n = Math.max(0, Math.min(maxOf(params.page, state), Number(params.shown) || 0));
      settle(anim, params, state);
      return anim;
    },
    advance: (anim, { dt, params, state }) => {
      /* the loop a page switch left running for the other page's press ends here */
      if (anim.halt) { anim.halt = false; anim.moving = false; settle(anim, params, state); return false; }
      const pg = anim.p[params.page];
      if (!pg) { anim.moving = false; return false; }
      const max = maxOf(params.page, state), ms = msOf(params.page, anim.mode);
      let more;
      if (pg.t < 1) { pg.t = Math.min(1, pg.t + dt / ms); more = pg.t < 1 || (anim.mode === "run" && pg.n < max); }
      else if (pg.n < max) { pg.n += 1; pg.t = 0; more = true; }
      else more = false;
      anim.moving = more;
      settle(anim, params, state);
      return more;
    },
    rebuild: (anim, { params, state }) => {
      /* A PRESS BELONGS TO THE PAGE IT STARTED ON (widget 70's rule): a switch
         mid-press finishes it, and `halt` ends the loop at its next frame. Only
         while a press moves: set otherwise, it would swallow the reader's next press. */
      if (anim.moving && (params.page !== anim.page || params.gene !== anim.gene)) {
        for (const pg of Object.values(anim.p)) pg.t = 1;
        anim.halt = true;
      }
      /* another gene is another protein: the page's writing starts over */
      if (params.gene !== anim.gene) { anim.gene = params.gene; anim.p["encoder-decoder"] = { n: 0, t: 1 }; }
      settle(anim, params, state);
    },
  },

  draw({ ctx, colors, w, params, state, anim }) {
    renderCard(params);
    if (params.page === "encoder-decoder") { drawEncDec(ctx, colors, w, params, state, pageOf(anim, params)); return; }
    drawSelf(ctx, colors, w, params, state);
    if (params.page === "decoder") drawGeneration(ctx, colors, w, state, pageOf(anim, params));
  },

  readout({ params, state, anim }) {
    const pg = pageOf(anim, params), k = pg.t >= 1 ? pg.n : pg.n - 1;
    if (params.page === "encoder-decoder") {
      const one = params.keys === "one", A = M.crossMean(state.dna), r = pg.n - 1;
      return [
        { label: S.tileAmino, value: `${Math.max(0, k)} of 6`, note: S.tileAminoNote },
        { label: S.tileCodon, value: r >= 0 && !one ? (A[r][3 * r] + A[r][3 * r + 1] + A[r][3 * r + 2]).toFixed(2) : S.wait, note: S.tileCodonNote },
        { label: S.tileKeys, value: one ? "1" : "18", note: S.tileKeysNote },
      ];
    }
    const R = params.page === "encoder" ? state.encRep : state.decRep, on = params.replace === "replaced";
    const moved = R.move.filter((v) => v > 0).length, top = R.move.indexOf(Math.max(...R.move));
    const tiles = [
      { label: S.tileMoved, value: on ? `${moved} of ${R.first}` : S.wait, note: S.tileMovedNote },
      { label: S.tileMax, value: on ? `${R.original.tokens[top]} ${R.move[top].toFixed(2)}` : S.wait, note: S.tileMaxNote },
    ];
    if (params.page === "encoder") {
      const a = R.original.tokens.slice(R.first, -1).join(" "), b = R.replaced.tokens.slice(R.first, -1).join(" ");
      return [{ label: S.tileReplaced, value: on ? `${a} → ${b}` : S.wait, note: S.tileReplacedNote }, ...tiles];
    }
    const st = pg.n > 0 ? state.gen.steps[pg.n - 1] : null;
    return [...tiles, { label: S.tileNext, value: st ? `${st.next} ${Math.max(...st.probs).toFixed(3)}` : S.wait, note: S.tileNextNote }];
  },

  summary({ params, state, anim }) {
    const pg = pageOf(anim, params);
    return S.sum(PAGES.find((p) => p.value === params.page).label, pg.n, maxOf(params.page, state));
  },
});
