/* ============================================================================
   Widget 84 · the models: three small trained transformers, read, never
   trained. `weights.js` is GENERATED by `_lab/transformer-weights.py`;
   `_lab/transformer-verify.mjs` holds every forward here to torch's own
   numbers on every input the widget draws.

     base    the language arc's tiny BERT, widget 83's model: 4 heads of 12,
             FFN 96, two post-LN blocks, masked-token pretraining on the
             synthetic clinical notes. The Encoder and Pre-training pages.
     causal  the same size, trained on the same notes by next-token
             prediction, every key after the query masked. The Decoder and
             Pre-training pages.
     dna     an encoder-decoder, 2 + 2 blocks, trained on DNA -> protein
             (08-1 cell 4's own sequence-to-sequence example). The Decoder
             page's cross-attention.

   A post-LN block, as nn.TransformerEncoderLayer's default and 08-3 cell 28:
     h = LayerNorm(x + Attention(x));  y = LayerNorm(h + FFN(h)),
     FFN(h) = ReLU(h W1^T + b1) W2^T + b2, the same network on every row.
   ========================================================================= */

import { MODELS, VOCABS } from "./weights.js";

export const D = 48, H = 4, DK = 12;
export const VOCAB = VOCABS.clinical;
const ID = Object.fromEntries(VOCAB.map((w, i) => [w, i]));

/* ------------------------------------------------------------ the weights */

function decode(b64) {
  let bytes;
  if (typeof Buffer !== "undefined") bytes = new Uint8Array(Buffer.from(b64, "base64"));
  else { const s = atob(b64); bytes = new Uint8Array(s.length); for (let i = 0; i < s.length; i++) bytes[i] = s.charCodeAt(i); }
  return new Float32Array(bytes.buffer, bytes.byteOffset, bytes.byteLength / 4);
}
/** { name: { v, shape } } for one model, sliced from its one Float32Array in SPEC's order */
function unpack({ spec, b64 }) {
  const all = decode(b64), out = {};
  let o = 0;
  for (const [name, shape] of spec) {
    const n = shape.reduce((a, b) => a * b, 1);
    out[name] = { v: all.subarray(o, o + n), shape };
    o += n;
  }
  if (o !== all.length) throw new Error(`weights: ${o} of ${all.length} numbers read`);
  return out;
}
const W = { base: unpack(MODELS.base), causal: unpack(MODELS.causal), dna: unpack(MODELS.dna) };

/* ------------------------------------------------------------ arithmetic */

/** torch's Linear on a row: y = x W^T + b, W [out][in] row-major */
function linear(x, Wt, bt) {
  const [nOut, nIn] = Wt.shape, y = new Array(nOut);
  for (let o = 0; o < nOut; o++) {
    let s = bt.v[o];
    for (let i = 0; i < nIn; i++) s += Wt.v[o * nIn + i] * x[i];
    y[o] = s;
  }
  return y;
}
function layerNorm(x, g, b) {
  const n = x.length, m = x.reduce((a, v) => a + v, 0) / n;
  const va = x.reduce((a, v) => a + (v - m) * (v - m), 0) / n, s = Math.sqrt(va + 1e-5);
  return x.map((v, i) => ((v - m) / s) * g.v[i] + b.v[i]);
}
const add = (a, b) => a.map((v, i) => v + b[i]);
function softmax(row) {
  let m = -Infinity;
  for (const s of row) if (s > m) m = s;
  const e = row.map((s) => (s === -Infinity ? 0 : Math.exp(s - m)));
  const z = e.reduce((a, b) => a + b, 0);
  return e.map((v) => v / z);
}

/** multi-head attention: queries from X, keys and values from Y (Y = X for self-attention);
    `causal` gives a key after its query the score −∞. Returns W_O's output rows and each
    head's weights [H][Lq][Lk]. */
function attention(T, pre, X, Y, { causal = false } = {}) {
  const Q = X.map((x) => linear(x, T[`${pre}.q`], T[`${pre}.qb`]));
  const K = Y.map((y) => linear(y, T[`${pre}.k`], T[`${pre}.kb`]));
  const V = Y.map((y) => linear(y, T[`${pre}.v`], T[`${pre}.vb`]));
  const alpha = [], Z = X.map(() => new Array(D).fill(0));
  for (let h = 0; h < H; h++) {
    const o = h * DK;
    const A = Q.map((q, i) => softmax(K.map((k, j) => {
      if (causal && j > i) return -Infinity;
      let s = 0;
      for (let d = 0; d < DK; d++) s += q[o + d] * k[o + d];
      return s / Math.sqrt(DK);
    })));
    A.forEach((row, i) => row.forEach((a, j) => { for (let d = 0; d < DK; d++) Z[i][o + d] += a * V[j][o + d]; }));
    alpha.push(A);
  }
  return { out: Z.map((z) => linear(z, T[`${pre}.o`], T[`${pre}.ob`])), alpha };
}
const ffn = (T, pre, x) => linear(linear(x, T[`${pre}.ff1`], T[`${pre}.ff1b`]).map((v) => Math.max(0, v)), T[`${pre}.ff2`], T[`${pre}.ff2b`]);

/** one post-LN encoder block (or a decoder-only block, `causal`): the row after each sublayer */
function block(T, pre, X, { causal = false } = {}) {
  const a = attention(T, `${pre}.att`, X, X, { causal });
  const mid = X.map((x, i) => layerNorm(add(x, a.out[i]), T[`${pre}.n1`], T[`${pre}.n1b`]));
  const out = mid.map((h) => layerNorm(add(h, ffn(T, pre, h)), T[`${pre}.n2`], T[`${pre}.n2b`]));
  return { mid, out, alpha: a.alpha };
}

/* ------------------------------------------------------------ the clinical models */

export const tokensOf = (sentence) => ["[CLS]", ...sentence.split(" "), "[SEP]"];
function embed(T, toks) {
  return toks.map((t, p) => {
    const r = ID[t];
    if (r === undefined) throw new Error(`not in the vocabulary: ${t}`);
    return Array.from({ length: D }, (_, d) => T.tok.v[r * D + d] + T.pos.v[p * D + d]);
  });
}
/** the rows after every stage, in order, and each block's weights */
function run(T, toks, { causal = false } = {}) {
  const x = embed(T, toks), stages = [x], alpha = [];
  let h = x;
  for (const b of ["b0", "b1"]) { const r = block(T, b, h, { causal }); stages.push(r.mid, r.out); alpha.push(r.alpha); h = r.out; }
  return { stages, alpha, h };
}
const predict = (T, row) => softmax(linear(row, T.mlm, T.mlmb));
/** any tokens through the base (encoder) or causal (decoder) model: every stage and each block's weights */
export const forward = (which, toks) => run(W[which], toks, { causal: which === "causal" });

/* The Encoder page's pair: "discharge" in its two senses, one row of the token
   table at the same position, 2 (08-1 cell 0's own example of a word read by
   its context; the arc measured the senses apart after block 1). */
export const PAIR = ["planned discharge home today", "yellow discharge from wound"];
export const PAIR_AT = 2;
export const STAGES = 5;   // x~, then each block's two sublayers
/** both sentences through the base model, every stage */
export const encoderPair = () => PAIR.map((s) => { const toks = tokensOf(s); return { tokens: toks, ...run(W.base, toks) }; });

/** the token table's row nearest a vector, by cosine: which token a row still reads as */
export function nearestToken(v) {
  const T = W.base.tok, nv = Math.hypot(...v);
  let best = -1, bs = -Infinity;
  for (let r = 0; r < VOCAB.length; r++) {
    let dot = 0, nr = 0;
    for (let d = 0; d < D; d++) { const u = T.v[r * D + d]; dot += u * v[d]; nr += u * u; }
    const c = dot / (Math.sqrt(nr) * nv);
    if (c > bs) { bs = c; best = r; }
  }
  return VOCAB[best];
}
export const cosine = (a, b) => { let s = 0, x = 0, y = 0; a.forEach((v, i) => { s += v * b[i]; x += v * v; y += b[i] * b[i]; }); return s / Math.sqrt(x * y); };

/* ------------------------------------------------------------ generation */

/* The Decoder page's prompts: 08-1 cell 4's own decoder example first ("The
   patient was treated with aspirin for" -> "chest"), then four clause openings
   from the notes. Greedy, fed back, and stopping at the first "." or [SEP]
   (his pick, 2026-09-26: the lesson's example ends at the clause; without the
   stop, greedy repeats one clause to the length limit). */
export const PROMPTS = ["treated with aspirin for", "treated with", "no", "yellow", "patient"];
export const STOP = new Set([".", "[SEP]"]);
const MAX_LEN = 16;
/** every step of greedy generation: the context, the next-token probabilities, each block's weights */
export function generate(prompt) {
  const cur = ["[CLS]", ...prompt.split(" ")], steps = [];
  while (cur.length < MAX_LEN) {
    const r = run(W.causal, cur, { causal: true }), probs = predict(W.causal, r.h[r.h.length - 1]);
    const next = VOCAB[probs.indexOf(Math.max(...probs))];
    steps.push({ context: cur.slice(), probs, alpha: r.alpha, next });
    cur.push(next);
    if (STOP.has(next)) break;
  }
  return { prompt, steps, tokens: cur };
}
/** the largest change in the weights rows already computed when the context grows by one:
    zero, since every key after a query is masked */
export function earlierRowChange(g, k, blk, h) {
  if (k < 1) return null;
  const a = g.steps[k - 1].alpha[blk][h], b = g.steps[k].alpha[blk][h];
  let m = 0;
  a.forEach((row, i) => row.forEach((v, j) => { m = Math.max(m, Math.abs(v - b[i][j])); }));
  return m;
}

/* ------------------------------------------------------------ pre-training */

/* The lesson's clause (08-1 cell 4: "treated with [MASK] for chest pain" ->
   "aspirin"; "treated with aspirin for" -> "chest"), token by token: the base
   model with that one token masked, and the causal model from the tokens to its
   left. And the same over EVERY treat clause the notes can hold (2 verbs x 10
   drug-symptom pairs): how often each model's top token is a right one. */
export const CLAUSE = "treated with aspirin for chest pain".split(" ");
export const SYM_DRUG = {
  "chest pain": ["aspirin", "nitrate"], fever: ["paracetamol", "ibuprofen"], infection: ["antibiotics", "cefazolin"],
  breathlessness: ["salbutamol", "oxygen"], nausea: ["ondansetron", "metoclopramide"],
};
export const TREATS = ["treated", "managed"].flatMap((v) => Object.entries(SYM_DRUG).flatMap(([s, ds]) => ds.map((d) => `${v} with ${d} for ${s}`)));
export function mlmAt(toks, j) {
  const x = tokensOf(toks.join(" ")); x[1 + j] = "[MASK]";
  const r = run(W.base, x);
  return predict(W.base, r.h[1 + j]);
}
export function causalAt(toks, j) {
  const r = run(W.causal, ["[CLS]", ...toks.slice(0, j)], { causal: true });
  return predict(W.causal, r.h[r.h.length - 1]);
}
/** the answers counted right at position j of a treat clause */
export function rightAt(toks, j) {
  if (j === 0) return ["treated", "managed"];
  if (j === 2) return SYM_DRUG[toks.slice(4).join(" ")];
  return [toks[j]];
}
const argmaxWord = (p) => VOCAB[p.indexOf(Math.max(...p))];
let TABLE = null;
/** per position of the clause: how many treat clauses each model gets right, and of how many */
export function treatTable() {
  if (TABLE) return TABLE;
  TABLE = Array.from({ length: CLAUSE.length }, () => ({ mlm: 0, causal: 0, n: 0 }));
  for (const c of TREATS) {
    const toks = c.split(" ");
    toks.forEach((_, j) => {
      const ok = rightAt(toks, j);
      TABLE[j].n += 1;
      if (ok.includes(argmaxWord(mlmAt(toks, j)))) TABLE[j].mlm += 1;
      if (ok.includes(argmaxWord(causalAt(toks, j)))) TABLE[j].causal += 1;
    });
  }
  return TABLE;
}
export function clauseSteps() {
  return CLAUSE.map((_, j) => ({ mlm: mlmAt(CLAUSE, j), causal: causalAt(CLAUSE, j), right: rightAt(CLAUSE, j) }));
}

/* ------------------------------------------------------------ DNA -> protein */

export const SRC = VOCABS.dnaSrc, TGT = VOCABS.dnaTgt;
/* the standard genetic code, TCAG order */
const AA = "FFLLSSSSYY**CC*WLLLLPPPPHHQQRRRRIIIMTTTTNNKKSSRRVVVVAAAADDEEGGGG";
export const CODE = {};
"TCAG".split("").forEach((a, i) => "TCAG".split("").forEach((b, j) => "TCAG".split("").forEach((c, k) => { CODE[a + b + c] = AA[16 * i + 4 * j + k]; })));
/* three genes of six codons, drawn by the generator's seeds 5, 11 and 23; the
   third reads glycine from three different codons (GGA, GGG, GGT) */
export const GENES = ["AAACTGGTACACGCCAGG", "CGGGAAACAGACGGAGCT", "GGAGCTGGGCCCGGTGAT"];
export const codons = (dna) => dna.match(/.../g);
export const protein = (dna) => codons(dna).map((c) => CODE[c]);
/** the gene through the encoder, and the protein (after [BOS]) through the decoder, teacher-forced:
    each decoder block's self- and cross-attention, and the decoder's top token at each position */
export function translate(dna) {
  const T = W.dna, src = dna.split("").map((c) => SRC.indexOf(c)), tgt = [1, ...protein(dna).map((a) => TGT.indexOf(a))];
  const emb = (tok, pos, ids) => ids.map((r, p) => Array.from({ length: D }, (_, d) => T[tok].v[r * D + d] + T[pos].v[p * D + d]));
  let m = emb("stok", "spos", src);
  for (const b of ["e0", "e1"]) m = block(T, b, m).out;
  let y = emb("ttok", "tpos", tgt);
  const self = [], cross = [];
  for (const b of ["d0", "d1"]) {
    const s = attention(T, `${b}.self`, y, y, { causal: true });
    y = y.map((r, i) => layerNorm(add(r, s.out[i]), T[`${b}.n1`], T[`${b}.n1b`]));
    const c = attention(T, `${b}.cross`, y, m);
    y = y.map((r, i) => layerNorm(add(r, c.out[i]), T[`${b}.n2`], T[`${b}.n2b`]));
    y = y.map((r) => layerNorm(add(r, ffn(T, b, r)), T[`${b}.n3`], T[`${b}.n3b`]));
    self.push(s.alpha); cross.push(c.alpha);
  }
  const top = y.map((r) => { const p = linear(r, T.out, T.outb); return TGT[p.indexOf(Math.max(...p))]; });
  return { dna, codons: codons(dna), protein: protein(dna), self, cross, top };
}
/** decoder block 2's cross-attention, the mean of its four heads (what the page draws) */
export const crossMean = (t) => t.cross[1][0].map((row, i) => row.map((_, j) => t.cross[1].reduce((s, hd) => s + hd[i][j], 0) / H));
