/* ============================================================================
   Widget 98 · Graphs: Explainability (`gnn-explainer`) — PHM5005 09-2 cells
   84–92 (GNNExplainer on the lesson's trained GAT: PyG's Explainer with
   GNNExplainer(epochs=300, lr=0.01), a feature mask M_x and an edge mask M_e,
   cell 90's scores, cell 92's heat overlay) and 09-1 cell 26 (the three
   families of GNN explanation).

   The misconception (catalogue § Slot 98): the highlighted bonds are why the
   molecule stops E. coli growing, and the mask is unique. Measured on the
   lesson's own model and molecule (`_lab/gnn-explainer-measure.py`): each of
   20 runs keeps 15–21 of the 39 bonds (mask above 0.5), and those bonds alone
   hold p(active) at 0.91–0.97, well above random sets of the same size — but
   two runs keep different sets (median Jaccard 0.52), and only the three
   bonds of N10, the β-lactam nitrogen, are kept by every run. 3,000 epochs
   instead of 300 leaves the runs as far apart.

   THREE PAGES under Step, every call his from `_lab/gnn-explainer-mock.html`
   (2026-10-10, "all recommendations"):

     MASK     one run's optimisation. Initialise draws the random start (every
              mask near 0.5, and the prediction falls to 0.08 because every
              feature is halved too); Optimise plays the 300 epochs, each bond
              as TWO lanes, one per direction, since M_e has one value per
              directed edge. p(active) and the loss beside.
     SCORES   cell 90, then cell 92: Collapse takes each bond's larger
              direction; Average takes each atom's mean over all 39 features of
              M_x (the grid below, most cells 0 because PyG zeroes a mask where
              the feature is 0); Scale stretches both to 0–1 within the
              molecule. The result is the lesson's heat overlay.
     RUNS     One run: the bonds the run keeps, and Test — p(active) with only
              those against 100 random sets of the same size. All runs:
              Overlay adds the 20 runs' kept sets one at a time.

   Random start (1–20) is one control on every page but All runs, so the
   Scores a student reads are the run the Mask page optimised; changing it
   keeps each page's progress. The waters and the two
   Na⁺ are drawn in a strip under the drug: separate pieces of the graph, with
   no bond to it, scored like any atom — max pooling reads every atom.

   Nothing optimises in the page: data.js (generated by
   `_lab/gnn-explainer-data.py`) holds every run's edge masks every 10 epochs,
   its final M_x and its random-set check. Cell 90's arithmetic (the max, the
   mean, the min–max) is done here, once, in `scoresOf`.
   ========================================================================= */

import { defineWidget } from "../core/index.js";
import { MOL, FEATURES, EPOCHS, INFO, RUNS } from "./data.js";

const PAGES = [
  { value: "mask", label: "Mask" },
  { value: "scores", label: "Scores" },
  { value: "runs", label: "Runs" },
];
const SHOW_OPTS = [{ value: "one", label: "One run" }, { value: "all", label: "All runs" }];
const ON = (page) => ({ param: "page", equals: page });
const NA = MOL.atoms.length, NB = MOL.bonds.length, NF = FEATURES.length, NR = RUNS.length, NE = EPOCHS.length;
const DRUG = MOL.atoms.map((a, i) => i).filter((i) => MOL.atoms[i][4]);
const SALT = MOL.atoms.map((a, i) => i).filter((i) => !MOL.atoms[i][4]);
const STEPS = { mask: 2, scores: 3, "runs-one": 1, "runs-all": 1 };
const k = (v) => v / 1000;
const f2 = (v) => v.toFixed(2);
const atomName = (i) => `${MOL.atoms[i][0]}${i}`;
const bondName = (b) => `${atomName(MOL.bonds[b][0])}–${atomName(MOL.bonds[b][1])}`;
/* the feature columns as cell 32 builds them: six numbers, the element, hybridisation, chirality */
const GROUPS = [[0, 6], [6, NF - 8], [NF - 8, NF - 3], [NF - 3, NF]];

/* --------------------------------------------------------------- scores */

/** cell 90, on one run's final masks: raw and min–max scaled, bonds and atoms */
const SCORES = [];
function scoresOf(run) {
  if (SCORES[run]) return SCORES[run];
  const R = RUNS[run], last = R.edges[NE - 1];
  const bondRaw = MOL.bonds.map((_, b) => Math.max(k(last[2 * b]), k(last[2 * b + 1])));
  const atomRaw = R.mx.map((row) => row.reduce((s, v) => s + k(v), 0) / NF);
  const scale = (v) => { const lo = Math.min(...v), hi = Math.max(...v); return v.map((x) => (x - lo) / (hi - lo + 1e-8)); };
  const atom = scale(atomRaw);
  const rank = (i) => 1 + atom.filter((v) => v > atom[i]).length;
  SCORES[run] = { bondRaw, atomRaw, bond: scale(bondRaw), atom, rank };
  return SCORES[run];
}
const keptOf = (run) => new Set(RUNS[run].kept);
const median = (a) => { const b = [...a].sort((p, q) => p - q), n = b.length; return n % 2 ? b[(n - 1) / 2] : (b[n / 2 - 1] + b[n / 2]) / 2; };
const KEEP_COUNT = MOL.bonds.map((_, b) => RUNS.filter((r) => r.kept.includes(b)).length);
const JACCARD = (() => {
  const J = [];
  for (let a = 0; a < NR; a++) for (let b = a + 1; b < NR; b++) {
    const A = keptOf(a), B = keptOf(b), inter = [...A].filter((x) => B.has(x)).length;
    J.push(inter / (A.size + B.size - inter));
  }
  return median(J);
})();
const ALWAYS = KEEP_COUNT.map((c, b) => (c === NR ? b : -1)).filter((b) => b >= 0);
const ALWAYS_ATOM = (() => { const c = {}; ALWAYS.forEach((b) => MOL.bonds[b].slice(0, 2).forEach((i) => { c[i] = (c[i] ?? 0) + 1; })); return Number(Object.keys(c).find((i) => c[i] === ALWAYS.length) ?? -1); })();

/* -------------------------------------------------------------- strings */

const S = {
  subtitle:
    "GNNExplainer learns a mask over a molecule's bonds and atom features that keeps the model's prediction while removing as much of the graph as it can. " +
    "The masks start random and are optimised, then averaged and scaled into one score per bond and per atom. " +
    "Each run from a new random start can keep a different set of bonds that holds the prediction just as well.",
  pageLabel: "Step",
  startLabel: "Random start",
  startDetail: "the random values the masks begin from; each start is optimised separately, and is one run",
  showLabel: "Show",
  showDetail: "One run: the bonds this run keeps; All runs: how many of the 20 runs keep each bond",

  stepLabel: {
    param: "page",
    labels: {
      mask: { anim: "beat", labels: { 0: "Initialise", 1: "Optimise" }, default: "Optimise" },
      scores: { anim: "beat", labels: { 0: "Collapse", 1: "Average", 2: "Scale" }, default: "Scale" },
      runs: { param: "show", labels: { one: "Test", all: "Overlay" }, default: "Test" },
    },
    default: "Initialise",
  },
  stepTitle: {
    param: "page",
    labels: {
      mask: { anim: "beat", labels: { 0: "Give every directed edge and every atom feature a random mask near 0.5", 1: "Optimise the masks for 300 epochs with Adam, learning rate 0.01" }, default: "Optimise the masks for 300 epochs with Adam, learning rate 0.01" },
      scores: { anim: "beat", labels: { 0: "Score each bond as the larger of its two directions' masks", 1: "Score each atom as the mean of its 39 feature masks", 2: "Scale the bond scores and the atom scores to 0–1 within the molecule" }, default: "Scale the bond scores and the atom scores to 0–1 within the molecule" },
      runs: { param: "show", labels: { one: "Predict with only this run's kept bonds, and with random sets of as many bonds", all: "Add the 20 runs' kept bonds one run at a time" }, default: "Predict with only this run's kept bonds, and with random sets of as many bonds" },
    },
    default: "Give every directed edge and every atom feature a random mask near 0.5",
  },

  head: "Ceftriaxone disodium · active",
  salt: "separate pieces:",
  saltNote: "three waters and two Na⁺, no bond to the drug",
  keyMask: ["mask 0", "1"],
  keyScore: ["score 0", "1"],
  keyCount: ["kept by 0 runs", "20"],
  lanes: "each bond carries a message each way, and each direction has its own mask",
  maskPlain: "before the masks: every message and every feature passes whole",

  /* Mask */
  pHead: "p(active) of the masked molecule",
  lossHead: "loss",
  lossTotal: "total",
  lossPred: "prediction term",
  unmasked: (p) => `unmasked ${p}`,
  epoch: (e) => `epoch ${e} of 300`,

  /* Scores */
  gridHead: "M_x: one mask per atom per feature",
  gridCols: "columns: atomic number, degree, hydrogens, charge, aromatic, in ring · element · hybridisation · chirality",
  meanHead: "mean",
  scaleHead: "scores before and after scaling",
  scaleAtoms: "atoms",
  scaleBonds: "bonds",

  /* Runs */
  testHead: "p(active) with only some bonds",
  testKept: (n) => `only this run's ${n} kept bonds`,
  testRand: (n) => `100 random sets of ${n} bonds`,
  barHead: "the 39 bonds, by how many runs keep them",
  always: (n) => `kept by every run: ${n} bonds, all on N10 (ringed)`,
  epochs3000: "At 3,000 epochs every mask ends at 0 or 1, and the runs still keep different bonds.",

  /* hover */
  hovAtom: (i, v) => `${atomName(i)}${v == null ? "" : ` · ${v}`}`,
  hovBond: (b, v) => `${bondName(b)} · ${MOL.bonds[b][2].toLowerCase()}${v == null ? "" : ` · ${v}`}`,
  hovLanes: (b, u, v) => `${bondName(b)} · → ${u} · ← ${v}`,
  hovCell: (i, f, v) => `${atomName(i)} · ${FEATURES[f]} · ${v}`,

  /* tiles */
  tileFull: "Unmasked",
  tileFullNote: `p(active) from a GAT trained on the dataset's scaffold split; its test macro F1 is ${INFO.testF1.toFixed(2)}`,
  tileMasked: "Masked",
  tileMaskedNote: "p(active) with every message and every feature multiplied by its mask",
  tileAbove: "Bonds above 0.5",
  tileAboveNote: (e) => `of ${NB}, a bond counted by its larger direction · epoch ${e}`,
  tileBonds: "Bond scores",
  tileBondsNote: "the larger of each bond's two directions",
  tileAtoms: "Atom scores",
  tileAtomsNote: `the mean over ${NF} features; the mask is 0 where the feature is 0`,
  tileWater: "The waters",
  tileWaterNote: "rank among 41 atoms; max pooling reads every atom, bonded or not",
  tileKept: "Kept bonds",
  tileKeptNote: `mask above 0.5, of ${NB}`,
  tileOnly: "Only those",
  tileOnlyNote: "p(active) with every other bond's messages removed",
  tileRand: "Random sets",
  tileRandNote: "median p(active) of 100 random sets of as many bonds",
  tileEvery: "Kept by every run",
  tileEveryNote: `bonds kept by all ${NR} runs`,
  tileSome: "Kept by some run",
  tileSomeNote: `bonds kept by at least one of ${NR} runs`,
  tileShare: "Two runs share",
  tileShareNote: "median, over every pair of runs, of the kept bonds they share as a share of the bonds either keeps",
  tileWait: "—",

  sumMask: (run, beat, e, p) => `Random start ${run}: ${beat === 0 ? "the molecule before the masks" : `the masks at epoch ${e}, p(active) ${p}`}`,
  sumScores: (run, beat) => `Random start ${run}: ${["each bond's two directions", "each bond scored", "each atom scored", "bonds and atoms scaled to 0–1"][beat]}`,
  sumRuns: (run, all, beat) => (all ? `${beat ? "how many of 20 runs keep each bond" : "the 20 runs, not yet overlaid"}` : `Random start ${run}: the bonds it keeps${beat ? ", tested" : ""}`),
};

/* ------------------------------------------------------ drawing helpers */

const rgb = (c) => { const m = String(c).match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : [128, 128, 128]; };
/** --c-magnitude's ramp from --surface-3; violet, so --c-highlight stays off these pages (ink instead) */
const ramp = (colors, v) => { const a = rgb(colors.surface3), b = rgb(colors.magnitude), u = Math.max(0, Math.min(1, v)); return `rgb(${a.map((x, i) => Math.round(x + (b[i] - x) * u)).join(",")})`; };
function fitText(ctx, s, maxW) {
  let out = s;
  while (ctx.measureText(out).width > maxW) {
    const cut = Math.max(out.lastIndexOf(" · "), out.lastIndexOf("; "), out.lastIndexOf(", "));
    if (cut <= 0) { while (out.length > 1 && ctx.measureText(out + "…").width > maxW) out = out.slice(0, -1); return out + "…"; }
    out = out.slice(0, cut);
  }
  return out;
}
function txt(ctx, colors, s, x, y, { font = null, fill = null, align = "left", baseline = "alphabetic", maxW = null } = {}) {
  ctx.save();
  ctx.font = font ?? `${colors.fsXs} ${colors.font}`;
  if (maxW != null) s = fitText(ctx, String(s), maxW);
  ctx.textAlign = align; ctx.textBaseline = baseline;
  ctx.fillStyle = fill ?? colors.ink2;
  ctx.fillText(s, x, y);
  ctx.restore();
}
const capFont = (colors) => `600 ${colors.fsSm} ${colors.font}`;
const nodeFont = (colors) => `600 ${colors.fsXs} ${colors.font}`;
function line(ctx, x1, y1, x2, y2, stroke, width = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = width; ctx.lineCap = "round"; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.restore();
}
function rect(ctx, x, y, w, h, fill, stroke = null, lw = 1) {
  ctx.save();
  if (fill) { ctx.fillStyle = fill; ctx.fillRect(x, y, w, h); }
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.strokeRect(x + lw / 2, y + lw / 2, w - lw, h - lw); }
  ctx.restore();
}
function dot(ctx, x, y, r, fill, stroke = null, lw = 1) {
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2);
  if (fill) { ctx.fillStyle = fill; ctx.fill(); }
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.stroke(); }
  ctx.restore();
}
function polyline(ctx, pts, stroke, width = 1.6, dash = null) {
  if (pts.length < 2) return;
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = width; ctx.lineJoin = "round"; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); pts.forEach(([x, y], i) => (i ? ctx.lineTo(x, y) : ctx.moveTo(x, y))); ctx.stroke(); ctx.restore();
}
function hoverLabel(ctx, colors, str, x, y, w) {
  ctx.save(); ctx.font = `600 ${colors.fsXs} ${colors.font}`;
  const tw = ctx.measureText(str).width; ctx.restore();
  const bx = Math.max(4, Math.min(w - tw - 14, x + 10)), by = Math.max(4, y - 26);
  rect(ctx, bx, by, tw + 10, 18, colors.surface, colors.ink3);
  txt(ctx, colors, str, bx + 5, by + 9.5, { font: `600 ${colors.fsXs} ${colors.font}`, fill: colors.ink1, baseline: "middle" });
}
/** the ramp's key: a bar and its two end words, right-aligned at x1 */
function rampKey(ctx, colors, x1, y, words, w = 70) {
  ctx.save(); ctx.font = `${colors.fsXs} ${colors.font}`; const tw = ctx.measureText(words[1]).width; ctx.restore();
  const x0 = x1 - tw - 6 - w;
  for (let q = 0; q < w; q++) line(ctx, x0 + q, y, x0 + q + 1, y, ramp(colors, q / (w - 1)), 8);
  txt(ctx, colors, words[0], x0 - 6, y + 3, { align: "right", fill: colors.ink3 });
  txt(ctx, colors, words[1], x1, y + 3, { align: "right", fill: colors.ink3 });
}

/* ------------------------------------------------------------ the molecule */

const NODE_R = 8, LANE = 2.6, STRIP = 30;
const MOL_H = 236;
/** the drug fitted to its box; the salt's one-atom pieces spaced along the strip under it */
function placeMol(w, top) {
  const xs = DRUG.map((i) => MOL.atoms[i][2]), ys = DRUG.map((i) => MOL.atoms[i][3]);
  const minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys);
  const boxH = MOL_H - STRIP - 54, s = Math.min((w - 2 * NODE_R - 24) / (maxX - minX), boxH / (maxY - minY));
  const cx = (minX + maxX) / 2, cy = (minY + maxY) / 2, my = top + 30 + boxH / 2;
  const P = MOL.atoms.map((a) => [w / 2 + (a[2] - cx) * s, my + (a[3] - cy) * s]);
  const sy = top + MOL_H - STRIP / 2;
  SALT.forEach((i, q) => { P[i] = [116 + q * 34, sy]; });
  return P;
}
/* the element in the node, a charge as a sign outside it: "Na+" overflows a node */
function drawAtom(ctx, colors, p, i, v) {
  const [el, ch] = MOL.atoms[i];
  const fill = v == null ? colors.surface : ramp(colors, v);
  dot(ctx, p[0], p[1], NODE_R, fill, colors.ink3, 1);
  txt(ctx, colors, el, p[0], p[1] + 0.5, { font: nodeFont(colors), align: "center", baseline: "middle", fill: v != null && v > 0.55 ? colors.surface : colors.ink1 });
  if (ch) txt(ctx, colors, ch > 0 ? "+" : "−", p[0] + NODE_R + 1, p[1] - NODE_R + 3, { font: nodeFont(colors), fill: colors.ink1 });
}
function drawStrip(ctx, colors, w, top) {
  const y = top + MOL_H - STRIP;
  line(ctx, 10, y, w - 10, y, colors.grid);
  txt(ctx, colors, S.salt, 12, y + STRIP / 2 + 4, { fill: colors.ink3 });
  txt(ctx, colors, S.saltNote, 116 + SALT.length * 34, y + STRIP / 2 + 4, { fill: colors.ink3, maxW: w - 126 - SALT.length * 34 });
}
/** one bond as two lanes, one per direction; `sep` 1 is apart, 0 merged into one line */
function drawLanes(ctx, colors, p, q, u, v, sep = 1) {
  const dx = q[0] - p[0], dy = q[1] - p[1], L = Math.hypot(dx, dy) || 1, nx = (-dy / L) * LANE * sep, ny = (dx / L) * LANE * sep;
  /* the bond itself, under its lanes, so a direction masked to 0 still shows where it runs */
  line(ctx, p[0], p[1], q[0], q[1], colors.ink3, 1);
  line(ctx, p[0] + nx, p[1] + ny, q[0] + nx, q[1] + ny, ramp(colors, u), 3.4);
  line(ctx, p[0] - nx, p[1] - ny, q[0] - nx, q[1] - ny, ramp(colors, v), 3.4);
}
/** one bond as one line, its width and colour a score in 0–1 */
function drawScoredBond(ctx, colors, p, q, v) {
  line(ctx, p[0], p[1], q[0], q[1], colors.ink3, 1);
  line(ctx, p[0], p[1], q[0], q[1], ramp(colors, v), 2 + 4.5 * v);
}
function nearestAtom(P, pt) {
  let best = -1, bd = NODE_R + 3;
  P.forEach((p, i) => { const d = Math.hypot(p[0] - pt.x, p[1] - pt.y); if (d < bd) { bd = d; best = i; } });
  return best;
}
function nearestBond(P, pt) {
  let best = -1, bd = 6;
  MOL.bonds.forEach(([i, j], b) => {
    const [ax, ay] = P[i], [bx, by] = P[j], vx = bx - ax, vy = by - ay, L2 = vx * vx + vy * vy;
    const t = Math.max(0, Math.min(1, ((pt.x - ax) * vx + (pt.y - ay) * vy) / L2));
    const d = Math.hypot(ax + t * vx - pt.x, ay + t * vy - pt.y);
    if (d < bd) { bd = d; best = b; }
  });
  return best;
}

/* ------------------------------------------------------------- timing */

const DUR = { 1: 1400, 2: 7000 };
const DUR_SCORES = 1800, DUR_TEST = 2400, DUR_OVERLAY = 4000;
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - (-2 * t + 2) ** 3 / 2);
const lerp = (a, b, t) => a + (b - a) * t;
const seg = (t, a, b) => Math.max(0, Math.min(1, (t - a) / (b - a)));
/** the Mask page's presses belong to its run; the Runs page's to its view */
/* a new random start keeps every page's progress (his round 1): after Optimise, sliding the start shows each run's learned masks */
const stageOf = (params) => (params.page === "mask" ? "mask" : params.page === "scores" ? "scores" : `runs-${params.show}`);
const kindOf = (stage) => stage.split("-").slice(0, stage.startsWith("runs") ? 2 : 1).join("-");
const stepsOf = (stage) => STEPS[kindOf(stage)];
const durOf = (stage, n) => (kindOf(stage) === "mask" ? DUR[n] : kindOf(stage) === "scores" ? DUR_SCORES : kindOf(stage) === "runs-one" ? DUR_TEST : DUR_OVERLAY);
const shownStep = (anim, stage) => (anim.n[stage] ?? 0) - (anim.stage === stage && anim.t < 1 ? 1 : 0);
const inFlight = (anim, stage) => (anim.stage === stage && anim.t < 1 ? anim.t : null);
const runOf = (params) => Number(params.start) - 1;

/* ---------------------------------------------------------- geometry */

const H_MASK = MOL_H + 22 + 172;
const GRID_TOP = MOL_H + 40, CELL_W = 5, CELL_H = 5;
const H_SCORES = GRID_TOP + 22 + NA * CELL_H + 34;
const H_RUNS = MOL_H + 22 + 160;

/* ---------------------------------------------------------------- Mask */

/** the mask page's epoch position: a frame index, fractional while Optimise plays */
function maskFrame(anim, stage) {
  const done = shownStep(anim, stage), t = inFlight(anim, stage);
  if (done >= 2) return NE - 1;
  if (done === 1 && t != null) return (NE - 1) * Math.min(1, t / 0.94);
  return 0;
}
function edgeAt(R, f) {
  const f0 = Math.floor(f), f1 = Math.min(NE - 1, f0 + 1), u = f - f0;
  return R.edges[f0].map((v, q) => k(lerp(v, R.edges[f1][q], u)));
}
const seriesAt = (arr, f) => { const f0 = Math.floor(f), f1 = Math.min(NE - 1, f0 + 1); return k(lerp(arr[f0], arr[f1], f - f0)); };
const epochAt = (f) => Math.round(lerp(EPOCHS[Math.floor(f)], EPOCHS[Math.min(NE - 1, Math.floor(f) + 1)], f - Math.floor(f)));

function drawMask(ctx, colors, w, params, anim, pointer) {
  const run = runOf(params), R = RUNS[run], stage = stageOf(params);
  const beat = shownStep(anim, stage), t = inFlight(anim, stage);
  const masked = beat >= 1 || t != null;
  const f = maskFrame(anim, stage), E = edgeAt(R, f);
  const P = placeMol(w, 0);
  txt(ctx, colors, S.head, 12, 16, { font: capFont(colors), fill: colors.ink1 });
  if (masked) rampKey(ctx, colors, w - 12, 12, S.keyMask);
  drawStrip(ctx, colors, w, 0);
  MOL.bonds.forEach(([i, j], b) => {
    if (masked) drawLanes(ctx, colors, P[i], P[j], E[2 * b], E[2 * b + 1]);
    else line(ctx, P[i][0], P[i][1], P[j][0], P[j][1], colors.ink2, 1.6);
  });
  MOL.atoms.forEach((_, i) => drawAtom(ctx, colors, P[i], i, null));
  txt(ctx, colors, masked ? S.lanes : S.maskPlain, 12, MOL_H - STRIP - 6, { fill: colors.ink3, maxW: w - 24 });

  /* p(active) and the loss, epoch by epoch, drawn up to the frame shown */
  const top = MOL_H + 22, ph = 120, gap = 52, pw = (w - 24 - gap - 30) / 2;
  const panels = [{ x0: 40, head: S.pHead }, { x0: 40 + pw + gap, head: S.lossHead }];
  const ex = (x0, e) => x0 + (pw * (e - 1)) / 299;
  const lmax = Math.max(...R.loss.map(k));
  panels.forEach(({ x0, head }, c) => {
    txt(ctx, colors, head, x0 - 28, top + 8, { font: capFont(colors), fill: colors.ink1, maxW: pw + 28 });
    const y0 = top + 18, y1 = y0 + ph;
    line(ctx, x0, y1, x0 + pw, y1, colors.axis); line(ctx, x0, y0, x0, y1, colors.axis);
    txt(ctx, colors, c === 0 ? "1" : f2(lmax), x0 - 4, y0 + 4, { align: "right", fill: colors.ink3 });
    txt(ctx, colors, "0", x0 - 4, y1 + 3, { align: "right", fill: colors.ink3 });
    txt(ctx, colors, "1", x0, y1 + 14, { fill: colors.ink3 });
    txt(ctx, colors, "300", x0 + pw, y1 + 14, { align: "right", fill: colors.ink3 });
    const sy = (v) => y1 - (c === 0 ? v : v / lmax) * ph;
    if (c === 0) {
      const pf = k(INFO.pFull);
      line(ctx, x0, sy(pf), x0 + pw, sy(pf), colors.ink3, 1, [3, 3]);
      /* under the line at its right end: the optimised curve ends above it */
      txt(ctx, colors, S.unmasked(f2(pf)), x0 + pw, sy(pf) + 13, { align: "right", fill: colors.ink3 });
    }
    if (!masked) return;
    const upto = Math.floor(f);
    const pts = (arr) => {
      const out = [];
      for (let q = 0; q <= upto; q++) out.push([ex(x0, EPOCHS[q]), sy(k(arr[q]))]);
      if (f > upto) out.push([ex(x0, epochAt(f)), sy(seriesAt(arr, f))]);
      return out;
    };
    /* Initialise: the prediction falls from the unmasked value to the random start's, as one moving dot */
    if (c === 0 && beat === 0) {
      const u = ease(t ?? 1);
      dot(ctx, ex(x0, 1), sy(lerp(k(INFO.pFull), k(R.p[0]), u)), 3.5, colors.ink1);
      return;
    }
    if (c === 1 && beat === 0) return;
    if (c === 0) {
      const pp = pts(R.p);
      polyline(ctx, pp, colors.ink1, 2);
      const last = pp[pp.length - 1]; dot(ctx, last[0], last[1], 3.5, colors.ink1);
    } else {
      polyline(ctx, pts(R.loss), colors.ink1, 2);
      polyline(ctx, pts(R.pred), colors.ink3, 1.6, [4, 3]);
      /* the key under the axis, where the curves never reach */
      const ky = y1 + 28;
      line(ctx, x0, ky - 3, x0 + 14, ky - 3, colors.ink1, 2);
      txt(ctx, colors, S.lossTotal, x0 + 18, ky, { fill: colors.ink2 });
      line(ctx, x0 + 56, ky - 3, x0 + 70, ky - 3, colors.ink3, 1.6, [4, 3]);
      txt(ctx, colors, S.lossPred, x0 + 74, ky, { fill: colors.ink2, maxW: pw - 74 });
    }
  });
  if (masked) txt(ctx, colors, S.epoch(epochAt(f)), w - 12, MOL_H - STRIP - 6, { align: "right", fill: colors.ink1, font: nodeFont(colors) });

  if (pointer) {
    const a = nearestAtom(P, pointer), b = a < 0 ? nearestBond(P, pointer) : -1;
    if (a >= 0) hoverLabel(ctx, colors, S.hovAtom(a, null), pointer.x, pointer.y, w);
    else if (b >= 0) hoverLabel(ctx, colors, masked ? S.hovLanes(b, f2(E[2 * b]), f2(E[2 * b + 1])) : S.hovBond(b, null), pointer.x, pointer.y, w);
  }
}

/* -------------------------------------------------------------- Scores */

/** where each atom's mean sits on the scale strip, as a fraction of the strip's width */
function drawScores(ctx, colors, w, params, anim, pointer) {
  const run = runOf(params), R = RUNS[run], stage = "scores", sc = scoresOf(run);
  const beat = shownStep(anim, stage), t = inFlight(anim, stage), last = R.edges[NE - 1];
  const P = placeMol(w, 0);
  txt(ctx, colors, S.head, 12, 16, { font: capFont(colors), fill: colors.ink1 });
  rampKey(ctx, colors, w - 12, 12, beat >= 3 ? S.keyScore : S.keyMask);
  drawStrip(ctx, colors, w, 0);

  /* Collapse: the two lanes slide together; the line takes the larger value when they meet */
  const tc = beat >= 1 ? 1 : beat === 0 && t != null ? ease(t) : 0;
  /* Scale: every score moves from its raw value to its scaled one */
  const ts = beat >= 3 ? 1 : beat === 2 && t != null ? ease(seg(t, 0, 0.9)) : 0;
  const bondV = (b) => lerp(sc.bondRaw[b], sc.bond[b], ts);
  MOL.bonds.forEach(([i, j], b) => {
    if (tc < 1) drawLanes(ctx, colors, P[i], P[j], k(last[2 * b]), k(last[2 * b + 1]), 1 - tc);
    else drawScoredBond(ctx, colors, P[i], P[j], bondV(b));
  });
  /* Average: the grid's rows are averaged top to bottom, each atom taking its mean when the sweep reaches its row */
  const ta = beat >= 2 ? NA : beat === 1 && t != null ? Math.floor(NA * seg(t, 0, 0.9)) : 0;
  const atomV = (i) => (i < ta ? lerp(sc.atomRaw[i], sc.atom[i], ts) : null);
  MOL.atoms.forEach((_, i) => drawAtom(ctx, colors, P[i], i, atomV(i)));

  /* M_x, one row an atom, one column a feature; the mean column fills with Average */
  const gx = 34, gy = GRID_TOP + 18;
  txt(ctx, colors, S.gridHead, 12, GRID_TOP + 6, { font: capFont(colors), fill: colors.ink1, maxW: gx + NF * CELL_W + 40 });
  GROUPS.forEach(([a]) => { if (a > 0) line(ctx, gx + a * CELL_W, gy - 4, gx + a * CELL_W, gy + NA * CELL_H + 2, colors.ink3, 1); });
  R.mx.forEach((row, i) => {
    /* every tenth row, then the first and last of the one-atom pieces: one label a row there overprints */
    if ((i % 10 === 0 && i < SALT[0] - 4) || i === SALT[0] || i === SALT[SALT.length - 1]) txt(ctx, colors, atomName(i), gx - 4, gy + i * CELL_H + CELL_H, { align: "right", fill: colors.ink3, font: `${colors.fsXs} ${colors.mono}` });
    row.forEach((v, q) => { if (v > 0) rect(ctx, gx + q * CELL_W, gy + i * CELL_H, CELL_W - 1, CELL_H - 1, ramp(colors, k(v))); });
  });
  rect(ctx, gx - 1, gy - 1, NF * CELL_W + 1, NA * CELL_H + 1, null, colors.grid);
  const mx = gx + NF * CELL_W + 8;
  txt(ctx, colors, S.meanHead, mx + 4, gy - 5, { align: "center", fill: colors.ink3 });
  for (let i = 0; i < ta; i++) rect(ctx, mx, gy + i * CELL_H, 9, CELL_H - 1, ramp(colors, lerp(sc.atomRaw[i], sc.atom[i], ts)));
  rect(ctx, mx - 1, gy - 1, 11, NA * CELL_H + 1, null, colors.grid);
  txt(ctx, colors, S.gridCols, 12, gy + NA * CELL_H + 16, { fill: colors.ink3, maxW: w - 24 });

  /* the scale strips: atoms and bonds as dots on 0–1, moving to their scaled places */
  const sx0 = mx + 46, sx1 = w - 16, sw = sx1 - sx0;
  const atomVal = (i) => lerp(sc.atomRaw[i], sc.atom[i], ts);
  const STRIPS = { bonds: { val: bondV, y: gy + 40, n: NB }, atoms: { val: atomVal, y: gy + 120, n: NA } };
  const dotAt = (kind, q) => [sx0 + STRIPS[kind].val(q) * sw, STRIPS[kind].y - 6 - (q % 3) * 4];
  txt(ctx, colors, S.scaleHead, sx0, GRID_TOP + 6, { font: capFont(colors), fill: colors.ink1, maxW: sw });
  [[S.scaleBonds, beat >= 1, "bonds"], [S.scaleAtoms, beat >= 2, "atoms"]].forEach(([name, ready, kind]) => {
    const { y, n, val } = STRIPS[kind];
    txt(ctx, colors, name, sx0, y - 22, { fill: colors.ink1 });
    line(ctx, sx0, y, sx1, y, colors.axis);
    [0, 0.5, 1].forEach((v) => { line(ctx, sx0 + v * sw, y, sx0 + v * sw, y + 4, colors.axis); txt(ctx, colors, String(v), sx0 + v * sw, y + 15, { align: "center", fill: colors.ink3 }); });
    if (!ready) return;
    for (let q = 0; q < n; q++) { const [x, yy] = dotAt(kind, q); dot(ctx, x, yy, 2.6, ramp(colors, val(q)), colors.ink3, 0.6); }
  });

  /* HOVER IS SYNCED ACROSS THE THREE VIEWS (his round 1, "does the hover sync?"): an atom, on the
     molecule or as its grid row, rings itself, outlines its row and mean cell, and rings its dot; a
     bond rings itself and its dot. Ink, not --c-highlight, which shares --c-magnitude's violet. */
  if (pointer) {
    const a = nearestAtom(P, pointer), b = a < 0 ? nearestBond(P, pointer) : -1;
    const ci = Math.floor((pointer.y - gy) / CELL_H), cq = Math.floor((pointer.x - gx) / CELL_W);
    const onGrid = a < 0 && b < 0 && ci >= 0 && ci < NA && cq >= 0 && cq <= NF + 3;
    const ha = a >= 0 ? a : onGrid ? ci : -1;
    if (ha >= 0) {
      dot(ctx, P[ha][0], P[ha][1], NODE_R + 4, null, colors.ink1, 1.8);
      rect(ctx, gx - 2, gy + ha * CELL_H - 1, mx + 11 - gx + 2, CELL_H + 1, null, colors.ink1, 1.2);
      if (beat >= 2) { const [x, y] = dotAt("atoms", ha); dot(ctx, x, y, 5.5, null, colors.ink1, 1.6); }
    }
    if (b >= 0) {
      const [i, j] = MOL.bonds[b];
      line(ctx, P[i][0], P[i][1], P[j][0], P[j][1], colors.ink1, 1.2, [3, 2]);
      if (beat >= 1) { const [x, y] = dotAt("bonds", b); dot(ctx, x, y, 5.5, null, colors.ink1, 1.6); }
    }
    if (a >= 0) hoverLabel(ctx, colors, S.hovAtom(a, atomV(a) == null ? null : f2(atomV(a))), pointer.x, pointer.y, w);
    else if (b >= 0) hoverLabel(ctx, colors, tc < 1 ? S.hovLanes(b, f2(k(last[2 * b])), f2(k(last[2 * b + 1]))) : S.hovBond(b, f2(bondV(b))), pointer.x, pointer.y, w);
    else if (onGrid && cq < NF) hoverLabel(ctx, colors, S.hovCell(ci, cq, f2(k(R.mx[ci][cq]))), pointer.x, pointer.y, w);
    else if (onGrid) hoverLabel(ctx, colors, S.hovAtom(ci, atomV(ci) == null ? null : f2(atomV(ci))), pointer.x, pointer.y, w);
  }
}

/* ---------------------------------------------------------------- Runs */

function drawRuns(ctx, colors, w, params, anim, pointer) {
  const all = params.show === "all", stage = stageOf(params);
  const beat = shownStep(anim, stage), t = inFlight(anim, stage);
  const P = placeMol(w, 0);
  txt(ctx, colors, S.head, 12, 16, { font: capFont(colors), fill: colors.ink1 });
  drawStrip(ctx, colors, w, 0);
  const top = MOL_H + 22;

  if (!all) {
    const run = runOf(params), R = RUNS[run], kept = keptOf(run);
    MOL.bonds.forEach(([i, j], b) => {
      if (kept.has(b)) line(ctx, P[i][0], P[i][1], P[j][0], P[j][1], colors.magnitude, 6);
      else line(ctx, P[i][0], P[i][1], P[j][0], P[j][1], colors.surface3, 2.2);
    });
    MOL.atoms.forEach((_, i) => drawAtom(ctx, colors, P[i], i, null));
    rampKey(ctx, colors, w - 12, 12, ["dropped", "kept"], 40);

    /* Test: 100 random sets' p fall onto the axis, then this run's kept set */
    const x0 = 24, x1 = w - 24, ax = top + 92, sx = (v) => x0 + v * (x1 - x0);
    txt(ctx, colors, S.testHead, 12, top + 8, { font: capFont(colors), fill: colors.ink1 });
    line(ctx, x0, ax, x1, ax, colors.axis);
    [0, 0.25, 0.5, 0.75, 1].forEach((v) => { line(ctx, sx(v), ax, sx(v), ax + 4, colors.axis); txt(ctx, colors, String(v), sx(v), ax + 16, { align: "center", fill: colors.ink3 }); });
    const pf = k(INFO.pFull);
    line(ctx, sx(pf), top + 20, sx(pf), ax, colors.ink3, 1, [3, 3]);
    txt(ctx, colors, S.unmasked(f2(pf)), sx(pf) - 4, top + 28, { align: "right", fill: colors.ink3 });
    const tt = beat >= 1 ? 1 : t ?? 0;
    if (beat >= 1 || t != null) {
      /* each random set's dot drops in turn, stacked by its 0.02 bin */
      const n = Math.floor(R.pRand.length * seg(tt, 0, 0.6)), stack = {};
      for (let q = 0; q < n; q++) {
        const v = k(R.pRand[q]), bin = Math.round(v * 50), h = (stack[bin] = (stack[bin] ?? 0) + 1);
        dot(ctx, sx(v), ax - 4 - (h - 1) * 5, 2.2, colors.ink3);
      }
      const u = ease(seg(tt, 0.65, 1));
      if (u > 0) {
        const v = k(R.pKept), y = lerp(top + 30, ax - 8, u);
        dot(ctx, sx(v), y, 6, colors.magnitude, colors.ink1, 1.4);
      }
      if (tt >= 1) {
        txt(ctx, colors, S.testKept(R.kept.length), sx(k(R.pKept)) - 10, top + 50, { align: "right", fill: colors.ink1, font: nodeFont(colors) });
        txt(ctx, colors, S.testRand(R.kept.length), x0, ax + 32, { fill: colors.ink3 });
      }
    }
    txt(ctx, colors, S.epochs3000, 12, top + 152, { fill: colors.ink3, maxW: w - 24 });
    if (pointer) {
      const a = nearestAtom(P, pointer), b = a < 0 ? nearestBond(P, pointer) : -1;
      if (a >= 0) hoverLabel(ctx, colors, S.hovAtom(a, null), pointer.x, pointer.y, w);
      else if (b >= 0) hoverLabel(ctx, colors, S.hovBond(b, kept.has(b) ? "kept" : "dropped"), pointer.x, pointer.y, w);
    }
    return;
  }

  /* All runs: Overlay adds one run's kept set at a time; a bond's shade is how many have kept it so far */
  const nIn = beat >= 1 ? NR : t != null ? Math.floor(NR * seg(t, 0, 0.92)) : 0;
  const cnt = MOL.bonds.map((_, b) => RUNS.slice(0, nIn).filter((r) => r.kept.includes(b)).length);
  MOL.bonds.forEach(([i, j], b) => drawScoredBond(ctx, colors, P[i], P[j], cnt[b] / NR));
  MOL.atoms.forEach((_, i) => drawAtom(ctx, colors, P[i], i, null));
  rampKey(ctx, colors, w - 12, 12, S.keyCount, 60);
  if (beat >= 1 && ALWAYS_ATOM >= 0) dot(ctx, P[ALWAYS_ATOM][0], P[ALWAYS_ATOM][1], NODE_R + 5, null, colors.ink1, 1.8);

  /* the bonds as bars, sorted by their final count so the bars only grow in place */
  txt(ctx, colors, S.barHead, 12, top + 8, { font: capFont(colors), fill: colors.ink1 });
  const order = MOL.bonds.map((_, b) => b).sort((a, b) => KEEP_COUNT[b] - KEEP_COUNT[a] || a - b);
  const bx0 = 24, bw = (w - 48) / NB, by1 = top + 104, bh = 80;
  line(ctx, bx0, by1, bx0 + NB * bw, by1, colors.axis);
  txt(ctx, colors, "20", bx0 - 4, by1 - bh + 4, { align: "right", fill: colors.ink3 });
  txt(ctx, colors, "0", bx0 - 4, by1 + 3, { align: "right", fill: colors.ink3 });
  line(ctx, bx0, by1 - bh, bx0 + NB * bw, by1 - bh, colors.grid, 1, [2, 3]);
  order.forEach((b, q) => { if (cnt[b]) rect(ctx, bx0 + q * bw + 1, by1 - (bh * cnt[b]) / NR, bw - 2, (bh * cnt[b]) / NR, ramp(colors, cnt[b] / NR)); });
  txt(ctx, colors, `run ${Math.min(NR, nIn)} of ${NR}`, w - 12, top + 8, { align: "right", fill: colors.ink3 });
  if (beat >= 1) txt(ctx, colors, S.always(ALWAYS.length), 12, by1 + 18, { fill: colors.ink1, maxW: w - 24 });
  txt(ctx, colors, S.epochs3000, 12, top + 152, { fill: colors.ink3, maxW: w - 24 });
  if (pointer) {
    const a = nearestAtom(P, pointer), b = a < 0 ? nearestBond(P, pointer) : -1;
    const q = Math.floor((pointer.x - bx0) / bw), inBars = pointer.y > by1 - bh - 4 && pointer.y < by1 + 2 && q >= 0 && q < NB;
    if (a >= 0) hoverLabel(ctx, colors, S.hovAtom(a, null), pointer.x, pointer.y, w);
    else if (b >= 0) hoverLabel(ctx, colors, S.hovBond(b, `kept by ${cnt[b]} of ${nIn} runs`), pointer.x, pointer.y, w);
    else if (inBars) hoverLabel(ctx, colors, S.hovBond(order[q], `kept by ${cnt[order[q]]} of ${nIn} runs`), pointer.x, pointer.y, w);
  }
}

/* ------------------------------------------------------------- widget */

defineWidget({
  slug: "gnn-explainer",
  status: "draft",
  title: "Deep Learning - Graphs: Explainability",
  subtitle: S.subtitle,
  credit: "Molecule data: Stokes et al., Cell 2020, via FinGAT",
  layout: "side",
  height: (params) => (params.page === "mask" ? H_MASK : params.page === "scores" ? H_SCORES : H_RUNS),
  pointer: true,

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "mask", display: true },
    /* hidden in All runs, which combines every start (his round 1: a control that did nothing) */
    start: { type: "int", label: S.startLabel, detail: S.startDetail, min: 1, max: NR, default: 1, display: true,
      when: { any: [{ param: "page", oneOf: ["mask", "scores"] }, { param: "show", equals: "one" }] } },
    show: { type: "segmented", label: S.showLabel, detail: S.showDetail, options: SHOW_OPTS, default: "one", display: true, when: ON("runs") },
    /* authoring escape hatch, first render only: presses already made on the stage the link opens */
    shown: { type: "int", min: 0, max: 3, default: 0, hidden: true },
  },

  /* none: each page keys its marks on the canvas (a ramp key, captions), and a legend reads params alone */
  legend: [],

  compute: () => ({}),

  animation: {
    stepLabel: S.stepLabel,
    stepTitle: S.stepTitle,
    /* each press is read, once: Step alone (play-only-for-motion-or-repetition) */
    runLabel: null,

    init: ({ params, fromScratch }) => {
      const stage = stageOf(params);
      const anim = { stage, n: {}, t: 1, dur: 1000, halt: false };
      anim.n[stage] = fromScratch ? 0 : Math.max(0, Math.min(stepsOf(stage), Number(params.shown) || 0));
      anim.beat = anim.n[stage];
      anim.done = anim.n[stage] >= stepsOf(stage);
      return anim;
    },

    advance: (anim, { dt }) => {
      /* a press a stage switch interrupted ends here, before the new stage's (mid-press-page-switch) */
      if (anim.halt) { anim.halt = false; return false; }
      const stage = anim.stage;
      if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
      else if ((anim.n[stage] ?? 0) < stepsOf(stage)) {
        anim.n[stage] = (anim.n[stage] ?? 0) + 1;
        anim.dur = durOf(stage, anim.n[stage]);
        anim.t = 0;
      }
      anim.beat = anim.n[stage] ?? 0;
      anim.done = anim.beat >= stepsOf(stage) && anim.t >= 1;
      return anim.t < 1;
    },

    rebuild: (anim, { params }) => {
      const stage = stageOf(params);
      /* only a change of stage ends a press in flight; a new random start keeps it */
      if (stage !== anim.stage && anim.t < 1) { anim.t = 1; anim.halt = true; }
      anim.stage = stage;
      anim.beat = anim.n[stage] ?? 0;
      anim.done = anim.beat >= stepsOf(stage) && anim.t >= 1;
    },
  },

  draw({ ctx, colors, w, params, anim, pointer }) {
    if (params.page === "mask") drawMask(ctx, colors, w, params, anim, pointer);
    else if (params.page === "scores") drawScores(ctx, colors, w, params, anim, pointer);
    else drawRuns(ctx, colors, w, params, anim, pointer);
  },

  readout({ params, anim }) {
    const stage = stageOf(params), beat = shownStep(anim, stage), run = runOf(params), R = RUNS[run];
    if (params.page === "mask") {
      const f = maskFrame(anim, stage), E = edgeAt(R, f), on = beat >= 1 || inFlight(anim, stage) != null;
      const above = MOL.bonds.filter((_, b) => Math.max(E[2 * b], E[2 * b + 1]) > 0.5).length;
      return [
        { label: S.tileFull, value: f2(k(INFO.pFull)), note: S.tileFullNote },
        { label: S.tileMasked, value: on ? f2(seriesAt(R.p, f)) : S.tileWait, note: S.tileMaskedNote },
        { label: S.tileAbove, value: on ? String(above) : S.tileWait, note: on ? S.tileAboveNote(epochAt(f)) : "" },
      ];
    }
    if (params.page === "scores") {
      const sc = scoresOf(run), ranks = SALT.filter((i) => MOL.atoms[i][0] === "O").map(sc.rank).sort((a, b) => a - b);
      return [
        { label: S.tileBonds, value: beat >= 1 ? String(NB) : S.tileWait, note: S.tileBondsNote },
        { label: S.tileAtoms, value: beat >= 2 ? String(NA) : S.tileWait, note: S.tileAtomsNote },
        { label: S.tileWater, value: beat >= 2 ? ranks.join(" · ") : S.tileWait, note: S.tileWaterNote },
      ];
    }
    if (params.show === "one") {
      return [
        { label: S.tileKept, value: String(R.kept.length), note: S.tileKeptNote },
        { label: S.tileOnly, value: beat >= 1 ? f2(k(R.pKept)) : S.tileWait, note: S.tileOnlyNote },
        { label: S.tileRand, value: beat >= 1 ? f2(k(median(R.pRand))) : S.tileWait, note: S.tileRandNote },
      ];
    }
    return [
      { label: S.tileEvery, value: beat >= 1 ? String(ALWAYS.length) : S.tileWait, note: S.tileEveryNote },
      { label: S.tileSome, value: beat >= 1 ? String(KEEP_COUNT.filter((c) => c > 0).length) : S.tileWait, note: S.tileSomeNote },
      { label: S.tileShare, value: beat >= 1 ? `${Math.round(100 * JACCARD)}%` : S.tileWait, note: S.tileShareNote },
    ];
  },

  summary({ params, anim }) {
    const stage = stageOf(params), beat = shownStep(anim, stage), R = RUNS[runOf(params)];
    if (params.page === "mask") { const f = maskFrame(anim, stage); return S.sumMask(params.start, beat, epochAt(f), f2(seriesAt(R.p, f))); }
    if (params.page === "scores") return S.sumScores(params.start, beat);
    return S.sumRuns(params.start, params.show === "all", beat);
  },
});
