/* ============================================================================
   Widget 98 · Graphs: Explainability (`gnn-explainer`) — PHM5005 09-2 cells
   84–92 (GNNExplainer on the lesson's trained GAT: PyG's Explainer with
   GNNExplainer(epochs=300, lr=0.01), a feature mask M_x and an edge mask M_e,
   cell 90's scores, cell 92's heat overlay) and 09-1 cell 26 (the three
   families of GNN explanation).

   The misconception (catalogue § Slot 98): the highlighted bonds are why the
   molecule stops E. coli growing, and the mask is unique. Measured on the
   lesson's own model and molecule (`_lab/gnn-explainer-measure.py`): each of
   20 runs keeps 15–21 of the 39 bonds (mask above 0.5), and those bonds alone
   hold p(active) at 0.91–0.97, well above random sets of the same size — but
   two runs keep different sets (median Jaccard 0.52), and only the three
   bonds of N10, the β-lactam nitrogen, are kept by every run. 3,000 epochs
   instead of 300 leaves the runs as far apart.

   THREE PAGES under Step, every call his from `_lab/gnn-explainer-mock.html`
   (2026-10-10, "all recommendations"):

     MASK     one run's optimisation. Initialise draws the random start (every
              mask near 0.5, and the prediction falls to 0.08 because every
              feature is halved too); Optimise plays the 300 epochs, each bond
              as TWO lanes, one per direction, since M_e has one value per
              directed edge. p(active) and the loss beside.
     SCORES   cell 90, then cell 92: Collapse takes each bond's larger
              direction; Average takes each atom's mean over all 39 features of
              M_x (the grid below, most cells 0 because PyG zeroes a mask where
              the feature is 0); Scale stretches both to 0–1 within the
              molecule. The result is the lesson's heat overlay.
     RUNS     One run: the bonds the run keeps, and Test — p(active) with only
              those against 100 random sets of the same size. All runs:
              Overlay adds the 20 runs' kept sets one at a time.

   Random start (1–20) is one control on every page but All runs, so the
   Scores a student reads are the run the Mask page optimised; changing it
   keeps each page's progress. The waters and the two
   Na⁺ are drawn in a strip under the drug: separate pieces of the graph, with
   no bond to it, scored like any atom — max pooling reads every atom.

   Nothing optimises in the page: data.js (generated by
   `_lab/gnn-explainer-data.py`) holds every run's edge masks every 10 epochs,
   its final M_x and its random-set check. Cell 90's arithmetic (the max, the
   mean, the min–max) is done here, once, in `scoresOf`.
   ========================================================================= */

import { defineWidget } from "../core/index.js";
import { MOL, FEATURES, EPOCHS, INFO, RUNS } from "./data.js";

const PAGES = [
  { value: "mask", label: "Mask" },
  { value: "scores", label: "Scores" },
  { value: "runs", label: "Runs" },
];
const SHOW_OPTS = [{ value: "one", label: "One run" }, { value: "all", label: "All runs" }];
const ON = (page) => ({ param: "page", equals: page });
const NA = MOL.atoms.length, NB = MOL.bonds.length, NF = FEATURES.length, NR = RUNS.length, NE = EPOCHS.length;
const DRUG = MOL.atoms.map((a, i) => i).filter((i) => MOL.atoms[i][4]);
const SALT = MOL.atoms.map((a, i) => i).filter((i) => !MOL.atoms[i][4]);
/* Mask: Initialise, then Optimise three times, 100 epochs a press (his round 2: the masks move in the second and third hundred) */
const STEPS = { mask: 4, scores: 3, "runs-one": 1, "runs-all": 1 };
const k = (v) => v / 1000;
const f2 = (v) => v.toFixed(2);
const atomName = (i) => `${MOL.atoms[i][0]}${i}`;
const bondName = (b) => `${atomName(MOL.bonds[b][0])}–${atomName(MOL.bonds[b][1])}`;
/* the feature columns as cell 32 builds them: six numbers, the element, hybridisation, chirality */
const GROUPS = [[0, 6], [6, NF - 8], [NF - 8, NF - 3], [NF - 3, NF]];

/* --------------------------------------------------------------- scores */

/** cell 90, on one run's final masks: raw and min–max scaled, bonds and atoms */
const SCORES = [];
function scoresOf(run) {
  if (SCORES[run]) return SCORES[run];
  const R = RUNS[run], last = R.edges[NE - 1];
  const bondRaw = MOL.bonds.map((_, b) => Math.max(k(last[2 * b]), k(last[2 * b + 1])));
  const atomRaw = mxAt(run, NE - 1).map((row) => row.reduce((s, v) => s + k(v), 0) / NF);
  const scale = (v) => { const lo = Math.min(...v), hi = Math.max(...v); return v.map((x) => (x - lo) / (hi - lo + 1e-8)); };
  const atom = scale(atomRaw);
  const rank = (i) => 1 + atom.filter((v) => v > atom[i]).length;
  SCORES[run] = { bondRaw, atomRaw, bond: scale(bondRaw), atom, rank };
  return SCORES[run];
}
const keptOf = (run) => new Set(RUNS[run].kept);
const median = (a) => { const b = [...a].sort((p, q) => p - q), n = b.length; return n % 2 ? b[(n - 1) / 2] : (b[n / 2 - 1] + b[n / 2]) / 2; };
const KEEP_COUNT = MOL.bonds.map((_, b) => RUNS.filter((r) => r.kept.includes(b)).length);
const JACCARD = (() => {
  const J = [];
  for (let a = 0; a < NR; a++) for (let b = a + 1; b < NR; b++) {
    const A = keptOf(a), B = keptOf(b), inter = [...A].filter((x) => B.has(x)).length;
    J.push(inter / (A.size + B.size - inter));
  }
  return median(J);
})();
const ALWAYS = KEEP_COUNT.map((c, b) => (c === NR ? b : -1)).filter((b) => b >= 0);
const ALWAYS_ATOM = (() => { const c = {}; ALWAYS.forEach((b) => MOL.bonds[b].slice(0, 2).forEach((i) => { c[i] = (c[i] ?? 0) + 1; })); return Number(Object.keys(c).find((i) => c[i] === ALWAYS.length) ?? -1); })();

/* -------------------------------------------------------------- strings */

const S = {
  subtitle:
    "GNNExplainer learns a mask over a molecule's bonds and atom features that keeps the model's prediction while removing as much of the graph as it can. " +
    "The masks start random and are optimised, then averaged and scaled into one score per bond and per atom. " +
    "Each run from a new random start can keep a different set of bonds that holds the prediction just as well.",
  pageLabel: "Step",
  startLabel: "Random start",
  startDetail: "the random values the masks begin from; each start is optimised separately, and is one run",
  showLabel: "Show",
  showDetail: "One run: the bonds this run keeps; All runs: how many of the 20 runs keep each bond",

  stepLabel: {
    param: "page",
    labels: {
      mask: { anim: "beat", labels: { 0: "Initialise", 1: "Optimise", 2: "Optimise", 3: "Optimise" }, default: "Optimise" },
      scores: { anim: "beat", labels: { 0: "Collapse", 1: "Average", 2: "Scale" }, default: "Scale" },
      runs: { param: "show", labels: { one: "Test", all: "Overlay" }, default: "Test" },
    },
    default: "Initialise",
  },
  stepTitle: {
    param: "page",
    labels: {
      mask: { anim: "beat", labels: { 0: "Give every directed edge and every atom feature a random mask near 0.5", 1: "Optimise the masks for epochs 1–100 with Adam, learning rate 0.01", 2: "Optimise the masks for epochs 101–200", 3: "Optimise the masks for epochs 201–300" }, default: "Optimise the masks for epochs 201–300" },
      scores: { anim: "beat", labels: { 0: "Score each bond as the larger of its two directions' masks", 1: "Score each atom as the mean of its 39 feature masks", 2: "Scale the bond scores and the atom scores to 0–1 within the molecule" }, default: "Scale the bond scores and the atom scores to 0–1 within the molecule" },
      runs: { param: "show", labels: { one: "Predict with only this run's kept bonds, and with random sets of as many bonds", all: "Add the 20 runs' kept bonds one run at a time" }, default: "Predict with only this run's kept bonds, and with random sets of as many bonds" },
    },
    default: "Give every directed edge and every atom feature a random mask near 0.5",
  },

  head: "Ceftriaxone disodium · active",
  salt: "separate pieces:",
  saltNote: "three waters and two Na⁺, no bond to the drug",
  keyMask: ["mask 0", "1"],
  keyScore: ["score 0", "1"],
  keyCount: ["kept by 0 runs", "20"],
  lanes: "two lanes a bond, one mask per direction, wider when larger · dashed: removed, both masks 0.5 or less",
  linesHead: "each bond's mask (its larger direction)",
  goals: "each mask moves up or down: keep p(active) high, keep the masks small",
  maskPlain: "before the masks: every message and every feature passes whole",

  /* Mask */
  pHead: "p(active) of the masked molecule",
  unmasked: (p) => `unmasked ${p}`,
  epoch: (e) => `epoch ${e} of 300`,

  /* Scores */
  gridHead: "M_x: one mask per atom per feature",
  gridCols: "columns: six numbers · element · hybridisation · chirality; empty: the feature is 0 for that atom",
  meanHead: "mean",
  status: [
    () => "each bond has two masks, one per direction; each atom has 39, one per feature (the grid)",
    () => "each bond has one score now: the larger of its two directions",
    (amax) => `each atom has one score now: the mean of its row, mostly 0, so every atom score is small (largest ${f2(amax)})`,
    () => "both sets stretched to 0–1 within the molecule: the lowest score becomes 0, the highest 1",
  ],
  cardHead: "from masks to scores",
  card: [["1 · Collapse", "bond = max(→ mask, ← mask)"], ["2 · Average", "atom = mean of its 39 masks"], ["3 · Scale", "score = (s − min) / (max − min)"]],
  /* the range each step produced; "now" was false once Scale had moved them */
  cardNum: [(r) => `bond scores ${r}`, (r) => `atom scores ${r}`, "both scaled to 0–1"],
  cardAtom: (n, m, sc) => `${n}: mean ${m}${sc == null ? "" : ` → score ${sc}`}`,

  /* Runs */
  testHead: "p(active) with only some bonds",
  testKept: (n) => `only this run's ${n} kept bonds`,
  testRand: (n) => `100 random sets of ${n} bonds`,
  barHead: "the 39 bonds, by how many runs keep them",
  always: (n) => `kept by every run: ${n} bonds, all on N10 (ringed)`,
  epochs3000: "At 3,000 epochs every mask ends at 0 or 1, and the runs still keep different bonds.",

  /* hover */
  hovAtom: (i, v) => `${atomName(i)}${v == null ? "" : ` · ${v}`}`,
  hovBond: (b, v) => `${bondName(b)} · ${MOL.bonds[b][2].toLowerCase()}${v == null ? "" : ` · ${v}`}`,
  hovLanes: (b, u, v) => `${bondName(b)} · → ${u} · ← ${v}`,
  hovCell: (i, f, v) => `${atomName(i)} · ${FEATURES[f]} · ${v}`,

  /* tiles */
  tileFull: "Unmasked",
  tileFullNote: `p(active) from a GAT trained on the dataset's scaffold split; its test macro F1 is ${INFO.testF1.toFixed(2)}`,
  tileMasked: "Masked",
  tileMaskedNote: "p(active) with every message and every feature multiplied by its mask",
  tileAbove: "Kept · removed",
  tileAboveNote: (e) => `bonds with a mask above 0.5 in either direction, and the rest · epoch ${e}`,
  tileBonds: "Bond scores",
  tileBondsNote: "the larger of each bond's two directions",
  tileAtoms: "Atom scores",
  tileAtomsNote: `the mean over ${NF} features; the mask is 0 where the feature is 0`,
  tileWater: "The waters",
  tileWaterNote: "rank among 41 atoms; max pooling reads every atom, bonded or not",
  tileKept: "Kept bonds",
  tileKeptNote: `mask above 0.5, of ${NB}`,
  tileOnly: "Only those",
  tileOnlyNote: "p(active) with every other bond's messages removed",
  tileRand: "Random sets",
  tileRandNote: "median p(active) of 100 random sets of as many bonds",
  tileEvery: "Kept by every run",
  tileEveryNote: `bonds kept by all ${NR} runs`,
  tileSome: "Kept by some run",
  tileSomeNote: `bonds kept by at least one of ${NR} runs`,
  tileShare: "Two runs share",
  tileShareNote: "median, over every pair of runs, of the kept bonds they share as a share of the bonds either keeps",
  tileWait: "—",

  sumMask: (run, beat, e, p) => `Random start ${run}: ${beat === 0 ? "the molecule before the masks" : `the masks at epoch ${e}, p(active) ${p}`}`,
  sumScores: (run, beat) => `Random start ${run}: ${["each bond's two directions", "each bond scored", "each atom scored", "bonds and atoms scaled to 0–1"][beat]}`,
  sumRuns: (run, all, beat) => (all ? `${beat ? "how many of 20 runs keep each bond" : "the 20 runs, not yet overlaid"}` : `Random start ${run}: the bonds it keeps${beat ? ", tested" : ""}`),
};

/* ------------------------------------------------------ drawing helpers */

const rgb = (c) => { const m = String(c).match(/^#([0-9a-f]{6})$/i); return m ? [0, 2, 4].map((i) => parseInt(m[1].slice(i, i + 2), 16)) : [128, 128, 128]; };
/** --c-magnitude's ramp from --surface-3; violet, so --c-highlight stays off these pages (ink instead) */
const ramp = (colors, v) => { const a = rgb(colors.surface3), b = rgb(colors.magnitude), u = Math.max(0, Math.min(1, v)); return `rgb(${a.map((x, i) => Math.round(x + (b[i] - x) * u)).join(",")})`; };
function fitText(ctx, s, maxW) {
  let out = s;
  while (ctx.measureText(out).width > maxW) {
    const cut = Math.max(out.lastIndexOf(" · "), out.lastIndexOf("; "), out.lastIndexOf(", "));
    if (cut <= 0) { while (out.length > 1 && ctx.measureText(out + "…").width > maxW) out = out.slice(0, -1); return out + "…"; }
    out = out.slice(0, cut);
  }
  return out;
}
function txt(ctx, colors, s, x, y, { font = null, fill = null, align = "left", baseline = "alphabetic", maxW = null } = {}) {
  ctx.save();
  ctx.font = font ?? `${colors.fsXs} ${colors.font}`;
  if (maxW != null) s = fitText(ctx, String(s), maxW);
  ctx.textAlign = align; ctx.textBaseline = baseline;
  ctx.fillStyle = fill ?? colors.ink2;
  ctx.fillText(s, x, y);
  ctx.restore();
}
const capFont = (colors) => `600 ${colors.fsSm} ${colors.font}`;
const nodeFont = (colors) => `600 ${colors.fsXs} ${colors.font}`;
function line(ctx, x1, y1, x2, y2, stroke, width = 1, dash = null) {
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = width; ctx.lineCap = "round"; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.stroke(); ctx.restore();
}
function rect(ctx, x, y, w, h, fill, stroke = null, lw = 1) {
  ctx.save();
  if (fill) { ctx.fillStyle = fill; ctx.fillRect(x, y, w, h); }
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.strokeRect(x + lw / 2, y + lw / 2, w - lw, h - lw); }
  ctx.restore();
}
function dot(ctx, x, y, r, fill, stroke = null, lw = 1) {
  ctx.save(); ctx.beginPath(); ctx.arc(x, y, r, 0, Math.PI * 2);
  if (fill) { ctx.fillStyle = fill; ctx.fill(); }
  if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = lw; ctx.stroke(); }
  ctx.restore();
}
function polyline(ctx, pts, stroke, width = 1.6, dash = null) {
  if (pts.length < 2) return;
  ctx.save(); ctx.strokeStyle = stroke; ctx.lineWidth = width; ctx.lineJoin = "round"; if (dash) ctx.setLineDash(dash);
  ctx.beginPath(); pts.forEach(([x, y], i) => (i ? ctx.lineTo(x, y) : ctx.moveTo(x, y))); ctx.stroke(); ctx.restore();
}
function hoverLabel(ctx, colors, str, x, y, w) {
  ctx.save(); ctx.font = `600 ${colors.fsXs} ${colors.font}`;
  const tw = ctx.measureText(str).width; ctx.restore();
  const bx = Math.max(4, Math.min(w - tw - 14, x + 10)), by = Math.max(4, y - 26);
  rect(ctx, bx, by, tw + 10, 18, colors.surface, colors.ink3);
  txt(ctx, colors, str, bx + 5, by + 9.5, { font: `600 ${colors.fsXs} ${colors.font}`, fill: colors.ink1, baseline: "middle" });
}
/** the ramp's key: a bar and its two end words, right-aligned at x1 */
function rampKey(ctx, colors, x1, y, words, w = 70) {
  ctx.save(); ctx.font = `${colors.fsXs} ${colors.font}`; const tw = ctx.measureText(words[1]).width; ctx.restore();
  const x0 = x1 - tw - 6 - w;
  for (let q = 0; q < w; q++) line(ctx, x0 + q, y, x0 + q + 1, y, ramp(colors, q / (w - 1)), 8);
  txt(ctx, colors, words[0], x0 - 6, y + 3, { align: "right", fill: colors.ink3 });
  txt(ctx, colors, words[1], x1, y + 3, { align: "right", fill: colors.ink3 });
}

/* ------------------------------------------------------------ the molecule */

const NODE_R = 8, LANE = 2.6, STRIP = 30;
const MOL_H = 236;
/** the drug fitted to its box; the salt's one-atom pieces spaced along the strip under it */
function placeMol(w, top) {
  const xs = DRUG.map((i) => MOL.atoms[i][2]), ys = DRUG.map((i) => MOL.atoms[i][3]);
  const minX = Math.min(...xs), maxX = Math.max(...xs), minY = Math.min(...ys), maxY = Math.max(...ys);
  const boxH = MOL_H - STRIP - 54, s = Math.min((w - 2 * NODE_R - 24) / (maxX - minX), boxH / (maxY - minY));
  const cx = (minX + maxX) / 2, cy = (minY + maxY) / 2, my = top + 30 + boxH / 2;
  const P = MOL.atoms.map((a) => [w / 2 + (a[2] - cx) * s, my + (a[3] - cy) * s]);
  const sy = top + MOL_H - STRIP / 2;
  SALT.forEach((i, q) => { P[i] = [116 + q * 34, sy]; });
  return P;
}
/* the element in the node, a charge as a sign outside it: "Na+" overflows a node */
function drawAtom(ctx, colors, p, i, v) {
  const [el, ch] = MOL.atoms[i];
  const fill = v == null ? colors.surface : ramp(colors, v);
  dot(ctx, p[0], p[1], NODE_R, fill, colors.ink3, 1);
  txt(ctx, colors, el, p[0], p[1] + 0.5, { font: nodeFont(colors), align: "center", baseline: "middle", fill: v != null && v > 0.55 ? colors.surface : colors.ink1 });
  if (ch) txt(ctx, colors, ch > 0 ? "+" : "−", p[0] + NODE_R + 1, p[1] - NODE_R + 3, { font: nodeFont(colors), fill: colors.ink1 });
}
function drawStrip(ctx, colors, w, top) {
  const y = top + MOL_H - STRIP;
  line(ctx, 10, y, w - 10, y, colors.grid);
  txt(ctx, colors, S.salt, 12, y + STRIP / 2 + 4, { fill: colors.ink3 });
  txt(ctx, colors, S.saltNote, 116 + SALT.length * 34, y + STRIP / 2 + 4, { fill: colors.ink3, maxW: w - 126 - SALT.length * 34 });
}
/** one bond as two lanes, one per direction; `sep` 1 is apart, 0 merged into one line */
function drawLanes(ctx, colors, p, q, u, v, sep = 1) {
  const dx = q[0] - p[0], dy = q[1] - p[1], L = Math.hypot(dx, dy) || 1, nx = (-dy / L) * LANE * sep, ny = (dx / L) * LANE * sep;
  /* the bond itself, under its lanes, so a direction masked to 0 still shows where it runs */
  line(ctx, p[0], p[1], q[0], q[1], colors.ink3, 1);
  line(ctx, p[0] + nx, p[1] + ny, q[0] + nx, q[1] + ny, ramp(colors, u), 3.4);
  line(ctx, p[0] - nx, p[1] - ny, q[0] - nx, q[1] - ny, ramp(colors, v), 3.4);
}
/** THE MASK PAGE'S BOND (his round 2, pick A): colour alone, its 0 end near the background, read as
    a bond fading, so the width carries the mask too, and a bond whose masks are both 0.5 or less is a
    grey dashed line: removed is a state the reader sees, not an absence */
function drawMaskBond(ctx, colors, p, q, u, v) {
  if (Math.max(u, v) <= 0.5) { line(ctx, p[0], p[1], q[0], q[1], colors.ink3, 1.4, [3, 3]); return; }
  const dx = q[0] - p[0], dy = q[1] - p[1], L = Math.hypot(dx, dy) || 1;
  [[u, 1], [v, -1]].forEach(([m, side]) => {
    const off = (LANE + 0.6) * side, nx = (-dy / L) * off, ny = (dx / L) * off;
    line(ctx, p[0] + nx, p[1] + ny, q[0] + nx, q[1] + ny, ramp(colors, 0.25 + 0.75 * m), 0.6 + 4.4 * m);
  });
}
/** one bond as one line, its width and colour a score in 0–1 */
function drawScoredBond(ctx, colors, p, q, v) {
  line(ctx, p[0], p[1], q[0], q[1], colors.ink3, 1);
  line(ctx, p[0], p[1], q[0], q[1], ramp(colors, v), 2 + 4.5 * v);
}
function nearestAtom(P, pt) {
  let best = -1, bd = NODE_R + 3;
  P.forEach((p, i) => { const d = Math.hypot(p[0] - pt.x, p[1] - pt.y); if (d < bd) { bd = d; best = i; } });
  return best;
}
function nearestBond(P, pt) {
  let best = -1, bd = 6;
  MOL.bonds.forEach(([i, j], b) => {
    const [ax, ay] = P[i], [bx, by] = P[j], vx = bx - ax, vy = by - ay, L2 = vx * vx + vy * vy;
    const t = Math.max(0, Math.min(1, ((pt.x - ax) * vx + (pt.y - ay) * vy) / L2));
    const d = Math.hypot(ax + t * vx - pt.x, ay + t * vy - pt.y);
    if (d < bd) { bd = d; best = b; }
  });
  return best;
}

/* ------------------------------------------------------------- timing */

const DUR = { 1: 1400, 2: 4000, 3: 4000, 4: 4000 };
const DUR_SCORES = 1800, DUR_TEST = 2400, DUR_OVERLAY = 4000;
const ease = (t) => (t < 0.5 ? 4 * t * t * t : 1 - (-2 * t + 2) ** 3 / 2);
const lerp = (a, b, t) => a + (b - a) * t;
const seg = (t, a, b) => Math.max(0, Math.min(1, (t - a) / (b - a)));
/** the Mask page's presses belong to its run; the Runs page's to its view */
/* a new random start keeps every page's progress (his round 1): after Optimise, sliding the start shows each run's learned masks */
const stageOf = (params) => (params.page === "mask" ? "mask" : params.page === "scores" ? "scores" : `runs-${params.show}`);
const kindOf = (stage) => stage.split("-").slice(0, stage.startsWith("runs") ? 2 : 1).join("-");
const stepsOf = (stage) => STEPS[kindOf(stage)];
const durOf = (stage, n) => (kindOf(stage) === "mask" ? DUR[n] : kindOf(stage) === "scores" ? DUR_SCORES : kindOf(stage) === "runs-one" ? DUR_TEST : DUR_OVERLAY);
const shownStep = (anim, stage) => (anim.n[stage] ?? 0) - (anim.stage === stage && anim.t < 1 ? 1 : 0);
const inFlight = (anim, stage) => (anim.stage === stage && anim.t < 1 ? anim.t : null);
const runOf = (params) => Number(params.start) - 1;

/* ---------------------------------------------------------- geometry */

const CELL_W = 5, CELL_H = 5, GRID_W = NF * CELL_W, GRID_H = NA * CELL_H;
const MASK_TOP = MOL_H + 22, MASK_GY = MASK_TOP + 28;
const H_MASK = MASK_GY + GRID_H + 46;
const GRID_TOP = MOL_H + 40, SCORES_GY = GRID_TOP + 18;
const H_SCORES = SCORES_GY + GRID_H + 34;
const H_RUNS = MOL_H + 22 + 160;

/* ------------------------------------------------------------ M_x */

/** the feature mask of one run at a traced frame (fractional while Optimise plays), as rows of
    41 atoms × 39 features in thousandths; 0 outside the run's hard mask */
const MX_FINAL = [];
function mxAt(run, f) {
  if (f >= NE - 1 && MX_FINAL[run]) return MX_FINAL[run];
  const R = RUNS[run], f0 = Math.floor(f), f1 = Math.min(NE - 1, f0 + 1), u = f - f0;
  const M = Array.from({ length: NA }, () => new Array(NF).fill(0));
  R.mxi.forEach((q, j) => { M[Math.floor(q / NF)][q % NF] = lerp(R.mxt[f0][j], R.mxt[f1][j], u); });
  if (f >= NE - 1) MX_FINAL[run] = M;
  return M;
}
/** the grid both pages draw: a row an atom, a column a feature, the empty cells features the atom
    does not have; optionally the mean column, an outlined row, and a frame round the lot */
function drawGrid(ctx, colors, gx, gy, M, { mean = null, hover = -1, frame = false } = {}) {
  const mx = gx + GRID_W + 8, right = mean ? mx + 24 : gx + GRID_W + 4;
  txt(ctx, colors, S.gridHead, gx - 30, gy - 12, { font: capFont(colors), fill: colors.ink1, maxW: right - gx + 30 });
  GROUPS.forEach(([a]) => { if (a > 0) line(ctx, gx + a * CELL_W, gy - 4, gx + a * CELL_W, gy + GRID_H + 2, colors.ink3, 1); });
  if (M) M.forEach((row, i) => row.forEach((v, q) => { if (v > 0) rect(ctx, gx + q * CELL_W, gy + i * CELL_H, CELL_W - 1, CELL_H - 1, ramp(colors, k(v))); }));
  for (let i = 0; i < NA; i++) {
    /* every tenth row, then the first and last of the one-atom pieces: one label a row there overprints */
    if ((i % 10 === 0 && i < SALT[0] - 4) || i === SALT[0] || i === SALT[SALT.length - 1]) txt(ctx, colors, atomName(i), gx - 4, gy + i * CELL_H + CELL_H, { align: "right", fill: colors.ink3, font: `${colors.fsXs} ${colors.mono}` });
  }
  rect(ctx, gx - 1, gy - 1, GRID_W + 1, GRID_H + 1, null, colors.grid);
  if (mean) {
    txt(ctx, colors, S.meanHead, mx + 4, gy - 5, { align: "center", fill: colors.ink3 });
    mean.forEach((v, i) => { if (v != null) rect(ctx, mx, gy + i * CELL_H, 9, CELL_H - 1, ramp(colors, v)); });
    rect(ctx, mx - 1, gy - 1, 11, GRID_H + 1, null, colors.grid);
  }
  if (hover >= 0) rect(ctx, gx - 2, gy + hover * CELL_H - 1, (mean ? mx + 11 : gx + GRID_W) - gx + 2, CELL_H + 1, null, colors.ink1, 1.2);
  if (frame) rect(ctx, gx - 34, gy - 26, right - gx + 34, GRID_H + 32, null, colors.ink1, 1.5);
  return { mx };
}
/** the grid cell under the pointer: [atom, feature] (feature NF..NF+3 is the mean column), or null */
function gridHit(gx, gy, pt) {
  const i = Math.floor((pt.y - gy) / CELL_H), q = Math.floor((pt.x - gx) / CELL_W);
  return i >= 0 && i < NA && q >= 0 && q <= NF + 3 ? [i, q] : null;
}
/* ---------------------------------------------------------------- Mask */

/** the mask page's epoch position: a frame index, fractional while Optimise plays */
function maskFrame(anim, stage) {
  const done = shownStep(anim, stage), t = inFlight(anim, stage);
  /* a press of Optimise covers ten traced frames, 100 epochs: epochs 1–101, 101–201, 201–300 */
  const per = (NE - 1) / 3;
  if (done === 0) return 0;
  if (t != null) return Math.min(NE - 1, per * (done - 1) + per * Math.min(1, t / 0.94));
  return Math.min(NE - 1, per * (done - 1));
}
function edgeAt(R, f) {
  const f0 = Math.floor(f), f1 = Math.min(NE - 1, f0 + 1), u = f - f0;
  return R.edges[f0].map((v, q) => k(lerp(v, R.edges[f1][q], u)));
}
const seriesAt = (arr, f) => { const f0 = Math.floor(f), f1 = Math.min(NE - 1, f0 + 1); return k(lerp(arr[f0], arr[f1], f - f0)); };
const epochAt = (f) => Math.round(lerp(EPOCHS[Math.floor(f)], EPOCHS[Math.min(NE - 1, Math.floor(f) + 1)], f - Math.floor(f)));

/** each bond's mask (its larger direction) against the epoch, drawn up to the frame shown: violet
    above 0.5, grey at or below; a hovered bond's line in ink */
function drawMaskLines(ctx, colors, R, f, on, x0, top, pw, hover) {
  const ph = 110, y0 = top + 18, y1 = y0 + ph, ex = (e) => x0 + (pw * (e - 1)) / 299, sy = (v) => y1 - v * ph;
  txt(ctx, colors, S.linesHead, x0 - 28, top + 8, { font: capFont(colors), fill: colors.ink1, maxW: pw + 28 });
  line(ctx, x0, y1, x0 + pw, y1, colors.axis); line(ctx, x0, y0, x0, y1, colors.axis);
  line(ctx, x0, sy(0.5), x0 + pw, sy(0.5), colors.ink3, 1, [2, 3]);
  txt(ctx, colors, "1", x0 - 4, y0 + 4, { align: "right", fill: colors.ink3 });
  txt(ctx, colors, "0.5", x0 - 4, sy(0.5) + 3, { align: "right", fill: colors.ink3 });
  txt(ctx, colors, "0", x0 - 4, y1 + 3, { align: "right", fill: colors.ink3 });
  txt(ctx, colors, "1", x0, y1 + 14, { fill: colors.ink3 });
  txt(ctx, colors, "300", x0 + pw, y1 + 14, { align: "right", fill: colors.ink3 });
  if (!on) return;
  const upto = Math.floor(f), f1 = Math.min(NE - 1, upto + 1), u = f - upto;
  const order = MOL.bonds.map((_, b) => b).filter((b) => b !== hover).concat(hover >= 0 ? [hover] : []);
  order.forEach((b) => {
    const val = (q) => Math.max(R.edges[q][2 * b], R.edges[q][2 * b + 1]) / 1000;
    const pts = [];
    for (let q = 0; q <= upto; q++) pts.push([ex(EPOCHS[q]), sy(val(q))]);
    if (u > 0) pts.push([ex(epochAt(f)), sy(lerp(val(upto), val(f1), u))]);
    const v = (y1 - pts[pts.length - 1][1]) / ph;
    polyline(ctx, pts, b === hover ? colors.ink1 : v <= 0.5 ? colors.ink3 : ramp(colors, 0.35 + 0.65 * v), b === hover ? 2.2 : 1.1);
  });
}

/* BOTH MASKS LEARN ON THIS PAGE (his round 1, pick A): the bonds' on the molecule, the atoms'
   features as M_x's grid beside p(active) — the grid the Scores page then averages. The loss panel
   it replaced repeated the curve's story in a quantity nobody read. */
function drawMask(ctx, colors, w, params, anim, pointer) {
  const run = runOf(params), R = RUNS[run], stage = stageOf(params);
  const beat = shownStep(anim, stage), t = inFlight(anim, stage);
  const masked = beat >= 1 || t != null;
  const f = maskFrame(anim, stage), E = edgeAt(R, f);
  const P = placeMol(w, 0);
  txt(ctx, colors, S.head, 12, 16, { font: capFont(colors), fill: colors.ink1 });
  if (masked) rampKey(ctx, colors, w - 12, 12, S.keyMask);
  drawStrip(ctx, colors, w, 0);
  MOL.bonds.forEach(([i, j], b) => {
    if (masked) drawMaskBond(ctx, colors, P[i], P[j], E[2 * b], E[2 * b + 1]);
    else line(ctx, P[i][0], P[i][1], P[j][0], P[j][1], colors.ink2, 1.6);
  });
  MOL.atoms.forEach((_, i) => drawAtom(ctx, colors, P[i], i, null));
  txt(ctx, colors, masked ? S.goals : S.maskPlain, 12, MOL_H - STRIP - 6, { fill: masked ? colors.ink1 : colors.ink3, maxW: w - 120 });
  if (masked) txt(ctx, colors, S.epoch(epochAt(f)), w - 12, MOL_H - STRIP - 6, { align: "right", fill: colors.ink1, font: nodeFont(colors) });

  /* M_x on the right; p(active) on the left with the lanes' note under it */
  const gx = w - 16 - GRID_W, gy = MASK_GY;
  const hit = pointer ? gridHit(gx, gy, pointer) : null;
  const hAtom = pointer ? nearestAtom(P, pointer) : -1;
  const hBond = pointer && hAtom < 0 ? nearestBond(P, pointer) : -1;
  const M = masked ? mxAt(run, f) : null;
  drawGrid(ctx, colors, gx, gy, M, { hover: hAtom >= 0 ? hAtom : hit && hit[1] < NF ? hit[0] : -1 });
  txt(ctx, colors, S.gridCols, 12, gy + GRID_H + 18, { fill: colors.ink3, maxW: w - 24 });
  if (masked) txt(ctx, colors, S.lanes, 12, gy + GRID_H + 34, { fill: colors.ink3, maxW: w - 24 });

  /* p(active), short, over each bond's mask as a line (his round 2, pick B): the split the optimiser makes, and how slowly */
  const x0 = 40, pw = gx - 34 - 30 - x0, top = MASK_TOP, y0 = top + 18, ph = 56, y1 = y0 + ph;
  const ex = (e) => x0 + (pw * (e - 1)) / 299, sy = (v) => y1 - v * ph;
  txt(ctx, colors, S.pHead, x0 - 28, top + 8, { font: capFont(colors), fill: colors.ink1, maxW: pw + 28 });
  line(ctx, x0, y1, x0 + pw, y1, colors.axis); line(ctx, x0, y0, x0, y1, colors.axis);
  txt(ctx, colors, "1", x0 - 4, y0 + 4, { align: "right", fill: colors.ink3 });
  txt(ctx, colors, "0", x0 - 4, y1 + 3, { align: "right", fill: colors.ink3 });
  const pf = k(INFO.pFull);
  line(ctx, x0, sy(pf), x0 + pw, sy(pf), colors.ink3, 1, [3, 3]);
  /* under the line at its right end: the optimised curve ends above it */
  txt(ctx, colors, S.unmasked(f2(pf)), x0 + pw, sy(pf) + 13, { align: "right", fill: colors.ink3 });
  if (masked) {
    if (beat === 0) {
      /* Initialise: the prediction falls from the unmasked value to the random start's, as one moving dot */
      dot(ctx, ex(1), sy(lerp(pf, k(R.p[0]), ease(t ?? 1))), 3.5, colors.ink1);
    } else {
      const upto = Math.floor(f), pp = [];
      for (let q = 0; q <= upto; q++) pp.push([ex(EPOCHS[q]), sy(k(R.p[q]))]);
      if (f > upto) pp.push([ex(epochAt(f)), sy(seriesAt(R.p, f))]);
      polyline(ctx, pp, colors.ink1, 2);
      const lastPt = pp[pp.length - 1]; dot(ctx, lastPt[0], lastPt[1], 3.5, colors.ink1);
    }
  }
  drawMaskLines(ctx, colors, R, f, masked && beat >= 1, x0, top + 96, pw, hBond);

  if (pointer) {
    const b = hBond;
    if (hAtom >= 0) { dot(ctx, P[hAtom][0], P[hAtom][1], NODE_R + 4, null, colors.ink1, 1.8); hoverLabel(ctx, colors, S.hovAtom(hAtom, null), pointer.x, pointer.y, w); }
    else if (b >= 0) hoverLabel(ctx, colors, masked ? S.hovLanes(b, f2(E[2 * b]), f2(E[2 * b + 1])) : S.hovBond(b, null), pointer.x, pointer.y, w);
    else if (hit && hit[1] < NF) {
      dot(ctx, P[hit[0]][0], P[hit[0]][1], NODE_R + 4, null, colors.ink1, 1.8);
      hoverLabel(ctx, colors, S.hovCell(hit[0], hit[1], M ? f2(k(M[hit[0]][hit[1]])) : "—"), pointer.x, pointer.y, w);
    }
  }
}

/* -------------------------------------------------------------- Scores */

/* ONE PLACE TO LOOK A PRESS (his round 1, pick B): a status line says what the press did, a frame
   goes round the part it changed (the molecule for Collapse and Scale, the grid for Average), and
   cell 90's three formulas stand beside the grid, the press's own in bold with its numbers. The dot
   axes of the draft are gone: Scale now shows on the molecule, every atom near blank before it
   (the largest atom score is under 0.1) and the full ramp after. */
function drawScores(ctx, colors, w, params, anim, pointer) {
  const run = runOf(params), R = RUNS[run], stage = "scores", sc = scoresOf(run);
  const beat = shownStep(anim, stage), t = inFlight(anim, stage), last = R.edges[NE - 1];
  const press = anim.n[stage] ?? 0;   /* the press in flight or, settled, the last one made */
  const P = placeMol(w, 0);
  txt(ctx, colors, S.head, 12, 16, { font: capFont(colors), fill: colors.ink1 });
  rampKey(ctx, colors, w - 12, 12, beat >= 3 ? S.keyScore : S.keyMask);
  drawStrip(ctx, colors, w, 0);

  /* Collapse: the two lanes slide together; the line takes the larger value when they meet */
  const tc = beat >= 1 ? 1 : beat === 0 && t != null ? ease(t) : 0;
  /* Scale: every score moves from its raw value to its scaled one */
  const ts = beat >= 3 ? 1 : beat === 2 && t != null ? ease(seg(t, 0, 0.9)) : 0;
  const bondV = (b) => lerp(sc.bondRaw[b], sc.bond[b], ts);
  MOL.bonds.forEach(([i, j], b) => {
    if (tc < 1) drawLanes(ctx, colors, P[i], P[j], k(last[2 * b]), k(last[2 * b + 1]), 1 - tc);
    else drawScoredBond(ctx, colors, P[i], P[j], bondV(b));
  });
  /* Average: the grid's rows are averaged top to bottom, each atom taking its mean when the sweep reaches its row */
  const ta = beat >= 2 ? NA : beat === 1 && t != null ? Math.floor(NA * seg(t, 0, 0.9)) : 0;
  const atomV = (i) => (i < ta ? lerp(sc.atomRaw[i], sc.atom[i], ts) : null);
  MOL.atoms.forEach((_, i) => drawAtom(ctx, colors, P[i], i, atomV(i)));
  txt(ctx, colors, S.status[press](Math.max(...sc.atomRaw)), 12, MOL_H - STRIP - 6, { fill: colors.ink1, font: nodeFont(colors), maxW: w - 24 });
  if (press === 1 || press === 3) rect(ctx, 6, 24, w - 12, MOL_H - STRIP - 38, null, colors.ink1, 1.5);

  const gx = 34, gy = SCORES_GY;
  const hit = pointer ? gridHit(gx, gy, pointer) : null;
  const hAtom = pointer ? nearestAtom(P, pointer) : -1, hb = pointer && hAtom < 0 ? nearestBond(P, pointer) : -1;
  const ha = hAtom >= 0 ? hAtom : hb < 0 && hit ? hit[0] : -1;
  const { mx } = drawGrid(ctx, colors, gx, gy, mxAt(run, NE - 1), { mean: MOL.atoms.map((_, i) => atomV(i)), hover: ha, frame: press === 2 });
  txt(ctx, colors, S.gridCols, 12, gy + GRID_H + 16, { fill: colors.ink3, maxW: w - 24 });

  /* cell 90 as three formulas; a step's numbers appear once its press is made */
  const sx0 = mx + 54, sw = w - 16 - sx0;
  txt(ctx, colors, S.cardHead, sx0, gy - 12, { font: capFont(colors), fill: colors.ink1, maxW: sw });
  const range = (v) => `${f2(Math.min(...v))}–${f2(Math.max(...v))}`;
  const nums = [S.cardNum[0](range(sc.bondRaw)), S.cardNum[1](range(sc.atomRaw)), S.cardNum[2]];
  S.card.forEach(([head, eq], q) => {
    const y = gy + 14 + q * 64, cur = press === q + 1, done = beat > q || cur;
    const ink = done ? colors.ink1 : colors.ink3;
    txt(ctx, colors, head, sx0, y, { fill: ink, font: `${cur ? 700 : 600} ${colors.fsXs} ${colors.font}`, maxW: sw });
    txt(ctx, colors, eq, sx0, y + 18, { fill: ink, font: `${cur ? "700 " : ""}${colors.fsXs} ${colors.mono}`, maxW: sw });
    if (beat > q) txt(ctx, colors, nums[q], sx0, y + 35, { fill: cur ? colors.ink1 : colors.ink2, maxW: sw });
    if (cur) rect(ctx, sx0 - 8, y - 15, sw + 16, 58, null, colors.ink1, 1.5);
  });
  /* the hovered atom's own numbers, under the formulas */
  if (ha >= 0 && beat >= 2) txt(ctx, colors, S.cardAtom(atomName(ha), f2(sc.atomRaw[ha]), beat >= 3 ? f2(sc.atom[ha]) : null), sx0, gy + 14 + 3 * 64 + 4, { fill: colors.ink1, font: nodeFont(colors), maxW: sw });

  /* HOVER IS SYNCED (his round 1): an atom, on the molecule or as its grid row, rings itself and
     outlines its row and mean cell; a bond is traced. Ink, not --c-highlight (--c-magnitude's violet). */
  if (pointer) {
    if (ha >= 0) dot(ctx, P[ha][0], P[ha][1], NODE_R + 4, null, colors.ink1, 1.8);
    if (hb >= 0) { const [i, j] = MOL.bonds[hb]; line(ctx, P[i][0], P[i][1], P[j][0], P[j][1], colors.ink1, 1.2, [3, 2]); }
    if (hAtom >= 0) hoverLabel(ctx, colors, S.hovAtom(hAtom, atomV(hAtom) == null ? null : f2(atomV(hAtom))), pointer.x, pointer.y, w);
    else if (hb >= 0) hoverLabel(ctx, colors, tc < 1 ? S.hovLanes(hb, f2(k(last[2 * hb])), f2(k(last[2 * hb + 1]))) : S.hovBond(hb, f2(bondV(hb))), pointer.x, pointer.y, w);
    else if (hit && hit[1] < NF) hoverLabel(ctx, colors, S.hovCell(hit[0], hit[1], f2(k(mxAt(run, NE - 1)[hit[0]][hit[1]]))), pointer.x, pointer.y, w);
    else if (hit) hoverLabel(ctx, colors, S.hovAtom(hit[0], atomV(hit[0]) == null ? null : f2(atomV(hit[0]))), pointer.x, pointer.y, w);
  }
}

/* ---------------------------------------------------------------- Runs */

function drawRuns(ctx, colors, w, params, anim, pointer) {
  const all = params.show === "all", stage = stageOf(params);
  const beat = shownStep(anim, stage), t = inFlight(anim, stage);
  const P = placeMol(w, 0);
  txt(ctx, colors, S.head, 12, 16, { font: capFont(colors), fill: colors.ink1 });
  drawStrip(ctx, colors, w, 0);
  const top = MOL_H + 22;

  if (!all) {
    const run = runOf(params), R = RUNS[run], kept = keptOf(run);
    MOL.bonds.forEach(([i, j], b) => {
      if (kept.has(b)) line(ctx, P[i][0], P[i][1], P[j][0], P[j][1], colors.magnitude, 6);
      else line(ctx, P[i][0], P[i][1], P[j][0], P[j][1], colors.surface3, 2.2);
    });
    MOL.atoms.forEach((_, i) => drawAtom(ctx, colors, P[i], i, null));
    rampKey(ctx, colors, w - 12, 12, ["dropped", "kept"], 40);

    /* Test: 100 random sets' p fall onto the axis, then this run's kept set */
    const x0 = 24, x1 = w - 24, ax = top + 92, sx = (v) => x0 + v * (x1 - x0);
    txt(ctx, colors, S.testHead, 12, top + 8, { font: capFont(colors), fill: colors.ink1 });
    line(ctx, x0, ax, x1, ax, colors.axis);
    [0, 0.25, 0.5, 0.75, 1].forEach((v) => { line(ctx, sx(v), ax, sx(v), ax + 4, colors.axis); txt(ctx, colors, String(v), sx(v), ax + 16, { align: "center", fill: colors.ink3 }); });
    const pf = k(INFO.pFull);
    line(ctx, sx(pf), top + 20, sx(pf), ax, colors.ink3, 1, [3, 3]);
    txt(ctx, colors, S.unmasked(f2(pf)), sx(pf) - 4, top + 28, { align: "right", fill: colors.ink3 });
    const tt = beat >= 1 ? 1 : t ?? 0;
    if (beat >= 1 || t != null) {
      /* each random set's dot drops in turn, stacked by its 0.02 bin */
      const n = Math.floor(R.pRand.length * seg(tt, 0, 0.6)), stack = {};
      for (let q = 0; q < n; q++) {
        const v = k(R.pRand[q]), bin = Math.round(v * 50), h = (stack[bin] = (stack[bin] ?? 0) + 1);
        dot(ctx, sx(v), ax - 4 - (h - 1) * 5, 2.2, colors.ink3);
      }
      const u = ease(seg(tt, 0.65, 1));
      if (u > 0) {
        const v = k(R.pKept), y = lerp(top + 30, ax - 8, u);
        dot(ctx, sx(v), y, 6, colors.magnitude, colors.ink1, 1.4);
      }
      if (tt >= 1) {
        txt(ctx, colors, S.testKept(R.kept.length), sx(k(R.pKept)) - 10, top + 50, { align: "right", fill: colors.ink1, font: nodeFont(colors) });
        txt(ctx, colors, S.testRand(R.kept.length), x0, ax + 32, { fill: colors.ink3 });
      }
    }
    txt(ctx, colors, S.epochs3000, 12, top + 152, { fill: colors.ink3, maxW: w - 24 });
    if (pointer) {
      const a = nearestAtom(P, pointer), b = a < 0 ? nearestBond(P, pointer) : -1;
      if (a >= 0) hoverLabel(ctx, colors, S.hovAtom(a, null), pointer.x, pointer.y, w);
      else if (b >= 0) hoverLabel(ctx, colors, S.hovBond(b, kept.has(b) ? "kept" : "dropped"), pointer.x, pointer.y, w);
    }
    return;
  }

  /* All runs: Overlay adds one run's kept set at a time; a bond's shade is how many have kept it so far */
  const nIn = beat >= 1 ? NR : t != null ? Math.floor(NR * seg(t, 0, 0.92)) : 0;
  const cnt = MOL.bonds.map((_, b) => RUNS.slice(0, nIn).filter((r) => r.kept.includes(b)).length);
  MOL.bonds.forEach(([i, j], b) => drawScoredBond(ctx, colors, P[i], P[j], cnt[b] / NR));
  MOL.atoms.forEach((_, i) => drawAtom(ctx, colors, P[i], i, null));
  rampKey(ctx, colors, w - 12, 12, S.keyCount, 60);
  if (beat >= 1 && ALWAYS_ATOM >= 0) dot(ctx, P[ALWAYS_ATOM][0], P[ALWAYS_ATOM][1], NODE_R + 5, null, colors.ink1, 1.8);

  /* the bonds as bars, sorted by their final count so the bars only grow in place */
  txt(ctx, colors, S.barHead, 12, top + 8, { font: capFont(colors), fill: colors.ink1 });
  const order = MOL.bonds.map((_, b) => b).sort((a, b) => KEEP_COUNT[b] - KEEP_COUNT[a] || a - b);
  const bx0 = 24, bw = (w - 48) / NB, by1 = top + 104, bh = 80;
  line(ctx, bx0, by1, bx0 + NB * bw, by1, colors.axis);
  txt(ctx, colors, "20", bx0 - 4, by1 - bh + 4, { align: "right", fill: colors.ink3 });
  txt(ctx, colors, "0", bx0 - 4, by1 + 3, { align: "right", fill: colors.ink3 });
  line(ctx, bx0, by1 - bh, bx0 + NB * bw, by1 - bh, colors.grid, 1, [2, 3]);
  order.forEach((b, q) => { if (cnt[b]) rect(ctx, bx0 + q * bw + 1, by1 - (bh * cnt[b]) / NR, bw - 2, (bh * cnt[b]) / NR, ramp(colors, cnt[b] / NR)); });
  txt(ctx, colors, `run ${Math.min(NR, nIn)} of ${NR}`, w - 12, top + 8, { align: "right", fill: colors.ink3 });
  if (beat >= 1) txt(ctx, colors, S.always(ALWAYS.length), 12, by1 + 18, { fill: colors.ink1, maxW: w - 24 });
  txt(ctx, colors, S.epochs3000, 12, top + 152, { fill: colors.ink3, maxW: w - 24 });
  if (pointer) {
    const a = nearestAtom(P, pointer), b = a < 0 ? nearestBond(P, pointer) : -1;
    const q = Math.floor((pointer.x - bx0) / bw), inBars = pointer.y > by1 - bh - 4 && pointer.y < by1 + 2 && q >= 0 && q < NB;
    if (a >= 0) hoverLabel(ctx, colors, S.hovAtom(a, null), pointer.x, pointer.y, w);
    else if (b >= 0) hoverLabel(ctx, colors, S.hovBond(b, `kept by ${cnt[b]} of ${nIn} runs`), pointer.x, pointer.y, w);
    else if (inBars) hoverLabel(ctx, colors, S.hovBond(order[q], `kept by ${cnt[order[q]]} of ${nIn} runs`), pointer.x, pointer.y, w);
  }
}

/* ------------------------------------------------------------- widget */

defineWidget({
  slug: "gnn-explainer",
  status: "draft",
  title: "Deep Learning - Graphs: Explainability",
  subtitle: S.subtitle,
  credit: "Molecule data: Stokes et al., Cell 2020, via FinGAT",
  layout: "side",
  height: (params) => (params.page === "mask" ? H_MASK : params.page === "scores" ? H_SCORES : H_RUNS),
  pointer: true,

  params: {
    page: { role: "page", type: "segmented", label: S.pageLabel, options: PAGES, default: "mask", display: true },
    /* hidden in All runs, which combines every start (his round 1: a control that did nothing) */
    start: { type: "int", label: S.startLabel, detail: S.startDetail, min: 1, max: NR, default: 1, display: true,
      when: { any: [{ param: "page", oneOf: ["mask", "scores"] }, { param: "show", equals: "one" }] } },
    show: { type: "segmented", label: S.showLabel, detail: S.showDetail, options: SHOW_OPTS, default: "one", display: true, when: ON("runs") },
    /* authoring escape hatch, first render only: presses already made on the stage the link opens */
    shown: { type: "int", min: 0, max: 4, default: 0, hidden: true },
  },

  /* none: each page keys its marks on the canvas (a ramp key, captions), and a legend reads params alone */
  legend: [],

  compute: () => ({}),

  animation: {
    stepLabel: S.stepLabel,
    stepTitle: S.stepTitle,
    /* each press is read, once: Step alone (play-only-for-motion-or-repetition) */
    runLabel: null,

    init: ({ params, fromScratch }) => {
      const stage = stageOf(params);
      const anim = { stage, n: {}, t: 1, dur: 1000, halt: false };
      anim.n[stage] = fromScratch ? 0 : Math.max(0, Math.min(stepsOf(stage), Number(params.shown) || 0));
      anim.beat = anim.n[stage];
      anim.done = anim.n[stage] >= stepsOf(stage);
      return anim;
    },

    advance: (anim, { dt }) => {
      /* a press a stage switch interrupted ends here, before the new stage's (mid-press-page-switch) */
      if (anim.halt) { anim.halt = false; return false; }
      const stage = anim.stage;
      if (anim.t < 1) anim.t = Math.min(1, anim.t + dt / anim.dur);
      else if ((anim.n[stage] ?? 0) < stepsOf(stage)) {
        anim.n[stage] = (anim.n[stage] ?? 0) + 1;
        anim.dur = durOf(stage, anim.n[stage]);
        anim.t = 0;
      }
      anim.beat = anim.n[stage] ?? 0;
      anim.done = anim.beat >= stepsOf(stage) && anim.t >= 1;
      return anim.t < 1;
    },

    rebuild: (anim, { params }) => {
      const stage = stageOf(params);
      /* only a change of stage ends a press in flight; a new random start keeps it */
      if (stage !== anim.stage && anim.t < 1) { anim.t = 1; anim.halt = true; }
      anim.stage = stage;
      anim.beat = anim.n[stage] ?? 0;
      anim.done = anim.beat >= stepsOf(stage) && anim.t >= 1;
    },
  },

  draw({ ctx, colors, w, params, anim, pointer }) {
    if (params.page === "mask") drawMask(ctx, colors, w, params, anim, pointer);
    else if (params.page === "scores") drawScores(ctx, colors, w, params, anim, pointer);
    else drawRuns(ctx, colors, w, params, anim, pointer);
  },

  readout({ params, anim }) {
    const stage = stageOf(params), beat = shownStep(anim, stage), run = runOf(params), R = RUNS[run];
    if (params.page === "mask") {
      const f = maskFrame(anim, stage), E = edgeAt(R, f), on = beat >= 1 || inFlight(anim, stage) != null;
      const above = MOL.bonds.filter((_, b) => Math.max(E[2 * b], E[2 * b + 1]) > 0.5).length;
      return [
        { label: S.tileFull, value: f2(k(INFO.pFull)), note: S.tileFullNote },
        { label: S.tileMasked, value: on ? f2(seriesAt(R.p, f)) : S.tileWait, note: S.tileMaskedNote },
        { label: S.tileAbove, value: on ? `${above} · ${NB - above}` : S.tileWait, note: on ? S.tileAboveNote(epochAt(f)) : "" },
      ];
    }
    if (params.page === "scores") {
      const sc = scoresOf(run), ranks = SALT.filter((i) => MOL.atoms[i][0] === "O").map(sc.rank).sort((a, b) => a - b);
      return [
        { label: S.tileBonds, value: beat >= 1 ? String(NB) : S.tileWait, note: S.tileBondsNote },
        { label: S.tileAtoms, value: beat >= 2 ? String(NA) : S.tileWait, note: S.tileAtomsNote },
        { label: S.tileWater, value: beat >= 2 ? ranks.join(" · ") : S.tileWait, note: S.tileWaterNote },
      ];
    }
    if (params.show === "one") {
      return [
        { label: S.tileKept, value: String(R.kept.length), note: S.tileKeptNote },
        { label: S.tileOnly, value: beat >= 1 ? f2(k(R.pKept)) : S.tileWait, note: S.tileOnlyNote },
        { label: S.tileRand, value: beat >= 1 ? f2(k(median(R.pRand))) : S.tileWait, note: S.tileRandNote },
      ];
    }
    return [
      { label: S.tileEvery, value: beat >= 1 ? String(ALWAYS.length) : S.tileWait, note: S.tileEveryNote },
      { label: S.tileSome, value: beat >= 1 ? String(KEEP_COUNT.filter((c) => c > 0).length) : S.tileWait, note: S.tileSomeNote },
      { label: S.tileShare, value: beat >= 1 ? `${Math.round(100 * JACCARD)}%` : S.tileWait, note: S.tileShareNote },
    ];
  },

  summary({ params, anim }) {
    const stage = stageOf(params), beat = shownStep(anim, stage), R = RUNS[runOf(params)];
    if (params.page === "mask") { const f = maskFrame(anim, stage); return S.sumMask(params.start, beat, epochAt(f), f2(seriesAt(R.p, f))); }
    if (params.page === "scores") return S.sumScores(params.start, beat);
    return S.sumRuns(params.start, params.show === "all", beat);
  },
});
